import type { TextStyle, ViewStyle } from 'react-native'

export const bookingFormStyleDefinitions = {
  bookingDateGridWide: {
    alignContent: 'flex-start',
    flex: 1,
    flexWrap: 'nowrap',
    gap: 0,
    marginTop: 7,
  },
  bookingDateOptionContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
    minWidth: 0,
    width: '100%',
  },
  bookingDateOptionContentWide: {
    flexDirection: 'column',
    gap: 0,
  },
  bookingDateOptionWide: {
    borderRadius: 0,
    borderWidth: 0,
    flexBasis: 0,
    flexGrow: 1,
    minHeight: 50,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 4,
  },
  bookingDateTextStack: {
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  bookingFieldWide: {
    gap: 6,
    marginBottom: 17,
  },
  bookingWideFieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginLeft: 2,
  },
  bookingInfoCardWide: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    boxShadow: 'none',
    elevation: 0,
    gap: 0,
    marginTop: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  bookingInfoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 18,
    paddingHorizontal: 2,
  },
  bookingInfoHeaderAction: {
    fontSize: 10.5,
    fontWeight: '700',
    lineHeight: 14,
  },
  bookingInfoHeaderTitle: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 23,
  },
  bookingWideCustomScheduleField: {
    gap: 7,
    marginTop: 0,
  },
  bookingWideCustomScheduleInput: {
    fontSize: 12.5,
    fontWeight: '600',
    lineHeight: 17,
    minHeight: 33,
    minWidth: 0,
    paddingHorizontal: 0,
  },
  bookingWideCustomScheduleInputShell: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    minHeight: 34,
    paddingHorizontal: 0,
  },
  bookingWideCustomScheduleLabel: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  bookingWideDescriptionField: {
    flex: 1,
    minWidth: 0,
  },
  bookingWideDescriptionIconShell: {
    borderRadius: 0,
    flexShrink: 0,
    height: 42,
    width: 42,
  },
  bookingWideDescriptionInput: {
    fontSize: 13,
    lineHeight: 18,
    minHeight: 58,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  bookingWideDescriptionInputShell: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    minHeight: 58,
    paddingHorizontal: 0,
  },
  bookingWideDescriptionRow: {
    alignItems: 'flex-start',
    borderCurve: 'continuous',
    borderRadius: 0,
    borderTopWidth: 1,
    borderWidth: 0,
    flexDirection: 'row',
    gap: 14,
    minHeight: 86,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingTop: 15,
  },
  bookingWideDraftSubmitButton: {
    borderRadius: 14,
    height: 48,
    marginTop: 0,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  bookingWideDraftSubmitIcon: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    position: 'absolute',
    right: 13,
    top: 14,
    width: 20,
  },
  bookingWideDraftSubmitText: {
    fontSize: 12.5,
    fontWeight: '800',
    lineHeight: 17,
  },
  bookingWideDraftSubmitWrap: {
    marginTop: 25,
    position: 'relative',
  },
  bookingWideFieldAdornment: {
    alignItems: 'center',
    flexShrink: 0,
    height: 0,
    justifyContent: 'center',
    opacity: 0,
    position: 'relative',
    width: 0,
  },
  bookingWideAuraLayer: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bookingWideHiddenAuraLayer: {
    opacity: 0,
  },
  bookingWideInlineIconShell: {
    borderRadius: 0,
    height: 48,
    width: 42,
  },
  bookingWideInlineInput: {
    fontSize: 13,
    lineHeight: 15,
    minHeight: 34,
  },
  bookingWideInputRow: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    gap: 14,
    minHeight: 70,
    paddingHorizontal: 0,
    paddingRight: 0,
  },
  bookingWideScheduleHeader: {
    gap: 14,
    marginBottom: 25,
    minHeight: 50,
  },
  bookingWideDateGroup: {
    flex: 1,
    gap: 0,
    minWidth: 0,
  },
  bookingWideDateLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  bookingWideScheduleMain: {
    flex: 1,
    minWidth: 0,
    paddingRight: 0,
  },
  bookingWideSchedulePanel: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    boxShadow: 'none',
    minHeight: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  bookingWideScheduleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    paddingTop: 0,
  },
  bookingWideScheduleRowSpaced: {
    marginTop: 30,
  },
  bookingWideCustomScheduleColumn: {
    minWidth: 94,
    paddingLeft: 2,
    width: 94,
  },
  bookingWideDateSelectionLine: {
    borderRadius: 999,
    height: 3,
    marginTop: 8,
    width: '70%',
  },
  bookingWideTimeChip: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    flex: 1,
    minHeight: 34,
    minWidth: 0,
    paddingHorizontal: 0,
  },
  bookingWideTimeChipText: {
    fontSize: 12.5,
    fontWeight: '600',
    lineHeight: 17,
  },
  bookingWideTimeGrid: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 0,
    marginTop: 9,
  },
  bookingWideTimeStartSection: {
    marginTop: 0,
  },
  bookingWideTimeSlotGroup: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    minWidth: 0,
  },
  bookingWideTimeStartLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginLeft: 0,
  },
  bookingWideTimeSeparator: {
    borderRadius: 999,
    height: 4,
    marginHorizontal: 2,
    width: 4,
  },
  bookingWideReadonlyText: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
} satisfies Record<string, TextStyle | ViewStyle>
