import { typography } from '@/design/theme'
import { Platform, type TextStyle, type ViewStyle } from 'react-native'

export const bookingFormStyleDefinitions = {
  bookingDateGridWide: {
    alignContent: 'flex-start',
    flex: 1,
    flexWrap: 'wrap',
    gap: 0,
    marginTop: 7,
    rowGap: 10,
  },
  bookingDateOptionContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
    minWidth: 0,
    width: '100%',
  },
  bookingDateOptionContentWide: {
    flexDirection: 'column',
    gap: 0,
  },
  bookingDateOptionWide: {
    borderRadius: 0,
    borderWidth: 0,
    flexBasis: '25%',
    flexGrow: 1,
    maxWidth: '25%',
    minHeight: 50,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 4,
  },
  bookingDateTextStack: {
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  bookingFieldWide: {
    gap: 6,
    marginBottom: 17,
  },
  bookingWideFieldLabel: {
    ...typography.caption1,
    fontWeight: '600',
    marginLeft: 2,
  },
  bookingInfoCardWide: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    boxShadow: 'none',
    elevation: 0,
    gap: 0,
    marginTop: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  bookingInfoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 18,
    paddingHorizontal: 2,
  },
  bookingInfoHeaderAction: {
    ...typography.caption2,
    fontWeight: '600',
  },
  bookingInfoHeaderTitle: {
    ...typography.title3,
    fontWeight: '600',
  },
  bookingWideCustomScheduleField: {
    gap: 0,
    marginTop: 0,
  },
  bookingWideCustomDateScheduleField: {
    gap: 7,
  },
  bookingWideCustomTimeScheduleField: {
    gap: 9,
  },
  bookingWideCustomScheduleInput: {
    ...typography.caption1,
    fontWeight: '600',
    minHeight: 33,
    minWidth: 0,
    paddingHorizontal: 0,
  },
  bookingWideCustomScheduleInputShell: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    minHeight: 34,
    paddingHorizontal: 0,
  },
  bookingWideCustomScheduleLabel: {
    ...typography.caption1,
    fontWeight: '600',
  },
  bookingWideDescriptionInput: {
    height: 70,
    maxHeight: 70,
    minHeight: 70,
    includeFontPadding: false,
    paddingHorizontal: 0,
    paddingVertical: 0,
    paddingTop: 0,
    textAlignVertical: 'center',
  },
  // textAlignVertical is Android-only; iOS/web ignore it and top-align multiline
  // text inside the fixed 70pt box, so those platforms need explicit padding to
  // land a single line at the same vertical center Android gets for free.
  bookingWideDescriptionInputCenterPad: Platform.OS !== 'android' ? {
    paddingBottom: 0,
    paddingTop: 27.5,
  } : {},
  bookingWideDraftSubmitButton: {
    borderRadius: 14,
    height: 48,
    marginTop: 0,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  bookingWideDraftSubmitText: {
    ...typography.caption1,
    fontWeight: '600',
  },
  bookingWideDraftSubmitWrap: {
    marginTop: 22,
    position: 'relative',
  },
  bookingWideFieldAdornment: {
    alignItems: 'center',
    flexShrink: 0,
    height: 0,
    justifyContent: 'center',
    opacity: 0,
    position: 'relative',
    width: 0,
  },
  bookingWideAuraLayer: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bookingWideHiddenAuraLayer: {
    opacity: 0,
  },
  bookingWideInlineIconShell: {
    alignSelf: 'center',
    borderRadius: 0,
    height: 48,
    width: 42,
  },
  bookingWideInlineInput: {
    ...typography.footnote,
    lineHeight: 15,
    minHeight: 34,
  },
  bookingWideInputRow: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    gap: 14,
    minHeight: 70,
    paddingHorizontal: 0,
    paddingRight: 0,
  },
  bookingWideScheduleHeader: {
    gap: 14,
    marginBottom: 25,
    minHeight: 50,
  },
  bookingWideDateGroup: {
    flex: 1,
    gap: 0,
    minWidth: 0,
  },
  bookingWideDateLabel: {
    ...typography.caption1,
    fontWeight: '600',
  },
  bookingWideScheduleMain: {
    flex: 1,
    minWidth: 0,
    paddingRight: 0,
  },
  bookingWideSchedulePanel: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    boxShadow: 'none',
    minHeight: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  bookingWideScheduleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    paddingTop: 0,
  },
  bookingWideScheduleRowSpaced: {
    marginTop: 20,
  },
  bookingWideCustomScheduleColumn: {
    minWidth: 110,
    paddingLeft: 0,
    width: 110,
  },
  bookingWideDateSelectionLine: {
    borderRadius: 999,
    height: 3,
    marginTop: 8,
    width: '70%',
  },
  bookingWideTimeChip: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    flex: 0,
    minHeight: 34,
    minWidth: 0,
    paddingHorizontal: 0,
    width: '100%',
  },
  bookingWideTimeChipText: {
    ...typography.caption1,
    fontWeight: '600',
  },
  bookingWideTimeGrid: {
    alignItems: 'stretch',
    alignContent: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 0,
    marginTop: 9,
  },
  bookingWideTimeStartSection: {
    marginTop: 0,
  },
  bookingWideTimeSlotGroup: {
    alignItems: 'center',
    flexBasis: '25%',
    flexDirection: 'column',
    flexGrow: 0,
    flexShrink: 0,
    minWidth: 0,
    width: '25%',
  },
  bookingWideTimeSelectionLine: {
    borderRadius: 999,
    height: 3,
    marginTop: 8,
    width: '70%',
  },
  bookingWideTimeStartLabel: {
    ...typography.caption1,
    fontWeight: '600',
    marginLeft: 0,
  },
  bookingWideReadonlyText: {
    ...typography.footnote,
    fontWeight: '600',
  },
} satisfies Record<string, TextStyle | ViewStyle>
