import { StyleSheet } from 'react-native'
import { createSurfaceShadow } from '@/components/ui/tokens'

export const customerV21BookingStyles = StyleSheet.create({
  mediaAnalyzeButtonAura: {
    ...StyleSheet.absoluteFill,
  },
  mediaDescriptionChip: {
    position: 'relative',
    zIndex: 1,
  },
  mediaDescriptionChipAura: {
    bottom: -7,
    left: -9,
    position: 'absolute',
    right: -9,
    top: -7,
    zIndex: 0,
  },
  mediaDescriptionChipFrame: {
    borderRadius: 999,
    overflow: 'visible',
    position: 'relative',
  },
  mediaEvidenceSlot: {
    alignItems: 'center',
    borderRadius: 15,
    borderWidth: 1,
    boxShadow: createSurfaceShadow({ color: '#085F57', offsetY: 7, opacity: 0.08, radius: 14 }),
    flex: 1,
    gap: 4,
    minHeight: 72,
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 8,
  },
  mediaEvidenceSlotActive: {
    boxShadow: createSurfaceShadow({ color: '#08AF9C', offsetY: 7, opacity: 0.13, radius: 14 }),
  },
  mediaHeroAura: {
    bottom: -34,
    left: -32,
    position: 'absolute',
    right: -32,
    top: -24,
    zIndex: 0,
  },
  mediaSlotIcon: {
    height: 30,
    width: 30,
  },
  mediaSlotLabel: {
    fontSize: 9.5,
    fontWeight: '600',
    lineHeight: 12,
    textAlign: 'center',
  },
  mediaSlotValue: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 15,
    textAlign: 'center',
  },
  mediaPrepAura: {
    bottom: -34,
    left: -28,
    position: 'absolute',
    right: -28,
    top: -24,
    zIndex: 0,
  },
  mediaPrepListAura: {
    bottom: -12,
    left: -12,
    position: 'absolute',
    right: -12,
    top: -12,
    zIndex: 0,
  },
  mediaPrepLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  mediaPrepRow: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    boxShadow: createSurfaceShadow({ color: '#08AF9C', offsetY: 6, opacity: 0.045, radius: 12 }),
    flexDirection: 'row',
    gap: 9,
    minHeight: 40,
    paddingHorizontal: 9,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  mediaPrepState: {
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  mediaPrepStateText: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 12,
  },
  mediaPrepValue: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
    maxWidth: 82,
    textAlign: 'right',
  },
  mediaVoice: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 52,
    paddingHorizontal: 12,
  },
  mediaVoiceBody: {
    flex: 1,
    gap: 2,
  },
  mediaVoiceIcon: {
    height: 30,
    width: 30,
  },
  mediaVoicePressed: {
    transform: [{ scale: 0.99 }],
  },
  mediaVoiceTitle: {
    fontSize: 10.5,
    fontWeight: '600',
    lineHeight: 13,
  },
  mediaVoiceValue: {
    fontSize: 9,
    fontWeight: '600',
    lineHeight: 12,
  },
  mediaWave: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    height: 28,
  },
  mediaWaveBar: {
    borderRadius: 2,
    width: 3,
  },
  prepLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
  },
  prepRow: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  prepState: {
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  prepStateText: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
  },
  prepValue: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
    maxWidth: 76,
    textAlign: 'right',
  },
  bookingAddressLookupText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 17,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bookingAddressSuggestionButton: {
    borderBottomWidth: 1,
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bookingAddressSuggestions: {
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    boxShadow: createSurfaceShadow({ color: '#085F57', offsetY: 8, opacity: 0.05, radius: 18 }),
    marginTop: 6,
    overflow: 'hidden',
  },
  bookingAddressSuggestionSubtitle: {
    fontSize: 11.5,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 15,
  },
  bookingAddressSuggestionTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 17,
  },
  bookingDateDay: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  bookingDateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 9,
    position: 'relative',
  },
  bookingDateOption: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '23%',
    flexGrow: 1,
    minHeight: 50,
    minWidth: 68,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  bookingDateValue: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    marginTop: 2,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  bookingCustomScheduleField: {
    gap: 5,
    marginTop: 10,
    position: 'relative',
    zIndex: 1,
  },
  bookingCustomScheduleHint: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 14,
    marginLeft: 2,
  },
  bookingCustomScheduleInput: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 0,
    position: 'relative',
    zIndex: 1,
  },
  bookingCustomScheduleInputShell: {
    borderCurve: 'continuous',
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 44,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    position: 'relative',
  },
  bookingCustomScheduleLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    lineHeight: 14,
    marginLeft: 2,
  },
  bookingDescriptionInput: {
    borderRadius: 18,
    boxShadow: createSurfaceShadow({ color: '#085F57', offsetY: 6, opacity: 0.04, radius: 14 }),
    minHeight: 84,
    paddingHorizontal: 14,
    paddingVertical: 11,
    position: 'relative',
    zIndex: 1,
  },
  bookingDescriptionInputShell: {
    borderCurve: 'continuous',
    borderRadius: 18,
    borderWidth: 1,
    minHeight: 84,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    position: 'relative',
  },
  bookingDraftSubmitButton: {
    borderColor: 'rgba(185,235,226,0.74)',
    boxShadow: createSurfaceShadow({ color: '#08AF9C', offsetY: 8, opacity: 0.08, radius: 18 }),
    marginTop: 14,
  },
  bookingField: {
    gap: 6,
    marginBottom: 9,
    position: 'relative',
    zIndex: 1,
  },
  bookingFieldLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    lineHeight: 14,
    marginLeft: 2,
  },
  bookingInfoCard: {
    borderColor: 'rgba(255,255,255,0.91)',
    borderRadius: 24,
    boxShadow: createSurfaceShadow({ color: '#087D72', offsetY: -3, opacity: 0.10, radius: 26 }),
    gap: 0,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 13,
    position: 'relative',
  },
  bookingInfoMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.8,
    zIndex: 0,
  },
  bookingFormulaMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.94,
    zIndex: 0,
  },
  bookingInlineIcon: {
    height: 28,
    width: 28,
  },
  bookingInlineInput: {
    alignSelf: 'stretch',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    includeFontPadding: false,
    lineHeight: 17,
    minHeight: 28,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    textAlignVertical: 'center',
    width: '100%',
  },
  bookingInlineInputMultiline: {
    lineHeight: 18,
    minHeight: 54,
    paddingBottom: 8,
    paddingTop: 8,
  },
  bookingInlineTextFieldShell: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    width: '100%',
  },
  bookingInlineTextFieldStack: {
    alignSelf: 'stretch',
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  bookingInputRow: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    boxShadow: createSurfaceShadow({ color: '#085F57', offsetY: 6, opacity: 0.04, radius: 14 }),
    flexDirection: 'row',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingRight: 14,
    position: 'relative',
  },
  bookingInputRowMultiline: {
    minHeight: 72,
    paddingVertical: 8,
  },
  bookingProblemField: {
    overflow: 'hidden',
    paddingBottom: 2,
    paddingTop: 2,
  },
  bookingProgressRail: {
    marginTop: 9,
  },
  bookingReadonlyText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  bookingScheduleHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  bookingScheduleContent: {
    position: 'relative',
    zIndex: 1,
  },
  bookingSchedulePanel: {
    borderCurve: 'continuous',
    borderRadius: 18,
    borderWidth: 1,
    boxShadow: createSurfaceShadow({ color: '#085F57', offsetY: 6, opacity: 0.04, radius: 14 }),
    minHeight: 48,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
    position: 'relative',
  },
  bookingSelectedServiceFrame: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    marginTop: 6,
    width: '100%',
  },
  bookingServiceGrid: {
    marginTop: 6,
  },
  bookingSourceStepCard: {
    borderColor: 'rgba(255,255,255,0.88)',
    borderRadius: 24,
    boxShadow: createSurfaceShadow({ color: '#087D72', offsetY: -3, opacity: 0.10, radius: 22 }),
    gap: 0,
    marginBottom: 0,
    minHeight: 74,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
  },
  bookingSourceStepContent: {
    position: 'relative',
    zIndex: 1,
  },
  bookingTimeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 7,
    position: 'relative',
  },
  bookingTimeStartSection: {
    gap: 3,
    marginTop: 12,
  },
  mediaAnalyzeButton: {
    borderColor: 'rgba(185,235,226,0.74)',
    boxShadow: createSurfaceShadow({ color: '#08AF9C', offsetY: 8, opacity: 0.10, radius: 18 }),
    marginTop: 14,
    overflow: 'hidden',
  },
  mediaCaptionText: {
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  mediaCard: {
    gap: 12,
  },
  mediaCaseRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 2,
    marginTop: 2,
  },
  mediaDescriptionCard: {
    minHeight: 84,
  },
  mediaDescriptionQuote: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 20,
    position: 'relative',
    zIndex: 1,
  },
  mediaHeroCard: {
    borderColor: 'rgba(255,255,255,0.90)',
    borderRadius: 30,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    boxShadow: createSurfaceShadow({ color: '#087D72', offsetY: -3, opacity: 0.12, radius: 28 }),
  },
  mediaHeroContent: {
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  mediaHeroIcon: {
    height: 66,
    minHeight: 66,
    minWidth: 66,
    width: 66,
  },
  mediaMicroNote: {
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    marginHorizontal: 12,
    marginTop: 8,
    textAlign: 'center',
  },
  mediaPrepSourceCard: {
    gap: 0,
    minHeight: 188,
  },
  mediaPrepStepList: {
    gap: 6,
    overflow: 'hidden',
    padding: 1,
    position: 'relative',
    zIndex: 1,
  },
  mediaSourceListCard: {
    borderColor: 'rgba(255,255,255,0.91)',
    borderRadius: 25,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 13,
    position: 'relative',
    boxShadow: createSurfaceShadow({ color: '#087D72', offsetY: -3, opacity: 0.09, radius: 22 }),
  },
  mediaStrip: {
    flexDirection: 'row',
    gap: 7,
  },
  mediaVoiceError: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
    marginLeft: 8,
    marginTop: -4,
  },
})
