import { typography } from '@/design/theme'
import { StyleSheet } from 'react-native'

import { bookingFormStyleDefinitions } from './booking-form-styles'

export const customerV21BookingStyles = StyleSheet.create({
  mediaAnalyzeButtonAura: {
    ...StyleSheet.absoluteFill,
  },
  mediaDescriptionChip: {
    position: 'relative',
    zIndex: 1,
  },
  mediaDescriptionChipAura: {
    bottom: -7,
    left: -9,
    position: 'absolute',
    right: -9,
    top: -7,
    zIndex: 0,
  },
  mediaDescriptionChipFrame: {
    borderRadius: 999,
    overflow: 'visible',
    position: 'relative',
  },
  mediaEvidenceSlot: {
    alignItems: 'center',
    borderRadius: 15,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    minHeight: 72,
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 8,
    shadowColor: '#085F57',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
  },
  mediaEvidenceSlotActive: {
    shadowColor: '#08AF9C',
    shadowOpacity: 0.13,
  },
  mediaHeroAura: {
    bottom: -34,
    left: -32,
    position: 'absolute',
    right: -32,
    top: -24,
    zIndex: 0,
  },
  mediaSlotIcon: {
    height: 30,
    width: 30,
  },
  mediaSlotLabel: {
    ...typography.caption2,
    fontWeight: '600',
    textAlign: 'center',
  },
  mediaSlotValue: {
    ...typography.caption1,
    fontWeight: '600',
    textAlign: 'center',
  },
  mediaPrepAura: {
    bottom: -34,
    left: -28,
    position: 'absolute',
    right: -28,
    top: -24,
    zIndex: 0,
  },
  mediaPrepListAura: {
    bottom: -12,
    left: -12,
    position: 'absolute',
    right: -12,
    top: -12,
    zIndex: 0,
  },
  mediaPrepLabel: {
    flex: 1,
    ...typography.caption1,
    fontWeight: '600',
  },
  mediaPrepRow: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 40,
    paddingHorizontal: 9,
    paddingVertical: 8,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.045,
    shadowRadius: 12,
    zIndex: 1,
  },
  mediaPrepState: {
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  mediaPrepStateText: {
    ...typography.caption2,
    fontWeight: '600',
  },
  mediaPrepValue: {
    ...typography.caption2,
    fontWeight: '600',
    maxWidth: 82,
    textAlign: 'right',
  },
  mediaVoice: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 52,
    paddingHorizontal: 12,
  },
  mediaVoiceBody: {
    flex: 1,
    gap: 2,
  },
  mediaVoiceIcon: {
    height: 30,
    width: 30,
  },
  mediaVoicePressed: {
    transform: [{ scale: 0.99 }],
  },
  mediaVoiceTitle: {
    ...typography.caption2,
    fontWeight: '600',
  },
  mediaVoiceValue: {
    ...typography.caption2,
    fontWeight: '600',
  },
  mediaWave: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    height: 28,
  },
  mediaWaveBar: {
    borderRadius: 2,
    width: 3,
  },
  prepLabel: {
    flex: 1,
    ...typography.footnote,
    fontWeight: '600',
  },
  prepRow: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  prepState: {
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  prepStateText: {
    ...typography.caption2,
    fontWeight: '600',
  },
  prepValue: {
    ...typography.caption2,
    fontWeight: '600',
    maxWidth: 76,
    textAlign: 'right',
  },
  bookingAddressLookupText: {
    ...typography.caption1,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bookingAddressSuggestionButton: {
    borderBottomWidth: 1,
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bookingAddressSuggestions: {
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 6,
    overflow: 'hidden',
    shadowColor: '#085F57',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
  },
  bookingAddressSuggestionSubtitle: {
    ...typography.caption2,
    fontWeight: '600',
  },
  bookingAddressSuggestionTitle: {
    ...typography.caption1,
    fontWeight: '600',
  },
  bookingDateDay: {
    ...typography.caption2,
    fontWeight: '600',
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  bookingDateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 9,
    position: 'relative',
  },
  bookingDateOption: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '23%',
    flexGrow: 1,
    minHeight: 50,
    minWidth: 68,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  bookingDateValue: {
    ...typography.caption1,
    fontWeight: '600',
    marginTop: 2,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  bookingCustomScheduleField: {
    gap: 5,
    marginTop: 10,
    position: 'relative',
    zIndex: 1,
  },
  bookingCustomScheduleHint: {
    ...typography.caption2,
    fontWeight: '600',
    marginLeft: 2,
  },
  bookingCustomScheduleInput: {
    ...typography.caption1,
    fontWeight: '600',
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 0,
    position: 'relative',
    zIndex: 1,
  },
  bookingCustomScheduleInputShell: {
    borderCurve: 'continuous',
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 44,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    position: 'relative',
  },
  bookingCustomScheduleLabel: {
    ...typography.caption2,
    fontWeight: '600',
    marginLeft: 2,
  },
  bookingDescriptionInput: {
    borderRadius: 18,
    minHeight: 72,
    paddingHorizontal: 14,
    paddingVertical: 11,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 14,
    zIndex: 1,
  },
  bookingDescriptionInputShell: {
    borderCurve: 'continuous',
    borderRadius: 18,
    borderWidth: 1,
    minHeight: 72,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    position: 'relative',
  },
  bookingDraftSubmitButton: {
    borderColor: 'rgba(185,235,226,0.74)',
    marginTop: 14,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  bookingField: {
    gap: 6,
    marginBottom: 9,
    position: 'relative',
    zIndex: 1,
  },
  bookingFieldLabel: {
    ...typography.caption2,
    fontWeight: '600',
    marginLeft: 2,
  },
  bookingInfoCard: {
    borderColor: 'rgba(255,255,255,0.91)',
    borderRadius: 24,
    gap: 0,
    marginTop: 18,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 13,
    position: 'relative',
    shadowColor: '#087D72',
    shadowOpacity: 0.10,
    shadowRadius: 26,
  },
  bookingInfoMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.8,
    zIndex: 0,
  },
  bookingFormulaMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.94,
    zIndex: 0,
  },
  bookingInlineIcon: {
    height: 28,
    width: 28,
  },
  bookingInlineIconShell: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 13,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  bookingInlineChevron: {
    ...typography.title2,
    marginLeft: 4,
    textAlign: 'center',
    width: 18,
  },
  bookingInlineInput: {
    alignSelf: 'stretch',
    flex: 1,
    ...typography.caption1,
    fontWeight: '600',
    includeFontPadding: false,
    minHeight: 28,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    textAlignVertical: 'center',
    width: '100%',
  },
  bookingInlineInputMultiline: {
    ...typography.footnote,
    fontWeight: '600',
    minHeight: 54,
    paddingBottom: 8,
    paddingTop: 8,
  },
  bookingInlineTextFieldShell: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 0,
    paddingVertical: 0,
    width: '100%',
  },
  bookingInlineTextFieldStack: {
    alignSelf: 'stretch',
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  bookingInputRow: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingRight: 14,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 14,
  },
  bookingInputRowMultiline: {
    minHeight: 72,
    paddingVertical: 8,
  },
  bookingProblemField: {
    overflow: 'hidden',
    paddingBottom: 2,
    paddingTop: 2,
  },
  bookingJourneyArtwork: {
    height: 164,
    width: '100%',
    zIndex: 0,
  },
  bookingJourneyArtworkFrame: {
    marginHorizontal: -16,
    marginTop: -11,
    overflow: 'hidden',
    position: 'relative',
    width: 'auto',
  },
  bookingJourneyCaption: {
    ...typography.caption2,
    fontWeight: '600',
    textAlign: 'center',
  },
  bookingJourneyCopy: {
    alignItems: 'center',
    gap: 1,
    paddingBottom: 7,
    paddingHorizontal: 12,
    paddingTop: 6,
    position: 'relative',
    zIndex: 2,
  },
  bookingJourneyTitle: {
    ...typography.headline,
    textAlign: 'center',
  },
  bookingWorkartServiceArtwork: {
    height: '100%',
    width: '100%',
  },
  bookingWorkartServiceCopy: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    overflow: 'hidden',
    paddingLeft: 16,
    paddingRight: 14,
    paddingVertical: 8,
  },
  bookingWorkartServiceDetail: {
    ...typography.caption2,
    fontWeight: '600',
  },
  bookingWorkartServiceDetailRail: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 5,
    marginTop: 2,
    overflow: 'hidden',
  },
  bookingWorkartServiceDetailRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    minWidth: 0,
  },
  bookingWorkartServiceDetailSeparator: {
    ...typography.caption1,
    fontWeight: '600',
  },
  bookingWorkartServiceHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    minWidth: 0,
  },
  bookingWorkartServiceTile: {
    alignItems: 'stretch',
    alignSelf: 'stretch',
    borderCurve: 'continuous',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 0,
    minHeight: 56,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  bookingWorkartServiceTitle: {
    flex: 1,
    ...typography.subheadline,
    fontWeight: '600',
    minWidth: 0,
  },
  bookingWorkartServiceVisualPanel: {
    alignSelf: 'stretch',
    flexBasis: '27%',
    flexGrow: 0,
    flexShrink: 0,
    justifyContent: 'center',
    minHeight: 56,
    overflow: 'hidden',
    position: 'relative',
    width: '27%',
  },
  bookingWorkartServiceWash: {
    bottom: 0,
    right: -1,
    position: 'absolute',
    top: 0,
    width: 42,
    zIndex: 1,
  },
  bookingReadonlyText: {
    flex: 1,
    ...typography.caption1,
    fontWeight: '600',
  },
  bookingScheduleHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  bookingScheduleContent: {
    position: 'relative',
    zIndex: 1,
  },
  bookingSchedulePanel: {
    borderCurve: 'continuous',
    borderRadius: 18,
    borderWidth: 1,
    minHeight: 48,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 14,
  },
  bookingSelectedServiceFrame: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    marginTop: 6,
    width: '100%',
  },
  bookingServiceGrid: {
    alignSelf: 'stretch',
    flexDirection: 'column',
    flexWrap: 'nowrap',
    marginHorizontal: 4,
    marginTop: 6,
  },
  bookingTimeGrid: {
    alignContent: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 0,
    marginTop: 7,
    position: 'relative',
  },
  bookingTimeSlotGroup: {
    flexBasis: '25%',
    flexGrow: 0,
    flexShrink: 0,
    minWidth: 0,
    width: '25%',
  },
  bookingTimeChip: {
    alignSelf: 'stretch',
    minHeight: 34,
    minWidth: 0,
    paddingHorizontal: 0,
    width: '100%',
  },
  bookingTimeStartSection: {
    gap: 3,
    marginTop: 12,
  },
  mediaAnalyzeButton: {
    borderColor: 'rgba(185,235,226,0.74)',
    marginTop: 14,
    overflow: 'hidden',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 18,
  },
  mediaCaptionText: {
    ...typography.caption2,
    marginTop: 2,
  },
  mediaCard: {
    gap: 12,
  },
  mediaCaseRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 2,
    marginTop: 2,
  },
  mediaDescriptionCard: {
    minHeight: 84,
  },
  mediaDescriptionQuote: {
    ...typography.subheadline,
    fontWeight: '600',
    position: 'relative',
    zIndex: 1,
  },
  mediaHeroCard: {
    borderColor: 'rgba(255,255,255,0.90)',
    borderRadius: 30,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    shadowColor: '#087D72',
    shadowOpacity: 0.12,
    shadowRadius: 28,
  },
  mediaHeroContent: {
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  mediaHeroIcon: {
    height: 66,
    minHeight: 66,
    minWidth: 66,
    width: 66,
  },
  mediaMicroNote: {
    ...typography.caption2,
    fontWeight: '600',
    marginHorizontal: 12,
    marginTop: 8,
    textAlign: 'center',
  },
  mediaPrepSourceCard: {
    gap: 0,
    minHeight: 188,
  },
  mediaPrepStepList: {
    gap: 6,
    overflow: 'hidden',
    padding: 1,
    position: 'relative',
    zIndex: 1,
  },
  mediaSourceListCard: {
    borderColor: 'rgba(255,255,255,0.91)',
    borderRadius: 25,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 13,
    position: 'relative',
    shadowColor: '#087D72',
    shadowOpacity: 0.09,
    shadowRadius: 22,
  },
  mediaStrip: {
    flexDirection: 'row',
    gap: 7,
  },
  mediaVoiceError: {
    ...typography.caption2,
    fontWeight: '600',
    marginLeft: 8,
    marginTop: -4,
  },
  ...bookingFormStyleDefinitions,
})
