import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  acceptBoundaryAura: {
    bottom: -72,
    height: 190,
    left: -50,
    opacity: 0.62,
    right: -50,
    top: -60,
  },
  acceptBoundaryNote: {
    backgroundColor: 'rgba(239,255,251,0.82)',
    borderColor: 'rgba(154,226,214,0.86)',
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 13,
    paddingVertical: 12,
    position: 'relative',
  },
  acceptBoundaryStrong: {
    color: color.text.strong,
    fontWeight: '700',
  },
  acceptBoundaryText: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
    position: 'relative',
    zIndex: 1,
  },
  acceptBoundaryZipAura: {
    height: 148,
    opacity: 0.44,
    right: -52,
    top: -46,
    width: 228,
  },
  acceptCheckLabel: {
    color: color.text.strong,
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  acceptCheckMeta: {
    color: color.text.secondary,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    maxWidth: 86,
    position: 'relative',
    textAlign: 'right',
    zIndex: 1,
  },
  acceptCheckRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(249,255,252,0.78)',
    borderColor: 'rgba(184,231,223,0.7)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 38,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  acceptCheckRowAura: {
    bottom: -40,
    height: 118,
    opacity: 0.5,
    right: -54,
    top: -38,
    width: 188,
  },
  acceptCheckRowGap: {},
  acceptCheckState: {
    alignItems: 'center',
    backgroundColor: 'rgba(235,245,243,0.9)',
    borderRadius: 12,
    height: 22,
    justifyContent: 'center',
    position: 'relative',
    width: 22,
    zIndex: 1,
  },
  acceptCheckStateBlocked: {
    backgroundColor: 'rgba(255,240,230,0.9)',
  },
  acceptCheckStateDone: {
    backgroundColor: 'rgba(209,255,244,0.95)',
  },
  acceptCheckStateText: {
    color: color.text.muted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
  },
  acceptCheckStateTextDone: {
    color: color.brand.primaryDark,
  },
  acceptChecklistAura: {
    bottom: -70,
    height: 240,
    left: -56,
    opacity: 0.64,
    right: -56,
    top: -56,
  },
  acceptChecklistCard: {
    backgroundColor: 'rgba(249,255,252,0.8)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 7,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    ...shadow.soft,
  },
  acceptChecklistZipAura: {
    height: 190,
    opacity: 0.48,
    right: -82,
    top: -58,
    width: 270,
  },
  acceptCommitmentAura: {
    bottom: -70,
    height: 230,
    left: -54,
    opacity: 0.58,
    right: -54,
    top: -58,
  },
  acceptCommitmentCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(249,255,252,0.82)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 78,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    ...shadow.soft,
  },
  acceptCommitmentCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  acceptCommitmentIcon: {
    height: 40,
    width: 40,
  },
  acceptCommitmentIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 17,
    borderWidth: 1,
    flexShrink: 0,
    height: 50,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 50,
    zIndex: 1,
  },
  acceptCommitmentMeta: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
    marginTop: 3,
  },
  acceptCommitmentTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  acceptCommitmentZipAura: {
    height: 178,
    opacity: 0.42,
    right: -70,
    top: -48,
    width: 260,
  },
  acceptSummaryAura: {
    bottom: -88,
    height: 272,
    left: -66,
    opacity: 1,
    right: -56,
    top: -72,
  },
  acceptSummaryCard: {
    backgroundColor: 'rgba(244,255,252,0.88)',
    borderColor: 'rgba(161,235,224,0.62)',
    borderRadius: 28,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 116,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
  },
  acceptSummaryCopy: {
    alignSelf: 'stretch',
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  acceptSummaryIcon: {
    alignSelf: 'center',
    height: 46,
    width: 46,
  },
  acceptSummaryIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 20,
    borderWidth: 1,
    flexShrink: 0,
    height: 58,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 58,
  },
  acceptSummaryLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    position: 'relative',
    zIndex: 1,
  },
  acceptSummaryMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    marginTop: 3,
    minWidth: 0,
  },
  acceptSummaryPrice: {
    color: color.brand.primaryDark,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  acceptSummaryPriceSlot: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
    justifyContent: 'center',
    maxWidth: 116,
    minWidth: 62,
  },
  acceptSummaryTitle: {
    color: color.text.strong,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
    minWidth: 0,
  },
  acceptSummaryZipAura: {
    height: 232,
    opacity: 0.78,
    right: -86,
    top: -64,
    width: 318,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
})
