import { StyleSheet } from 'react-native'

import { color, component, glass, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  actionRailButtonText: {
    fontSize: 13,
    lineHeight: 17,
  },
  actionRailFormulaAura: {
    bottom: -42,
    left: -34,
    opacity: 0.82,
    right: -34,
    top: -48,
  },
  actionRailPrimaryText: {
    color: color.brand.primaryDark,
  },
  actionRailZipAura: {
    bottom: -18,
    height: 118,
    left: '42%',
    opacity: 0.56,
    right: -42,
    top: -26,
  },
  chatBubble: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: color.surface.stroke,
    borderRadius: 18,
    borderWidth: 1,
    maxWidth: '86%',
    minWidth: 0,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  chatBubbleBody: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  chatBubbleLabel: {
    color: color.text.muted,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    marginTop: 6,
    textAlign: 'right',
  },
  chatBubbleRight: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(197,248,235,0.72)',
    borderColor: 'rgba(13,174,154,0.25)',
  },
  navButton: {
    alignItems: 'center',
    borderRadius: component.button.secondary.radius,
    flex: 1,
    justifyContent: 'center',
    minHeight: 52,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 14,
    position: 'relative',
    zIndex: 1,
  },
  navButtonDisabled: {
    opacity: 0.52,
  },
  navButtonDisabledText: {
    color: color.text.muted,
  },
  navButtonPrimary: {
    backgroundColor: color.brand.primary,
    ...shadow.primary,
  },
  navButtonPrimaryText: {
    color: color.text.inverse,
  },
  navButtonSecondary: {
    backgroundColor: glass.bgStrong,
    borderColor: color.surface.strokeStrong,
    borderWidth: 1,
  },
  navButtonText: {
    color: color.brand.primaryDark,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 19,
    textAlign: 'center',
  },
  navigationRow: {
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    position: 'relative',
  },
  onsiteAdvisoryRail: {
    backgroundColor: 'rgba(239, 251, 246, 0.9)',
    borderColor: color.mint.mint100,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  onsiteAdvisoryText: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  primaryActionButton: {
    alignItems: 'center',
    backgroundColor: color.brand.primary,
    borderColor: component.button.primary.border,
    borderRadius: 26,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 56,
    overflow: 'hidden',
    paddingHorizontal: 18,
    position: 'relative',
    ...shadow.primary,
  },
  primaryActionButtonSource: {
    backgroundColor: '#13CBB8',
    borderColor: 'rgba(2,126,115,0.22)',
    borderWidth: 1,
    shadowColor: '#059F8E',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.27,
    shadowRadius: 28,
  },
  primaryActionText: {
    color: color.text.inverse,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0,
    zIndex: 2,
  },
  sourceActionDisabled: {
    backgroundColor: component.button.disabled.bg,
    borderColor: component.button.disabled.border,
    shadowOpacity: 0,
  },
  sourceActionDisabledText: {
    color: component.button.disabled.text,
  },
  suggestionChip: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    maxWidth: '32%',
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  suggestionChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  suggestionChipText: {
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
    textAlign: 'center',
  },
})
