import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  approvalHeroAmount: {
    color: color.brand.primaryDark,
    ...typography.title2,
    fontWeight: '600',
    marginTop: 8,
  },
  approvalHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 118,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  approvalHeroCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  approvalHeroMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    marginTop: 3,
  },
  approvalHeroPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF7E6',
    borderColor: '#F6D18B',
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.text.strong,
    ...typography.caption2,
    fontWeight: '600',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  approvalLens: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 34,
    borderWidth: 1,
    flexShrink: 0,
    height: 74,
    justifyContent: 'center',
    position: 'relative',
    width: 74,
    zIndex: 1,
    ...shadow.primary,
  },
  approvalLensLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  approvalLensValue: {
    color: color.brand.primaryDark,
    ...typography.title3,
    fontWeight: '600',
  },
  checkInHeroAura: {
    bottom: -92,
    height: 292,
    left: -78,
    opacity: 1,
    right: -58,
    top: -86,
  },
  checkInHeroZipAura: {
    height: 252,
    opacity: 0.84,
    right: -96,
    top: -82,
    width: 336,
  },
  settlementCell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 70,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 8,
    position: 'relative',
    ...shadow.soft,
  },
  settlementCellMintAura: {
    opacity: 0.78,
  },
  settlementCellZipMintAura: {
    opacity: 0.58,
  },
  settlementFormula: {
    color: color.text.muted,
    ...typography.caption2,
    paddingHorizontal: 4,
  },
  settlementGroup: {
    gap: 8,
  },
  settlementLabel: {
    color: color.text.muted,
    flexShrink: 1,
    ...typography.caption2,
    fontWeight: '600',
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  settlementStrip: {
    flexDirection: 'row',
    gap: 8,
  },
  settlementValue: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.caption1,
    fontWeight: '600',
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
})
