import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  caseClosedAmount: {
    color: color.brand.primaryDark,
    fontVariant: ['tabular-nums'],
    marginTop: 6,
    textAlign: 'center',
    ...typography.title1,
  },
  caseClosedAmountLabel: {
    color: color.text.muted,
    maxWidth: '84%',
    textAlign: 'center',
    ...typography.caption2,
  },
  caseClosedHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    gap: 8,
    minHeight: 250,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 20,
    position: 'relative',
    ...shadow.raised,
  },
  caseClosedTitle: {
    color: color.text.strong,
    marginTop: 10,
    maxWidth: '90%',
    textAlign: 'center',
    ...typography.title2,
  },
  caseTrailCard: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  caseTrailCopy: {
    flex: 1,
    gap: 3,
    marginLeft: 46,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  caseTrailIcon: {
    height: 46,
    position: 'relative',
    width: 46,
    zIndex: 1,
  },
  caseTrailIconMintAura: {
    opacity: 0.92,
  },
  caseTrailIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 21,
    borderWidth: 1,
    flexShrink: 0,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 64,
    zIndex: 1,
  },
  caseTrailMeta: {
    color: color.text.secondary,
    ...typography.footnote,
  },
  caseTrailRow: {
    alignItems: 'stretch',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 0,
    minHeight: 96,
    overflow: 'hidden',
    padding: 13,
    position: 'relative',
  },
  caseTrailRowAura: {
    bottom: -56,
    height: 208,
    left: -52,
    opacity: 0.74,
    right: -52,
    top: -56,
  },
  caseTrailRowZipAura: {
    height: 220,
    opacity: 0.56,
    right: -92,
    top: -78,
    width: 300,
  },
  caseTrailStatus: {
    alignSelf: 'center',
    backgroundColor: 'rgba(230,251,243,0.88)',
    borderColor: 'rgba(127,226,215,0.76)',
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    maxWidth: 86,
    marginLeft: 10,
    minWidth: 64,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
    ...typography.caption2,
  },
  caseTrailTitle: {
    color: color.text.strong,
    ...typography.subheadline,
  },
  chatMessage: {
    borderRadius: 18,
    maxWidth: '82%',
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...shadow.soft,
  },
  chatMessageBody: {
    color: color.text.secondary,
    marginTop: 3,
    ...typography.footnote,
  },
  chatMessageLabel: {
    color: color.text.strong,
    ...typography.caption2,
  },
  chatMessagePeer: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderBottomLeftRadius: 6,
    borderColor: 'rgba(216,235,232,0.9)',
    borderWidth: 1,
  },
  chatMessageSystem: {
    alignSelf: 'stretch',
    backgroundColor: 'rgba(247,250,255,0.92)',
    borderColor: '#D9E5FB',
    borderWidth: 1,
    maxWidth: '100%',
  },
  chatMessageUser: {
    alignSelf: 'flex-end',
    backgroundColor: color.mint.mint100,
    borderBottomRightRadius: 6,
    borderColor: 'rgba(126,224,207,0.48)',
    borderWidth: 1,
  },
  chatPreviewCard: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 9,
    overflow: 'hidden',
    padding: 11,
    ...shadow.soft,
  },
  chatPreviewRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  chatPreviewRowUser: {
    justifyContent: 'flex-end',
  },
})
