import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  checkInChecklist: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 8,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
  },
  checkInChecklistAura: {
    bottom: -88,
    height: 282,
    left: -76,
    opacity: 0.96,
    right: -58,
    top: -78,
  },
  checkInChecklistZipAura: {
    height: 246,
    opacity: 0.78,
    right: -96,
    top: -82,
    width: 326,
  },
  checkInHero: {
    alignItems: 'center',
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 112,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  checkInHeroAura: {
    bottom: -92,
    height: 292,
    left: -78,
    opacity: 1,
    right: -58,
    top: -86,
  },
  checkInHeroZipAura: {
    height: 252,
    opacity: 0.84,
    right: -96,
    top: -82,
    width: 336,
  },
  checkInIcon: {
    height: 42,
    position: 'relative',
    width: 42,
    zIndex: 1,
  },
  checkInIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 20,
    borderWidth: 1,
    height: 58,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 58,
  },
  checkInKicker: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  checkInLabel: {
    color: color.text.strong,
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    minWidth: 0,
  },
  checkInMeta: {
    color: color.text.muted,
    flexShrink: 1,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    maxWidth: 86,
    minWidth: 44,
    textAlign: 'right',
  },
  checkInRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: color.surface.stroke,
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 56,
    paddingHorizontal: 10,
    paddingVertical: 9,
    position: 'relative',
    zIndex: 1,
  },
  checkInState: {
    alignItems: 'center',
    backgroundColor: color.mint.mint50,
    borderRadius: 13,
    height: 27,
    justifyContent: 'center',
    width: 27,
  },
  checkInStateActive: {
    backgroundColor: color.mint.mint100,
  },
  checkInStateDone: {
    backgroundColor: color.brand.primary,
  },
  checkInStateText: {
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
  },
  checkInStateTextOn: {
    color: color.text.inverse,
  },
  checkInTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  checkInTitle: {
    color: color.text.strong,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 5,
  },
  checkInTitleMeta: {
    color: color.text.muted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 1,
  },
  contactBody: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  contactCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 76,
    overflow: 'hidden',
    padding: 11,
    position: 'relative',
    ...shadow.soft,
  },
  contactIcon: {
    height: 36,
    width: 36,
  },
  contactIconRow: {
    flexDirection: 'row',
    flexShrink: 0,
    gap: 6,
    position: 'relative',
    zIndex: 1,
  },
  contactIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 17,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 48,
    zIndex: 1,
  },
  contactListAura: {
    bottom: -70,
    height: 210,
    left: -48,
    opacity: 0.68,
    right: -52,
    top: -58,
  },
  contactListZipAura: {
    height: 198,
    opacity: 0.54,
    right: -80,
    top: -70,
    width: 282,
  },
  contactMiniIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 14,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 28,
    ...shadow.soft,
  },
  contactMiniIconImage: {
    height: 17,
    width: 17,
  },
  contactText: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  contactTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
})
