import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  completionHeroAura: {
    bottom: -92,
    height: 292,
    left: -78,
    opacity: 1,
    right: -58,
    top: -86,
  },
  completionHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 118,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  completionHeroCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  completionHeroMeta: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 3,
  },
  completionHeroTitle: {
    color: color.text.strong,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 23,
    marginTop: 0,
  },
  completionHeroZipAura: {
    height: 252,
    opacity: 0.84,
    right: -96,
    top: -82,
    width: 336,
  },
  completionLens: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 34,
    borderWidth: 1,
    flexShrink: 0,
    height: 74,
    justifyContent: 'center',
    position: 'relative',
    width: 74,
    zIndex: 1,
    ...shadow.primary,
  },
  completionLensLabel: {
    color: color.text.muted,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 11,
  },
  completionLensValue: {
    color: color.brand.primaryDark,
    fontSize: 25,
    fontWeight: '700',
    lineHeight: 29,
  },
  finalChecklistAura: {
    bottom: -88,
    height: 282,
    left: -76,
    opacity: 0.96,
    right: -58,
    top: -78,
  },
  finalChecklistCard: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 25,
    borderWidth: 1,
    gap: 7,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    ...shadow.soft,
  },
  finalChecklistMeta: {
    color: color.text.muted,
    flexShrink: 1,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    maxWidth: 78,
    minWidth: 48,
    textAlign: 'right',
  },
  finalChecklistRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: color.surface.stroke,
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  finalChecklistState: {
    alignItems: 'center',
    backgroundColor: '#EDF3F2',
    borderRadius: 12,
    height: 25,
    justifyContent: 'center',
    width: 25,
  },
  finalChecklistStateDone: {
    backgroundColor: color.brand.primary,
  },
  finalChecklistStateText: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
  },
  finalChecklistStateTextDone: {
    color: color.text.inverse,
  },
  finalChecklistTitle: {
    color: color.text.strong,
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    minWidth: 0,
  },
  finalChecklistZipAura: {
    height: 246,
    opacity: 0.78,
    right: -96,
    top: -82,
    width: 326,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
})
