import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  evidencePickerButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 11,
    height: 60,
    justifyContent: 'center',
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 10,
    position: 'relative',
    ...shadow.soft,
  },
  evidencePickerIcon: {
    height: 38,
    position: 'relative',
    width: 38,
    zIndex: 1,
  },
  evidencePickerRow: {
    flexDirection: 'row',
    gap: 10,
  },
  evidencePickerText: {
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
    position: 'relative',
    zIndex: 1,
  },
  evidenceTray: {
    flexDirection: 'row',
    gap: 9,
  },
  evidenceTrayBadge: {
    backgroundColor: 'rgba(4,29,34,0.66)',
    borderRadius: radius.pill,
    bottom: 7,
    color: color.text.inverse,
    fontSize: 8,
    fontWeight: '700',
    lineHeight: 10,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
    position: 'absolute',
    right: 7,
  },
  evidenceTrayIcon: {
    height: 34,
    width: 34,
  },
  evidenceTrayIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderColor: 'rgba(255,255,255,0.8)',
    borderRadius: 22,
    borderWidth: 1,
    height: 54,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 54,
  },
  evidenceTrayImage: {
    height: '100%',
    width: '100%',
  },
  evidenceTrayTile: {
    alignItems: 'center',
    backgroundColor: '#D6E7E4',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    height: 82,
    justifyContent: 'center',
    minWidth: 0,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  navButtonDisabled: {
    opacity: 0.52,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
})
