import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  iconTileMintAura: {
    opacity: 0.92,
  },
  offerDetailChip: {
    backgroundColor: 'rgba(227,255,247,0.88)',
    borderColor: 'rgba(154,226,214,0.86)',
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  offerDetailChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 12,
    position: 'relative',
    zIndex: 1,
  },
  offerDetailIcon: {
    alignSelf: 'center',
    height: 44,
    width: 44,
  },
  offerDetailIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 18,
    borderWidth: 1,
    flexShrink: 0,
    height: 54,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 54,
  },
  offerDetailEmptyIcon: {
    flexShrink: 0,
    height: 54,
    width: 54,
  },
  offerDetailEmptySummaryLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
    minHeight: 104,
    position: 'relative',
    zIndex: 1,
  },
  offerDetailListAura: {
    bottom: -70,
    height: 246,
    left: -56,
    opacity: 0.66,
    right: -56,
    top: -56,
  },
  offerDetailListCard: {
    backgroundColor: 'rgba(249,255,252,0.8)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  offerDetailListDivider: {
    borderTopColor: 'rgba(205,226,222,0.78)',
    borderTopWidth: 1,
  },
  offerDetailListLowerAura: {
    bottom: -76,
    height: 220,
    left: -64,
    opacity: 0.46,
    right: -36,
    top: 'auto',
  },
  offerDetailListRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 74,
    padding: 12,
    position: 'relative',
    zIndex: 1,
  },
  offerDetailListZipAura: {
    height: 196,
    opacity: 0.52,
    right: -82,
    top: -58,
    width: 274,
  },
  offerDetailMeta: {
    color: color.text.muted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 3,
    minWidth: 0,
  },
  offerDetailPrice: {
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22,
    maxWidth: 124,
    minWidth: 86,
    textAlign: 'right',
  },
  offerDetailRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  offerDetailRowIcon: {
    alignSelf: 'center',
    flexShrink: 0,
    height: 40,
    position: 'relative',
    width: 40,
    zIndex: 1,
  },
  offerDetailRowMeta: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
    marginTop: 3,
  },
  offerDetailRowStatus: {
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 0,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    maxWidth: 82,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: 'center',
  },
  offerDetailRowTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
  },
  offerDetailStatusChip: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  offerDetailSummaryAura: {
    bottom: -86,
    height: 276,
    left: -60,
    opacity: 0.9,
    right: -60,
    top: -64,
  },
  offerDetailSummaryCard: {
    backgroundColor: 'rgba(249,255,252,0.84)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 24,
    borderWidth: 1,
    minHeight: 132,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
  },
  offerDetailSummaryCopy: {
    flex: 1,
    minWidth: 0,
  },
  offerDetailSummaryLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    position: 'relative',
    zIndex: 1,
  },
  offerDetailSummaryZipAura: {
    height: 210,
    opacity: 0.66,
    right: -76,
    top: -48,
    width: 292,
  },
  offerDetailTitle: {
    color: color.text.strong,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 7,
    minWidth: 0,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
})
