import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  checkInChecklistAura: {
    bottom: -88,
    height: 282,
    left: -76,
    opacity: 0.96,
    right: -58,
    top: -78,
  },
  checkInChecklistZipAura: {
    height: 246,
    opacity: 0.78,
    right: -96,
    top: -82,
    width: 326,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  progressRail: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    position: 'relative',
    zIndex: 1,
  },
  railCard: {
    backgroundColor: 'rgba(255,255,255,0.73)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 13,
    paddingVertical: 12,
    position: 'relative',
    ...shadow.soft,
  },
  railLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    minWidth: 0,
    textAlign: 'center',
    width: '100%',
  },
  railLabelActive: {
    color: color.brand.primaryDark,
    fontWeight: '600',
  },
  railLine: {
    backgroundColor: '#DCEBEA',
    borderRadius: 2,
    height: 2,
    left: '50%',
    position: 'absolute',
    right: '-50%',
    top: 11,
    zIndex: 0,
  },
  railLineDone: {
    backgroundColor: color.brand.primary,
  },
  railNode: {
    alignItems: 'center',
    backgroundColor: '#EEF4F3',
    borderColor: '#E0EBEA',
    borderRadius: 12,
    borderWidth: 1,
    height: 23,
    justifyContent: 'center',
    width: 23,
    zIndex: 1,
  },
  railNodeActive: {
    shadowColor: color.brand.primary,
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  railNodeOn: {
    backgroundColor: color.brand.primary,
    borderColor: color.brand.primary,
  },
  railNodeText: {
    color: '#8DA1A4',
    ...typography.caption2,
    fontWeight: '600',
  },
  railNodeTextOn: {
    color: color.text.inverse,
  },
  railSegment: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    minWidth: 0,
    position: 'relative',
  },
  stepList: {
    gap: 7,
  },
  stepListFormula: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 25,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 10,
    position: 'relative',
    ...shadow.soft,
  },
  stepMeta: {
    color: color.text.muted,
    flexShrink: 1,
    ...typography.caption2,
    fontWeight: '600',
    marginLeft: 'auto',
    maxWidth: 86,
    minWidth: 48,
    textAlign: 'right',
  },
  stepRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(247,255,251,0.76)',
    borderColor: 'rgba(216,235,232,0.8)',
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 56,
    paddingHorizontal: 10,
    paddingVertical: 9,
    position: 'relative',
    zIndex: 1,
  },
  stepRowActive: {
    borderColor: 'rgba(13,174,154,0.34)',
    shadowColor: color.brand.primary,
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
  },
  stepRowDone: {
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  stepState: {
    alignItems: 'center',
    backgroundColor: '#EDF3F2',
    borderRadius: 12,
    height: 27,
    justifyContent: 'center',
    width: 27,
  },
  stepStateActive: {
    backgroundColor: color.brand.primary,
    shadowColor: color.brand.primary,
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
  },
  stepStateDone: {
    backgroundColor: color.mint.mint50,
  },
  stepStateText: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  stepStateTextActive: {
    color: color.text.inverse,
  },
  stepStateTextDone: {
    color: color.brand.primaryDark,
  },
  stepTitle: {
    color: color.text.strong,
    flex: 1,
    ...typography.caption2,
    fontWeight: '600',
    minWidth: 0,
  },
  workProgressBoardMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  workProgressBoardShell: {
    gap: 8,
  },
  workProgressBoardTitle: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
  },
})
