import { StyleSheet } from 'react-native'

import { color, component, glass, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  authorityText: {
    color: color.text.strong,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  glassCard: {
    backgroundColor: 'rgba(255,255,255,0.76)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 30,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  navButton: {
    alignItems: 'center',
    borderRadius: component.button.secondary.radius,
    flex: 1,
    justifyContent: 'center',
    minHeight: 52,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 14,
    position: 'relative',
    zIndex: 1,
  },
  navButtonPrimary: {
    backgroundColor: color.brand.primary,
    ...shadow.primary,
  },
  navButtonPrimaryText: {
    color: color.text.inverse,
  },
  navButtonSecondary: {
    backgroundColor: glass.bgStrong,
    borderColor: color.surface.strokeStrong,
    borderWidth: 1,
  },
  navButtonText: {
    color: color.brand.primaryDark,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 19,
    textAlign: 'center',
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  primaryActionButtonSource: {
    backgroundColor: '#13CBB8',
    borderColor: 'rgba(2,126,115,0.22)',
    borderWidth: 1,
    shadowColor: '#059F8E',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.27,
    shadowRadius: 28,
  },
  privateKaelMediaImage: {
    backgroundColor: color.mint.mint100,
    borderRadius: 10,
    height: 42,
    width: 42,
  },
  privateKaelMediaPreview: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: color.mint.mint100,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    maxWidth: 190,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  privateKaelMediaRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  privateKaelMediaText: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  scopeHeroAura: {
    bottom: -92,
    height: 292,
    left: -78,
    opacity: 1,
    right: -58,
    top: -86,
  },
  scopeHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 118,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  scopeHeroIcon: {
    height: 42,
    width: 42,
  },
  scopeHeroIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 25,
    borderWidth: 1,
    height: 70,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 70,
    zIndex: 1,
  },
  scopeHeroMeta: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 3,
  },
  scopeHeroPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF7E6',
    borderColor: '#F6D18B',
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.text.strong,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  scopeHeroText: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  scopeHeroTextNoPill: {
    alignSelf: 'flex-start',
    paddingTop: 3,
  },
  scopeHeroTitle: {
    color: color.text.strong,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 8,
  },
  scopeHeroTitleNoPill: {
    marginTop: 0,
  },
  scopeHeroZipAura: {
    height: 252,
    opacity: 0.84,
    right: -96,
    top: -82,
    width: 336,
  },
  scopePhotoPickerButton: {
    flexBasis: 112,
    flexGrow: 0,
    flexShrink: 0,
    minHeight: 50,
    paddingHorizontal: 12,
  },
  scopePhotoPickerHint: {
    flex: 1,
    lineHeight: 17,
    minWidth: 0,
  },
  scopePhotoPickerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  scopeSubmitButton: {
    flex: 0,
    minHeight: 54,
    width: '100%',
  },
  scopeSubmitButtonText: {
    color: color.text.inverse,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'center',
    zIndex: 2,
  },
  scopeSubmitDisabled: {
    backgroundColor: 'rgba(229,247,243,0.92)',
    borderColor: color.mint.mint100,
    shadowOpacity: 0,
  },
  scopeSubmitDisabledText: {
    color: color.brand.primaryDark,
    opacity: 0.58,
  },
  sectionStack: {
    gap: 14,
  },
  workerChatTextFieldShell: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    minHeight: 38,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  workerChatTextFieldStack: {
    flex: 1,
  },
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
})
