import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  infoCell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: 'rgba(255,255,255,0.9)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 74,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 10,
    ...shadow.soft,
  },
  infoCellLabel: {
    color: color.text.muted,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    textAlign: 'center',
  },
  infoCellValue: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    textAlign: 'center',
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  infoIcon: {
    height: 42,
    width: 42,
  },
  infoIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    flexShrink: 0,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 64,
    ...shadow.soft,
  },
  infoLabel: {
    color: color.text.strong,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  infoRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 16,
    position: 'relative',
    zIndex: 1,
  },
  infoTextColumn: {
    flex: 1,
    gap: 3,
  },
  infoValue: {
    color: color.text.secondary,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  profileRouteIconVisualBoost: {
    height: 52,
    width: 52,
  },
  kaelDraftAvatar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 18,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 52,
    zIndex: 1,
  },
  kaelDraftBody: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
  },
  kaelDraftCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 21,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 74,
    overflow: 'hidden',
    padding: 11,
    position: 'relative',
    ...shadow.soft,
  },
  kaelDraftChevron: {
    color: color.brand.primaryDark,
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 24,
    position: 'relative',
    zIndex: 1,
  },
  kaelDraftCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  kaelDraftIcon: {
    height: 36,
    width: 36,
  },
  kaelDraftTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  formulaWideAura: {
    bottom: -88,
    height: 282,
    left: -76,
    opacity: 0.96,
    right: -58,
    top: -78,
  },
  formulaZipAura: {
    height: 246,
    opacity: 0.78,
    right: -96,
    top: -82,
    width: 326,
  },
  priceLine: {
    alignItems: 'flex-start',
    borderBottomColor: 'rgba(216,235,232,0.64)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minHeight: 44,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 1,
  },
  priceLineLabel: {
    color: color.text.secondary,
    flex: 1,
    minWidth: 0,
    paddingRight: 2,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  priceLineValue: {
    color: color.text.strong,
    flex: 1.1,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    minWidth: 92,
    textAlign: 'right',
  },
  priceLinesCard: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 22,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 6,
    position: 'relative',
    ...shadow.soft,
  },
  priceTotalLabel: {
    color: color.text.strong,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    minWidth: 0,
    paddingRight: 2,
  },
  priceTotalLine: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minHeight: 52,
    paddingTop: 12,
    position: 'relative',
    zIndex: 1,
  },
  priceTotalValue: {
    color: color.brand.primaryDark,
    flex: 1.1,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 23,
    minWidth: 98,
    textAlign: 'right',
  },
})
