import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  approvalDecisionCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  approvalDecisionIcon: {
    height: 42,
    width: 42,
  },
  approvalDecisionIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    flexShrink: 0,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 64,
  },
  approvalDecisionList: {
    backgroundColor: 'rgba(255,255,255,0.77)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    ...shadow.soft,
  },
  approvalDecisionMeta: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  approvalDecisionRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 72,
    padding: 12,
    position: 'relative',
  },
  approvalDecisionStatus: {
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    ...typography.caption2,
    fontWeight: '600',
    maxWidth: 92,
    minWidth: 54,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: 'center',
  },
  approvalDecisionTitle: {
    color: color.text.strong,
    ...typography.caption1,
    fontWeight: '600',
  },
  scheduleSummaryAmount: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  scheduleSummaryCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(249,255,253,0.82)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 112,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  scheduleSummaryAura: {
    bottom: -34,
    height: 176,
    left: -42,
    opacity: 0.86,
    right: -34,
    top: -34,
  },
  scheduleSummaryCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  scheduleSummaryLens: {
    alignItems: 'center',
    backgroundColor: 'rgba(235,255,249,0.82)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 42,
    borderWidth: 1,
    height: 78,
    justifyContent: 'center',
    paddingHorizontal: 8,
    position: 'relative',
    width: 78,
    zIndex: 1,
    ...shadow.soft,
  },
  scheduleSummaryLensLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    textAlign: 'center',
  },
  scheduleSummaryLensValue: {
    color: color.brand.primaryDark,
    ...typography.title2,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  scheduleSummaryMeta: {
    color: color.text.muted,
    ...typography.caption1,
    fontWeight: '600',
    marginTop: 2,
  },
  scheduleSummaryZipAura: {
    height: 164,
    opacity: 0.68,
    right: -60,
    top: -34,
    width: 204,
  },
  searchPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(16,169,150,0.82)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 50,
    paddingHorizontal: 16,
    ...shadow.soft,
  },
  searchFeedback: {
    color: color.text.muted,
    ...typography.caption1,
    fontWeight: '600',
    paddingHorizontal: 12,
  },
  searchFieldStack: {
    gap: 0,
  },
  searchInput: {
    color: color.text.strong,
    flex: 1,
    ...typography.footnote,
    fontWeight: '600',
    minWidth: 0,
  },
  searchStack: {
    gap: 8,
    position: 'relative',
    zIndex: 3,
  },
  searchSuggestionButton: {
    gap: 2,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  searchSuggestionMeta: {
    color: color.text.muted,
    ...typography.caption1,
    fontWeight: '600',
  },
  searchSuggestionTitle: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
  },
  searchSuggestions: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(20,158,140,0.16)',
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'hidden',
    ...shadow.soft,
  },
  shiftIcon: {
    height: 42,
    position: 'relative',
    width: 42,
    zIndex: 1,
  },
  shiftIconFormulaAura: {
    height: 92,
    opacity: 0.88,
    right: -34,
    top: -24,
    width: 112,
  },
  shiftIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 20,
    borderWidth: 1,
    height: 58,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 58,
  },
  shiftMeta: {
    color: color.text.muted,
    ...typography.caption1,
    fontWeight: '600',
    marginTop: 1,
  },
  shiftSourceAura: {
    bottom: 'auto',
    height: 156,
    left: '34%',
    opacity: 0.82,
    right: -56,
    top: -68,
  },
  shiftSourceList: {
    backgroundColor: 'rgba(248,255,252,0.86)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 26,
    position: 'relative',
  },
  shiftSourceRow: {
    minHeight: 76,
    paddingHorizontal: 14,
    paddingVertical: 13,
    position: 'relative',
    zIndex: 1,
  },
  shiftSourceStatus: {
    backgroundColor: 'rgba(218,250,240,0.9)',
    borderColor: 'rgba(78,202,177,0.42)',
    maxWidth: 106,
    minWidth: 64,
  },
  shiftSourceTitle: {
    ...typography.footnote,
  },
  shiftSummaryCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(248,255,252,0.82)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 118,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  shiftSummaryTextColumn: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    minHeight: 58,
  },
  shiftSummaryTitle: {
    marginTop: 0,
  },
  shiftTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  shiftTitle: {
    color: color.text.strong,
    ...typography.callout,
    fontWeight: '600',
    marginTop: 5,
  },
  sourceProgressFill: {
    backgroundColor: 'rgba(184,231,223,0.42)',
    borderRadius: radius.pill,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '0%',
  },
  sourceProgressFillActive: {
    backgroundColor: color.mint.mint50,
    width: '100%',
  },
  sourceProgressShell: {
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    marginTop: 7,
    overflow: 'hidden',
    paddingHorizontal: 10,
    position: 'relative',
  },
  sourceProgressText: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
    zIndex: 1,
  },
})
