import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  actionRailPrimaryText: {
    color: color.brand.primaryDark,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  scheduleActionButton: {
    alignItems: 'center',
    borderRadius: 26,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 56,
    overflow: 'hidden',
    paddingHorizontal: 16,
    position: 'relative',
  },
  scheduleActionPrimary: {
    backgroundColor: '#13CBB8',
    borderColor: 'rgba(2,126,115,0.22)',
    shadowColor: '#059F8E',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.27,
    shadowRadius: 28,
  },
  scheduleActionPrimaryText: {
    color: color.text.inverse,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 20,
    position: 'relative',
    textAlign: 'center',
    zIndex: 2,
  },
  scheduleActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  scheduleActionSecondary: {
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.92)',
    ...shadow.soft,
  },
  scheduleActionSecondaryText: {
    color: color.brand.primaryDark,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 20,
    textAlign: 'center',
  },
  scheduleAside: {
    color: color.brand.primaryDark,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    maxWidth: 104,
    textAlign: 'right',
  },
  scheduleEmptyAura: {
    bottom: -26,
    height: 128,
    left: -34,
    opacity: 0.76,
    right: -30,
    top: -28,
  },
  scheduleEmptyCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.80)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 76,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    ...shadow.soft,
  },
  scheduleEmptyIcon: {
    height: 32,
    width: 32,
  },
  scheduleEmptyIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 17,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 48,
    zIndex: 1,
  },
  scheduleEmptyMeta: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
  },
  scheduleEmptyText: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  scheduleEmptyTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
  },
  scheduleEmptyZipAura: {
    height: 132,
    opacity: 0.56,
    right: -70,
    top: -58,
    width: 174,
  },
  scheduleList: {
    gap: 7,
  },
  scheduleMeta: {
    color: color.text.muted,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    marginTop: 2,
  },
  scheduleRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 7,
    ...shadow.soft,
  },
  scheduleTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  scheduleTime: {
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    width: 47,
  },
  scheduleTitle: {
    color: color.text.strong,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
  },
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
})
