import { StyleSheet } from 'react-native'

import { color, typography } from '@/design/theme'

import { stageLayout } from './stage-ratio'

export const prototypeCoreStyles = StyleSheet.create({
  bodyStack: {
    gap: 16,
  },
  text: {
    ...typography.body,
  },
  opportunityInboxNew: {
    gap: stageLayout.sectionGap,
  },
  opportunityActions: {
    flexDirection: 'row',
    gap: stageLayout.componentGap,
  },
  opportunityAction: {
    alignItems: 'center',
    borderRadius: stageLayout.buttonRadius,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: stageLayout.buttonHeight,
    paddingHorizontal: stageLayout.innerPadding,
  },
  opportunityActionSecondary: {
    backgroundColor: 'rgba(255,255,255,0.76)',
    borderColor: color.surface.strokeStrong,
  },
  opportunityActionPrimary: {
    backgroundColor: color.brand.primary,
    borderColor: color.brand.primary,
  },
  opportunityActionDisabled: {
    backgroundColor: color.surface.disabled,
    borderColor: color.surface.stroke,
  },
  opportunityActionText: {
    ...typography.body,
    fontWeight: '700',
    textAlign: 'center',
  },
  opportunityActionSecondaryText: {
    color: color.brand.primaryDark,
  },
  opportunityActionPrimaryText: {
    color: color.text.inverse,
  },
  opportunityActionDisabledText: {
    color: color.text.disabled,
  },
  opportunityCard: {
    alignItems: 'stretch',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: stageLayout.cardRadius,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 172,
    overflow: 'hidden',
    position: 'relative',
  },
  opportunityCardCopy: {
    flex: 1,
    gap: 7,
    justifyContent: 'center',
    maxWidth: '60%',
    minHeight: 172,
    paddingHorizontal: stageLayout.cardPadding,
    paddingVertical: stageLayout.cardPadding,
  },
  opportunityCardTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '700',
  },
  opportunityCardMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '600',
  },
  opportunityMetaRow: {
    alignItems: 'center',
    columnGap: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 6,
    marginTop: 2,
  },
  opportunityMetaItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 22,
  },
  opportunityMetaIcon: {
    alignItems: 'center',
    height: 16,
    justifyContent: 'center',
    width: 16,
  },
  opportunityMetaText: {
    color: color.text.secondary,
    ...typography.caption2,
    flexShrink: 1,
    fontWeight: '600',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  opportunityMetaTextSelected: {
    color: color.brand.primaryDark,
    fontWeight: '700',
  },
  opportunityPriceText: {
    color: color.text.secondary,
    fontWeight: '400',
  },
  offerSummaryPrice: {
    color: color.text.secondary,
    ...typography.caption1,
    flexShrink: 1,
    fontWeight: '400',
  },
  opportunitySelectionHintNew: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  offerStageStack: {
    gap: 16,
  },
  offerSummaryCard: {
    alignItems: 'stretch',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 26,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    minHeight: 164,
    overflow: 'hidden',
  },
  offerSummaryCopy: {
    flex: 1,
    flexBasis: 196,
    flexGrow: 1,
    flexShrink: 1,
    gap: 7,
    justifyContent: 'center',
    maxWidth: '100%',
    minWidth: 0,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  offerSummaryTitle: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.title3,
    fontWeight: '700',
  },
  offerSummaryMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '600',
  },
  stagePaymentKicker: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  stagePaymentAmount: {
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontVariant: ['tabular-nums'],
    maxWidth: '100%',
    ...typography.title1,
    fontWeight: '700',
  },
  stagePaymentMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    ...typography.footnote,
    fontWeight: '500',
  },
  offerSummaryArtwork: {
    alignSelf: 'stretch',
    flexBasis: 132,
    flexGrow: 1,
    flexShrink: 1,
    height: 144,
    marginLeft: 'auto',
    maxWidth: 180,
    minWidth: 0,
  },
  offerInfoCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    gap: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  offerInfoGroup: {
    gap: 8,
  },
  offerInfoGroupTitle: {
    color: color.text.strong,
    ...typography.body,
    fontWeight: '700',
  },
  offerInfoGroupHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  offerInfoRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingVertical: 7,
  },
  offerInfoRowCopy: {
    flex: 1,
    flexBasis: 150,
    flexShrink: 1,
    gap: 2,
    minWidth: 0,
  },
  offerInfoRowTitle: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '700',
  },
  offerInfoRowMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
  },
  offerInfoRowStatus: {
    color: color.text.secondary,
    ...typography.caption1,
    alignSelf: 'flex-start',
    flexBasis: 94,
    flexShrink: 1,
    fontWeight: '600',
    marginLeft: 'auto',
    maxWidth: '42%',
    marginTop: 20,
    minWidth: 0,
    textAlign: 'right',
  },
  offerInfoMark: {
    backgroundColor: color.mint.mint100,
    borderRadius: 8,
    height: 8,
    marginTop: 5,
    width: 8,
  },
  offerChecklistCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  offerChecklistHeader: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 6,
  },
  offerChecklistTitle: {
    color: color.text.strong,
    ...typography.body,
    fontWeight: '700',
  },
  offerChecklistCount: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '700',
  },
  offerCheckRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 9,
  },
  offerCheckDot: {
    backgroundColor: color.surface.strokeStrong,
    borderRadius: 5,
    height: 10,
    marginTop: 4,
    width: 10,
  },
  offerCheckDotDone: {
    backgroundColor: color.brand.primary,
  },
  offerCheckDotBlocked: {
    backgroundColor: color.accent.warning,
  },
  offerCheckCopy: {
    flex: 1,
    gap: 2,
  },
  offerCheckLabel: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
  },
  offerCheckMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
  },
  offerCheckState: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    alignSelf: 'flex-start',
    maxWidth: '26%',
    marginTop: 2,
    textAlign: 'right',
  },
  offerEtaCard: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 70,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  offerEtaCopy: {
    flex: 1,
    gap: 2,
  },
  offerEtaTitle: {
    color: color.text.strong,
    ...typography.body,
    fontWeight: '600',
  },
  routeStageStack: {
    gap: 14,
  },
  routeMapPanel: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 28,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 248,
    overflow: 'hidden',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  routeMapEmptyContent: {
    alignItems: 'center',
    gap: 10,
    maxWidth: '82%',
  },
  routeMapEmptyTitle: {
    color: color.text.strong,
    ...typography.title3,
    fontWeight: '600',
    textAlign: 'center',
  },
  routeMapEmptyMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '500',
    textAlign: 'center',
  },
  routeEtaSummaryCard: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 112,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  routeEtaSummaryCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  routeEtaLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  routeEtaLabel: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  routeEtaValue: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
  },
  routeEtaMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
    marginTop: 2,
  },
  routeMetrics: {
    flexDirection: 'row',
    gap: 8,
  },
  routeMetricCell: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    justifyContent: 'center',
    minHeight: 76,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  routeMetricValue: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '700',
    textAlign: 'center',
  },
  routeMetricLabel: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '500',
    textAlign: 'center',
  },
  stageSummaryCard: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 124,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  stageSummaryCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  stageSummaryEyebrow: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  stageSummaryTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
  },
  stageSummaryMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
  },
  stageSummaryCount: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 38,
    borderWidth: 8,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  stageSummaryCountText: {
    color: color.brand.primaryDark,
    ...typography.body,
    fontWeight: '700',
  },
  stageSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  stageSectionTitle: {
    color: color.text.strong,
    ...typography.body,
    fontWeight: '600',
  },
  stageSectionAction: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
  },
  stageEvidenceRow: {
    flexDirection: 'row',
    gap: 10,
  },
  stageEvidenceSlot: {
    alignItems: 'center',
    backgroundColor: color.mint.mint50,
    borderRadius: 18,
    flex: 1,
    height: 112,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  stageEvidenceSlotDisabled: {
    opacity: 0.68,
  },
  stageEvidenceImage: {
    height: '100%',
    width: '100%',
  },
  stageEvidencePlus: {
    color: color.brand.primaryDark,
    ...typography.title1,
    fontWeight: '400',
    lineHeight: 34,
  },
  stageActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  stageActionButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexBasis: 140,
    flexShrink: 1,
    justifyContent: 'center',
    minHeight: 54,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 12,
    position: 'relative',
  },
  stageActionSecondary: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
  },
  stageActionPrimary: {
    borderColor: color.brand.primary,
  },
  stageActionDisabled: {
    backgroundColor: color.surface.disabled,
    borderColor: color.surface.stroke,
  },
  stageActionText: {
    fontWeight: '600',
    textAlign: 'center',
  },
  stageActionSecondaryText: {
    color: color.brand.primaryDark,
  },
  stageActionPrimaryText: {
    color: color.text.inverse,
  },
  stageActionDisabledText: {
    color: color.text.disabled,
  },
})
