import { StyleSheet } from 'react-native'

import type { WorkerThemeTokens } from '../worker-theme'

export function createStageFourStyles(scale: number, tokens: WorkerThemeTokens) {
  const s = (value: number) => Math.round(value * scale)
  const controlSize = Math.max(44, s(44))

  return StyleSheet.create({
    actionIcon: {
      alignItems: 'center',
      backgroundColor: tokens.water,
      borderRadius: s(14),
      height: s(36),
      justifyContent: 'center',
      width: s(36),
    },
    card: {
      backgroundColor: tokens.base,
      borderColor: tokens.border,
      borderRadius: s(18),
      borderWidth: 1,
      overflow: 'hidden',
    },
    cardContent: {
      padding: s(10),
    },
    chip: {
      alignItems: 'center',
      backgroundColor: tokens.base,
      borderColor: tokens.border,
      borderRadius: s(19),
      borderWidth: 1,
      flexDirection: 'row',
      gap: s(10),
      minHeight: Math.max(54, s(54)),
      paddingHorizontal: s(12),
      shadowColor: tokens.primary,
      shadowOpacity: tokens.mode === 'dark' ? 0.12 : 0.08,
      shadowRadius: s(12),
      shadowOffset: { height: s(6), width: 0 },
    },
    chipCopy: {
      flex: 1,
      minWidth: 0,
    },
    chipIcon: {
      alignItems: 'center',
      backgroundColor: tokens.water,
      borderRadius: s(10),
      height: s(34),
      justifyContent: 'center',
      width: s(34),
    },
    contentStack: {
      gap: s(6),
      paddingHorizontal: s(12),
    },
    customerBody: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: s(8),
      marginTop: s(3),
    },
    customerCopy: {
      flex: 1,
      minWidth: 0,
    },
    customerInitial: {
      alignItems: 'center',
      backgroundColor: tokens.water,
      borderRadius: s(21),
      height: s(42),
      justifyContent: 'center',
      width: s(42),
    },
    customerTitleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: s(3),
      minWidth: 0,
    },
    detailButton: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: s(4),
      minHeight: Math.max(44, s(28)),
      paddingHorizontal: s(3),
    },
    detailButtonPosition: {
      position: 'absolute',
      right: s(8),
      top: s(5),
      zIndex: 3,
    },
    destinationBody: {
      flexDirection: 'row',
      gap: s(8),
      minWidth: 0,
    },
    destinationCopy: {
      flex: 1,
      minWidth: 0,
      paddingRight: s(2),
    },
    error: {
      color: tokens.danger,
      fontSize: s(12),
      lineHeight: s(16),
      marginTop: s(1),
    },
    etaDisclosure: {
      alignItems: 'center',
      backgroundColor: tokens.base,
      borderColor: tokens.border,
      borderRadius: s(17),
      borderWidth: 1,
      height: s(34),
      justifyContent: 'center',
      width: s(34),
    },
    etaSheet: {
      backgroundColor: tokens.base,
      borderColor: tokens.border,
      borderRadius: s(21),
      borderWidth: 1,
      bottom: 0,
      left: s(12),
      minHeight: Math.max(70, s(70)),
      paddingHorizontal: s(12),
      paddingVertical: s(8),
      position: 'absolute',
      right: s(12),
      shadowColor: tokens.primary,
      shadowOpacity: tokens.mode === 'dark' ? 0.16 : 0.10,
      shadowRadius: s(14),
      shadowOffset: { height: s(8), width: 0 },
      zIndex: 5,
    },
    etaSheetRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: s(12),
      minHeight: Math.max(54, s(54)),
    },
    emptyMap: {
      alignItems: 'center',
      backgroundColor: tokens.service,
      borderRadius: s(24),
      bottom: s(76),
      justifyContent: 'center',
      left: s(18),
      paddingHorizontal: s(18),
      position: 'absolute',
      right: s(18),
      top: s(110),
    },
    header: {
      alignItems: 'center',
      flexDirection: 'row',
      height: s(52),
      justifyContent: 'space-between',
      left: s(14),
      position: 'absolute',
      right: s(14),
      top: s(11),
      zIndex: 4,
    },
    headerTitle: {
      alignItems: 'center',
      left: s(88),
      position: 'absolute',
      right: s(88),
      top: 0,
    },
    helpButton: {
      alignItems: 'center',
      backgroundColor: tokens.base,
      borderColor: tokens.border,
      borderRadius: s(18),
      borderWidth: 1,
      flexDirection: 'row',
      gap: s(7),
      minHeight: Math.max(44, s(44)),
      paddingHorizontal: s(13),
      shadowColor: tokens.primary,
      shadowOpacity: tokens.mode === 'dark' ? 0.12 : 0.08,
      shadowRadius: s(10),
      shadowOffset: { height: s(5), width: 0 },
    },
    hero: {
      backgroundColor: tokens.canvas,
      marginBottom: s(0),
      minHeight: s(372),
      overflow: 'hidden',
      position: 'relative',
    },
    mapControlColumn: {
      gap: s(9),
      position: 'absolute',
      right: s(12),
      top: s(134),
      zIndex: 4,
    },
    mapControl: {
      alignItems: 'center',
      backgroundColor: tokens.base,
      borderRadius: s(22),
      height: controlSize,
      justifyContent: 'center',
      width: controlSize,
    },
    mapImage: {
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    metric: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      gap: s(7),
      minWidth: 0,
      paddingHorizontal: s(1),
    },
    metricIcon: {
      alignItems: 'center',
      backgroundColor: tokens.water,
      borderRadius: s(16),
      height: s(31),
      justifyContent: 'center',
      width: s(31),
    },
    metricStack: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      minWidth: 0,
    },
    noteBody: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: s(9),
    },
    noteCopy: {
      flex: 1,
      gap: s(3),
      minWidth: 0,
    },
    noteSurface: {
      alignItems: 'center',
      backgroundColor: tokens.service,
      borderRadius: s(13),
      flexDirection: 'row',
      gap: s(9),
      minHeight: s(45),
      paddingHorizontal: s(10),
      paddingVertical: s(5),
    },
    primary: {
      alignItems: 'center',
      backgroundColor: tokens.primary,
      borderRadius: s(33),
      height: Math.max(60, s(66)),
      justifyContent: 'center',
      marginTop: s(1),
      overflow: 'hidden',
      shadowColor: tokens.primary,
      shadowOpacity: tokens.mode === 'dark' ? 0.20 : 0.18,
      shadowRadius: s(12),
      shadowOffset: { height: s(7), width: 0 },
    },
    primaryCopy: {
      alignItems: 'center',
      flexShrink: 1,
    },
    primaryRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: s(11),
      justifyContent: 'center',
      paddingHorizontal: s(16),
    },
    screen: {
      backgroundColor: tokens.canvas,
      paddingBottom: s(10),
    },
    sectionTitleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: s(9),
    },
    smallAction: {
      alignItems: 'center',
      backgroundColor: tokens.service,
      borderColor: tokens.border,
      borderRadius: s(14),
      borderWidth: 1,
      flex: 1,
      flexDirection: 'row',
      gap: s(6),
      justifyContent: 'center',
      minHeight: Math.max(46, s(46)),
      paddingHorizontal: s(4),
    },
    smallActionRow: {
      flexDirection: 'row',
      gap: s(5),
      marginTop: s(0),
    },
    verticalDivider: {
      backgroundColor: tokens.border,
      height: '64%',
      marginHorizontal: s(7),
      width: 1,
    },
    workAction: {
      alignItems: 'center',
      backgroundColor: tokens.service,
      borderRadius: s(14),
      flexShrink: 0,
      gap: s(3),
      justifyContent: 'center',
      minHeight: Math.max(50, s(50)),
      paddingHorizontal: s(4),
      width: s(58),
    },
  })
}
