import { StyleSheet } from 'react-native'
import { color, typography } from '@/design/theme'

export const workerJobsLegacyPrototypeStylePartB = StyleSheet.create({
  stageEvidenceEmpty: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 82,
  },
  stageEvidenceEmptyIcon: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  stageEvidenceEmptyText: {
    color: color.text.secondary,
    ...typography.body,
    fontWeight: '600',
  },
  stageSevenHero: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 148,
    overflow: 'hidden',
    paddingLeft: 18,
    paddingRight: 18,
    paddingVertical: 14,
  },
  stageSevenCopy: {
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  stageSevenKicker: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  stageSevenTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '700',
  },
  stageSevenMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '500',
  },
  stageSevenStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  stageSevenStatusText: {
    color: color.brand.primaryDark,
    ...typography.footnote,
    fontWeight: '700',
  },
  stageSevenArtwork: {
    alignSelf: 'stretch',
    height: '116%',
    marginLeft: 'auto',
    transform: [{ scale: 1.08 }],
    width: '38%',
  },
  stageTimelineCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 29,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  stageTimelineItem: {
    flexDirection: 'row',
    minHeight: 54,
  },
  stageTimelineMarkerColumn: {
    alignItems: 'center',
    marginRight: 10,
    width: 22,
  },
  stageTimelineMarker: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: 'center',
    marginTop: 4,
    width: 20,
  },
  stageTimelineMarkerDone: {
    backgroundColor: color.brand.primary,
    borderColor: color.brand.primary,
  },
  stageTimelineMarkerActive: {
    borderColor: color.brand.primary,
    borderWidth: 2,
  },
  stageTimelineMarkerText: {
    color: color.text.muted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
  },
  stageTimelineMarkerTextDone: {
    color: color.text.inverse,
  },
  stageTimelineConnector: {
    backgroundColor: color.surface.stroke,
    flex: 1,
    marginVertical: 4,
    width: 1,
  },
  stageTimelineCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
    paddingBottom: 8,
  },
  stageTimelineTitle: {
    color: color.text.strong,
    ...typography.body,
    fontWeight: '600',
  },
  stageTimelineMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
  },
  stageCompletionHero: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 148,
    overflow: 'hidden',
    paddingLeft: 18,
    paddingVertical: 14,
  },
  stageCompletionCopy: {
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  stageCompletionKicker: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  stageCompletionTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '700',
  },
  stageCompletionMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '500',
  },
  stageCompletionPhotoCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    minHeight: 90,
    overflow: 'hidden',
    padding: 12,
  },
  stageCompletionPhotoEmpty: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
  },
  stageCompletionPhotoEmptyIcon: {
    alignItems: 'center',
    borderColor: color.surface.strokeStrong,
    borderRadius: 12,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  stageCompletionPhotoCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  stageCompletionPhotoTitle: {
    color: color.text.strong,
    ...typography.body,
    fontWeight: '600',
  },
  stageCompletionPhotoMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
  },
  stageCompletionInlineAction: {
    alignItems: 'center',
    borderColor: color.surface.strokeStrong,
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  stageCompletionInlineActionText: {
    color: color.brand.primaryDark,
    ...typography.footnote,
    fontWeight: '700',
  },
  stageCompletionPhoto: {
    borderRadius: 14,
    height: 88,
    width: 88,
  },
  stageCompletionCheckCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 12,
  },
  stageCompletionCheckRow: {
    alignItems: 'center',
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    paddingVertical: 8,
  },
  stageCompletionCheckRowLast: {
    borderBottomWidth: 0,
  },
  stageCompletionCheckIcon: {
    alignItems: 'center',
    borderColor: color.surface.strokeStrong,
    borderRadius: 12,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  stageCompletionCheckIconDone: {
    backgroundColor: color.brand.primary,
    borderColor: color.brand.primary,
  },
  stageCompletionCheckIconText: {
    color: color.text.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  stageCompletionCheckIconTextDone: {
    color: color.text.inverse,
  },
  stageCompletionCheckCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  stageCompletionCheckTitle: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
  },
  stageCompletionCheckMeta: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '500',
  },
  stageCompletionCheckStatus: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    maxWidth: 86,
    textAlign: 'right',
  },
  stageCompletionNoteShell: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    minHeight: 108,
  },
  stageCompletionNoteInput: {
    color: color.text.strong,
    minHeight: 76,
    paddingTop: 0,
    textAlign: 'left',
    textAlignVertical: 'center',
    ...typography.body,
  },
  stageSubmissionHero: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 142,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  stageSubmissionCopy: {
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  stageSubmissionKicker: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  stageSubmissionTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '700',
  },
  stageSubmissionMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '500',
  },
  stageSubmissionStatus: {
    alignItems: 'center',
    gap: 6,
    marginLeft: 12,
    maxWidth: 132,
  },
  stageSubmissionStatusArtwork: {
    height: 100,
    width: 130,
  },
  stageSubmissionStatusText: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '700',
    textAlign: 'center',
  },
  stageSubmissionCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  stageSubmissionRow: {
    alignItems: 'center',
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    paddingVertical: 8,
  },
  stageSubmissionRowLast: {
    borderBottomWidth: 0,
  },
  stageSubmissionRowCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  stageSubmissionRowLabel: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
  },
  stageSubmissionRowMeta: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '500',
  },
  stageSubmissionRowValue: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    maxWidth: 132,
    textAlign: 'right',
  },
  stageClosedHero: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 148,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  stageClosedCopy: {
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  stageClosedKicker: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  stageClosedTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '700',
  },
  stageClosedMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '500',
  },
  stageClosedStatus: {
    alignItems: 'center',
    gap: 6,
    marginLeft: 12,
    maxWidth: 132,
  },
  stageClosedStatusArtwork: {
    height: 100,
    width: 130,
  },
  stageClosedStatusText: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '700',
    textAlign: 'center',
  },
  stageClosedSummaryCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  stageClosedSummaryRow: {
    alignItems: 'center',
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 62,
    paddingVertical: 8,
  },
  stageClosedSummaryRowLast: {
    borderBottomWidth: 0,
  },
  stageClosedSummaryCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  stageClosedSummaryLabel: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
  },
  stageClosedSummaryMeta: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '500',
  },
  stageClosedSummaryValue: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '700',
    maxWidth: 160,
    textAlign: 'right',
  },
})
