import { StyleSheet } from 'react-native'

import { color, typography } from '@/design/theme'

export const prototypeStageStyles = StyleSheet.create({
  stageProposalCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  stageProposalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 44,
  },
  stageProposalIcon: {
    alignItems: 'center',
    borderColor: color.surface.strokeStrong,
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  stageProposalHeaderCopy: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  stageProposalKicker: {
    color: color.text.secondary,
  },
  stageProposalTitle: {
    color: color.text.strong,
  },
  stageProposalAction: {
    color: color.brand.primaryDark,
    textAlign: 'right',
  },
  stageProposalRow: {
    alignItems: 'center',
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 48,
    paddingVertical: 8,
  },
  stageProposalRowLast: {
    borderBottomWidth: 0,
  },
  stageProposalLabel: {
    color: color.text.secondary,
  },
  stageProposalValue: {
    color: color.text.strong,
    flex: 1,
    textAlign: 'right',
  },
  stageProposalTotalValue: {
    color: color.brand.primaryDark,
  },
  stageCompletionHero: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 148,
    overflow: 'hidden',
    paddingLeft: 18,
    paddingVertical: 14,
  },
  stageCompletionCopy: {
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  stageCompletionWorkart: {
    height: 136,
    marginRight: -4,
    width: 174,
  },
  stageCompletionKicker: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  stageCompletionTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '700',
  },
  stageCompletionMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '500',
  },
  stageCompletionPhotoCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    minHeight: 90,
    overflow: 'hidden',
    padding: 12,
  },
  stageCompletionPhotoEmpty: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
  },
  stageCompletionPhotoEmptyIcon: {
    alignItems: 'center',
    borderColor: color.surface.strokeStrong,
    borderRadius: 12,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  stageCompletionPhotoCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  stageCompletionPhotoTitle: {
    color: color.text.strong,
    ...typography.body,
    fontWeight: '600',
  },
  stageCompletionPhotoMeta: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '500',
  },
  stageCompletionInlineAction: {
    alignItems: 'center',
    borderColor: color.surface.strokeStrong,
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  stageCompletionInlineActionText: {
    color: color.brand.primaryDark,
    ...typography.footnote,
    fontWeight: '700',
  },
  stageCompletionPhoto: {
    borderRadius: 14,
    height: 88,
    width: 88,
  },
  stageCompletionCheckCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 12,
  },
  stageCompletionCheckRow: {
    alignItems: 'center',
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    paddingVertical: 8,
  },
  stageCompletionCheckRowLast: {
    borderBottomWidth: 0,
  },
  stageCompletionCheckIcon: {
    alignItems: 'center',
    borderColor: color.surface.strokeStrong,
    borderRadius: 12,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  stageCompletionCheckIconDone: {
    backgroundColor: color.brand.primary,
    borderColor: color.brand.primary,
  },
  stageCompletionCheckIconText: {
    color: color.text.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  stageCompletionCheckIconTextDone: {
    color: color.text.inverse,
  },
  stageCompletionCheckCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  stageCompletionCheckTitle: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
  },
  stageCompletionCheckMeta: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '500',
  },
  stageCompletionCheckStatus: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    maxWidth: 86,
    textAlign: 'right',
  },
  stageCompletionNoteShell: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    minHeight: 108,
  },
  stageCompletionNoteInput: {
    color: color.text.strong,
    minHeight: 76,
    paddingTop: 0,
    textAlign: 'left',
    textAlignVertical: 'center',
    ...typography.body,
  },
  stageSubmissionHero: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 142,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  stageSubmissionCopy: {
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  stageSubmissionKicker: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  stageSubmissionTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '700',
  },
  stageSubmissionMeta: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '500',
  },
  stageSubmissionStatus: {
    alignItems: 'center',
    flexBasis: 124,
    flexShrink: 1,
    gap: 6,
    marginLeft: 12,
    maxWidth: '100%',
    minWidth: 0,
  },
  stageSubmissionStatusArtwork: {
    flexShrink: 1,
    height: 100,
    maxWidth: 130,
    width: '100%',
  },
  stageSubmissionStatusText: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '700',
    textAlign: 'center',
  },
  stageSubmissionCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.strokeStrong,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  stageSubmissionRow: {
    alignItems: 'center',
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minHeight: 58,
    paddingVertical: 8,
  },
  stageSubmissionRowLast: {
    borderBottomWidth: 0,
  },
  stageSubmissionRowCopy: {
    flex: 1,
    flexBasis: 150,
    flexShrink: 1,
    gap: 2,
    minWidth: 0,
  },
  stageSubmissionRowLabel: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
  },
  stageSubmissionRowMeta: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '500',
  },
  stageSubmissionRowValue: {
    color: color.text.secondary,
    ...typography.caption1,
    flexBasis: 94,
    flexShrink: 1,
    fontWeight: '600',
    marginLeft: 'auto',
    maxWidth: '42%',
    minWidth: 0,
    textAlign: 'right',
  },
})
