import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  kaelBriefBody: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  kaelBriefCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 76,
    overflow: 'hidden',
    padding: 11,
    position: 'relative',
    ...shadow.soft,
  },
  kaelBriefAura: {
    bottom: -30,
    height: 124,
    left: -26,
    opacity: 0.72,
    right: -34,
    top: -26,
  },
  kaelBriefChevron: {
    color: color.brand.primaryDark,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
    position: 'relative',
    zIndex: 1,
  },
  kaelBriefZipAura: {
    height: 136,
    opacity: 0.58,
    right: -72,
    top: -62,
    width: 176,
  },
  kaelBriefIcon: {
    height: 36,
    width: 36,
  },
  kaelBriefIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 17,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 48,
    zIndex: 1,
  },
  kaelBriefText: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  kaelBriefTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  homeQuickActionCard: {
    minHeight: 62,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  quickActionCard: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 0,
    minHeight: 72,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 10,
    position: 'relative',
    width: '48.7%',
    ...shadow.soft,
  },
  quickActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  quickActionIcon: {
    height: 32,
    width: 32,
  },
  quickActionIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 16,
    borderWidth: 1,
    flexShrink: 0,
    height: 42,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 42,
    zIndex: 1,
  },
  quickActionMeta: {
    color: color.text.muted,
    flexShrink: 1,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    marginTop: 2,
  },
  quickActionText: {
    flex: 1,
    marginLeft: 38,
    minWidth: 0,
    zIndex: 1,
  },
  quickActionTitle: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
  },
})
