import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  opportunityCaption: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    marginTop: 2,
    textAlign: 'right',
  },
  opportunityOpenButton: {
    alignItems: 'center',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    marginTop: 8,
    minHeight: 28,
    minWidth: 52,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  opportunityOpenButtonText: {
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
  },
  opportunityCard: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 0,
    minHeight: 84,
    overflow: 'hidden',
    padding: 11,
    position: 'relative',
    ...shadow.soft,
  },
  opportunityCardSelected: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderColor: 'rgba(19,203,184,0.78)',
    borderWidth: 1.5,
    shadowColor: '#13CBB8',
    shadowOpacity: 0.24,
    shadowRadius: 16,
  },
  opportunityIcon: {
    height: 38,
    width: 38,
  },
  opportunityIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 16,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 48,
  },
  opportunityMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    marginTop: 2,
  },
  opportunityPayout: {
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    textAlign: 'right',
  },
  opportunityPayoutColumn: {
    alignItems: 'flex-end',
    alignSelf: 'stretch',
    justifyContent: 'center',
    marginLeft: 14,
    maxWidth: 136,
    minWidth: 114,
  },
  opportunitySelectionHint: {
    color: color.text.secondary,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    paddingHorizontal: 4,
  },
  opportunityTextColumn: {
    flex: 1,
    justifyContent: 'center',
    marginLeft: 38,
    minWidth: 0,
  },
  opportunityTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
})
