import { typography } from '@/design/theme'
import { StyleSheet } from 'react-native'

export const customerV21ProfileSettingsStyles = StyleSheet.create({
  actionBody: {
    ...typography.caption1,
    marginTop: 2,
  },
  actionCopy: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    paddingBottom: 13,
    paddingLeft: 34,
    paddingRight: 6,
    paddingTop: 13,
    position: 'relative',
    zIndex: 1,
  },
  actionIcon: {
    height: 64,
    position: 'relative',
    width: 64,
    zIndex: 1,
  },
  actionRow: {
    alignItems: 'stretch',
    borderCurve: 'continuous',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 112,
    overflow: 'hidden',
    paddingRight: 10,
    position: 'relative',
  },
  actionTitle: {
    ...typography.callout,
    fontWeight: '600',
  },
  connector: {
    height: 1,
    position: 'absolute',
    right: -25,
    top: '50%',
    width: 25,
    zIndex: 2,
  },
  connectorDot: {
    borderRadius: 7,
    borderWidth: 1,
    height: 14,
    marginTop: -7,
    position: 'absolute',
    right: -7,
    top: '50%',
    width: 14,
    zIndex: 3,
  },
  detailDivider: {
    height: 15,
    marginHorizontal: 5,
    width: 1,
  },
  detailItem: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 4,
    minWidth: 0,
  },
  detailLabel: {
    flexShrink: 1,
    ...typography.caption2,
    minWidth: 0,
  },
  detailRail: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 5,
    minWidth: 0,
  },
  heroCard: {
    borderColor: 'rgba(74,218,197,0.48)',
    borderRadius: 28,
    padding: 0,
  },
  heroConnector: {
    height: 1,
    position: 'absolute',
    right: -24,
    top: '50%',
    width: 24,
    zIndex: 2,
  },
  heroConnectorDot: {
    borderRadius: 7,
    borderWidth: 1,
    height: 14,
    marginTop: -7,
    position: 'absolute',
    right: -7,
    top: '50%',
    width: 14,
    zIndex: 3,
  },
  heroContent: {
    alignItems: 'stretch',
    flexDirection: 'row',
    minHeight: 142,
  },
  heroCopy: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    paddingBottom: 14,
    paddingLeft: 43,
    paddingRight: 8,
    paddingTop: 14,
  },
  heroDetail: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 5,
    minWidth: 0,
  },
  heroDetailDivider: {
    height: 15,
    marginHorizontal: 5,
    width: 1,
  },
  heroDetailRail: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 7,
    minWidth: 0,
  },
  heroDetailText: {
    flexShrink: 1,
    ...typography.caption2,
    minWidth: 0,
  },
  heroIconAura: {
    bottom: -28,
    left: -28,
    opacity: 0.92,
    position: 'absolute',
    right: -28,
    top: -28,
    zIndex: 0,
  },
  heroIconImage: {
    height: 82,
    position: 'relative',
    width: 82,
    zIndex: 1,
  },
  heroStatus: {
    alignSelf: 'center',
    flexShrink: 0,
    marginRight: 16,
    maxWidth: 104,
  },
  heroSummary: {
    marginTop: 2,
  },
  heroTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroVisualPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRightWidth: 1,
    flexShrink: 0,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
    width: 116,
    zIndex: 1,
  },
  iconAura: {
    bottom: -24,
    left: -24,
    opacity: 0.92,
    position: 'absolute',
    right: -24,
    top: -24,
    zIndex: 0,
  },
  statusChip: {
    minHeight: 34,
    minWidth: 58,
    paddingHorizontal: 11,
  },
  statusFrame: {
    alignSelf: 'center',
    flexShrink: 0,
    marginLeft: 4,
    maxWidth: 112,
    position: 'relative',
    zIndex: 1,
  },
  statusText: {
    ...typography.caption2,
    fontWeight: '600',
  },
  visualPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRightWidth: 1,
    flexShrink: 0,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
    width: 96,
    zIndex: 1,
  },
})
