import { typography } from '@/design/theme'
import { StyleSheet } from 'react-native'

export const customerV21ProfileUtilityStyles = StyleSheet.create({
  bodyText: {
    ...typography.subheadline,
  },
  cardTitle: {
    ...typography.title3,
    fontWeight: '600',
  },
  flex: {
    flex: 1,
  },
  infoNoticeIcon: {
    flexShrink: 0,
  },
  pressed: {
    transform: [{ scale: 0.985 }],
  },
  profileInsightChip: {
    backgroundColor: 'rgba(224,252,245,0.88)',
    borderColor: 'rgba(85,214,195,0.40)',
    minWidth: 68,
    position: 'relative',
    zIndex: 1,
  },
  profileInsightEmptyChip: {
    backgroundColor: 'rgba(236,253,248,0.84)',
    borderColor: 'rgba(85,214,195,0.34)',
    minWidth: 68,
    position: 'relative',
    zIndex: 1,
  },
  profileInsightEmptyChipText: {
    color: '#0B8579',
    fontWeight: '600',
  },
  profileInsightChipFrame: {
    alignSelf: 'center',
    borderRadius: 999,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 14,
  },
  profileInsightTitle: {
    ...typography.callout,
    fontWeight: '600',
  },
  profileInsightRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 86,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileMintChipText: {
    color: '#087D72',
    fontWeight: '600',
  },
  profileAuraCard: {
    gap: 0,
    overflow: 'hidden',
    position: 'relative',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 28,
  },
  profileAuraCardShadowDark: {
    shadowColor: '#000000',
  },
  profileAuraCardShadowLight: {
    shadowColor: '#087D72',
  },
  profileAuraContent: {
    position: 'relative',
    zIndex: 1,
  },
  profileFormulaMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.5,
    zIndex: 0,
  },
  profileFormulaMintContent: {
    position: 'relative',
    zIndex: 1,
  },
  profileFormulaMintSurface: {
    overflow: 'hidden',
    position: 'relative',
  },
  profileAddressAddButton: {
    minHeight: 44,
    minWidth: 86,
  },
  profileAddressAddRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  profileAddressBlock: {
    gap: 10,
  },
  profileAddressBlockHeader: {
    gap: 3,
  },
  profileAddressDefaultButton: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  profileAddressDefaultText: {
    ...typography.caption1,
    fontWeight: '600',
  },
  profileAddressDivider: {
    height: 1,
    opacity: 0.86,
  },
  profileAddressHint: {
    ...typography.caption1,
    fontWeight: '600',
  },
  profileAddressHub: {
    gap: 14,
  },
  profileAddressHubHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileAddressHubIcon: {
    flexShrink: 0,
    minHeight: 76,
    minWidth: 76,
  },
  profileAddressInput: {
    borderRadius: 18,
    borderWidth: 1,
    ...typography.footnote,
    fontWeight: '600',
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  profileAddressMessage: {
    ...typography.footnote,
    fontWeight: '600',
    textAlign: 'center',
  },
  profileAddressSaveDefaultButton: {
    borderRadius: 22,
  },
  profileAddressSaveDefaultButtonActive: {
    backgroundColor: '#12B8A4',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
  },
  profileAddressSavedIcon: {
    flexShrink: 0,
    minHeight: 62,
    minWidth: 62,
  },
  profileAddressSavedList: {
    gap: 10,
  },
  profileAddressSavedRow: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileAddressSimpleCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  profileAddressSimpleHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileAddressSimpleHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  profileAddressSimpleHeaderIcon: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  profileAddressSimpleInput: {
    borderRadius: 16,
    borderWidth: 1,
    ...typography.body,
    minHeight: 56,
    paddingHorizontal: 14,
    paddingVertical: 0,
  },
  profileAddressSimpleSavedIcon: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexShrink: 0,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  profileAddressUtilityTitle: {
    fontWeight: '400',
  },
  profileAvatarEditBadge: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    bottom: -2,
    height: 26,
    justifyContent: 'center',
    position: 'absolute',
    right: -2,
    width: 26,
  },
  profileAvatarLarge: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    height: 84,
    justifyContent: 'center',
    position: 'relative',
    width: 84,
  },
  profileAvatarImage: {
    borderRadius: 999,
    height: '100%',
    width: '100%',
  },
  profileHeroLarge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 24,
    minHeight: 76,
  },
  profileHeroName: {
    ...typography.title3,
  },
  profileInsightIcon: {
    minHeight: 68,
    minWidth: 68,
  },
  profileKaelNote: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileListCard: {
    padding: 10,
  },
  profileListContent: {
    gap: 0,
  },
  profileListDivider: {
    height: 1,
    marginHorizontal: 14,
    opacity: 0.78,
  },
  profileMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  profileMoneyBody: {
    ...typography.callout,
    maxWidth: 292,
    textAlign: 'center',
  },
  profileMoneyHero: {
    alignItems: 'center',
    gap: 12,
    minHeight: 318,
    justifyContent: 'center',
  },
  profileMoneyKicker: {
    ...typography.subheadline,
    fontWeight: '600',
    textAlign: 'center',
  },
  profileNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  profileOverviewActionStack: {
    gap: 12,
    marginTop: 12,
  },
  profileOverviewFrame: {
    minWidth: 0,
    paddingTop: 4,
  },
  profileOverviewHeroCard: {
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 18,
    marginTop: 10,
    padding: 16,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 22, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 44,
  },
  profileRefundAccountFeedback: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileRefundAccountFeedbackBody: {
    ...typography.caption1,
    fontWeight: '600',
  },
  profileRefundAccountFeedbackCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  profileRefundAccountFeedbackTitle: {
    ...typography.footnote,
    fontWeight: '600',
  },
  profileRefundAccountUsageNote: {
    ...typography.footnote,
    fontWeight: '600',
  },
  profileProgressFill: {
    backgroundColor: '#08AF9C',
    overflow: 'hidden',
    shadowColor: '#087D72',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
  },
  profileProgressSheen: {
    backgroundColor: 'rgba(255,255,255,0.70)',
    borderRadius: 999,
    bottom: -3,
    position: 'absolute',
    top: -3,
    width: 54,
  },
  profileProtectedJob: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileRankingHero: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 8,
    minHeight: 198,
  },
  profileRankingHeroCard: {
    borderColor: 'rgba(113,225,209,0.50)',
    borderRadius: 24,
    gap: 0,
    marginHorizontal: 7,
    marginTop: 0,
    padding: 10,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 20, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 42,
  },
  profileRankingHeroBody: {
    ...typography.caption1,
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 15,
    maxWidth: 194,
  },
  profileRankingHeroCopy: {
    borderBottomRightRadius: 24,
    borderTopRightRadius: 24,
    flex: 1,
    gap: 4,
    justifyContent: 'center',
    minWidth: 0,
    paddingLeft: 12,
    paddingRight: 16,
    paddingVertical: 12,
    position: 'relative',
    zIndex: 3,
  },
  profileRankingHeroCurrentLine: {
    ...typography.footnote,
    fontSize: 14,
    lineHeight: 19,
    marginLeft: 0,
    transform: [{ translateY: -2 }],
  },
  profileRankingHeroKicker: {
    ...typography.footnote,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
  },
  profileRankingHeroPointLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    maxWidth: 194,
  },
  profileRankingHeroNextPointsText: {
    ...typography.caption2,
    flexShrink: 1,
    fontWeight: '600',
  },
  profileRankingHeroPoints: {
    ...typography.caption2,
    flexShrink: 1,
    fontWeight: '600',
    maxWidth: 194,
  },
  profileRankingHeroPointsGroup: {
    gap: 6,
    maxWidth: 194,
    transform: [{ translateY: 2 }],
  },
  profileRankingHeroProgress: {
    marginTop: 6,
    width: '100%',
  },
  profileRankingHeroValue: {
    ...typography.footnote,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
  },
  profileRankingHeroWorkart: {
    height: 198,
    transform: [{ scale: 1.8 }],
    width: '100%',
  },
  profileRankingHeroWorkartFrame: {
    alignItems: 'center',
    flexShrink: 0,
    height: 198,
    justifyContent: 'center',
    marginLeft: -4,
    width: '50%',
  },
  profileRankingMilestoneLabel: {
    ...typography.caption2,
    fontWeight: '600',
    textAlign: 'center',
  },
  profileRankingMilestoneLabelFrame: {
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  profileRankingMilestoneLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  profileRankingMilestoneNode: {
    borderRadius: 6,
    borderWidth: 1.25,
    height: 12,
    marginLeft: -6,
    position: 'absolute',
    top: 8,
    width: 12,
  },
  profileRankingMilestoneNodes: {
    height: 28,
    left: 0,
    position: 'absolute',
    top: 0,
    width: '100%',
  },
  profileRankingMilestoneRail: {
    gap: 2,
    marginTop: 3,
    paddingHorizontal: 2,
  },
  profileRankingMilestoneStage: {
    height: 28,
    position: 'relative',
    width: '100%',
  },
  profileRankingMilestoneTrack: {
    left: 0,
    position: 'absolute',
    top: 0,
  },
  profileRankingRuleBody: {
    ...typography.caption1,
  },
  profileRankingRuleCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
    paddingHorizontal: 8,
  },
  profileRankingRuleDivider: {
    height: 1,
    marginHorizontal: 0,
  },
  profileRankingRuleIconFrame: {
    alignItems: 'center',
    flexShrink: 0,
    height: 58,
    justifyContent: 'center',
    width: 56,
  },
  profileRankingRuleRow: {
    alignItems: 'center',
    borderRadius: 0,
    borderWidth: 0,
    flexDirection: 'row',
    minHeight: 88,
    paddingVertical: 10,
  },
  profileRankingRuleTitle: {
    ...typography.footnote,
    fontWeight: '600',
  },
  profileRankingRulesCard: {
    borderRadius: 20,
    marginTop: 8,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  profileRankingRulesContent: {
    gap: 0,
  },
  profileRankProcess: {
    borderRadius: 21,
    borderWidth: 1,
    marginTop: 10,
    minHeight: 58,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
  },
  profileRankProcessContent: {
    gap: 7,
    position: 'relative',
    zIndex: 1,
  },
  profileRankProcessLabel: {
    ...typography.caption1,
    fontWeight: '600',
  },
  profileRankProcessValue: {
    ...typography.caption1,
    fontWeight: '600',
    textAlign: 'right',
  },
  profileSubscreenBody: {
    marginTop: 14,
    width: '100%',
  },
  profileSubscreenFrame: {
    width: '100%',
  },
  profileSubscreenTopBarDark: {
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  profileUtilityStack: {
    gap: 14,
    position: 'relative',
  },
})
