import type { AppLanguage } from '@/lib/app-language'

import type {
  WorkerV5Phase,
  WorkerV5ScreenDefinition,
  WorkerV5ScreenId,
} from './types'

export const WORKER_V5_SCREENS: WorkerV5ScreenDefinition[] = [
  {
    authority: 'worker',
    guardrail: 'Kael chỉ đồng bộ bối cảnh và gợi ý; thợ tự bật/tắt nhận việc.',
    icon: 'home',
    id: '1.1-worker-home',
    order: 1,
    phase: 'prepare',
    primaryNext: '1.2-shift-brief',
    section: 'home',
    title: { en: 'Worker home', vi: 'Trang chủ thợ' },
  },
  {
    authority: 'worker',
    guardrail: 'Không hiển thị thời tiết, nhu cầu hoặc ưu tiên nếu chưa có dữ liệu thật.',
    icon: 'calendar',
    id: '1.2-shift-brief',
    order: 2,
    phase: 'prepare',
    primaryNext: '1.3-demand-map',
    section: 'jobs',
    title: { en: 'Work board', vi: 'Bảng công việc' },
  },
  {
    authority: 'worker',
    guardrail: 'Bản đồ cơ hội chỉ dùng khu vực phục vụ hoặc cơ hội thật, không vẽ nhu cầu giả.',
    icon: 'map',
    id: '1.3-demand-map',
    order: 3,
    phase: 'discover',
    primaryNext: '1.4-smart-schedule',
    section: 'jobs',
    title: { en: 'Opportunity map', vi: 'Bản đồ cơ hội' },
  },
  {
    authority: 'kael_assist',
    guardrail: 'Kael được đề xuất lịch, nhưng không tự nhận việc hoặc đổi lịch thay thợ.',
    icon: 'tools',
    id: '1.4-smart-schedule',
    order: 4,
    phase: 'discover',
    primaryNext: '2.1-opportunity-inbox',
    section: 'jobs',
    title: { en: 'Work optimization', vi: 'Tối ưu việc làm' },
  },
  {
    authority: 'worker',
    guardrail: 'Kael chỉ lọc và giải thích mức phù hợp; thợ là người mở, nhận hoặc từ chối.',
    icon: 'jobs',
    id: '2.1-opportunity-inbox',
    order: 5,
    phase: 'discover',
    primaryNext: '2.2-offer-detail',
    section: 'jobs',
    title: { en: 'Opportunity inbox', vi: 'Hộp thư cơ hội' },
  },
  {
    authority: 'worker',
    guardrail: 'Địa chỉ đầy đủ chỉ hiển thị sau khi NestScout đã giao việc cho thợ.',
    icon: 'document',
    id: '2.2-offer-detail',
    order: 6,
    phase: 'discover',
    primaryNext: '2.3-accept-review',
    section: 'jobs',
    title: { en: 'Offer detail', vi: 'Chi tiết đề nghị' },
  },
  {
    authority: 'worker',
    guardrail: 'Kael không thể bấm nhận việc thay thợ; nút này cần xác nhận rõ từ người dùng.',
    icon: 'shield',
    id: '2.3-accept-review',
    order: 7,
    phase: 'accept',
    primaryNext: '2.4-route-eta',
    section: 'jobs',
    title: { en: 'Accept review', vi: 'Xác nhận nhận việc' },
  },
  {
    authority: 'worker',
    guardrail: 'Thời gian đến và liên hệ khách dùng dữ liệu việc thật; không tự đổi lịch hẹn.',
    icon: 'map',
    id: '2.4-route-eta',
    order: 8,
    phase: 'travel',
    primaryNext: '2.5-arrival-checkin',
    section: 'jobs',
    title: { en: 'Route and ETA', vi: 'Di chuyển và thời gian đến' },
  },
  {
    authority: 'worker',
    guardrail: 'Đến nơi cần tín hiệu vị trí hoặc bằng chứng thủ công, không tự đánh dấu.',
    icon: 'map',
    id: '2.5-arrival-checkin',
    order: 9,
    phase: 'travel',
    primaryNext: '2.7-in-progress',
    section: 'jobs',
    title: { en: 'Location', vi: 'Địa điểm' },
  },
  {
    authority: 'worker',
    guardrail: 'Thợ chỉ cập nhật tiến độ và bằng chứng; Kael không tự chuyển trạng thái thay thợ.',
    icon: 'tools',
    id: '2.7-in-progress',
    order: 10,
    phase: 'execute',
    primaryNext: '2.10-completion-evidence',
    section: 'jobs',
    title: { en: 'In progress', vi: 'Đang thực hiện' },
  },
  {
    authority: 'worker',
    guardrail: 'Kael được soạn nháp từ việc hiện tại; thợ phải kiểm tra nội dung trước khi gửi đổi phạm vi.',
    icon: 'scope',
    id: '2.8-scope-change',
    order: 11,
    phase: 'approval',
    primaryNext: '2.9-approval-wait',
    section: 'jobs',
    title: { en: 'Scope change', vi: 'Đổi phạm vi' },
  },
  {
    authority: 'system',
    guardrail: 'Chỉ làm phần phát sinh sau khi NestScout duyệt.',
    icon: 'clock',
    id: '2.9-approval-wait',
    order: 12,
    phase: 'approval',
    primaryNext: '2.10-completion-evidence',
    section: 'jobs',
    title: { en: 'Customer approval wait', vi: 'Chờ khách phê duyệt' },
  },
  {
    authority: 'worker',
    guardrail: 'Hồ sơ hoàn tất cần ghi chú hoặc ảnh thật; thợ là người gửi, Kael chỉ đối chiếu.',
    icon: 'evidence',
    id: '2.10-completion-evidence',
    order: 13,
    phase: 'complete',
    primaryNext: '2.11-completion-submitted',
    section: 'jobs',
    title: { en: 'Completion evidence', vi: 'Bằng chứng hoàn tất' },
  },
  {
    authority: 'system',
    guardrail: 'Sau khi gửi, thợ chờ NestScout cập nhật xác nhận và đối soát; ứng dụng không tự đóng việc.',
    icon: 'shield',
    id: '2.11-completion-submitted',
    order: 14,
    phase: 'complete',
    primaryNext: '2.12-case-closed',
    section: 'jobs',
    title: { en: 'Completion submitted', vi: 'Đã gửi hoàn tất' },
  },
  {
    authority: 'system',
    guardrail: 'Số đối soát và rút tiền chỉ hiển thị khi hệ thống đã ghi nhận, không tự tạo thu nhập.',
    icon: 'wallet',
    id: '2.12-case-closed',
    order: 15,
    phase: 'complete',
    primaryNext: '4.1-earnings-overview',
    section: 'jobs',
    title: { en: 'Case closed', vi: 'Case đã đóng' },
  },
  {
    authority: 'kael_assist',
    guardrail: 'Kael chat là tư vấn giới hạn, không nhận việc, không đổi giá và không quyết kết quả.',
    icon: 'chat',
    id: '3.1-kael-chat-normal',
    order: 16,
    phase: 'assist',
    primaryNext: '3.2-kael-job-intake',
    section: 'kael',
    title: { en: 'Kael', vi: 'Kael' },
  },
  {
    authority: 'kael_assist',
    guardrail: 'Kael có thể lọc và giải thích cơ hội; thợ vẫn là người mở và nhận việc.',
    icon: 'jobs',
    id: '3.2-kael-job-intake',
    order: 17,
    phase: 'assist',
    primaryNext: '2.2-offer-detail',
    section: 'kael',
    title: { en: 'Kael job intake', vi: 'Kael nhận việc' },
  },
  {
    authority: 'system',
    guardrail: 'Thu nhập chỉ đọc từ dữ liệu đối soát thật, không tạo số tháng hay giao dịch mẫu.',
    icon: 'earnings',
    id: '4.1-earnings-overview',
    order: 24,
    phase: 'settle',
    primaryNext: '4.2-ledger-detail',
    section: 'earnings',
    title: { en: 'Earnings overview', vi: 'Thu nhập' },
  },
  {
    authority: 'system',
    guardrail: 'Chi tiết đối soát chỉ dùng số đã ghi nhận, không tự mở tiền rút.',
    icon: 'wallet',
    id: '4.2-ledger-detail',
    order: 25,
    phase: 'settle',
    primaryNext: '4.3-payout-request',
    section: 'earnings',
    title: { en: 'Ledger detail', vi: 'Chi tiết đối soát' },
  },
  {
    authority: 'worker',
    guardrail: 'Yêu cầu rút tiền cần xác nhận rõ của thợ và tài khoản đã xác minh.',
    icon: 'wallet',
    id: '4.3-payout-request',
    order: 26,
    phase: 'settle',
    primaryNext: '4.4-payout-method',
    section: 'earnings',
    title: { en: 'Payout request', vi: 'Yêu cầu rút tiền' },
  },
  {
    authority: 'worker',
    guardrail: 'Đổi tài khoản nhận tiền cần đi qua luồng xác minh hiện hữu.',
    icon: 'shield',
    id: '4.4-payout-method',
    order: 27,
    phase: 'settle',
    primaryNext: '4.3-payout-request',
    section: 'earnings',
    title: { en: 'Payout method', vi: 'Tài khoản nhận tiền' },
  },
  {
    authority: 'worker',
    guardrail: 'Hồ sơ chỉ hiển thị thông tin thợ thật, không bịa cấp bậc hoặc số việc.',
    icon: 'profile',
    id: '5.1-profile-overview',
    order: 28,
    phase: 'grow',
    primaryNext: '5.2-worker-ranking',
    section: 'profile',
    title: { en: 'Worker profile', vi: 'Hồ sơ thợ' },
  },
  {
    authority: 'system',
    guardrail: 'Xếp hạng chỉ đọc từ dữ liệu hiệu suất thật; nếu thiếu thì hiển thị trạng thái trống.',
    icon: 'shield',
    id: '5.2-worker-ranking',
    order: 29,
    phase: 'grow',
    primaryNext: '5.4-reliability-insights',
    section: 'profile',
    title: { en: 'Worker ranking', vi: 'Xếp hạng thợ' },
  },
  {
    authority: 'worker',
    guardrail: 'Kỹ năng và khu vực chỉ lấy từ hồ sơ thợ thật; không vẽ vùng phủ hoặc nhãn trạng thái giả.',
    icon: 'tools',
    id: '5.3-skills-service-area',
    order: 30,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Skills and service area', vi: 'Kỹ năng và khu vực' },
  },
  {
    authority: 'system',
    guardrail: 'Độ tin cậy chỉ tính từ dữ liệu hiệu suất thật; chỉ số đẹp trong mẫu thiết kế không được dùng làm dữ liệu.',
    icon: 'shield',
    id: '5.4-reliability-insights',
    order: 31,
    phase: 'grow',
    primaryNext: '5.2-worker-ranking',
    section: 'profile',
    title: { en: 'Reliability insights', vi: 'Độ tin cậy' },
  },
  {
    authority: 'worker',
    guardrail: 'Alias cài đặt cũ chỉ mở màn cài đặt tài khoản; không còn hiển thị hub tiện ích tài khoản cũ.',
    icon: 'shield',
    id: '5.5-account-utilities',
    order: 32,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Settings', vi: 'Cài đặt' },
  },
  {
    authority: 'worker',
    guardrail: 'Bộ nhớ Kael chỉ là tùy chọn có quyền kiểm soát; shell này không lưu ưu tiên mới hay tự lọc cơ hội.',
    icon: 'shield',
    id: '5.6-agent-memory-preferences',
    order: 33,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Kael memory preferences', vi: 'Bộ nhớ & ưu tiên' },
  },
  {
    authority: 'system',
    guardrail: 'Giấy tờ xác minh chỉ hiện tình trạng thật từ hồ sơ; thiếu giấy tờ thì hiển thị trạng thái trống an toàn.',
    icon: 'document',
    id: '5.7-verification-documents',
    order: 34,
    phase: 'grow',
    primaryNext: '5.8-bank-tax-center',
    section: 'profile',
    title: { en: 'Verification documents', vi: 'Giấy tờ & xác minh' },
  },
  {
    authority: 'system',
    guardrail: 'Ngân hàng và thuế chỉ đọc tài khoản nhận tiền, đối soát và chứng từ đã có; không tự yêu cầu rút tiền.',
    icon: 'wallet',
    id: '5.8-bank-tax-center',
    order: 35,
    phase: 'grow',
    primaryNext: '5.10-support-settings',
    section: 'profile',
    title: { en: 'Bank and tax center', vi: 'Ngân hàng và thuế' },
  },
  {
    authority: 'system',
    guardrail: 'Đánh giá và phản hồi chỉ dùng dữ liệu tổng hợp thật; không đếng lời khách hoặc chuỗi 5 sao giả.',
    icon: 'chat',
    id: '5.9-reviews-feedback',
    order: 36,
    phase: 'grow',
    primaryNext: '5.2-worker-ranking',
    section: 'profile',
    title: { en: 'Reviews and feedback', vi: 'Đánh giá và phản hồi' },
  },
  {
    authority: 'worker',
    guardrail: 'Cài đặt tài khoản chỉ dùng hồ sơ, bảo mật, ngôn ngữ và bộ nhớ Kael được phép.',
    icon: 'shield',
    id: '5.10-support-settings',
    order: 37,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Settings', vi: 'Cài đặt' },
  },
]

export const workerV5EnglishGuardrails: Partial<Record<WorkerV5ScreenId, string>> = {
  '1.1-worker-home': 'Kael only syncs context and suggestions; the worker controls availability.',
  '1.2-shift-brief': 'Weather, demand, and priority signals stay hidden until real data exists.',
  '1.3-demand-map': 'The opportunity map uses service areas or real broadcasts, never invented demand.',
  '1.4-smart-schedule': 'Kael may suggest a schedule, but it cannot accept work or change plans for the worker.',
  '2.1-opportunity-inbox': 'Kael can filter and explain fit; the worker opens, accepts, or declines.',
  '2.2-offer-detail': 'Full address is shown only after NestScout assigns the job to the worker.',
  '2.3-accept-review': 'Kael cannot accept work for the worker; confirmation must be explicit.',
  '2.4-route-eta': 'ETA and customer contact use real job data and do not create a new promise.',
  '2.5-arrival-checkin': 'Check-in needs location signal or manual evidence; it is never automatic.',
  '2.7-in-progress': 'Workers update progress and evidence; Kael does not change status for them.',
  '2.8-scope-change': 'Kael can draft from the work resolution context; the worker reviews before sending.',
  '2.9-approval-wait': 'Approval stays NestScout-recorded; extra work waits for a real NestScout decision.',
  '2.10-completion-evidence': 'Completion needs real notes or photos; the worker submits the artifact.',
  '2.11-completion-submitted': 'After submission, the worker waits for NestScout confirmation and settlement.',
  '2.12-case-closed': 'Ledger and payout data appear only after the system records them.',
  '3.1-kael-chat-normal': 'Kael chat is bounded advisory, not a work decision surface.',
  '3.2-kael-job-intake': 'Kael can filter and explain opportunities; the worker still accepts.',
  '4.1-earnings-overview': 'Earnings read from real settlement data and never invent monthly totals.',
  '4.2-ledger-detail': 'Ledger detail uses recorded settlement numbers only.',
  '4.3-payout-request': 'Payout requests need explicit worker confirmation and a verified account.',
  '4.4-payout-method': 'Changing payout account must use the existing verification flow.',
  '5.1-profile-overview': 'Profile shows real worker data only, without invented level or job totals.',
  '5.2-worker-ranking': 'Ranking reads from real performance insights or shows an honest empty state.',
  '5.3-skills-service-area': 'Skills and service area update through the real worker profile.',
  '5.4-reliability-insights': 'Reliability uses real performance insights, never decorative reference numbers.',
  '5.5-account-utilities': 'Legacy settings alias opens the account settings surface instead of the old utility hub.',
  '5.6-agent-memory-preferences': 'Kael memory remains worker-controlled and this shell does not save new preferences.',
  '5.7-verification-documents': 'Verification documents show real profile status and honest missing states.',
  '5.8-bank-tax-center': 'Bank and tax center reads recorded payout data only and never submits payout by itself.',
  '5.9-reviews-feedback': 'Reviews use real aggregate feedback only; customer quotes are not fabricated.',
  '5.10-support-settings': 'Settings stay in-app and keep account, security, language, and Kael memory controls explicit.',
}

export const phaseCopy: Record<WorkerV5Phase, Record<AppLanguage, string>> = {
  accept: { en: 'Accept', vi: 'Nhận việc' },
  approval: { en: 'Approval', vi: 'Chờ quyết định' },
  assist: { en: 'Assist', vi: 'Hỗ trợ' },
  close: { en: 'Close', vi: 'Kết thúc việc' },
  complete: { en: 'Complete', vi: 'Hoàn tất' },
  discover: { en: 'Discover', vi: 'Tìm cơ hội' },
  execute: { en: 'Execute', vi: 'Thực hiện' },
  grow: { en: 'Growth', vi: 'Phát triển' },
  money: { en: 'Money', vi: 'Thu nhập' },
  prepare: { en: 'Prepare', vi: 'Chuẩn bị' },
  profile: { en: 'Profile', vi: 'Hồ sơ' },
  settle: { en: 'Settlement', vi: 'Đối soát' },
  travel: { en: 'Travel', vi: 'Di chuyển' },
  work: { en: 'Work', vi: 'Đang làm' },
}

export function getWorkerV5Screen(id: string | undefined) {
  return WORKER_V5_SCREENS.find((screen) => screen.id === id) ?? null
}

export function requireWorkerV5Screen(id: WorkerV5ScreenId) {
  const screen = getWorkerV5Screen(id)
  if (!screen) throw new Error(`Missing worker v5 screen: ${id}`)
  return screen
}
