import type { AppLanguage } from '@/lib/app-language'

import type {
  WorkerV5Phase,
  WorkerV5ScreenDefinition,
  WorkerV5ScreenId,
} from './types'

export const WORKER_V5_SCREENS: WorkerV5ScreenDefinition[] = [
  {
    authority: 'worker',
    guardrail: 'Kael chỉ đồng bộ bối cảnh và gợi ý; thợ tự bật/tắt nhận việc.',
    icon: 'home',
    id: '1.1-worker-home',
    order: 1,
    phase: 'prepare',
    primaryNext: '2.1-opportunity-inbox',
    section: 'home',
    title: { en: 'Worker home', vi: 'Trang chủ thợ' },
  },
  {
    authority: 'worker',
    guardrail: 'Kael chỉ lọc và giải thích mức phù hợp; thợ là người mở, nhận hoặc từ chối.',
    icon: 'jobs',
    id: '2.1-opportunity-inbox',
    order: 5,
    phase: 'discover',
    primaryNext: '2.2-offer-detail',
    section: 'jobs',
    title: { en: 'Work', vi: 'Công việc' },
  },
  {
    authority: 'worker',
    guardrail: 'Thợ xem đủ thông tin được phép rồi tự nhận hoặc từ chối; địa chỉ vẫn theo quyền backend.',
    icon: 'document',
    id: '2.2-offer-detail',
    order: 6,
    phase: 'accept',
    primaryNext: '2.3-customer-confirmation-wait',
    section: 'jobs',
    title: { en: 'New opportunity', vi: 'Cơ hội mới' },
  },
  {
    authority: 'system',
    guardrail: 'Sau khi thợ nhận việc, chỉ khách mới có thể xác nhận lựa chọn; chưa mở địa chỉ chi tiết hay thao tác thi công.',
    icon: 'clock',
    id: '2.3-customer-confirmation-wait',
    order: 7,
    phase: 'accept',
    primaryNext: '2.4-route-eta',
    section: 'jobs',
    title: { en: 'Awaiting customer', vi: 'Chờ khách xác nhận' },
  },
  {
    authority: 'worker',
    guardrail: 'Thời gian đến và liên hệ khách dùng dữ liệu việc thật; không tự đổi lịch hẹn.',
    icon: 'map',
    id: '2.4-route-eta',
    order: 8,
    phase: 'travel',
    primaryNext: '2.7-in-progress',
    section: 'jobs',
    title: { en: 'Route and ETA', vi: 'Di chuyển và thời gian đến' },
  },
  {
    authority: 'worker',
    guardrail: 'Thợ chỉ cập nhật tiến độ và bằng chứng; Kael không tự chuyển trạng thái thay thợ.',
    icon: 'tools',
    id: '2.7-in-progress',
    order: 10,
    phase: 'execute',
    primaryNext: '2.10-completion-evidence',
    section: 'jobs',
    title: { en: 'In progress', vi: 'Đang thực hiện' },
  },
  {
    authority: 'worker',
    guardrail: 'Kael được soạn nháp từ việc hiện tại; thợ phải kiểm tra nội dung trước khi gửi đổi phạm vi.',
    icon: 'scope',
    id: '2.8-scope-change',
    order: 11,
    phase: 'approval',
    primaryNext: '2.9-approval-wait',
    section: 'jobs',
    title: { en: 'Scope change', vi: 'Đổi phạm vi' },
  },
  {
    authority: 'system',
    guardrail: 'Chỉ làm phần phát sinh sau khi khách duyệt trong ứng dụng.',
    icon: 'clock',
    id: '2.9-approval-wait',
    order: 12,
    phase: 'approval',
    primaryNext: '2.10-completion-evidence',
    section: 'jobs',
    title: { en: 'Customer approval wait', vi: 'Chờ khách phê duyệt' },
  },
  {
    authority: 'worker',
    guardrail: 'Hồ sơ hoàn tất cần ghi chú hoặc ảnh thật; thợ là người gửi, Kael chỉ đối chiếu.',
    icon: 'evidence',
    id: '2.10-completion-evidence',
    order: 13,
    phase: 'complete',
    primaryNext: '2.11-completion-submitted',
    section: 'jobs',
    title: { en: 'Completion evidence', vi: 'Bằng chứng hoàn tất' },
  },
  {
    authority: 'system',
    guardrail: 'Sau khi gửi, thợ chờ xác nhận của khách và đối soát từ hệ thống; ứng dụng không tự đóng việc.',
    icon: 'shield',
    id: '2.11-completion-submitted',
    order: 14,
    phase: 'complete',
    primaryNext: '2.12-case-closed',
    section: 'jobs',
    title: { en: 'Completion submitted', vi: 'Đã gửi hoàn tất' },
  },
  {
    authority: 'system',
    guardrail: 'Số đối soát và rút tiền chỉ hiển thị khi hệ thống đã ghi nhận, không tự tạo thu nhập.',
    icon: 'wallet',
    id: '2.12-case-closed',
    order: 15,
    phase: 'complete',
    primaryNext: '4.1-earnings-overview',
    section: 'jobs',
    title: { en: 'Case closed', vi: 'Case đã đóng' },
  },
  {
    authority: 'kael_assist',
    guardrail: 'Kael chat là tư vấn giới hạn, không nhận việc, không đổi giá và không quyết kết quả.',
    icon: 'chat',
    id: '3.1-kael-chat-normal',
    order: 16,
    phase: 'assist',
    primaryNext: '3.2-kael-job-intake',
    section: 'kael',
    title: { en: 'Kael', vi: 'Kael' },
  },
  {
    authority: 'kael_assist',
    guardrail: 'Kael có thể lọc và giải thích cơ hội; thợ vẫn là người mở và nhận việc.',
    icon: 'jobs',
    id: '3.2-kael-job-intake',
    order: 17,
    phase: 'assist',
    primaryNext: '2.2-offer-detail',
    section: 'kael',
    title: { en: 'Kael job intake', vi: 'Kael nhận việc' },
  },
  {
    authority: 'system',
    guardrail: 'Thu nhập chỉ đọc từ dữ liệu đối soát thật, không tạo số tháng hay giao dịch mẫu.',
    icon: 'earnings',
    id: '4.1-earnings-overview',
    order: 24,
    phase: 'settle',
    primaryNext: '4.2-ledger-detail',
    section: 'earnings',
    title: { en: 'Earnings overview', vi: 'Thu nhập' },
  },
  {
    authority: 'system',
    guardrail: 'Lịch sử chỉ hiển thị những giao dịch thu nhập đã được ghi nhận.',
    icon: 'wallet',
    id: '4.2-ledger-detail',
    order: 25,
    phase: 'settle',
    primaryNext: '4.1-earnings-overview',
    section: 'earnings',
    title: { en: 'Transaction history', vi: 'Lịch sử giao dịch' },
  },
  {
    authority: 'system',
    guardrail: 'Thợ chỉ tạo yêu cầu rút từ số dư có thể rút, sau khi tài khoản nhận tiền đã được quản trị viên xác nhận.',
    icon: 'wallet',
    id: '4.3-payout-request',
    order: 26,
    phase: 'settle',
    primaryNext: '4.1-earnings-overview',
    section: 'earnings',
    title: { en: 'Withdrawal request', vi: 'Yêu cầu rút tiền' },
  },
  {
    authority: 'worker',
    guardrail: 'Đổi tài khoản nhận tiền cần đi qua luồng xác minh hiện hữu.',
    icon: 'shield',
    id: '4.4-payout-method',
    order: 27,
    phase: 'settle',
    primaryNext: '4.1-earnings-overview',
    section: 'earnings',
    title: { en: 'Payout method', vi: 'Tài khoản nhận tiền' },
  },
  {
    authority: 'system',
    guardrail: 'Mức khởi điểm là 15%; bậc cao hơn chỉ giảm phí khi đáp ứng điều kiện đã ghi nhận.',
    icon: 'wallet',
    id: '4.5-commission-policy',
    order: 27.5,
    phase: 'settle',
    primaryNext: '4.1-earnings-overview',
    section: 'earnings',
    title: { en: 'Commission policy', vi: 'Chính sách hoa hồng' },
  },
  {
    authority: 'worker',
    guardrail: 'Hồ sơ chỉ hiển thị thông tin thợ thật, không bịa cấp bậc hoặc số việc.',
    icon: 'profile',
    id: '5.1-profile-overview',
    order: 28,
    phase: 'grow',
    primaryNext: '5.2-worker-ranking',
    section: 'profile',
    title: { en: 'Worker profile', vi: 'Hồ sơ thợ' },
  },
  {
    authority: 'worker',
    guardrail: 'Xóa tài khoản phải được xác nhận rõ ràng và đi qua hỗ trợ để kiểm tra công việc, đối soát và dữ liệu cần lưu.',
    icon: 'profile',
    id: '5.15-worker-delete-account',
    order: 28.5,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Delete account', vi: 'Xóa tài khoản' },
  },
  {
    authority: 'system',
    guardrail: 'Xếp hạng chỉ đọc từ dữ liệu hiệu suất thật; nếu thiếu thì hiển thị trạng thái trống.',
    icon: 'shield',
    id: '5.2-worker-ranking',
    order: 29,
    phase: 'grow',
    primaryNext: '5.4-reliability-insights',
    section: 'profile',
    title: { en: 'Worker ranking', vi: 'Xếp hạng thợ' },
  },
  {
    authority: 'worker',
    guardrail: 'Kỹ năng và khu vực chỉ lấy từ hồ sơ thợ thật; không vẽ vùng phủ hoặc nhãn trạng thái giả.',
    icon: 'tools',
    id: '5.3-skills-service-area',
    order: 30,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Skills and service area', vi: 'Kỹ năng và khu vực' },
  },
  {
    authority: 'system',
    guardrail: 'Độ tin cậy chỉ tính từ dữ liệu hiệu suất thật; chỉ số đẹp trong mẫu thiết kế không được dùng làm dữ liệu.',
    icon: 'shield',
    id: '5.4-reliability-insights',
    order: 31,
    phase: 'grow',
    primaryNext: '5.2-worker-ranking',
    section: 'profile',
    title: { en: 'Reliability insights', vi: 'Độ tin cậy' },
  },
  {
    authority: 'worker',
    guardrail: 'Alias cài đặt cũ chỉ mở màn cài đặt tài khoản; không còn hiển thị hub tiện ích tài khoản cũ.',
    icon: 'shield',
    id: '5.5-account-utilities',
    order: 32,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Settings', vi: 'Cài đặt' },
  },
  {
    authority: 'worker',
    guardrail: 'Bộ nhớ Kael chỉ là tùy chọn có quyền kiểm soát; shell này không lưu ưu tiên mới hay tự lọc cơ hội.',
    icon: 'shield',
    id: '5.6-agent-memory-preferences',
    order: 33,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Kael memory preferences', vi: 'Bộ nhớ & ưu tiên' },
  },
  {
    authority: 'system',
    guardrail: 'Giấy tờ xác minh chỉ hiện tình trạng thật từ hồ sơ; thiếu giấy tờ thì hiển thị trạng thái trống an toàn.',
    icon: 'document',
    id: '5.7-verification-documents',
    order: 34,
    phase: 'grow',
    section: 'profile',
    title: { en: 'Verification documents', vi: 'Giấy tờ & xác minh' },
  },
  {
    authority: 'system',
    guardrail: 'Đánh giá và phản hồi chỉ dùng dữ liệu tổng hợp thật; không đếng lời khách hoặc chuỗi 5 sao giả.',
    icon: 'chat',
    id: '5.9-reviews-feedback',
    order: 35,
    phase: 'grow',
    primaryNext: '5.2-worker-ranking',
    section: 'profile',
    title: { en: 'Reviews and feedback', vi: 'Đánh giá và phản hồi' },
  },
  {
    authority: 'worker',
    guardrail: 'Cài đặt tài khoản chỉ dùng hồ sơ, bảo mật, ngôn ngữ và bộ nhớ Kael được phép.',
    icon: 'shield',
    id: '5.10-support-settings',
    order: 36,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Settings', vi: 'Cài đặt' },
  },
  {
    authority: 'worker',
    guardrail: 'Trạng thái nhận việc chỉ đổi qua thao tác sẵn có và không tạo lịch nghỉ hoặc số liệu giả.',
    icon: 'calendar',
    id: '5.11-worker-availability',
    order: 37,
    phase: 'grow',
    primaryNext: '5.1-profile-overview',
    section: 'profile',
    title: { en: 'Work availability', vi: 'Lịch nhận việc' },
  },
  {
    authority: 'worker',
    guardrail: 'Thông báo chỉ hiển thị dữ liệu đã có và đánh dấu đã đọc qua thao tác sẵn có.',
    icon: 'chat',
    id: '5.12-worker-notifications',
    order: 38,
    phase: 'grow',
    primaryNext: '5.10-support-settings',
    section: 'profile',
    title: { en: 'Notifications', vi: 'Thông báo' },
  },
  {
    authority: 'worker',
    guardrail: 'Hỗ trợ chỉ dẫn đến công việc hiện có hoặc Kael; không tự gửi yêu cầu hoặc thay đổi quyết định.',
    icon: 'chat',
    id: '5.13-worker-support',
    order: 39,
    phase: 'grow',
    primaryNext: '5.10-support-settings',
    section: 'profile',
    title: { en: 'Help and support', vi: 'Trợ giúp & hỗ trợ' },
  },
  {
    authority: 'system',
    guardrail: 'Chính sách dùng nội dung rõ ràng, không đưa ra cam kết ngoài các luồng đã có trong ứng dụng.',
    icon: 'shield',
    id: '5.14-worker-policies',
    order: 40,
    phase: 'grow',
    primaryNext: '5.10-support-settings',
    section: 'profile',
    title: { en: 'Worker policies', vi: 'Chính sách dành cho thợ' },
  },
]

export const workerV5EnglishGuardrails: Partial<Record<WorkerV5ScreenId, string>> = {
  '1.1-worker-home': 'Kael only syncs context and suggestions; the worker controls availability.',
  '2.1-opportunity-inbox': 'Kael can filter and explain fit; the worker opens, accepts, or declines.',
  '2.2-offer-detail': 'The worker explicitly accepts or declines while address detail follows backend access policy.',
  '2.3-customer-confirmation-wait': 'Only the customer can confirm the candidate; travel, address detail, and execution stay locked meanwhile.',
  '2.4-route-eta': 'ETA and customer contact use real job data and do not create a new promise.',
  '2.7-in-progress': 'Workers update progress and evidence; Kael does not change status for them.',
  '2.8-scope-change': 'Kael can draft from the work resolution context; the worker reviews before sending.',
  '2.9-approval-wait': 'Approval stays system-recorded; extra work waits for the customer decision.',
  '2.10-completion-evidence': 'Completion needs real notes or photos; the worker submits the artifact.',
  '2.11-completion-submitted': 'After submission, the worker waits for customer confirmation and system settlement.',
  '2.12-case-closed': 'Ledger and payout data appear only after the system records them.',
  '3.1-kael-chat-normal': 'Kael chat is bounded advisory, not a work decision surface.',
  '3.2-kael-job-intake': 'Kael can filter and explain opportunities; the worker still accepts.',
  '4.1-earnings-overview': 'Earnings read from real settlement data and never invent monthly totals.',
  '4.2-ledger-detail': 'Transaction history uses recorded earnings entries only.',
  '4.3-payout-request': 'Workers request only their recorded available balance after the receiving account has been verified.',
  '4.4-payout-method': 'Changing payout account must use the existing verification flow.',
  '4.5-commission-policy': 'The starting commission is 15%; higher levels may reduce it only after recorded requirements are met.',
  '5.1-profile-overview': 'Profile shows real worker data only, without invented level or job totals.',
  '5.15-worker-delete-account': 'Account deletion requires explicit confirmation and support review of active work, settlement, and retained records.',
  '5.2-worker-ranking': 'Ranking reads from real performance insights or shows an honest empty state.',
  '5.3-skills-service-area': 'Skills and service area update through the real worker profile.',
  '5.4-reliability-insights': 'Reliability uses real performance insights, never decorative reference numbers.',
  '5.5-account-utilities': 'Legacy settings alias opens the account settings surface instead of the old utility hub.',
  '5.6-agent-memory-preferences': 'Kael memory remains worker-controlled and this shell does not save new preferences.',
  '5.7-verification-documents': 'Verification documents show real profile status and honest missing states.',
  '5.9-reviews-feedback': 'Reviews use real aggregate feedback only; customer quotes are not fabricated.',
  '5.10-support-settings': 'Settings stay in-app and keep account, security, language, and Kael memory controls explicit.',
  '5.11-worker-availability': 'Availability uses the existing worker control and never invents a schedule or pause state.',
  '5.12-worker-notifications': 'Notifications use recorded updates and the existing read action.',
  '5.13-worker-support': 'Support leads to existing work or Kael help without submitting decisions on the worker’s behalf.',
  '5.14-worker-policies': 'Policies explain the current product boundaries without promises beyond the implemented workflow.',
}

export const phaseCopy: Record<WorkerV5Phase, Record<AppLanguage, string>> = {
  accept: { en: 'Accept', vi: 'Nhận việc' },
  approval: { en: 'Approval', vi: 'Chờ quyết định' },
  assist: { en: 'Assist', vi: 'Hỗ trợ' },
  close: { en: 'Close', vi: 'Kết thúc việc' },
  complete: { en: 'Complete', vi: 'Hoàn tất' },
  discover: { en: 'Discover', vi: 'Tìm cơ hội' },
  execute: { en: 'Execute', vi: 'Thực hiện' },
  grow: { en: 'Growth', vi: 'Phát triển' },
  money: { en: 'Money', vi: 'Thu nhập' },
  prepare: { en: 'Prepare', vi: 'Chuẩn bị' },
  profile: { en: 'Profile', vi: 'Hồ sơ' },
  settle: { en: 'Settlement', vi: 'Đối soát' },
  travel: { en: 'Travel', vi: 'Di chuyển' },
  work: { en: 'Work', vi: 'Đang làm' },
}

export function getWorkerV5Screen(id: string | undefined) {
  return WORKER_V5_SCREENS.find((screen) => screen.id === id) ?? null
}

export function requireWorkerV5Screen(id: WorkerV5ScreenId) {
  const screen = getWorkerV5Screen(id)
  if (!screen) throw new Error(`Missing worker v5 screen: ${id}`)
  return screen
}
