// Geometry and asset bindings extracted from the approved Login Gate source package.
export const DESIGN = {
  reference: {
    width: 941,
    height: 1672,
  },
  appCrop: {
    x: 70,
    y: 98,
    width: 800,
    height: 1510,
  },
  brand: {
    id: 'brand',
    rect: [284, 104, 384, 104],
    taglineMask: [154, 78, 180, 26],
    label: 'NestScout',
  },
  texts: [
    {
      id: 'heading',
      rect: [279, 248, 391, 84],
      text: 'Chọn lối vào',
      fontSize: 68,
      lineHeight: 84,
      fontWeight: '700',
      letterSpacing: -2.4,
      align: 'center',
      color: '#073D41',
      role: 'heading',
    },
    {
      id: 'intro',
      rect: [283, 337, 385, 37],
      text: 'Cùng nhau, ngôi nhà luôn ổn.',
      fontSize: 28,
      lineHeight: 37,
      fontWeight: '400',
      letterSpacing: -0.65,
      align: 'center',
      color: '#59767D',
      role: 'text',
    },
    {
      id: 'customer-title',
      rect: [115, 617, 269, 61],
      text: 'Khách hàng',
      fontSize: 46,
      lineHeight: 61,
      fontWeight: '700',
      letterSpacing: -1.35,
      align: 'left',
      color: '#073D41',
      role: 'heading',
      parent: 'customer',
    },
    {
      id: 'customer-description',
      rect: [116, 688, 243, 70],
      text: 'Đặt dịch vụ,\nnhà luôn gọn gàng.',
      fontSize: 28,
      lineHeight: 36,
      fontWeight: '400',
      letterSpacing: -0.6,
      align: 'left',
      color: '#56737B',
      role: 'text',
      parent: 'customer',
    },
    {
      id: 'worker-title',
      rect: [115, 1110, 248, 62],
      text: 'Đối tác thợ',
      fontSize: 46,
      lineHeight: 62,
      fontWeight: '700',
      letterSpacing: -1.35,
      align: 'left',
      color: '#073D41',
      role: 'heading',
      parent: 'worker',
    },
    {
      id: 'worker-description',
      rect: [116, 1180, 253, 73],
      text: 'Nhận việc linh hoạt,\ngia tăng thu nhập.',
      fontSize: 28,
      lineHeight: 36,
      fontWeight: '400',
      letterSpacing: -0.6,
      align: 'left',
      color: '#56737B',
      role: 'text',
      parent: 'worker',
    },
    {
      id: 'footer-caption',
      rect: [264, 1541, 386, 25],
      text: 'DỊCH VỤ NHÀ  •  CUỘC SỐNG TỐT HƠN',
      fontSize: 13,
      lineHeight: 25,
      fontWeight: '400',
      letterSpacing: 3.1,
      align: 'center',
      color: '#657F87',
      role: 'text',
    },
  ],
  cards: [
    {
      id: 'customer',
      rect: [82, 470, 776, 495],
      arrow: [115, 793, 116, 114],
      label: 'Khách hàng',
      description: 'Đặt dịch vụ, nhà luôn gọn gàng.',
      testID: 'auth-entry-role-customer',
    },
    {
      id: 'worker',
      rect: [82, 979, 776, 495],
      arrow: [115, 1290, 116, 114],
      label: 'Đối tác thợ',
      description: 'Nhận việc linh hoạt, gia tăng thu nhập.',
      testID: 'auth-entry-role-worker',
    },
  ],
  rules: {
    textModeDefault: 'reference',
    appMaxWidth: 480,
    uniformScaling: true,
    nativeMinScale: 0.4,
    overlapPixels: 2,
  },
} as const

export const ASSETS = {
  'reference-backdrop': require('./assets/reference-backdrop.png'),
  brand: require('./assets/brand.png'),
  heading: require('./assets/heading.png'),
  'heading-clean': require('./assets/heading-clean.png'),
  intro: require('./assets/intro.png'),
  'intro-clean': require('./assets/intro-clean.png'),
  'customer-title': require('./assets/customer-title.png'),
  'customer-title-clean': require('./assets/customer-title-clean.png'),
  'customer-description': require('./assets/customer-description.png'),
  'customer-description-clean': require('./assets/customer-description-clean.png'),
  'worker-title': require('./assets/worker-title.png'),
  'worker-title-clean': require('./assets/worker-title-clean.png'),
  'worker-description': require('./assets/worker-description.png'),
  'worker-description-clean': require('./assets/worker-description-clean.png'),
  'footer-caption': require('./assets/footer-caption.png'),
  'footer-caption-clean': require('./assets/footer-caption-clean.png'),
  'customer-surface': require('./assets/customer-surface.png'),
  'customer-arrow': require('./assets/customer-arrow.png'),
  'worker-surface': require('./assets/worker-surface.png'),
  'worker-arrow': require('./assets/worker-arrow.png'),
  'app-backdrop': require('./assets/app-backdrop.png'),
} as const

export type AssetKey = keyof typeof ASSETS
export type TextSpec = (typeof DESIGN.texts)[number]
export type CardSpec = (typeof DESIGN.cards)[number]
