import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  approvalDecisionCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  approvalDecisionIcon: {
    height: 42,
    width: 42,
  },
  approvalDecisionIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  approvalDecisionList: {
    backgroundColor: 'rgba(255,255,255,0.77)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    ...shadow.soft,
  },
  approvalDecisionMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  approvalDecisionRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 72,
    padding: 12,
    position: 'relative',
  },
  approvalDecisionStatus: {
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
    maxWidth: 92,
    minWidth: 54,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: 'center',
  },
  approvalDecisionTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  bankChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.93)',
    borderRadius: 21,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 68,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 11,
    position: 'relative',
    ...shadow.soft,
  },
  bankChipCheck: {
    alignItems: 'center',
    backgroundColor: color.brand.primary,
    borderRadius: 8,
    height: 16,
    justifyContent: 'center',
    position: 'absolute',
    right: 5,
    top: 5,
    width: 16,
  },
  bankChipCheckText: {
    color: color.text.inverse,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 11,
  },
  bankChipGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  bankChipLabel: {
    color: color.text.strong,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    textAlign: 'center',
  },
  bankChipSelected: {
    borderColor: 'rgba(13,179,159,0.52)',
    shadowColor: color.brand.primary,
    shadowOffset: { height: 13, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 27,
  },
  bankChipValue: {
    color: color.text.muted,
    fontSize: 8,
    fontWeight: '700',
    lineHeight: 11,
    marginTop: 3,
    textAlign: 'center',
  },
  bankLogoImage: {
    height: 34,
    width: 58,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 27,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 32,
    marginTop: 8,
  },
  earningsHeroAura: {
    bottom: 'auto',
    height: 190,
    left: '34%',
    right: -70,
    top: -74,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 148,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  earningsHeroIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 3,
  },
  earningsHeroPill: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
})
