import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.72,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  profileAvatar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 18,
    borderWidth: 1,
    height: 54,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 54,
    ...shadow.soft,
  },
  profileAvatarAddGlyph: {
    color: color.brand.primaryDark,
    fontSize: 25,
    fontWeight: '400',
    lineHeight: 28,
  },
  profileAvatarEmpty: {
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  profileAvatarImage: {
    height: '100%',
    width: '100%',
  },
  profileAvatarPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.975 }],
  },
  profileDashboard: {
    flexDirection: 'row',
    gap: 10,
  },
  profileDashboardCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.80)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 24,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 98,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 12,
    position: 'relative',
    ...shadow.soft,
  },
  profileDashboardCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  profileDashboardScore: {
    alignItems: 'center',
    backgroundColor: 'rgba(232,255,249,0.84)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 19,
    borderWidth: 1,
    flexShrink: 0,
    height: 54,
    justifyContent: 'center',
    width: 54,
    ...shadow.soft,
  },
  profileDashboardScoreLabel: {
    color: color.text.muted,
    fontSize: 8,
    fontWeight: '700',
    lineHeight: 10,
  },
  profileDashboardScoreValue: {
    color: color.brand.primaryDark,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 24,
  },
  profileDashboardTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileHeader: {
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 82,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 9,
    position: 'relative',
    width: '94%',
    ...shadow.soft,
  },
  profileHeaderMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
  },
  profileHeaderName: {
    color: color.text.strong,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20,
  },
  profileHeaderText: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  profileProgressFill: {
    backgroundColor: '#08AF9C',
    borderRadius: 999,
    height: '100%',
  },
  profileProgressTrack: {
    backgroundColor: 'rgba(10,139,125,0.12)',
    borderColor: 'rgba(127,226,215,0.42)',
    borderRadius: 999,
    borderWidth: 1,
    height: 6,
    overflow: 'hidden',
    width: '100%',
  },
})
