import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.72,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  profileAvatar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    width: 64,
    ...shadow.soft,
  },
  profileAvatarImage: {
    height: 42,
    width: 42,
  },
  profileDashboard: {
    flexDirection: 'row',
    gap: 10,
  },
  profileDashboardCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.80)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 24,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 98,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 12,
    position: 'relative',
    ...shadow.soft,
  },
  profileDashboardCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  profileDashboardScore: {
    alignItems: 'center',
    backgroundColor: 'rgba(232,255,249,0.84)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 19,
    borderWidth: 1,
    flexShrink: 0,
    height: 54,
    justifyContent: 'center',
    width: 54,
    ...shadow.soft,
  },
  profileDashboardScoreLabel: {
    color: color.text.muted,
    fontSize: 8,
    fontWeight: '700',
    lineHeight: 10,
  },
  profileDashboardScoreValue: {
    color: color.brand.primaryDark,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 24,
  },
  profileDashboardTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileHeader: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 13,
    minHeight: 112,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
  },
  profileHeaderChip: {
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    maxWidth: 118,
    minWidth: 72,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  profileHeaderChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    paddingTop: 2,
  },
  profileHeaderChipText: {
    color: color.brand.primaryDark,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    textAlign: 'center',
  },
  profileHeaderMeta: {
    color: color.text.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileHeaderMiniChip: {
    backgroundColor: 'rgba(229,255,249,0.78)',
    borderColor: 'rgba(127,226,215,0.62)',
    borderRadius: 999,
    borderWidth: 1,
    color: color.brand.primaryDark,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    maxWidth: 112,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  profileHeaderName: {
    color: color.text.strong,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 23,
  },
  profileHeaderText: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  profileProgressFill: {
    backgroundColor: '#08AF9C',
    borderRadius: 999,
    height: '100%',
    minWidth: 3,
  },
  profileProgressTrack: {
    backgroundColor: 'rgba(10,139,125,0.12)',
    borderColor: 'rgba(127,226,215,0.42)',
    borderRadius: 999,
    borderWidth: 1,
    height: 7,
    marginTop: 2,
    overflow: 'hidden',
    width: '100%',
  },
})
