import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: -0.5,
    lineHeight: 33,
    marginTop: 7,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 136,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  earningsHeroIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 25,
    borderWidth: 1,
    height: 70,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 70,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    position: 'relative',
    zIndex: 1,
  },
  memorySwitchCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  memorySwitchIcon: {
    height: 42,
    width: 42,
  },
  memorySwitchIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    flexShrink: 0,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 64,
    zIndex: 1,
    ...shadow.soft,
  },
  memorySwitchList: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  memorySwitchRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 13,
    minHeight: 82,
    paddingHorizontal: 14,
    paddingVertical: 11,
    position: 'relative',
    zIndex: 1,
  },
  memorySwitchRowLast: {
    borderBottomWidth: 0,
  },
  memorySwitchTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
  },
  memorySwitchValue: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
  },
  profileRouteIconVisualBoost: {
    transform: [{ scale: 1.32 }],
  },
  toggleKnob: {
    backgroundColor: color.mint.white,
    borderRadius: 10,
    height: 20,
    shadowColor: color.text.strong,
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    width: 20,
  },
  toggleKnobOn: {
    marginLeft: 18,
  },
  toggleTrack: {
    backgroundColor: '#DFE9E7',
    borderRadius: radius.pill,
    flexShrink: 0,
    height: 26,
    padding: 3,
    width: 44,
  },
  toggleTrackOn: {
    backgroundColor: color.brand.primary,
  },
})
