import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  approvalDecisionCopy: {
    flex: 1,
    gap: 2,
    marginLeft: 46,
    minWidth: 0,
  },
  approvalDecisionIcon: {
    height: 42,
    width: 42,
  },
  approvalDecisionIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  approvalDecisionList: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    ...shadow.soft,
  },
  approvalDecisionMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  approvalDecisionRow: {
    alignItems: 'stretch',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 0,
    minHeight: 72,
    padding: 12,
    position: 'relative',
  },
  approvalDecisionStatus: {
    alignSelf: 'center',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
    maxWidth: 92,
    marginLeft: 10,
    minWidth: 54,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: 'center',
  },
  approvalDecisionTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 27,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 32,
    marginTop: 8,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 148,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 3,
  },
  earningsHeroPill: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
  offerDetailListDivider: {
    borderTopColor: 'rgba(205,226,222,0.78)',
    borderTopWidth: 1,
  },
  rankingHeroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    position: 'relative',
    zIndex: 1,
  },
  rankingHeroTitle: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 23,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 28,
  },
  rankingProgressFill: {
    backgroundColor: color.brand.primaryDark,
    borderRadius: radius.pill,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
  },
  rankingProgressTrack: {
    backgroundColor: 'rgba(180,220,214,0.58)',
    borderRadius: radius.pill,
    height: 6,
    marginTop: 3,
    overflow: 'hidden',
    width: '100%',
  },
  rankingScoreOrb: {
    alignItems: 'center',
    backgroundColor: 'rgba(232,255,249,0.72)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 43,
    borderWidth: 1,
    flexShrink: 0,
    height: 86,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 86,
    ...shadow.soft,
  },
  rankingScoreOrbAura: {
    bottom: -44,
    height: 168,
    left: -42,
    opacity: 0.7,
    right: -42,
    top: -42,
  },
  rankingScoreOrbLabel: {
    color: color.text.muted,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    textAlign: 'center',
  },
  rankingScoreOrbValue: {
    color: color.brand.primaryDark,
    fontSize: 27,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 32,
    textAlign: 'center',
  },
  settlementCell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 70,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 8,
    position: 'relative',
    ...shadow.soft,
  },
  settlementLabel: {
    color: color.text.muted,
    flexShrink: 1,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  settlementStrip: {
    flexDirection: 'row',
    gap: 8,
  },
  settlementValue: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
})
