import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  cardTopHighlight: {
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderRadius: radius.pill,
    height: 1,
    left: '10%',
    opacity: 0.86,
    position: 'absolute',
    right: '10%',
    top: 0,
  },
  reliabilityAxisCopy: {
    flex: 1,
    gap: 7,
    marginLeft: 46,
    minWidth: 0,
  },
  reliabilityAxisFill: {
    backgroundColor: color.brand.primary,
    borderRadius: radius.pill,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
  },
  reliabilityAxisIcon: {
    height: 42,
    width: 42,
  },
  reliabilityAxisIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
    ...shadow.soft,
  },
  reliabilityAxisList: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    padding: 12,
    ...shadow.soft,
  },
  reliabilityAxisMeta: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  reliabilityAxisRow: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderColor: 'rgba(217,232,229,0.92)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 0,
    minHeight: 72,
    overflow: 'hidden',
    paddingRight: 12,
  },
  reliabilityAxisScore: {
    alignSelf: 'center',
    color: color.brand.primaryDark,
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginLeft: 12,
    textAlign: 'right',
    width: 58,
  },
  reliabilityAxisTitle: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  reliabilityAxisTrack: {
    backgroundColor: '#D9EBE8',
    borderRadius: radius.pill,
    height: 7,
    overflow: 'hidden',
  },
  reliabilityStatLabel: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  reliabilityStatsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  reliabilityStatTile: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 7,
    justifyContent: 'center',
    minHeight: 76,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 15,
    paddingVertical: 13,
    position: 'relative',
    ...shadow.soft,
  },
  reliabilityStatValue: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 25,
  },
})
