import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  approvalDecisionCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  approvalDecisionIcon: {
    height: 42,
    width: 42,
  },
  approvalDecisionIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  approvalDecisionList: {
    backgroundColor: 'rgba(255,255,255,0.77)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    ...shadow.soft,
  },
  approvalDecisionMeta: {
    color: color.text.muted,
    ...typography.caption2,
  },
  approvalDecisionRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 72,
    padding: 12,
    position: 'relative',
  },
  approvalDecisionStatus: {
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    maxWidth: 92,
    minWidth: 54,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: 'center',
    ...typography.caption2,
  },
  approvalDecisionTitle: {
    color: color.text.strong,
    ...typography.caption1,
  },
  completionLens: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 34,
    borderWidth: 1,
    flexShrink: 0,
    height: 74,
    justifyContent: 'center',
    position: 'relative',
    width: 74,
    zIndex: 1,
    ...shadow.primary,
  },
  completionLensLabel: {
    color: color.text.muted,
    ...typography.caption2,
  },
  completionLensValue: {
    color: color.brand.primaryDark,
    fontVariant: ['tabular-nums'],
    ...typography.title1,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontVariant: ['tabular-nums'],
    marginTop: 8,
    ...typography.title1,
  },
  earningsHeroAura: {
    bottom: 'auto',
    height: 190,
    left: '34%',
    right: -70,
    top: -74,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 148,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    marginTop: 3,
    ...typography.caption1,
  },
  earningsHeroPill: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    textTransform: 'uppercase',
    ...typography.caption2,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
})
