import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: -0.5,
    lineHeight: 33,
    marginTop: 7,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 136,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  earningsHeroIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 25,
    borderWidth: 1,
    height: 70,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 70,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    position: 'relative',
    zIndex: 1,
  },
  serviceCardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    position: 'relative',
    zIndex: 1,
  },
  serviceSourceCard: {
    backgroundColor: 'rgba(255,255,255,0.80)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 23,
    borderWidth: 1,
    minHeight: 128,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 12,
    position: 'relative',
    width: '31.8%',
    ...shadow.soft,
  },
  serviceSourceCardSelected: {
    backgroundColor: 'rgba(232,255,249,0.88)',
    borderColor: 'rgba(13,179,159,0.48)',
    shadowColor: '#079B8A',
    shadowOffset: { height: 13, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
  },
  serviceSourceCardFull: {
    width: '100%',
  },
  serviceSourceCardHalf: {
    width: '48.7%',
  },
  serviceSourceCopy: {
    gap: 4,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  serviceSourceIcon: {
    height: 42,
    width: 42,
  },
  serviceSourceIconTile: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    marginBottom: 10,
    overflow: 'hidden',
    position: 'relative',
    width: 64,
    zIndex: 1,
  },
  serviceSourceMeta: {
    color: color.text.muted,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    textAlign: 'center',
  },
  serviceSourceTitle: {
    color: color.text.strong,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
    textAlign: 'center',
  },
  skillsServiceHeroAmount: {
    fontSize: 24,
    lineHeight: 29,
    marginTop: 0,
  },
})
