import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontVariant: ['tabular-nums'],
    marginTop: 7,
    ...typography.title1,
  },
  earningsHeroCard: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 136,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  earningsHeroIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 25,
    borderWidth: 1,
    height: 70,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 70,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    position: 'relative',
    zIndex: 1,
    ...typography.caption1,
  },
  serviceCardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    position: 'relative',
    zIndex: 1,
  },
  serviceCardShell: {
    borderRadius: 24,
  },
  serviceFormCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  serviceFormHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  serviceFormIntroIcon: {
    alignItems: 'center',
    borderRadius: 12,
    flexShrink: 0,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  serviceFormIntroCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  serviceFormIntroTitle: {
    ...typography.callout,
    fontWeight: '700',
  },
  serviceFormIntroBody: {
    ...typography.footnote,
  },
  serviceSummary: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 62,
    paddingHorizontal: 14,
  },
  serviceSummaryCopy: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  serviceSummaryLabel: {
    ...typography.caption1,
  },
  serviceSummaryValue: {
    ...typography.body,
    fontWeight: '600',
  },
  serviceSummaryStatus: {
    alignItems: 'center',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  serviceSummaryStatusDot: {
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  serviceSummaryStatusText: {
    ...typography.caption2,
    fontWeight: '700',
  },
  serviceList: {
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
  },
  serviceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 76,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  serviceRowPressed: {
    opacity: 0.76,
  },
  serviceIcon: {
    alignItems: 'center',
    borderRadius: 12,
    flexShrink: 0,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  serviceCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  serviceTitle: {
    ...typography.body,
    fontWeight: '600',
  },
  serviceDetailRail: {
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  serviceDetail: {
    ...typography.caption1,
  },
  serviceState: {
    alignItems: 'flex-end',
    flexShrink: 0,
    gap: 6,
    minWidth: 76,
  },
  serviceStatus: {
    ...typography.caption2,
    fontWeight: '600',
  },
  selectionMark: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  serviceDivider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: 64,
  },
  serviceEmpty: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 92,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  serviceEmptyIcon: {
    alignItems: 'center',
    borderRadius: 12,
    flexShrink: 0,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  serviceEmptyCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  serviceEmptyTitle: {
    ...typography.body,
    fontWeight: '600',
  },
  serviceEmptyMeta: {
    ...typography.caption1,
  },
  serviceFormHelper: {
    ...typography.caption1,
    paddingHorizontal: 2,
  },
  serviceSourceCard: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 23,
    borderWidth: 1,
    minHeight: 128,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 12,
    position: 'relative',
    width: '31.8%',
    ...shadow.soft,
  },
  serviceSourceCardSelected: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(70,194,174,0.58)',
    shadowColor: '#79D8C8',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
  },
  serviceSourceCardInactive: {
    backgroundColor: 'rgba(245,250,249,0.9)',
    borderColor: 'rgba(196,214,211,0.78)',
    opacity: 0.68,
  },
  serviceSourceCardQualityLocked: {
    backgroundColor: 'rgba(255,248,241,0.96)',
    borderColor: 'rgba(220,166,112,0.58)',
  },
  serviceSourceCardPressed: {
    opacity: 0.82,
  },
  serviceSourceCardFull: {
    width: '100%',
  },
  serviceSourceCardHalf: {
    width: '48.7%',
  },
  serviceSourceCopy: {
    gap: 4,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  serviceSourceIcon: {
    height: 42,
    width: 42,
  },
  serviceSourceIconTile: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    marginBottom: 10,
    overflow: 'hidden',
    position: 'relative',
    width: 64,
    zIndex: 1,
  },
  serviceSourceIntegratedIcon: {
    marginBottom: 10,
  },
  serviceSourceIntegratedIconPlain: {
    backgroundColor: 'transparent',
  },
  serviceSourceMeta: {
    color: color.text.muted,
    textAlign: 'center',
    ...typography.caption2,
  },
  serviceSourceTitle: {
    color: color.text.strong,
    textAlign: 'center',
    ...typography.caption2,
  },
  serviceQualityNotice: {
    color: '#8A552D',
    marginTop: 4,
    textAlign: 'center',
    ...typography.caption2,
  },
  servicePreferenceControls: {
    gap: 8,
    marginTop: 3,
    width: '100%',
  },
  servicePreferenceHelper: {
    color: color.text.secondary,
    paddingHorizontal: 4,
    ...typography.caption1,
  },
  servicePreferenceMessage: {
    color: color.text.secondary,
    paddingHorizontal: 4,
    ...typography.caption1,
  },
  servicePreferenceSave: {
    minHeight: 52,
  },
  skillsServiceHeroAmount: {
    marginTop: 0,
    ...typography.title1,
  },
  skillsServiceHeroContent: {
    padding: 16,
  },
  skillsServiceHeroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  skillsServiceHeroCopy: {
    gap: 6,
    justifyContent: 'center',
  },
})
