import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 27,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 32,
    marginTop: 8,
  },
  earningsHeroAura: {
    bottom: 'auto',
    height: 190,
    left: '34%',
    right: -70,
    top: -74,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 148,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  earningsHeroIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 3,
  },
  earningsHeroPill: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
  profileRouteIconVisualBoost: {
    height: 52,
    width: 52,
  },
  verificationDocumentCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  verificationDocumentIcon: {
    height: 42,
    width: 42,
  },
  verificationDocumentIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 17,
    borderWidth: 1,
    flexShrink: 0,
    height: 50,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 50,
    zIndex: 1,
  },
  verificationDocumentList: {
    backgroundColor: 'rgba(255,255,255,0.80)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  verificationDocumentListAura: {
    bottom: -64,
    height: 226,
    left: -58,
    opacity: 0.58,
    right: -50,
    top: -62,
  },
  verificationDocumentListZipAura: {
    height: 170,
    opacity: 0.42,
    right: -74,
    top: -50,
    width: 238,
  },
  verificationDocumentMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  verificationDocumentRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(205,226,222,0.78)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 78,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'relative',
    zIndex: 1,
  },
  verificationDocumentRowLast: {
    borderBottomWidth: 0,
  },
  verificationDocumentStatus: {
    alignItems: 'center',
    backgroundColor: 'rgba(245,255,252,0.92)',
    borderColor: 'rgba(154,226,214,0.86)',
    borderRadius: radius.pill,
    borderWidth: 1,
    flexShrink: 0,
    justifyContent: 'center',
    minHeight: 30,
    minWidth: 48,
    paddingHorizontal: 10,
    zIndex: 1,
  },
  verificationDocumentStatusDone: {
    backgroundColor: 'rgba(221,255,247,0.92)',
  },
  verificationDocumentStatusText: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
  },
  verificationDocumentStatusTextDone: {
    color: color.brand.primaryDark,
  },
  verificationDocumentTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
})
