import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  sectionStack: {
    gap: 14,
  },
  summaryCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 20,
    borderWidth: 1,
    gap: 14,
    padding: 16,
    ...shadow.soft,
  },
  reviewsSummaryCard: {
    gap: 9,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  summaryIconFrame: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 16,
    borderWidth: 1,
    flexShrink: 0,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  summaryCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  summaryEyebrow: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  summaryTitle: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.title2,
    fontWeight: '600',
  },
  summaryMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    ...typography.caption1,
  },
  summaryValue: {
    color: color.brand.primaryDark,
    flexShrink: 0,
    fontVariant: ['tabular-nums'],
    ...typography.title2,
    fontWeight: '600',
  },
  progressTrack: {
    backgroundColor: color.surface.disabled,
    borderRadius: radius.pill,
    height: 7,
    overflow: 'hidden',
    width: '100%',
  },
  progressFill: {
    backgroundColor: color.brand.primary,
    borderRadius: radius.pill,
    height: '100%',
  },
  sectionHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 4,
  },
  sectionHeadingTitle: {
    color: color.text.strong,
    flex: 1,
    ...typography.headline,
  },
  sectionHeadingAction: {
    color: color.brand.primaryDark,
    flexShrink: 1,
    textAlign: 'right',
    ...typography.caption1,
    fontWeight: '600',
  },
  listCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    ...shadow.soft,
  },
  listRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 68,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  listRowTall: {
    alignItems: 'flex-start',
    minHeight: 88,
  },
  rowIconFrame: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 13,
    borderWidth: 1,
    flexShrink: 0,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  rowCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  rowTitle: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.subheadline,
    fontWeight: '600',
  },
  rowMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    ...typography.caption1,
  },
  rowStatus: {
    color: color.brand.primaryDark,
    flexShrink: 0,
    maxWidth: 82,
    textAlign: 'right',
    ...typography.caption1,
    fontWeight: '600',
  },
  rowStatusMuted: {
    color: color.text.muted,
    fontWeight: '400',
  },
  divider: {
    backgroundColor: color.surface.stroke,
    height: StyleSheet.hairlineWidth,
    marginLeft: 63,
  },
  compactMetricList: {
    flexDirection: 'row',
  },
  compactMetric: {
    alignItems: 'center',
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 76,
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  compactMetricBorder: {
    borderLeftColor: color.surface.stroke,
    borderLeftWidth: StyleSheet.hairlineWidth,
  },
  compactMetricValue: {
    color: color.text.strong,
    flexShrink: 1,
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
    ...typography.headline,
  },
  compactMetricLabel: {
    color: color.text.secondary,
    flexShrink: 1,
    textAlign: 'center',
    ...typography.caption1,
  },
  inlineDetail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 1,
  },
  inlineDetailText: {
    color: color.text.muted,
    ...typography.caption2,
  },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 22,
    borderWidth: 1,
    gap: 6,
    paddingHorizontal: 22,
    paddingVertical: 22,
    ...shadow.soft,
  },
  emptyTitle: {
    color: color.text.strong,
    ...typography.headline,
  },
  emptyBody: {
    color: color.text.secondary,
    textAlign: 'center',
    ...typography.footnote,
  },
  noteCard: {
    backgroundColor: color.surface.soft,
    borderColor: color.surface.stroke,
    borderRadius: 18,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  noteTitle: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
  },
  noteBody: {
    color: color.text.secondary,
    ...typography.caption1,
  },
  rowProgress: {
    marginTop: 5,
  },
  rowDetail: {
    marginTop: 5,
    width: '100%',
  },
})
