import { StyleSheet } from 'react-native'

import { radius, spacing, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  capabilityIdentity: { flexShrink: 0, gap: spacing.xs },
  capabilityPurpose: { ...typography.footnote, flex: 1 },
  capabilityRow: {
    alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderLeftWidth: 2, flexDirection: 'row', gap: spacing.lg,
    minHeight: 80, outlineStyle: 'solid', outlineWidth: 0, paddingHorizontal: spacing.lg, paddingVertical: spacing.md,
  },
  capabilityRowCompact: { alignItems: 'stretch', flexDirection: 'column', gap: spacing.sm, minHeight: 104 },
  capabilityTitle: { fontWeight: '600' },
  closeButton: { minWidth: 100 },
  columnHeader: {
    alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.lg,
    minHeight: 40, paddingHorizontal: spacing.lg,
  },
  columnLabel: { ...typography.caption1, fontWeight: '600', textTransform: 'uppercase' },
  descriptionColumn: { flex: 1 },
  detailContent: { gap: spacing.lg, paddingBottom: spacing.xl, paddingHorizontal: spacing.xl, paddingTop: spacing.lg },
  detailContentCompact: { paddingHorizontal: spacing.md },
  detailContextRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  detailEyebrow: { ...typography.caption1, fontWeight: '600', textTransform: 'uppercase' },
  detailFooter: {
    alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', justifyContent: 'flex-end',
    paddingHorizontal: spacing.xl, paddingVertical: spacing.md,
  },
  detailFooterCompact: { paddingHorizontal: spacing.md },
  detailHeader: {
    borderBottomWidth: StyleSheet.hairlineWidth, gap: spacing.sm, paddingBottom: spacing.md,
    paddingHorizontal: spacing.xl, paddingTop: spacing.sm,
  },
  detailHeaderCompact: { paddingHorizontal: spacing.md },
  detailOwnedScroll: { flex: 1, minHeight: 0 },
  detailScroll: { flex: 1, outlineColor: 'transparent', outlineStyle: 'solid', outlineWidth: 0 },
  detailSheet: {
    borderRadius: radius.xl, borderWidth: 1, height: '92%', maxWidth: 920, overflow: 'hidden',
    paddingTop: spacing.sm, width: '100%',
  },
  detailStatus: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  detailStatusText: { ...typography.footnote, fontWeight: '600' },
  detailTitle: { ...typography.title2, fontWeight: '700' },
  disclosureSlot: { alignItems: 'flex-end', justifyContent: 'center', width: 16 },
  emptyState: { borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: spacing.lg, paddingVertical: spacing.xl },
  emptyText: {},
  guidanceLabel: { ...typography.caption1, fontWeight: '700', textTransform: 'uppercase' },
  guidanceText: { ...typography.footnote, flex: 1 },
  modalOverlay: {
    alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.48)', flex: 1, justifyContent: 'flex-end', padding: spacing.lg,
  },
  modalOverlayCompact: { padding: spacing.md },
  ownerLabel: { ...typography.caption1, fontWeight: '600' },
  ownerLabelCompact: { marginRight: 'auto' },
  refreshingBar: {
    alignItems: 'center', borderLeftWidth: 3, flexDirection: 'row', gap: spacing.sm, minHeight: 40, paddingHorizontal: spacing.md,
  },
  refreshingDot: { borderRadius: radius.pill, height: 8, width: 8 },
  refreshingText: { ...typography.footnote, flex: 1 },
  searchField: { flexShrink: 1, maxWidth: 288, minWidth: 240, width: 288 },
  searchFieldCompact: { maxWidth: '100%', minWidth: 0, width: '100%' },
  searchInput: { ...typography.callout, flex: 1, minHeight: 46, paddingHorizontal: 0, paddingVertical: 0 },
  searchInputShell: { borderRadius: radius.pill, borderWidth: 1, minHeight: 48, paddingHorizontal: spacing.md },
  sectionGuidance: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 24 },
  sectionHeader: { gap: spacing.sm, paddingBottom: spacing.md },
  sectionHeaderMain: { alignItems: 'center', flexDirection: 'row', gap: spacing.lg, justifyContent: 'space-between' },
  sectionHeaderMainCompact: { alignItems: 'stretch', flexDirection: 'column' },
  sectionTitle: { ...typography.title1, flex: 1, fontWeight: '700' },
  sectionTitleCompact: { flexGrow: 0, flexShrink: 0 },
  sheetHandle: { alignSelf: 'center', borderRadius: radius.pill, height: 4, width: 42 },
  statusCell: { alignItems: 'flex-end', flexShrink: 0, width: 120 },
  statusCellCompact: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
  statusColumn: { textAlign: 'right', width: 120 },
  statusDot: { borderRadius: radius.pill, height: 9, width: 9 },
  statusMeta: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 24 },
  statusText: { ...typography.caption1, fontWeight: '600', textAlign: 'right', width: 76 },
  unavailableState: { borderRadius: radius.lg, borderWidth: 1, padding: spacing.lg },
  unavailableText: {},
  workstream: { width: '100%' },
  workstreamHeader: {
    borderBottomWidth: StyleSheet.hairlineWidth, paddingBottom: spacing.sm,
    paddingHorizontal: spacing.lg, paddingTop: spacing.md,
  },
  workstreamList: { gap: spacing.xl },
  workstreamTitle: { fontWeight: '600' },
})
