import { StyleSheet } from 'react-native'
import { color, component, radius, shadow, spacing, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  safeArea: { backgroundColor: color.surface.base, flex: 1 },
  stack: { gap: spacing.lg },
  scrollContent: { paddingBottom: spacing.xxxl },
  page: { alignSelf: 'stretch', maxWidth: 1040, paddingHorizontal: spacing.screenHorizontalPadding, paddingTop: spacing.lg },
  hero: { backgroundColor: color.surface.mint, borderColor: color.surface.strokeStrong, borderRadius: component.card.largeRadius, borderWidth: 1, marginBottom: spacing.lg, padding: spacing.lg, ...shadow.soft },
  heroTopRow: { alignItems: 'flex-start', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, justifyContent: 'space-between' },
  heroSignOutButton: { flexShrink: 0, minWidth: 108 },
  heroTitle: { ...typography.title2, color: color.text.strong, flex: 1, fontWeight: '600', includeFontPadding: false, minWidth: 190 },
  heroBody: { ...typography.callout, color: color.text.secondary, includeFontPadding: false, marginTop: spacing.sm, maxWidth: 700 },
  summarySurface: { alignItems: 'center', backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-around', marginBottom: spacing.lg, padding: spacing.lg, ...shadow.soft },
  summaryItem: { alignItems: 'center', flex: 1, gap: spacing.xs },
  summaryValue: { ...typography.title2, color: color.text.strong, fontVariant: ['tabular-nums'], fontWeight: '600', includeFontPadding: false },
  summaryLabel: { ...typography.caption1, color: color.text.secondary, fontWeight: '600', textAlign: 'center' },
  summaryDivider: { backgroundColor: color.surface.stroke, height: 34, width: 1 },
  toolbar: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.lg },
  searchField: { flexBasis: 240, flexGrow: 1, flexShrink: 1, minWidth: 220 },
  searchInput: { backgroundColor: component.input.bg, borderColor: component.input.border, borderRadius: component.input.radius, borderWidth: 1, minHeight: component.input.height },
  searchText: { ...typography.body, color: color.text.primary, minHeight: component.input.height - 2, paddingHorizontal: 0 },
  refreshButton: { flexShrink: 0, paddingHorizontal: spacing.lg },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.lg },
  notice: { backgroundColor: component.chip.successStatus.bg, borderColor: component.chip.successStatus.border, borderRadius: radius.sm, borderWidth: 1, marginBottom: spacing.lg, padding: spacing.md },
  noticeText: { ...typography.footnote, color: component.chip.successStatus.text },
  error: { alignItems: 'center', backgroundColor: color.surface.mint, borderColor: color.surface.strokeStrong, borderRadius: radius.sm, borderWidth: 1, flexDirection: 'row', gap: spacing.md, marginBottom: spacing.lg, padding: spacing.md },
  errorText: { ...typography.footnote, color: color.brand.primaryDark, flex: 1 },
  errorAction: { ...typography.label, color: color.brand.primaryDark, fontWeight: '600' },
  loading: { alignItems: 'center', gap: spacing.md, paddingVertical: spacing.xxxl },
  loadingText: { ...typography.label, color: color.text.secondary },
  refreshingText: { ...typography.caption1, color: color.text.secondary, textAlign: 'right' },
  detailLoading: { alignItems: 'center', padding: spacing.lg },
  empty: { alignItems: 'center', backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, padding: spacing.xxxl },
  emptyText: { ...typography.body, color: color.text.secondary, textAlign: 'center' },
  card: { backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, marginBottom: spacing.lg, padding: spacing.lg },
  cardPressArea: { gap: spacing.md },
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  cardTitleBlock: { flex: 1, gap: spacing.xs },
  cardTitle: { ...typography.headline, color: color.text.strong, fontWeight: '600', includeFontPadding: false },
  cardSubtitle: { ...typography.footnote, color: color.text.secondary },
  statusPill: { alignSelf: 'flex-start', backgroundColor: color.surface.disabled, borderColor: color.surface.stroke, borderRadius: component.chip.radius, borderWidth: 1, flexShrink: 1, maxWidth: '48%', paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  statusWarning: { backgroundColor: component.chip.warning.bg, borderColor: component.chip.warning.border },
  statusSuccess: { backgroundColor: component.chip.successStatus.bg, borderColor: component.chip.successStatus.border },
  statusDanger: { backgroundColor: component.chip.error.bg, borderColor: component.chip.error.border },
  statusPillText: { ...typography.caption2, color: color.text.strong, fontWeight: '600' },
  metaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  metaItem: { flexBasis: '45%', flexGrow: 1, gap: spacing.xs, minWidth: 120 },
  metaLabel: { ...typography.caption2, color: color.text.muted, fontWeight: '600', textTransform: 'uppercase' },
  metaValue: { ...typography.footnote, color: color.text.primary },
  cardHint: { ...typography.footnote, color: color.text.secondary },
  actionRow: { alignItems: 'center', borderTopColor: color.surface.stroke, borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.lg, paddingTop: spacing.md },
  actionButton: { flexGrow: 1 },
  modalButton: { width: '100%' },
  modalActionButton: { flex: 1 },
  transactionCard: { padding: spacing.lg },
  transactionAuraClip: { ...StyleSheet.absoluteFill, borderRadius: component.card.radius, overflow: 'hidden' },
  transactionContent: { position: 'relative', zIndex: 1 },
  transactionHeader: { alignItems: 'flex-start', borderBottomColor: color.surface.stroke, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between', paddingBottom: spacing.md },
  transactionSummary: { alignItems: 'flex-start', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginVertical: spacing.md },
  transactionSummaryItem: { flexBasis: 120, flexGrow: 1, gap: spacing.xs, minWidth: 120 },
  transactionSummaryLabel: { ...typography.caption2, color: color.text.muted, fontWeight: '600' },
  transactionAmount: { ...typography.headline, color: color.text.strong, fontVariant: ['tabular-nums'], fontWeight: '600', includeFontPadding: false },
  transactionStatus: { ...typography.headline, color: color.text.strong, fontWeight: '600', includeFontPadding: false },
  transactionMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  transactionMetaItem: { flexBasis: '45%', flexGrow: 1, gap: spacing.xs, minWidth: 120 },
  transactionMetaLabel: { ...typography.caption2, color: color.text.muted, fontWeight: '600' },
  transactionMetaValue: { ...typography.footnote, color: color.text.primary },
  modalBackdrop: { alignItems: 'center', backgroundColor: 'rgba(7,26,36,0.58)', flex: 1, justifyContent: 'center', padding: spacing.lg },
  modalCard: { backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.largeRadius, borderWidth: 1, maxHeight: '90%', maxWidth: 620, padding: spacing.xl, width: '100%', ...shadow.raised },
  transactionModal: { maxWidth: 720, overflow: 'hidden' },
  transactionModalAuraClip: { ...StyleSheet.absoluteFill, borderRadius: component.card.largeRadius, overflow: 'hidden' },
  transactionModalContent: { flex: 1, minHeight: 0, position: 'relative', zIndex: 1 },
  transactionModalScroll: { flex: 1, minHeight: 0 },
  modalHeader: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md },
  modalTitle: { ...typography.title2, color: color.text.strong, flex: 1, fontWeight: '600', includeFontPadding: false },
  modalSubtitle: { ...typography.footnote, color: color.text.secondary, marginBottom: spacing.lg },
  closeLabel: { ...typography.title1, color: color.text.secondary, fontWeight: '400', paddingLeft: spacing.md },
  modalHint: { ...typography.footnote, color: color.text.secondary, marginTop: spacing.lg },
  modalActionStack: { gap: spacing.sm, marginTop: spacing.xl },
  reasonInput: { backgroundColor: color.surface.soft, borderColor: component.input.border, borderRadius: component.input.radius, borderWidth: 1, minHeight: 112 },
  reasonText: { ...typography.body, color: color.text.primary, minHeight: 108, padding: spacing.md, textAlignVertical: 'top' },
  modalActionRow: { flexDirection: 'row', gap: spacing.sm, justifyContent: 'flex-end', marginTop: spacing.lg },
  modalScrollContent: { gap: spacing.lg, paddingBottom: spacing.sm },
  modalBodyScroll: { marginHorizontal: -spacing.sm },
  reviewSection: { backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, gap: spacing.md, padding: spacing.lg },
  reviewSectionTitle: { ...typography.headline, color: color.text.strong, fontWeight: '600' },
  reviewSummary: { backgroundColor: color.surface.soft, borderRadius: component.card.radius, gap: spacing.sm, padding: spacing.md },
  reviewSummaryText: { ...typography.footnote, color: color.text.secondary },
  documentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  documentCard: { flexBasis: 150, flexGrow: 1, gap: spacing.sm, minWidth: 140 },
  documentImage: { aspectRatio: 1.55, backgroundColor: color.surface.soft, borderRadius: radius.md, width: '100%' },
  documentLabel: { ...typography.caption1, color: color.text.primary, fontWeight: '600' },
  historyRow: { borderBottomColor: color.surface.stroke, borderBottomWidth: StyleSheet.hairlineWidth, gap: spacing.xs, paddingVertical: spacing.sm },
  historyDecision: { ...typography.label, color: color.text.strong, fontWeight: '600' },
  historyReason: { ...typography.footnote, color: color.text.secondary },
  inlineActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  inlineAction: { flexGrow: 1 },
  teamActionSurface: { backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, gap: spacing.md, padding: spacing.lg, ...shadow.soft },
  formSection: { backgroundColor: color.surface.soft, borderRadius: component.card.radius, gap: spacing.md, padding: spacing.lg },
  formSectionTitle: { ...typography.label, color: color.text.strong, fontWeight: '600' },
  capabilityList: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  pendingAccountList: { gap: spacing.md },
  pendingAccountCard: { backgroundColor: color.surface.soft, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, gap: spacing.md, padding: spacing.md },
  pendingAccountHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  pendingAccountTitle: { ...typography.headline, color: color.text.strong, flex: 1, fontWeight: '600' },
  amountBlock: { alignItems: 'flex-start', backgroundColor: color.mint.mint50, borderRadius: component.card.radius, overflow: 'hidden', padding: spacing.lg, position: 'relative' },
  amountContent: { position: 'relative', zIndex: 1 },
  amountLabel: { ...typography.caption1, color: color.text.secondary, fontWeight: '600', textAlign: 'left' },
  amountValue: { ...typography.title1, color: color.text.strong, fontVariant: ['tabular-nums'], fontWeight: '600', marginTop: spacing.xs, textAlign: 'left' },
  sectionTitle: { ...typography.headline, color: color.text.strong, fontWeight: '600' },
  timeline: { gap: spacing.lg },
  timelineRow: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md },
  timelineDot: { backgroundColor: color.brand.primary, borderRadius: radius.pill, height: 10, marginTop: 5, width: 10 },
  timelineLabel: { ...typography.label, color: color.text.primary, fontWeight: '600' },
  timelineDate: { ...typography.caption1, color: color.text.secondary, marginTop: spacing.xs },
  ledgerBlock: { backgroundColor: color.surface.soft, borderRadius: component.card.radius, gap: spacing.md, padding: spacing.lg },
  activationScrollContent: { flexGrow: 1, justifyContent: 'center', padding: spacing.lg },
  activationCard: { alignSelf: 'center', gap: spacing.lg, maxWidth: 560, width: '100%' },
  activationForm: { gap: spacing.md },
})
