import { StyleSheet } from 'react-native'

import { color, component, radius, spacing, typography } from '@/design/theme'

export const adminPayoutStyles = StyleSheet.create({
  stack: { gap: spacing.md },
  searchInput: { backgroundColor: color.surface.base, borderColor: component.input.border, borderRadius: component.input.radius, borderWidth: 1, minHeight: component.input.height },
  searchText: { ...typography.body, color: color.text.primary, minHeight: component.input.height - 2, paddingHorizontal: spacing.md },
  toolbar: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' },
  filterRow: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  reloadButton: { minHeight: 44 },
  notice: { alignItems: 'center', backgroundColor: component.chip.successStatus.bg, borderColor: component.chip.successStatus.border, borderRadius: radius.sm, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, padding: spacing.md },
  noticeText: { ...typography.footnote, color: component.chip.successStatus.text, flex: 1 },
  noticeClose: { ...typography.title3, color: component.chip.successStatus.text, paddingHorizontal: spacing.xs },
  error: { alignItems: 'center', backgroundColor: color.surface.mint, borderColor: color.surface.strokeStrong, borderRadius: radius.sm, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, padding: spacing.md },
  errorText: { ...typography.footnote, color: color.brand.primaryDark, flex: 1 },
  errorAction: { ...typography.label, color: color.brand.primaryDark, fontWeight: '600' },
  loading: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xxxl },
  loadingText: { ...typography.footnote, color: color.text.secondary },
  detailLoading: { alignItems: 'center', padding: spacing.lg },
  empty: { alignItems: 'center', backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, padding: spacing.xxxl },
  emptyText: { ...typography.body, color: color.text.secondary, textAlign: 'center' },
  card: { backgroundColor: color.surface.base, borderColor: color.surface.stroke, borderRadius: component.card.radius, borderWidth: 1, overflow: 'hidden', padding: spacing.lg, position: 'relative' },
  cardContent: { gap: spacing.md, position: 'relative', zIndex: 1 },
  cardHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  cardTitleBlock: { flex: 1, gap: spacing.xs },
  cardTitle: { ...typography.headline, color: color.text.strong, fontWeight: '600', includeFontPadding: false },
  cardSubtitle: { ...typography.footnote, color: color.text.secondary },
  statusPill: { backgroundColor: color.surface.disabled, borderColor: color.surface.stroke, borderRadius: component.chip.radius, borderWidth: 1, flexShrink: 1, maxWidth: '46%', paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  statusWarning: { backgroundColor: component.chip.warning.bg, borderColor: component.chip.warning.border },
  statusSuccess: { backgroundColor: component.chip.successStatus.bg, borderColor: component.chip.successStatus.border },
  statusDanger: { backgroundColor: component.chip.error.bg, borderColor: component.chip.error.border },
  statusPillText: { ...typography.caption2, color: color.text.strong, fontWeight: '600' },
  withdrawalNumbers: { borderTopColor: color.surface.stroke, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.md, paddingTop: spacing.md },
  amountItem: { flex: 1, gap: spacing.xs, minWidth: 132 },
  amountItemLabel: { ...typography.caption2, color: color.text.muted, fontWeight: '600' },
  amountItemValue: { ...typography.label, color: color.text.strong, fontVariant: ['tabular-nums'], fontWeight: '600' },
  cardFooter: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  cardMeta: { ...typography.caption2, color: color.text.secondary, flex: 1 },
  cardAction: { ...typography.caption1, color: color.brand.primaryDark, fontWeight: '600' },
})
