import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  boundaryBody: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
    position: 'relative',
    zIndex: 1,
  },
  boundaryNote: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 4,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    ...shadow.soft,
  },
  boundaryTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    position: 'relative',
    zIndex: 1,
  },
  checkInChecklistAura: {
    bottom: -88,
    height: 282,
    left: -76,
    opacity: 0.96,
    right: -58,
    top: -78,
  },
  checkInChecklistZipAura: {
    height: 246,
    opacity: 0.78,
    right: -96,
    top: -82,
    width: 326,
  },
  successBody: {
    color: color.text.secondary,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    textAlign: 'center',
  },
  successCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.42)',
    borderColor: 'rgba(255,255,255,0.64)',
    borderRadius: 32,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    paddingHorizontal: 22,
    paddingVertical: 26,
    position: 'relative',
  },
  successCheck: {
    alignItems: 'center',
    backgroundColor: '#08AF9C',
    borderColor: 'rgba(255,255,255,0.82)',
    borderRadius: 29,
    borderWidth: 2,
    height: 58,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 58,
    zIndex: 1,
    boxShadow: '0 8px 16px rgba(8,125,114,0.24)',
  },
  successCheckText: {
    color: color.text.inverse,
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 36,
    position: 'relative',
    zIndex: 1,
  },
  successEmblem: {
    alignItems: 'center',
    backgroundColor: 'rgba(203,248,238,0.42)',
    borderColor: 'rgba(255,255,255,0.86)',
    borderRadius: 46,
    borderWidth: 1,
    height: 92,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 92,
    boxShadow: '0 16px 30px rgba(8,125,114,0.14)',
  },
  successStatusPill: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: 'rgba(77,211,192,0.48)',
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    maxWidth: '86%',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  successStatusDivider: {
    backgroundColor: 'rgba(77,211,192,0.34)',
    height: 20,
    width: 1,
  },
  successStatusDots: {
    flexDirection: 'row',
    gap: 5,
  },
  successStatusText: {
    color: color.brand.primaryDark,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  successTitle: {
    color: color.text.strong,
    fontSize: 23,
    fontWeight: '700',
    lineHeight: 29,
    marginTop: 2,
    textAlign: 'center',
  },
  statusDotSmall: {
    backgroundColor: color.brand.primary,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  statusDotMid: {
    opacity: 0.72,
  },
  statusDotSoft: {
    opacity: 0.4,
  },
  timerCaption: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  timerCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(186,240,230,0.78)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minHeight: 100,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
    shadowColor: '#087D72',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 38,
  },
  timerLabel: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  timerRing: {
    alignItems: 'center',
    flexShrink: 0,
    height: 70,
    justifyContent: 'center',
    position: 'relative',
    width: 70,
    zIndex: 1,
  },
  timerRingLens: {
    alignItems: 'center',
    backgroundColor: '#FAFFFD',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 28,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    position: 'absolute',
    width: 52,
  },
  timerRingValue: {
    color: color.brand.primaryDark,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  timerTextColumn: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  timerValue: {
    color: color.text.strong,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 29,
  },
})
