import { StyleSheet } from 'react-native'
import { createSurfaceShadow } from '@/components/ui/tokens'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  boundaryBody: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
    position: 'relative',
    zIndex: 1,
  },
  boundaryNote: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 4,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    ...shadow.soft,
  },
  boundaryTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    position: 'relative',
    zIndex: 1,
  },
  checkInChecklistAura: {
    bottom: -88,
    height: 282,
    left: -76,
    opacity: 0.96,
    right: -58,
    top: -78,
  },
  checkInChecklistZipAura: {
    height: 246,
    opacity: 0.78,
    right: -96,
    top: -82,
    width: 326,
  },
  successBody: {
    color: color.text.secondary,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    textAlign: 'center',
  },
  successCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.42)',
    borderColor: 'rgba(255,255,255,0.64)',
    borderRadius: 32,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    paddingHorizontal: 22,
    paddingVertical: 22,
    position: 'relative',
  },
  completionStateIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderColor: 'rgba(255,255,255,0.84)',
    borderRadius: 34,
    borderWidth: 1,
    height: 68,
    justifyContent: 'center',
    position: 'relative',
    width: 68,
    boxShadow: '0 12px 24px rgba(8,125,114,0.14)',
  },
  completionStateIconLarge: {
    borderRadius: 38,
    height: 76,
    marginTop: 8,
    width: 76,
  },
  completionStateIconRim: {
    alignItems: 'center',
    backgroundColor: 'rgba(210,249,241,0.64)',
    borderColor: 'rgba(255,255,255,0.78)',
    borderRadius: 29,
    borderWidth: 1,
    height: 58,
    justifyContent: 'center',
    width: 58,
    boxShadow: '0 7px 16px rgba(0,117,106,0.18)',
  },
  completionStateIconRimLarge: {
    borderRadius: 33,
    height: 66,
    width: 66,
  },
  completionStateIconRimOpaque: {
    backgroundColor: '#E2F7F2',
    borderColor: '#FFFFFF',
  },
  completionStateIconEmpty: {
    backgroundColor: 'rgba(244,249,248,0.82)',
    borderColor: 'rgba(167,199,193,0.48)',
  },
  completionStateIconSubmitted: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: 'rgba(255,255,255,0.92)',
    boxShadow: '0 14px 28px rgba(0,101,92,0.16)',
  },
  completionStateIconSubmittedOpaque: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCEDE9',
  },
  successStatusPill: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: radius.pill,
    borderWidth: 1,
    maxWidth: '90%',
    minHeight: 42,
    padding: 3,
    boxShadow: '0 10px 22px rgba(0,101,92,0.12)',
  },
  successStatusPillOpaque: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCEDE9',
  },
  successStatusMark: {
    alignItems: 'center',
    borderRadius: 9,
    height: 18,
    justifyContent: 'center',
    width: 18,
    boxShadow: '0 4px 8px rgba(0,117,106,0.18)',
  },
  successStatusPillInner: {
    alignItems: 'center',
    backgroundColor: 'rgba(226,249,244,0.78)',
    borderColor: 'rgba(255,255,255,0.72)',
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  successStatusPillInnerOpaque: {
    backgroundColor: '#E8F8F4',
    borderColor: '#FFFFFF',
  },
  successStatusText: {
    color: color.brand.primaryDark,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  successTitle: {
    color: color.text.strong,
    fontSize: 23,
    fontWeight: '700',
    lineHeight: 29,
    marginTop: 2,
    textAlign: 'center',
  },
  timerCaption: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  timerCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(186,240,230,0.78)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minHeight: 100,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
    boxShadow: createSurfaceShadow({ color: '#087D72', offsetY: 18, opacity: 0.16, radius: 38 }),
  },
  timerLabel: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    textTransform: 'uppercase',
  },
  timerRing: {
    alignItems: 'center',
    flexShrink: 0,
    height: 70,
    justifyContent: 'center',
    position: 'relative',
    width: 70,
    zIndex: 1,
  },
  timerRingLens: {
    alignItems: 'center',
    backgroundColor: '#FAFFFD',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 28,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    position: 'absolute',
    width: 52,
  },
  timerRingValue: {
    color: color.brand.primaryDark,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  timerTextColumn: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  timerValue: {
    color: color.text.strong,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 29,
  },
})
