import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  actionButton: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 44, minWidth: 0, paddingHorizontal: 3 },
  actionMenu: { backgroundColor: 'rgba(252,255,254,0.98)', borderRadius: 12, borderWidth: 1, flexDirection: 'row', minHeight: 44, overflow: 'hidden' },
  actionText: { fontSize: 10.5, fontWeight: '700' },
  check: { fontSize: 16, fontWeight: '700', marginLeft: 4 },
  confirmAction: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 48, paddingHorizontal: 5 },
  confirmCancel: { fontSize: 10, fontWeight: '700' },
  confirmDelete: { color: '#E5484D', fontSize: 10, fontWeight: '700' },
  deleteConfirm: { alignItems: 'center', backgroundColor: 'rgba(255,250,250,0.98)', borderRadius: 12, borderWidth: 1, flexDirection: 'row', minHeight: 52 },
  deleteConfirmCopy: { flex: 1, fontSize: 9.5, fontWeight: '600', lineHeight: 12, paddingHorizontal: 7 },
  linkedCaseDeleteConfirm: { minHeight: 66 },
  disabled: { opacity: 0.48 },
  error: { color: '#D94C51', fontSize: 10.5, fontWeight: '600', lineHeight: 14, paddingHorizontal: 4 },
  feedback: { fontSize: 10.5, fontWeight: '600', lineHeight: 14, paddingHorizontal: 4 },
  menu: { borderRadius: 16, borderWidth: 1, gap: 3, overflow: 'hidden', padding: 5 },
  menuPosition: { maxWidth: 208, position: 'absolute', right: 10, top: 74, width: '59%', zIndex: 42 },
  moreButton: { alignItems: 'center', alignSelf: 'stretch', borderRadius: 13, justifyContent: 'center', minWidth: 36 },
  moreButtonOpen: { backgroundColor: 'rgba(217,246,240,0.78)' },
  newSession: { alignItems: 'center', backgroundColor: 'rgba(229,250,245,0.92)', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 6, justifyContent: 'center', minHeight: 44, paddingHorizontal: 8 },
  newSessionText: { fontSize: 13, fontWeight: '700' },
  renameActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end' },
  renameEditor: { backgroundColor: 'rgba(246,253,251,0.98)', borderRadius: 15, borderWidth: 1, gap: 5, padding: 8 },
  renameInput: { fontSize: 12, minHeight: 38, paddingHorizontal: 10, paddingVertical: 7 },
  renameInputShell: { borderRadius: 12, minHeight: 40 },
  renamePrimary: { alignItems: 'center', borderRadius: 999, justifyContent: 'center', minHeight: 44, minWidth: 70, paddingHorizontal: 13 },
  renamePrimaryText: { color: '#FFFFFF', fontSize: 11.5, fontWeight: '700' },
  renameSecondary: { alignItems: 'center', borderRadius: 999, justifyContent: 'center', minHeight: 44, minWidth: 64, paddingHorizontal: 10 },
  renameSecondaryText: { fontSize: 11.5, fontWeight: '700' },
  session: { alignItems: 'center', backgroundColor: 'rgba(247,252,251,0.94)', borderRadius: 13, borderWidth: 1, flexDirection: 'row', minHeight: 44 },
  sessionCopy: { flex: 1, minWidth: 0 },
  sessionGroup: { gap: 3 },
  sessionList: { gap: 3 },
  sessionListViewport: { marginTop: 6, maxHeight: 138 },
  sessionMain: { alignItems: 'center', flex: 1, flexDirection: 'row', minHeight: 44, paddingLeft: 8, paddingRight: 2 },
  sessionMeta: { fontSize: 9.5, fontWeight: '500', lineHeight: 12 },
  sessionSelected: { backgroundColor: 'rgba(231,252,247,0.98)' },
  sessionTitle: { flexShrink: 1, fontSize: 10.5, fontWeight: '700', lineHeight: 14 },
  sessionTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 3, minWidth: 0 },
  statusDot: { backgroundColor: 'rgba(143,174,169,0.68)', borderRadius: 4, height: 6, marginRight: 7, width: 6 },
})
