import { StyleSheet } from 'react-native'

import { typography } from '@/design/theme'

export const styles = StyleSheet.create({
  actionButton: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 44, minWidth: 0, paddingHorizontal: 3 },
  actionMenu: { backgroundColor: 'rgba(252,255,254,0.98)', borderRadius: 12, borderWidth: 1, flexDirection: 'row', minHeight: 44, overflow: 'hidden' },
  actionText: { ...typography.caption2, fontWeight: '600' },
  check: { ...typography.callout, fontWeight: '600', marginLeft: 4 },
  confirmAction: { alignItems: 'center', justifyContent: 'center', minHeight: 44, minWidth: 48, paddingHorizontal: 5 },
  confirmCancel: { ...typography.caption2, fontWeight: '600' },
  confirmDelete: { ...typography.caption2, color: '#E5484D', fontWeight: '600' },
  deleteConfirm: { alignItems: 'center', backgroundColor: 'rgba(255,250,250,0.98)', borderRadius: 12, borderWidth: 1, flexDirection: 'row', minHeight: 52 },
  deleteConfirmCopy: { ...typography.caption2, flex: 1, fontWeight: '600', paddingHorizontal: 7 },
  linkedCaseDeleteConfirm: { minHeight: 66 },
  disabled: { opacity: 0.48 },
  error: { ...typography.caption2, color: '#D94C51', fontWeight: '600', paddingHorizontal: 4 },
  feedback: { ...typography.caption2, fontWeight: '600', paddingHorizontal: 4 },
  menuGlass: { borderRadius: 18, overflow: 'hidden' },
  menuContent: { gap: 3, overflow: 'hidden', padding: 5 },
  menuPosition: { maxWidth: 208, position: 'absolute', right: 10, top: 74, width: '59%', zIndex: 42 },
  menuPositionExpanded: { maxWidth: 440, width: '92%' },
  moreButtonOpen: { backgroundColor: 'rgba(217,246,240,0.78)' },
  newSession: { alignItems: 'center', alignSelf: 'stretch', backgroundColor: 'rgba(255,255,255,0.18)', borderColor: 'rgba(255,255,255,0.72)', borderRadius: 999, borderWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', marginHorizontal: -4, minHeight: 44, paddingHorizontal: 13, position: 'relative' },
  newSessionLiquid: { borderWidth: 0 },
  newSessionText: { ...typography.footnote, fontWeight: '600' },
  renameActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end', width: '100%' },
  renameEditor: { backgroundColor: 'rgba(246,253,251,0.98)', borderRadius: 15, borderWidth: 1, gap: 5, padding: 8, width: '100%' },
  renameInput: { ...typography.subheadline, flex: 1, minHeight: 38, minWidth: 0, paddingHorizontal: 10, paddingVertical: 7, width: '100%' },
  renameInputShell: { borderRadius: 12, minHeight: 40, width: '100%' },
  renamePrimary: { alignItems: 'center', borderRadius: 999, justifyContent: 'center', minHeight: 44, minWidth: 70, paddingHorizontal: 13 },
  renamePrimaryText: { ...typography.caption2, color: '#FFFFFF', fontWeight: '600' },
  renameSecondary: { alignItems: 'center', borderRadius: 999, justifyContent: 'center', minHeight: 44, minWidth: 64, paddingHorizontal: 10 },
  renameSecondaryText: { ...typography.caption2, fontWeight: '600' },
  session: { alignItems: 'center', backgroundColor: 'rgba(250,253,252,0.96)', borderCurve: 'continuous', borderRadius: 16, borderWidth: 1, flexDirection: 'row', minHeight: 44, overflow: 'hidden', position: 'relative' },
  sessionCopy: { flex: 1, gap: 0, minWidth: 0 },
  sessionGroup: { gap: 3 },
  sessionList: { gap: 3 },
  sessionListViewport: { marginTop: 6, maxHeight: 138 },
  sessionListViewportExpanded: { maxHeight: 240 },
  sessionMain: { alignItems: 'center', flex: 1, flexDirection: 'row', minHeight: 44, minWidth: 0, paddingLeft: 8, paddingRight: 8, position: 'relative', zIndex: 0 },
  moreButton: { alignItems: 'center', alignSelf: 'stretch', borderRadius: 13, flexShrink: 0, justifyContent: 'center', minHeight: 44, minWidth: 44, position: 'relative', width: 44, zIndex: 2, elevation: 2 },
  sessionMeta: { ...typography.caption2 },
  sessionTitle: { ...typography.caption2, flexShrink: 1, fontWeight: '600' },
  sessionTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 3, minWidth: 0 },
  statusDot: { backgroundColor: 'rgba(143,174,169,0.68)', borderRadius: 4, height: 6, marginRight: 7, width: 6 },
})
