import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  attachButton: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    paddingHorizontal: 13,
  },
  attachText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  bodyText: {
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 20,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  closeButton: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  closeText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  composer: {
    alignItems: 'flex-end',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 9,
    padding: 12,
  },
  content: {
    gap: 14,
    padding: 16,
    paddingBottom: 24,
  },
  customerTurn: {
    alignSelf: 'flex-end',
  },
  confirmPrompt: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  confirmPromptText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 18,
  },
  disclaimer: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
    marginTop: 4,
  },
  errorCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  errorText: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  estimateCard: {
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  estimateHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    paddingBottom: 10,
  },
  headerCopy: {
    flex: 1,
    gap: 3,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
    width: 94,
  },
  infoRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  infoValue: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
  },
  inlineEstimate: {
    borderTopWidth: 1,
    marginTop: 10,
    paddingTop: 9,
  },
  inlineEstimateText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
  },
  input: {
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 20,
    maxHeight: 110,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  kaelTurn: {
    alignSelf: 'flex-start',
  },
  keyboard: {
    flex: 1,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  safe: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 22,
  },
  sendButton: {
    alignItems: 'center',
    borderRadius: 16,
    height: 46,
    justifyContent: 'center',
    minWidth: 58,
    paddingHorizontal: 13,
  },
  sendText: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  serviceChip: {
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 38,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  stateCard: {
    alignItems: 'flex-start',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  statusPill: {
    borderRadius: 999,
    borderWidth: 1,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 18,
  },
  summaryCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  turnBubble: {
    borderRadius: 18,
    borderWidth: 1,
    maxWidth: '86%',
    padding: 13,
  },
  turnList: {
    gap: 10,
  },
  turnRole: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  turnText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
  },
})
