import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  attachButton: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  micButton: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  attachText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  addressBar: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 10,
    marginTop: 8,
    minHeight: 44,
    paddingHorizontal: 11,
  },
  addressDistrictPill: {
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    fontSize: 10,
    fontWeight: '800',
    maxWidth: 92,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  addressInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    minHeight: 34,
    minWidth: 0,
    paddingVertical: 6,
  },
  addressLiftFrame: {
    minHeight: 5,
    overflow: 'visible',
    position: 'relative',
  },
  addressLiftSlot: {
    overflow: 'hidden',
  },
  addressRevealHandle: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'flex-start',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 5,
    zIndex: 4,
  },
  addressRevealCue: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 16,
    justifyContent: 'center',
    width: 34,
  },
  agentAvatar: {
    alignItems: 'center',
    borderRadius: 21,
    borderWidth: 1,
    flexShrink: 0,
    height: 50,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 50,
  },
  agentAvatarImage: {
    height: 42,
    transform: [{ translateY: 2 }],
    width: 42,
  },
  agentFocusCard: {
    borderRadius: 28,
    borderWidth: 1,
    gap: 16,
    overflow: 'hidden',
    paddingHorizontal: 17,
    paddingBottom: 18,
    paddingTop: 16,
  },
  agentHead: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
  },
  agentStatusAccent: {
    borderRadius: 999,
    height: 26,
    width: 6,
  },
  agentStatusRail: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 13,
  },
  agentStatusText: {
    flex: 1,
    fontSize: 14.5,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 18.5,
  },
  agentStepCard: {
    borderRadius: 17,
    borderWidth: 1,
    flex: 1,
    minHeight: 64,
    paddingHorizontal: 9,
    paddingVertical: 10,
  },
  agentStepIndex: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 12,
    marginBottom: 6,
  },
  agentSteps: {
    flexDirection: 'row',
    gap: 9,
    paddingHorizontal: 3,
  },
  agentStepTitle: {
    fontSize: 11.5,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 15,
  },
  bodyText: {
    fontSize: 13.5,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  briefField: {
    borderRadius: 17,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: 58,
    padding: 9,
  },
  briefFieldLabel: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 12,
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  briefFieldValue: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 15,
  },
  briefFieldWide: {
    flexBasis: '100%',
  },
  briefGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  chatFrame: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 430,
    overflow: 'hidden',
    position: 'relative',
  },
  chatAmbientField: {
    bottom: 0,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
  },
  chatAmbientMint: {
    borderRadius: 999,
    height: 190,
    opacity: 0.32,
    position: 'absolute',
    right: -70,
    top: 76,
    transform: [{ rotate: '-10deg' }],
    width: 220,
  },
  chatAmbientSweep: {
    height: '132%',
    opacity: 0.18,
    position: 'absolute',
    right: 88,
    top: -80,
    transform: [{ rotate: '9deg' }],
    width: 42,
  },
  chatAmbientWarm: {
    borderRadius: 999,
    bottom: 86,
    height: 150,
    left: -74,
    opacity: 0.14,
    position: 'absolute',
    transform: [{ rotate: '12deg' }],
    width: 190,
  },
  closeButton: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  closeText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  composer: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 9,
    paddingBottom: 8,
    paddingTop: 0,
  },
  composerGlass: {
    marginBottom: 14,
    marginHorizontal: 20.5,
    position: 'relative',
    zIndex: 3,
  },
  content: {
    gap: 14,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
  },
  contextRail: {
    gap: 10,
    paddingHorizontal: 3,
    paddingVertical: 3,
  },
  contextRailTitle: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  chatQuickServices: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 1,
  },
  customerTurn: {
    alignSelf: 'flex-end',
  },
  confirmPrompt: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  confirmPromptText: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 18,
  },
  disclaimer: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
    marginTop: 4,
  },
  errorCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  errorText: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 19,
  },
  estimateCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  estimateHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  emptyChatStart: {
    gap: 13,
  },
  emptyTicketCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  emptyTicketPill: {
    alignSelf: 'stretch',
    borderRadius: 999,
    borderWidth: 1,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 16,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  headerMinimal: {
    minHeight: 54,
  },
  headerCopy: {
    flex: 1,
    gap: 3,
  },
  headerGlass: {
    borderRadius: 26,
    marginHorizontal: 16,
    marginTop: 16,
    minHeight: 74,
    position: 'relative',
    zIndex: 3,
  },
  headerSpacer: {
    flex: 1,
    minHeight: 42,
  },
  hiddenMarker: {
    height: 0,
    opacity: 0,
    position: 'absolute',
    width: 0,
  },
  kaelAvatar: {
    alignItems: 'center',
    borderRadius: 19,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 46,
  },
  kaelAvatarImage: {
    height: 52,
    transform: [{ translateY: 4 }],
    width: 52,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
    width: 94,
  },
  infoRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  infoValue: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
  },
  inlineEstimate: {
    borderTopWidth: 1,
    marginTop: 10,
    paddingTop: 9,
  },
  inlineEstimateText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
  },
  input: {
    borderRadius: 16,
    borderWidth: 0,
    flex: 1,
    fontSize: 14.5,
    fontWeight: '800',
    height: 46,
    letterSpacing: 0,
    lineHeight: 20,
    maxHeight: 46,
    minHeight: 46,
    paddingHorizontal: 8,
    paddingBottom: 13,
    paddingTop: 13,
    textAlignVertical: 'center',
  },
  inputInvisibleFocus: { backgroundColor: 'transparent', borderColor: 'transparent', borderWidth: 0, boxShadow: 'none', outlineColor: 'transparent', outlineOffset: 0, outlineStyle: 'none', outlineWidth: 0 } as any,
  kaelTurn: {
    alignSelf: 'flex-start',
  },
  keyboard: {
    flex: 1,
    position: 'relative',
    zIndex: 2,
  },
  pressed: {
    opacity: 0.82,
  },
  onlinePill: {
    borderRadius: 999,
    borderWidth: 1,
    fontSize: 10,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  safe: {
    alignItems: 'center',
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 22,
  },
  sendButton: {
    alignItems: 'center',
    borderRadius: 16,
    height: 44,
    justifyContent: 'center',
    minWidth: 44,
    width: 44,
  },
  sendText: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  serviceChip: {
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 36,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  stateCard: {
    alignItems: 'flex-start',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  statusPill: {
    borderRadius: 999,
    borderWidth: 1,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 18,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  turnBubble: {
    borderRadius: 23,
    borderWidth: 1,
    maxWidth: '83%',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  turnBubbleWithAvatar: {
    flex: 1,
    maxWidth: '100%',
  },
  turnList: {
    gap: 14,
  },
  turnRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  turnRowCustomer: {
    justifyContent: 'flex-end',
  },
  turnAvatar: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexShrink: 0,
    height: 42,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 42,
  },
  turnAvatarImage: {
    height: 34,
    width: 34,
  },
  turnRole: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  turnText: {
    fontSize: 14.2,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 20.5,
  },
  traceBody: {
    fontSize: 10.8,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 14,
    marginTop: 2,
  },
  traceCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 9,
    padding: 13,
  },
  traceCopy: {
    flex: 1,
    minWidth: 0,
  },
  traceIndex: {
    borderRadius: 12,
    borderWidth: 1,
    fontSize: 10.5,
    fontWeight: '900',
    height: 28,
    lineHeight: 28,
    overflow: 'hidden',
    textAlign: 'center',
    width: 28,
  },
  traceLabel: {
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 15,
  },
  traceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 36,
  },
  traceState: {
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    maxWidth: 72,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 5,
    textAlign: 'center',
  },
  traceTitle: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 14,
    marginBottom: 5,
  },
  threadScroll: {
    flex: 1,
  },
})
