import { StyleSheet } from 'react-native'

import { color, glass, radius, shadow, signature, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  authorityCard: {
    backgroundColor: 'rgba(231,255,248,0.83)',
    borderColor: 'rgba(184,231,223,0.88)',
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: 6,
    padding: 16,
    ...shadow.soft,
  },
  authorityLabel: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  authorityText: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
  },
  availabilityCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 62,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...shadow.soft,
  },
  availabilityCardRebuild: {
    borderRadius: 24,
    minHeight: 92,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  availabilityCardProfile: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    elevation: 0,
    minHeight: 76,
    paddingHorizontal: 16,
    paddingVertical: 13,
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  availabilityCardDark: {
    backgroundColor: '#1A332F',
    borderColor: 'rgba(169,213,204,0.35)',
  },
  availabilityCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  availabilityCopyRebuild: {
    gap: 2,
    paddingLeft: 4,
  },
  availabilityArtwork: {
    borderRadius: 42,
    height: '100%',
    opacity: 0.92,
    width: '100%',
  },
  availabilityArtworkFrame: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 42,
    borderWidth: 1,
    flexShrink: 0,
    height: 84,
    justifyContent: 'center',
    position: 'relative',
    width: 84,
  },
  availabilityArtworkFrameDark: {
    backgroundColor: '#1D2522',
    borderColor: 'rgba(190,210,205,0.16)',
  },
  availabilityArtworkPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.975 }],
  },
  availabilityAvatarPlaceholder: {
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  availabilityCameraBadge: {
    alignItems: 'center',
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 999,
    borderWidth: 1,
    bottom: -2,
    height: 26,
    justifyContent: 'center',
    position: 'absolute',
    right: -2,
    width: 26,
  },
  availabilityCameraBadgeDark: {
    backgroundColor: '#1D2522',
    borderColor: 'rgba(190,210,205,0.16)',
  },
  availabilityKnob: {
    backgroundColor: color.mint.white,
    borderRadius: 10,
    boxShadow: '0 3px 8px rgba(7,26,36,0.16)',
    height: 20,
    position: 'relative',
    width: 20,
    zIndex: 2,
  },
  availabilitySwitch: {
    backgroundColor: '#DFE9E7',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: radius.pill,
    borderWidth: 0,
    height: 26,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 3,
    width: 44,
  },
  availabilitySwitchDark: {
    backgroundColor: '#29433F',
    borderColor: 'rgba(169,213,204,0.32)',
  },
  availabilitySwitchDisabled: {
    opacity: 0.58,
  },
  availabilitySwitchOn: {
    backgroundColor: '#16C7B4',
    boxShadow: '0 8px 16px rgba(8,175,156,0.22)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  availabilitySwitchSheen: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: radius.pill,
    height: 20,
    left: 0,
    position: 'absolute',
    top: 3,
    width: 8,
    zIndex: 1,
  },
  availabilityTitle: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
  },
  availabilityTitleDark: {
    color: '#F1F6F4',
  },
  availabilityDescription: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '500',
  },
  availabilityDescriptionDark: {
    color: '#A9B7B3',
  },
  homeCommandBody: {
    color: color.text.muted,
    ...typography.footnote,
    fontWeight: '600',
    marginTop: 6,
  },
  homeCommandCard: {
    backgroundColor: 'rgba(255,255,255,0.76)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 28,
    borderWidth: 1,
    gap: 12,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  homeCommandCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  homeCommandTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
    marginTop: 0,
  },
  homeCommandTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  homeQuickAuraFrame: {
    position: 'relative',
  },
  homeScoreLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 0,
    maxWidth: 54,
    textAlign: 'center',
  },
  homeScoreShell: {
    alignItems: 'center',
    height: 92,
    justifyContent: 'center',
    position: 'relative',
    width: 92,
  },
  homeScoreText: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  homeScoreValue: {
    color: color.brand.primaryDark,
    ...typography.title2,
    fontWeight: '600',
  },
  homeSourceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 58,
  },
  homeSourceHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  homeSourceScrollContent: {
    gap: 9,
    paddingBottom: 118,
    paddingHorizontal: 16,
    paddingTop: 12,
    position: 'relative',
  },
  homeSourceScroll: {
    position: 'relative',
    zIndex: 1,
  },
  homeSourceSubtitle: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 2,
  },
  homeSourceTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
  },
  homeStatGrid: {
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  homeStatLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 4,
    textAlign: 'center',
  },
  homeStatTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: color.surface.stroke,
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 60,
    minWidth: 0,
    paddingHorizontal: 6,
    paddingVertical: 9,
  },
  homeStatValue: {
    color: color.text.strong,
    ...typography.headline,
    textAlign: 'center',
  },
  boundaryBody: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    position: 'relative',
    zIndex: 1,
  },
  boundaryNote: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 4,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    ...shadow.soft,
  },
  boundaryTitle: {
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '600',
    position: 'relative',
    zIndex: 1,
  },
  cardMintAura: {
    bottom: 'auto',
    height: 210,
    left: '24%',
    right: -70,
    top: -92,
  },
  cardTopHighlight: {
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderRadius: radius.pill,
    height: 1,
    left: '10%',
    opacity: 0.86,
    position: 'absolute',
    right: '10%',
    top: 0,
  },
  glassCard: {
    backgroundColor: 'rgba(255,255,255,0.76)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 30,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  composerIcon: {
    height: 18,
    width: 18,
  },
  composerPlaceholder: {
    color: color.text.muted,
    flex: 1,
    ...typography.caption1,
    fontWeight: '600',
    minWidth: 0,
  },
  composerSend: {
    alignItems: 'center',
    backgroundColor: color.brand.primary,
    borderColor: 'rgba(255,255,255,0.82)',
    borderRadius: 20,
    borderWidth: 1,
    flexShrink: 0,
    height: 40,
    justifyContent: 'center',
    width: 40,
    ...shadow.primary,
  },
  composerSendIcon: {
    height: 21,
    tintColor: color.text.inverse,
    width: 21,
  },
  composerShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 58,
    overflow: 'hidden',
    paddingLeft: 15,
    paddingRight: 7,
    ...shadow.soft,
  },
  jobRoomComposerInput: {
    color: color.text.strong,
    flex: 1,
    ...typography.footnote,
    fontWeight: '600',
    maxHeight: 92,
    minHeight: 38,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 8,
  },
  workerChatTextFieldShell: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    minHeight: 38,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  workerChatTextFieldStack: {
    flex: 1,
  },
  privateKaelMediaImage: {
    backgroundColor: color.mint.mint100,
    borderRadius: 10,
    height: 42,
    width: 42,
  },
  privateKaelMediaPreview: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: color.mint.mint100,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    maxWidth: 190,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  privateKaelMediaRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  privateKaelMediaText: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.caption1,
    fontWeight: '600',
  },
  privateKaelGreeting: {
    color: color.text.strong,
    ...typography.headline,
  },
  composerUtility: {
    alignItems: 'center',
    backgroundColor: color.mint.mint50,
    borderRadius: 15,
    flexShrink: 0,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  completionHeroAura: {
    bottom: 'auto',
    height: 170,
    left: '36%',
    right: -62,
    top: -70,
  },
  completionLens: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 34,
    borderWidth: 1,
    flexShrink: 0,
    height: 74,
    justifyContent: 'center',
    position: 'relative',
    width: 74,
    zIndex: 1,
    ...shadow.primary,
  },
  completionLensLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  completionLensValue: {
    color: color.brand.primaryDark,
    ...typography.title2,
    fontWeight: '600',
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  headerTextColumn: {
    flex: 1,
    gap: 2,
  },
  earningsOverviewHeaderRow: {
    position: 'relative',
    zIndex: 2,
  },
  headerMenuText: {
    color: color.brand.primaryDark,
    ...typography.title3,
    height: 42,
    fontWeight: '600',
    includeFontPadding: false,
    textAlign: 'center',
    textAlignVertical: 'center',
    width: 42,
  },
  headerSubtitleText: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  headerSubtitleTextDark: {
    color: '#A9B7B3',
  },
  heroBody: {
    color: color.text.secondary,
    ...typography.subheadline,
    fontWeight: '600',
  },
  heroTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
  },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  iconBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 22,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 52,
    ...shadow.soft,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: glass.bgStrong,
    borderColor: 'rgba(184,231,223,0.78)',
    borderRadius: radius.md,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    padding: 0,
    width: 42,
    ...shadow.soft,
  },
  iconImage: {
    height: 30,
    width: 30,
  },
  infoListCard: {
    backgroundColor: 'rgba(255,255,255,0.73)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 25,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  acceptReviewStack: {
    gap: 10,
  },
  offerDetailStack: {
    gap: 10,
  },
  offerDetailListDivider: {
    borderTopColor: 'rgba(205,226,222,0.78)',
    borderTopWidth: 1,
  },
  kaelBriefBody: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '600',
  },
  kaelBriefCard: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(204,223,219,0.94)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 0,
    minHeight: 76,
    overflow: 'hidden',
    padding: 11,
    position: 'relative',
    ...shadow.soft,
  },
  kaelBriefAura: {
    bottom: -30,
    height: 124,
    left: -26,
    opacity: 0.72,
    right: -34,
    top: -26,
  },
  kaelBriefChevron: {
    color: color.brand.primaryDark,
    ...typography.title2,
    fontWeight: '600',
    alignSelf: 'center',
    marginLeft: 10,
    position: 'relative',
    zIndex: 1,
  },
  kaelBriefZipAura: {
    height: 136,
    opacity: 0.58,
    right: -72,
    top: -62,
    width: 176,
  },
  kaelBriefIcon: {
    height: 36,
    width: 36,
  },
  kaelBriefIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 17,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 48,
    zIndex: 1,
  },
  kaelBriefText: {
    flex: 1,
    gap: 3,
    marginLeft: 38,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  kaelBriefTitle: {
    color: color.text.strong,
    ...typography.caption1,
    fontWeight: '600',
  },
  kickerText: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  listCardMintAura: {
    bottom: 'auto',
    height: 160,
    left: '42%',
    right: -68,
    top: -74,
  },
  mapGridLine: {
    backgroundColor: 'rgba(169,210,202,0.48)',
    height: 2,
    left: 18,
    position: 'absolute',
    right: 18,
    top: 72,
    transform: [{ rotate: '-13deg' }],
  },
  mapPanel: {
    backgroundColor: 'rgba(244,255,252,0.9)',
    borderColor: 'rgba(161,235,224,0.62)',
    borderRadius: 27,
    borderWidth: 1,
    height: 210,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  demandMapPanelAura: {
    bottom: -18,
    left: -10,
    opacity: 0.95,
    right: -10,
    top: -18,
    zIndex: 1,
  },
  routeMapPanelAura: {
    bottom: -18,
    left: -10,
    opacity: 0.98,
    right: -10,
    top: -18,
    zIndex: 1,
  },
  routeMapCaption: {
    backgroundColor: 'rgba(248,255,252,0.92)',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 14,
    borderWidth: 1,
    bottom: 12,
    left: 12,
    maxWidth: '82%',
    paddingHorizontal: 10,
    paddingVertical: 7,
    position: 'absolute',
    zIndex: 3,
  },
  routeMapCaptionMeta: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '600',
  },
  routeMapCaptionTitle: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
  },
  mapStaticImage: {
    height: '100%',
    position: 'relative',
    width: '100%',
    zIndex: 0,
  },
  mapUnavailable: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    justifyContent: 'center',
    paddingHorizontal: 28,
    position: 'relative',
    zIndex: 2,
  },
  mapUnavailableMeta: {
    color: color.text.muted,
    ...typography.caption1,
    fontWeight: '600',
    textAlign: 'center',
  },
  mapUnavailableTitle: {
    color: color.text.strong,
    ...typography.callout,
    fontWeight: '600',
    textAlign: 'center',
  },
  mapPoint: {
    alignItems: 'center',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    width: 44,
  },
  mapPointJob: {
    backgroundColor: color.brand.primary,
    right: 42,
    top: 44,
  },
  mapPointAreaOne: {
    backgroundColor: color.brand.primary,
    left: 72,
    top: 58,
  },
  mapPointAreaTwo: {
    backgroundColor: color.brand.primary,
    bottom: 30,
    right: 38,
  },
  mapPointCustomer: {
    backgroundColor: color.brand.primary,
    right: 34,
    top: 118,
    width: 64,
  },
  mapPointSelf: {
    backgroundColor: '#5d77f0',
    left: '46%',
    top: 105,
  },
  mapPointText: {
    color: '#ffffff',
    ...typography.footnote,
    fontWeight: '600',
  },
  mapRoad: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: 'rgba(174,211,205,0.38)',
    borderRadius: 999,
    borderWidth: 1,
    height: 5,
    position: 'absolute',
  },
  mapRoadFour: {
    left: 66,
    top: 148,
    transform: [{ rotate: '8deg' }],
    width: 236,
  },
  mapRoadOne: {
    left: 18,
    top: 92,
    transform: [{ rotate: '-14deg' }],
    width: 310,
  },
  mapRoadThree: {
    left: 102,
    top: 34,
    transform: [{ rotate: '64deg' }],
    width: 220,
  },
  mapRoadTwo: {
    left: 48,
    top: 138,
    transform: [{ rotate: '8deg' }],
    width: 280,
  },
  metricLabel: {
    color: color.text.secondary,
    flexShrink: 1,
    ...typography.caption1,
    fontWeight: '600',
  },
  metricTile: {
    backgroundColor: 'rgba(255,255,255,0.73)',
    borderColor: color.surface.stroke,
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    minHeight: 86,
    minWidth: 0,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
  },
  metricValue: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.headline,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  workerProfileAuraButton: {
    backgroundColor: 'rgba(248,255,253,0.92)',
    borderColor: 'rgba(45,211,193,0.38)',
    overflow: 'hidden',
    boxShadow: '0 12px 24px rgba(8,125,114,0.12)',
  },
  workerProfileLogoutCta: {
    marginTop: -2,
  },
  navigationRow: {
    flexDirection: 'row',
    gap: 10,
    overflow: 'visible',
    position: 'relative',
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  opaqueCardDark: {
    backgroundColor: '#1A332F',
  },
  opportunityInboxStack: {
    gap: 8,
  },
  opportunityList: {
    gap: 8,
  },
  opportunityInboxPageZipAura: {
    height: 340,
    opacity: 0.24,
    right: -92,
    top: 118,
    width: 390,
  },
  offerDetailPageZipAura: {
    height: 340,
    opacity: 0.24,
    right: -92,
    top: 120,
    width: 390,
  },
  offerDetailPageLowerAura: {
    bottom: 84,
    height: 320,
    left: -58,
    opacity: 0.24,
    right: -58,
    top: 'auto',
  },
  routeEtaPageZipAura: {
    height: 340,
    opacity: 0.24,
    right: -92,
    top: 122,
    width: 390,
  },
  arrivalCheckinPageZipAura: {
    height: 340,
    opacity: 0.24,
    right: -92,
    top: 122,
    width: 390,
  },
  kaelOrbPageZipAura: {
    bottom: 84,
    height: 360,
    opacity: 0.24,
    right: -98,
    top: 'auto',
    width: 390,
  },
  caseFlowPageLowerAura: {
    bottom: 66,
    height: 360,
    left: -68,
    opacity: 0.24,
    right: -68,
    top: 'auto',
  },
  demandMapInfoListAura: {
    bottom: -58,
    height: 250,
    left: -46,
    opacity: 0.22,
    right: -46,
    top: -48,
  },
  smartSchedulePageLowerAura: {
    bottom: 72,
    height: 360,
    left: -62,
    opacity: 0.24,
    right: -62,
    top: 'auto',
  },
  smartSchedulePageZipAura: {
    height: 360,
    opacity: 0.26,
    right: -96,
    top: 112,
    width: 390,
  },
  shiftBriefHeroCard: {
    backgroundColor: 'rgba(248,255,252,0.82)',
    borderColor: 'rgba(255,255,255,0.94)',
    minHeight: 120,
    padding: 16,
  },
  shiftBriefHeroCopy: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  shiftBriefHeroIcon: {
    height: 46,
    width: 46,
  },
  shiftBriefHeroIconTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 20,
    borderWidth: 1,
    flexShrink: 0,
    height: 66,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 66,
    zIndex: 1,
    ...shadow.soft,
  },
  shiftBriefHeroInner: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    position: 'relative',
    zIndex: 1,
  },
  phaseText: {
    color: color.brand.primaryDark,
    ...typography.footnote,
    fontWeight: '600',
  },
  phaseTextDark: {
    color: '#63E6D0',
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  disabledButton: {
    opacity: 0.62,
  },
  serviceAreaMapShell: {
    borderRadius: 26,
    overflow: 'hidden',
    position: 'relative',
  },
  serviceAreaChevronOpen: {
    transform: [{ rotate: '90deg' }],
  },
  serviceAreaExpandedStack: {
    gap: 10,
  },
  serviceAreaSummaryCard: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  serviceAreaSummaryPressed: {
    opacity: 0.78,
  },
  serviceAreaSummaryIcon: {
    alignItems: 'center',
    borderRadius: 12,
    flexShrink: 0,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  serviceAreaSummaryText: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  serviceAreaSummaryTitle: {
    ...typography.body,
    fontWeight: '600',
  },
  serviceAreaSummaryBody: {
    ...typography.caption1,
  },
  serviceAreaSummaryChevron: {
    ...typography.title2,
    fontWeight: '500',
  },
  serviceAreaOpenCard: {
    minHeight: 82,
  },
  serviceAreaPlaceMeta: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    position: 'relative',
    zIndex: 1,
  },
  serviceAreaPlaceName: {
    color: color.text.strong,
    flex: 1,
    ...typography.caption1,
    fontWeight: '600',
    minWidth: 0,
  },
  serviceAreaPlacePanel: {
    backgroundColor: 'rgba(249,255,252,0.86)',
    borderColor: 'rgba(151,232,221,0.68)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    ...shadow.soft,
  },
  serviceAreaPlacePin: {
    alignItems: 'center',
    backgroundColor: 'rgba(221,255,247,0.92)',
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  serviceAreaPlacePinText: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
  },
  serviceAreaInlineEditor: {
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  serviceAreaDraftLabel: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
  },
  serviceAreaDraftShell: {
    backgroundColor: 'rgba(255,255,255,0.84)',
    borderColor: 'rgba(139,232,220,0.74)',
    minHeight: 54,
  },
  serviceAreaDraftInput: {
    color: color.text.strong,
    ...typography.subheadline,
  },
  serviceAreaSaveInlineButton: {
    backgroundColor: 'rgba(219,247,239,0.84)',
    borderColor: 'rgba(39,189,166,0.34)',
    borderWidth: 1,
    minHeight: 46,
  },
  serviceAreaPlaceRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderColor: 'rgba(205,226,222,0.78)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 10,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  serviceAreaPlaceRowSelected: {
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(139,232,220,0.86)',
  },
  serviceAreaPlaceRowPending: {
    backgroundColor: 'rgba(232,255,249,0.76)',
    borderColor: 'rgba(39,189,166,0.48)',
  },
  serviceAreaPlaceTitle: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
    position: 'relative',
    zIndex: 1,
  },
  routeLine: {
    borderRadius: 999,
    height: 5,
    position: 'absolute',
  },
  routeLineEnd: {
    backgroundColor: color.brand.primary,
    right: 56,
    top: 115,
    transform: [{ rotate: '10deg' }],
    width: 122,
  },
  routeLineStart: {
    backgroundColor: '#4f9be8',
    left: 82,
    top: 118,
    transform: [{ rotate: '-21deg' }],
    width: 132,
  },
  safeArea: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  scrollContent: {
    gap: 18,
    paddingBottom: 126,
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  customerConfirmationWait: {
    gap: 12,
    paddingHorizontal: 8,
    paddingTop: 22,
  },
  customerConfirmationWaitBody: {
    color: color.text.secondary,
    ...typography.subheadline,
    maxWidth: 520,
  },
  customerConfirmationWaitDot: {
    backgroundColor: color.brand.primary,
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  customerConfirmationWaitMeta: {
    color: color.text.muted,
    ...typography.caption1,
    fontWeight: '600',
    marginTop: 4,
  },
  customerConfirmationWaitRule: {
    backgroundColor: 'rgba(13,167,151,0.24)',
    height: 1,
    marginBottom: 8,
    width: '100%',
  },
  customerConfirmationWaitStatus: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
  },
  customerConfirmationWaitStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  customerConfirmationWaitTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
    maxWidth: 520,
  },
  sectionStack: {
    gap: 14,
  },
  workerSettingsScreenStack: {
    paddingBottom: 92,
  },
  fieldEvidenceKaelConfirmation: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
    paddingHorizontal: 2,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: -4,
    paddingHorizontal: 2,
  },
  sectionHeaderAction: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
  },
  sectionHeaderTitle: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
  },
  successBody: {
    color: color.text.secondary,
    ...typography.footnote,
    fontWeight: '600',
    textAlign: 'center',
  },
  successCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 28,
    borderWidth: 1,
    gap: 8,
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 18,
    position: 'relative',
    ...shadow.raised,
  },
  successAura: {
    bottom: 'auto',
    height: 190,
    left: '18%',
    right: -72,
    top: -86,
  },
  successCheck: {
    alignItems: 'center',
    backgroundColor: '#08AF9C',
    borderColor: 'rgba(255,255,255,0.82)',
    borderRadius: 18,
    borderWidth: 3,
    height: 63,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 63,
    zIndex: 1,
    boxShadow: '0 10px 18px rgba(8,125,114,0.28)',
  },
  successCheckFill: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  successCheckText: {
    color: color.text.inverse,
    ...typography.largeTitle,
    fontWeight: '600',
    position: 'relative',
    zIndex: 1,
  },
  successEmblem: {
    alignItems: 'center',
    backgroundColor: 'rgba(203,248,238,0.56)',
    borderColor: 'rgba(255,255,255,0.78)',
    borderRadius: 34,
    borderWidth: 1,
    height: 104,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 104,
    boxShadow: '0 18px 34px rgba(8,125,114,0.16)',
  },
  successEmblemAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.66,
    zIndex: 0,
  },
  successStatusPill: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    maxWidth: '86%',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  successStatusText: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  successTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
    textAlign: 'center',
  },
  statusDot: {
    backgroundColor: color.brand.primary,
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 7,
    borderWidth: 2,
    height: 14,
    width: 14,
  },
  statusDotSmall: {
    backgroundColor: color.brand.primary,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  surfaceGlass: {
    backgroundColor: signature.bg,
  },
  surfaceDark: {
    backgroundColor: '#122724',
  },
  surfaceSolid: {
    backgroundColor: color.surface.base,
  },
  timerCaption: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  timerCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(186,240,230,0.78)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minHeight: 100,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    boxShadow: '0 18px 38px rgba(8,125,114,0.16)',
  },
  timerLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  timerRing: {
    alignItems: 'center',
    flexShrink: 0,
    height: 70,
    justifyContent: 'center',
    position: 'relative',
    width: 70,
    zIndex: 1,
  },
  timerRingLens: {
    alignItems: 'center',
    backgroundColor: '#FAFFFD',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 28,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    position: 'absolute',
    width: 52,
  },
  timerRingValue: {
    color: color.brand.primaryDark,
    ...typography.footnote,
    fontWeight: '600',
  },
  timerTextColumn: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  timerValue: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
  },
  titleText: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
  },
  titleTextDark: {
    color: '#F1F6F4',
  },
  earningsOverviewTitle: {
    marginLeft: 8,
  },
  profileRouteIconVisualBoost: {
    height: 52,
    width: 52,
  },
  scheduleSupportAura: {
    bottom: -42,
    height: 210,
    left: -34,
    opacity: 0.56,
    right: -34,
    top: -42,
  },
  scheduleSupportAuraGroup: {
    position: 'relative',
  },
  scheduleSupportContent: {
    gap: 14,
    position: 'relative',
    zIndex: 1,
  },
  scheduleSupportZipAura: {
    height: 230,
    opacity: 0.42,
    right: -92,
    top: -78,
    width: 260,
  },
  checkInChecklistAura: {
    bottom: -88,
    height: 282,
    left: -76,
    opacity: 0.96,
    right: -58,
    top: -78,
  },
  checkInChecklistZipAura: {
    height: 246,
    opacity: 0.78,
    right: -96,
    top: -82,
    width: 326,
  },
  workerV5CustomerCaseWideMintAura: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  workerV5CustomerCaseWorkCardAura: {
    bottom: -28,
    left: -24,
    position: 'absolute',
    right: -24,
    top: -20,
    zIndex: 0,
  },
  workerV5CustomerMapMintAura: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  workerV5CustomerZipMintAura: {
    height: 180,
    position: 'absolute',
    right: -84,
    top: -96,
    width: 220,
    zIndex: 0,
  },
  shiftHeroAura: {
    bottom: 'auto',
    height: 172,
    left: '30%',
    opacity: 0.92,
    right: -58,
    top: -64,
  },
  shiftKicker: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  intakeEmptyCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  intakeEmptyIcon: {
    height: 34,
    width: 34,
  },
  intakeEmptyIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 17,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 48,
  },
  intakeEmptyMeta: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  intakeEmptyRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.76)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 70,
    padding: 11,
    ...shadow.soft,
  },
  intakeEmptyTitle: {
    color: color.text.strong,
    ...typography.caption1,
    fontWeight: '600',
  },
  intakeStack: {
    gap: 9,
  },
  jobRoomBubbleStack: {
    flex: 1,
    gap: 10,
    minWidth: 0,
  },
  jobRoomThreadAura: {
    bottom: 'auto',
    height: 210,
    left: '30%',
    right: -74,
    top: -84,
  },
  jobRoomThreadCard: {
    alignItems: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 250,
    overflow: 'hidden',
    padding: 15,
    position: 'relative',
    ...shadow.raised,
  },
  kaelOrbBubble: {
    borderRadius: 22,
    borderWidth: 1,
    maxWidth: '84%',
    minWidth: 0,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  kaelOrbBubbleLeft: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderBottomLeftRadius: 8,
    borderColor: 'rgba(216,235,232,0.9)',
  },
  kaelOrbBubbleRight: {
    alignSelf: 'flex-end',
    backgroundColor: color.brand.primary,
    borderBottomRightRadius: 8,
    borderColor: 'rgba(255,255,255,0.72)',
  },
  kaelOrbBubbleRole: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 5,
    textAlign: 'right',
  },
  kaelOrbBubbleText: {
    color: color.text.secondary,
    ...typography.subheadline,
    fontWeight: '600',
  },
  kaelOrbBubbleTextStrong: {
    color: color.text.strong,
    fontWeight: '600',
  },
  kaelOrbBubbleTextRight: {
    color: color.text.inverse,
  },
  kaelOrbComposerStack: {
    gap: 0,
    marginBottom: 0,
    marginTop: 0,
    paddingBottom: 0,
    position: 'relative',
    zIndex: 3,
  },
  kaelIntakeReadinessCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderColor: color.mint.mint100,
    borderRadius: 24,
    borderWidth: 1,
    gap: 8,
    marginTop: 10,
    padding: 14,
    ...shadow.soft,
  },
  kaelIntakeReadinessTitle: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
  },
  kaelIntakeReadinessBody: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  kaelIntakeReadinessButton: {
    marginTop: 2,
  },
  kaelOrbComposerAura: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  kaelOrbComposerCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 26,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 56,
    overflow: 'hidden',
    padding: 8,
    position: 'relative',
    boxShadow: '0 10px 24px rgba(5,155,138,0.10)',
  },
  kaelOrbComposerCameraButton: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  kaelOrbComposerCameraBadge: {
    alignItems: 'center',
    backgroundColor: color.brand.primaryDark,
    borderRadius: 8,
    height: 16,
    justifyContent: 'center',
    minWidth: 16,
    paddingHorizontal: 4,
    position: 'absolute',
    right: -4,
    top: -4,
  },
  kaelOrbComposerCameraBadgeText: {
    color: color.text.inverse,
    ...typography.caption2,
    fontWeight: '600',
  },
  kaelOrbComposerDisclaimer: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 6,
    paddingBottom: 2,
    textAlign: 'center',
  },
  kaelOrbComposerField: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  kaelOrbComposerInput: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 0,
    textAlignVertical: 'center',
  },
  kaelOrbComposerInputShell: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  kaelOrbCustomerChatFrame: {
    flex: 1,
    gap: 10,
    paddingBottom: 18,
    paddingHorizontal: 16,
    paddingTop: 10,
    position: 'relative',
  },
  kaelOrbCustomerChatFrameIntake: {
    gap: 9,
  },
  kaelOrbCustomerModeMenu: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderColor: 'rgba(255,255,255,0.72)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 3,
    minHeight: 0,
    overflow: 'hidden',
    paddingBottom: 4,
    paddingHorizontal: 4,
    paddingTop: 4,
    position: 'absolute',
    maxWidth: 208,
    boxShadow: '0 10px 22px rgba(8,125,114,0.10)',
    right: 16,
    top: 68,
    width: '59%',
    zIndex: 20,
  },
  kaelOrbCustomerModeMenuOption: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderColor: 'rgba(255,255,255,0.48)',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 10,
    paddingVertical: 5,
    position: 'relative',
    width: '100%',
    zIndex: 2,
  },
  kaelOrbCustomerModeMenuOptionActive: {
    backgroundColor: 'rgba(255,255,255,0.42)',
    borderColor: 'rgba(255,255,255,0.78)',
    boxShadow: '0 6px 14px rgba(4,99,88,0.07)',
  },
  kaelOrbCustomerModeMenuCheck: {
    color: color.brand.primary,
    ...typography.callout,
    fontWeight: '600',
    marginLeft: 8,
  },
  kaelOrbCustomerModeMenuCopy: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  kaelOrbCustomerModeMenuOptions: {
    gap: 3,
    zIndex: 2,
  },
  kaelOrbCustomerModeMenuDescription: {
    color: color.text.muted,
    ...typography.caption2,
  },
  kaelOrbCustomerModeMenuText: {
    color: color.text.strong,
    ...typography.caption1,
    fontWeight: '600',
  },
  kaelOrbCustomerModeMenuTextActive: {
    color: color.brand.primary,
  },
  kaelOrbCustomerHeaderRow: {
    minHeight: 62,
  },
  kaelOrbCustomerHeaderTitle: {
    ...typography.title1,
  },
  kaelOrbCustomerKeyboard: {
    flex: 1,
    position: 'relative',
    zIndex: 2,
  },
  kaelOrbCustomerSafeArea: {
    maxWidth: '100%',
    width: '100%',
  },
  kaelOrbCustomerScrollContent: {
    gap: 12,
    paddingBottom: 34,
    paddingTop: 12,
  },
  kaelOrbCustomerTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 58,
  },
  kaelOrbCustomerTopSpacer: {
    flex: 1,
    minWidth: 0,
  },
  kaelOrbCustomerHeaderActions: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderColor: 'rgba(255,255,255,0.72)',
    borderCurve: 'continuous',
    borderRadius: 22,
    borderWidth: 1,
    boxShadow: '0 7px 16px rgba(8,125,114,0.08)',
    flexDirection: 'row',
    height: 44,
    overflow: 'hidden',
  },
  kaelOrbCustomerHeaderActionsOpen: {
    borderColor: 'rgba(255,255,255,0.86)',
  },
  kaelOrbCustomerHeaderActionsLiquid: {
    borderWidth: 0,
  },
  kaelOrbCustomerSessionTrigger: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 21,
    height: 44,
    justifyContent: 'center',
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    width: 44,
  },
  kaelOrbCustomerSessionTriggerOpen: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
  },
  kaelOrbCustomerHeaderTriggerPressed: {
    opacity: 0.78,
  },
  kaelOrbCustomerSessionTriggerPressedReduced: {
    opacity: 0.78,
  },
  kaelOrbCustomerModeTrigger: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 21,
    flexDirection: 'row',
    height: 44,
    justifyContent: 'center',
    width: 114,
  },
  kaelOrbCustomerModeTriggerOpen: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
  },
  kaelOrbCustomerModeTriggerPressedReduced: {
    opacity: 0.82,
  },
  kaelOrbCustomerModeTriggerPressTarget: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flex: 1,
    justifyContent: 'center',
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    paddingHorizontal: 11,
  },
  kaelOrbCustomerModeTriggerText: {
    alignSelf: 'stretch',
    color: color.text.strong,
    ...typography.footnote,
    fontWeight: '700',
    includeFontPadding: false,
    textAlign: 'center',
    textAlignVertical: 'center',
    transform: [{ translateX: -14 }, { translateY: -1 }],
  },
  kaelOrbMediaAura: {
    bottom: -44,
    height: 120,
    left: -36,
    opacity: 0.48,
    right: -36,
    top: -42,
  },
  kaelOrbMediaLine: {
    backgroundColor: 'rgba(238,255,251,0.9)',
    borderRadius: radius.pill,
    height: 4,
    width: '74%',
  },
  kaelOrbMediaStrip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 9,
    width: '86%',
  },
  kaelOrbMediaThumb: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    height: 70,
    justifyContent: 'flex-end',
    minWidth: 0,
    overflow: 'hidden',
    paddingBottom: 10,
    position: 'relative',
    ...shadow.soft,
  },
  kaelOrbMediaThumbDark: {
    backgroundColor: '#435D63',
  },
  kaelOrbMediaThumbSoft: {
    backgroundColor: '#D8E9E6',
  },
  kaelOrbOpenButton: {
    alignItems: 'center',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    minHeight: 28,
    minWidth: 58,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  kaelOrbOpenButtonText: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
    textAlign: 'center',
  },
  kaelOrbOpportunityAside: {
    alignItems: 'flex-end',
    gap: 7,
    maxWidth: 108,
    minWidth: 76,
    position: 'relative',
    zIndex: 1,
  },
  kaelOrbOpportunityCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 70,
    overflow: 'hidden',
    padding: 13,
    position: 'relative',
    ...shadow.soft,
  },
  kaelOrbOpportunityCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  kaelOrbOpportunityIcon: {
    height: 32,
    width: 32,
  },
  kaelOrbOpportunityIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.84)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 16,
    borderWidth: 1,
    flexShrink: 0,
    height: 46,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 46,
    zIndex: 1,
  },
  kaelOrbOpportunityList: {
    alignSelf: 'flex-start',
    gap: 9,
    marginBottom: 6,
    marginTop: 2,
    width: '92%',
  },
  kaelOrbOpportunityMeta: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  kaelOrbOpportunityMetaStrong: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
  },
  kaelOrbOpportunityPayout: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
    textAlign: 'right',
  },
  kaelOrbOpportunityStatus: {
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 0,
    ...typography.caption2,
    fontWeight: '600',
    minWidth: 52,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  kaelOrbOpportunityTitle: {
    color: color.text.strong,
    ...typography.caption2,
    fontWeight: '600',
  },
  kaelOrbQuickChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  kaelOrbQuickChipDisabled: {
    opacity: 0.52,
  },
  kaelOrbQuickChipSelected: {
    backgroundColor: 'rgba(224,251,244,0.88)',
    borderColor: 'rgba(127,226,215,0.78)',
  },
  kaelOrbQuickChipText: {
    color: color.text.secondary,
    ...typography.caption1,
    fontWeight: '600',
  },
  kaelOrbQuickChipTextSelected: {
    color: color.brand.primaryDark,
  },
  kaelOrbQuickChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  kaelOrbSendButton: {
    alignItems: 'center',
    borderRadius: 22,
    flexShrink: 0,
    height: 44,
    justifyContent: 'center',
    position: 'relative',
    width: 44,
    zIndex: 1,
  },
  kaelOrbStack: {
    gap: 10,
    paddingBottom: 22,
  },
  kaelSourceHeaderAura: {
    bottom: -74,
    height: 188,
    left: -42,
    opacity: 0.76,
    right: -54,
    top: -62,
  },
  kaelSourceHeaderCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 27,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 13,
    minHeight: 112,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.raised,
  },
  kaelSourceHeaderCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  kaelSourceHeaderIcon: {
    height: 42,
    position: 'relative',
    width: 42,
    zIndex: 1,
  },
  kaelSourceHeaderIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 21,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 64,
    zIndex: 1,
  },
  kaelSourceHeaderSubtitle: {
    color: color.text.muted,
    ...typography.caption1,
    fontWeight: '600',
  },
  kaelSourceHeaderTitle: {
    color: color.text.strong,
    ...typography.title2,
    fontWeight: '600',
  },
  workerSettingsDivider: {
    backgroundColor: 'rgba(176,222,214,0.36)',
    height: 1,
    marginHorizontal: 14,
  },
  workerSettingsForm: {
    gap: 10,
    paddingBottom: 10,
    paddingHorizontal: 4,
    paddingTop: 2,
  },
  workerSettingsInput: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
  },
  workerSettingsInputShell: {
    backgroundColor: 'rgba(255,255,255,0.84)',
    borderColor: 'rgba(176,222,214,0.54)',
    minHeight: 48,
  },
  workerSettingsInputShellError: {
    borderColor: 'rgba(39,189,166,0.48)',
  },
  workerSettingsListCard: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    gap: 8,
    overflow: 'hidden',
    padding: 10,
    position: 'relative',
    ...shadow.soft,
  },
  workerSettingsMessage: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  workerSettingsMessageError: {
    color: color.brand.primaryDark,
    ...typography.caption1,
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  workerSettingsSaveButton: {
    backgroundColor: 'rgba(219,247,239,0.64)',
    borderColor: 'rgba(39,189,166,0.28)',
    borderWidth: 1,
  },
  workerSettingsSaveButtonActive: {
    backgroundColor: color.brand.primary,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.title1,
    fontWeight: '600',
    marginTop: 8,
  },
  earningsHeroAura: {
    bottom: 'auto',
    height: 190,
    left: '34%',
    right: -70,
    top: -74,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 148,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  earningsHeroContent: {
    flex: 1,
    gap: 12,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  earningsHeroIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    ...typography.caption1,
    fontWeight: '600',
    marginTop: 3,
  },
  earningsHeroPill: {
    alignSelf: 'flex-start',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    ...typography.caption2,
    fontWeight: '600',
    maxWidth: '100%',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
  earningsHeroMainRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  earningsStatGrid: {
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  earningsStatLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    textAlign: 'center',
  },
  earningsStatTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderColor: 'rgba(255,255,255,0.88)',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 56,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 9,
  },
  earningsStatValue: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.subheadline,
    fontWeight: '600',
    textAlign: 'center',
  },
})
