// Worker UI copy dictionaries (VI/EN), extracted from worker-surfaces.tsx (C4 stage 3).
import type { WorkerVerificationStatus } from '@home-services/shared'
import { appCopy } from '@/lib/app-language'
import type { WorkerLanguageMode } from './types'

export const workerCopy = {
  vi: {
    frame: { availabilityOff: 'Tắt nhận việc', availabilityOn: 'Bật nhận việc', safe: 'An toàn', themeLight: 'Sáng', themeDark: 'Tối', lang: 'Đổi sang English' },
    nav: { chat: 'Nhắn', earnings: 'Tiền', home: 'Nhà', jobs: 'Việc', profile: 'Hồ sơ' },
    home: {
      eyebrow: 'Thợ',
      title: 'Ca trực',
      readinessTitle: 'Sẵn sàng nhận việc',
      readinessSubtitle: 'Trạng thái quyết định yêu cầu mới',
      readinessNoProfile: 'Hoàn tất hồ sơ thợ trước khi nhận yêu cầu mới.',
      readinessOnline: 'Bật nhận việc khi hồ sơ đã được duyệt và bạn đang rảnh.',
      readinessOffline: 'Tắt nhận việc khi đang bận hoặc chưa đủ điều kiện nhận yêu cầu.',
      readinessSuspended: 'Tài khoản đang tạm khóa. Tắt nhận việc và liên hệ hỗ trợ trước khi nhận yêu cầu mới.',
      readinessVerification: 'Xác minh',
      readinessAvailability: 'Khả dụng',
      readinessRequest: 'Yêu cầu mới',
      mapSearch: 'Chưa có khu vực',
      mapTitle: 'Điện, nước, vệ sinh',
      mapMeta: 'Chưa có yêu cầu',
      electric: 'Điện',
      water: 'Nước',
      status: 'Trạng thái',
      online: 'Chờ duyệt',
      today: 'Trạng thái',
      rating: 'Phản hồi',
      shiftTitle: 'Nhịp xử lý',
      shiftAction: '',
      phases: ['Kael gửi', 'Tóm tắt', 'Nhận việc', 'Di chuyển'],
      nextTitle: 'Yêu cầu',
      serviceHeading: '',
      serviceSkillLabel: 'Kỹ năng',
      serviceProfileTitle: 'Hồ sơ thợ',
      serviceProfileMeta: 'Chờ duyệt kỹ năng',
      servicePendingLabel: 'Chờ duyệt',
      electricianCard: 'Sửa điện',
      plumberCard: 'Sửa nước',
      cleaningCard: 'Vệ sinh',
    },
    request: {
      service: 'Chờ duyệt',
      title: 'Chưa có yêu cầu mới',
      area: 'Khu vực chung',
      briefTitle: 'Tóm tắt Kael',
      brief: ['Kael chưa chuyển yêu cầu mới.'],
      customerEstimate: 'Ước tính Kael',
      workerEarns: 'Thợ nhận',
      decline: 'Bỏ qua',
      accept: 'Nhận việc',
    },
    jobs: {
      eyebrow: 'Công việc',
      title: 'Yêu cầu',
      subtitle: 'Quyết định nhanh, giữ riêng tư địa chỉ',
      filters: ['Chờ nhận', 'Đang làm', 'Cần xử lý'],
      emptyStatus: 'Đang theo dõi',
      emptyTitle: 'Chưa có việc đang làm',
      emptyBody: 'Kael sẽ đưa yêu cầu mới vào đây khi phiếu đủ dữ liệu để điều phối.',
      waitingEmptyTitle: 'Chưa có yêu cầu mới',
      waitingEmptyBody: 'Yêu cầu mới sẽ hiện ở mục Chờ nhận.',
      activeEmptyTitle: 'Chưa nhận việc',
      activeEmptyBody: 'Việc đã nhận và Phòng việc sẽ hiện tại đây.',
      needsEmptyTitle: 'Không có mục chặn',
      needsEmptyBody: 'Phát sinh hoặc quyết định Kael sẽ hiện ở đây.',
      scopeStatus: 'Kael đang xét',
      scopeTitle: 'Thay đổi phạm vi',
      scopeBody: 'Kael đang xét phạm vi mới; khách có thể cung cấp thêm dữ liệu, khiếu nại hoặc hủy nếu thực tế chưa đúng.',
      jobRoomCta: 'Mở phòng việc',
    },
    chat: {
      eyebrow: 'Tin nhắn',
      title: 'Phòng việc',
      jobRoomTitle: 'Phòng việc Kael',
      relaySubtitle: 'Kael chuyển tiếp với khách',
      acceptedPill: 'Đã nhận',
      waitingTitle: 'Đang chờ Kael đưa việc',
      waitingBody: 'Khi Kael có phiếu đủ dữ liệu, Phòng việc sẽ mở tóm tắt công việc, khu vực chung và ghi chú việc.',
      waitingInput: 'Nhắn trong Phòng việc...',
      handoffTitle: 'Kael giao việc',
      privacyGate: 'Địa chỉ chi tiết chỉ mở sau khi thợ chấp nhận.',
      acceptedGate: 'Đã nhận việc. Ghi chú hiện lưu trong phiên này.',
      lockedGate: 'Chấp nhận việc để mở ghi chú việc.',
      attach: 'Đính kèm',
      attachHint: 'Đính kèm chưa mở trong Phòng việc này. Thợ ghi chú bằng chữ trước.',
      mic: 'Mic',
      micHint: 'Mic chưa sẵn sàng trong Phòng việc này. Thợ nhập ghi chú để Kael giữ bối cảnh trước.',
      serviceLabel: 'Dịch vụ',
      problemLabel: 'Vấn đề',
      areaLabel: 'Khu vực',
      statusLabel: 'Trạng thái',
      briefTitle: 'Tóm tắt Kael',
      briefBody: 'Kael giữ tóm tắt công việc và mốc an toàn trước khi thợ phản hồi.',
      emptyTitle: 'Chưa có tin nhắn',
      emptyBody: 'Tin nhắn chỉ mở khi có yêu cầu thật hoặc thợ đã nhận việc.',
      input: 'Nhập...',
      send: 'Gửi',
      sendErrorTitle: 'Chưa gửi được',
      sendErrorBody: 'Kael chưa lưu được tin nhắn. Thử lại sau.',
      worker: 'Thợ',
      kael: 'Kael',
    },
    earnings: {
      eyebrow: 'Thu nhập',
      title: 'Thu nhập',
      subtitle: 'Theo dõi tiền công dễ hiểu hơn',
      today: 'Hôm nay',
      month: 'Tháng này',
      noReconciliation: 'Chờ dữ liệu',
      // Honest empty-chart copy (shown when there is no settled earning).
      chartEmpty: 'Chưa có dữ liệu đối soát',
      summaryHint: 'Khi có đối soát',
      body: '',
      complete: 'Hoàn tất',
      waiting: 'Chờ Kael',
      ledgerTitle: 'Sổ đối soát',
      rows: [
        ['Sổ đối soát', appCopy.vi.common.noData],
        ['Tài khoản nhận tiền', 'Chưa lưu'],
      ],
    },
    profile: {
      eyebrow: 'Hồ sơ',
      title: 'Hồ sơ',
      name: 'Hồ sơ thợ',
      body: '',
      scoreTitle: 'Trạng thái hồ sơ',
      scoreBody: '',
      theme: 'Giao diện',
      language: 'Ngôn ngữ',
      skills: ['Chờ duyệt', 'Chưa có hồ sơ', 'Chờ phản hồi'],
      rows: [
        ['Xác minh danh tính', 'Chờ duyệt'],
        ['Kỹ năng dịch vụ', 'Chưa lưu hệ thống'],
        ['Khu vực làm việc', 'Chưa lưu hệ thống'],
      ],
    },
  },
  en: {
    frame: { availabilityOff: 'Go offline', availabilityOn: 'Go online', safe: 'Safe', themeLight: 'Light', themeDark: 'Dark', lang: 'Switch to Tiếng Việt' },
    nav: { chat: 'Chat', earnings: 'Pay', home: 'Home', jobs: 'Jobs', profile: 'Profile' },
    home: {
      eyebrow: 'Worker',
      title: 'Shift',
      readinessTitle: 'Ready for jobs',
      readinessSubtitle: 'Status that controls new jobs',
      readinessNoProfile: 'Complete your worker profile before receiving new requests.',
      readinessOnline: 'Go online when your profile is approved and you are available.',
      readinessOffline: 'Stay offline while busy or not eligible for new requests.',
      readinessSuspended: 'This account is suspended. Stay offline and contact support before receiving new requests.',
      readinessVerification: 'Verification',
      readinessAvailability: 'Availability',
      readinessRequest: 'New request',
      mapSearch: 'No area yet',
      mapTitle: 'Power, plumbing, cleaning',
      mapMeta: 'No request yet',
      electric: 'Power',
      water: 'Water',
      status: 'Status',
      online: 'Pending approval',
      today: 'Status',
      rating: 'Feedback',
      shiftTitle: 'Work rhythm',
      shiftAction: '',
      phases: ['Kael sent', 'Briefed', 'Accept', 'Travel'],
      nextTitle: 'Request',
      serviceHeading: '',
      serviceSkillLabel: 'Skill',
      serviceProfileTitle: 'Worker profile',
      serviceProfileMeta: 'Skills pending review',
      servicePendingLabel: 'Pending',
      electricianCard: 'Electrical',
      plumberCard: 'Plumbing',
      cleaningCard: 'Cleaning',
    },
    request: {
      service: 'Pending',
      title: 'No live request',
      area: 'General area',
      briefTitle: 'Kael brief',
      brief: ['Waiting for Kael to hand off a request.'],
      customerEstimate: 'Kael estimate',
      workerEarns: 'Worker earns',
      decline: 'Skip',
      accept: 'Accept',
    },
    jobs: {
      eyebrow: 'Jobs',
      title: 'Requests',
      subtitle: 'Decide quickly while address stays private',
      filters: ['Pending', 'Active', 'Needs review'],
      emptyStatus: 'Watching',
      emptyTitle: 'No active job',
      emptyBody: 'Kael will place new requests here when a ticket has enough data to orchestrate.',
      waitingEmptyTitle: 'No new request',
      waitingEmptyBody: 'New requests appear in the Pending tab.',
      activeEmptyTitle: 'No accepted job',
      activeEmptyBody: 'Accepted work and JobRoom appear here.',
      needsEmptyTitle: 'Nothing blocked',
      needsEmptyBody: 'Scope or Kael decision blockers appear here.',
      scopeStatus: 'Kael reviewing',
      scopeTitle: 'Scope change',
      scopeBody: 'Kael is reviewing the new scope; the customer can add evidence, appeal, or cancel if the facts are wrong.',
      jobRoomCta: 'Open JobRoom',
    },
    chat: {
      eyebrow: 'Chat',
      title: 'JobRoom',
      jobRoomTitle: 'Kael JobRoom',
      relaySubtitle: 'Kael relays with the customer',
      acceptedPill: 'Accepted',
      waitingTitle: 'Waiting for Kael to hand off a job',
      waitingBody: 'When Kael has enough ticket data, JobRoom opens the job brief, general area, and job notes.',
      waitingInput: 'Message in JobRoom...',
      handoffTitle: 'Kael handoff',
      privacyGate: 'Detailed address opens only after acceptance.',
      acceptedGate: 'Job accepted. Notes are saved for this session.',
      lockedGate: 'Accept the job to unlock job notes.',
      attach: 'Attach',
      attachHint: 'Attachments are not open in this JobRoom yet. Add a written note first.',
      mic: 'Mic',
      micHint: 'Voice input is not ready in this JobRoom yet. Type a note so Kael can keep context first.',
      serviceLabel: 'Service',
      problemLabel: 'Problem',
      areaLabel: 'Area',
      statusLabel: 'Status',
      briefTitle: 'Kael brief',
      briefBody: 'Kael keeps the job brief and safety context before worker replies.',
      emptyTitle: 'No messages yet',
      emptyBody: 'Messages open only for a real request or an accepted job.',
      input: 'Type...',
      send: 'Send',
      sendErrorTitle: 'Message not sent',
      sendErrorBody: 'Kael could not save this message. Try again.',
      worker: 'Worker',
      kael: 'Kael',
    },
    earnings: {
      eyebrow: 'Earnings',
      title: 'Earnings',
      subtitle: 'Track payout clearly',
      today: 'Today',
      month: 'This month',
      noReconciliation: 'Waiting for data',
      // Honest empty-chart copy (shown when there is no settled earning).
      chartEmpty: 'No reconciliation data yet',
      summaryHint: 'After reconciliation',
      body: '',
      complete: 'Completed',
      waiting: 'Waiting for Kael',
      ledgerTitle: 'Ledger',
      rows: [
        ['Ledger', appCopy.en.common.noData],
        ['Payout account', 'Not stored'],
      ],
    },
    profile: {
      eyebrow: 'Profile',
      title: 'Profile',
      name: 'Service profile',
      body: '',
      scoreTitle: 'Profile status',
      scoreBody: '',
      theme: 'Theme',
      language: 'Language',
      skills: ['Pending approval', 'No profile yet', 'Feedback pending'],
      rows: [
        ['Identity verification', 'Pending approval'],
        ['Service skills', 'Not stored yet'],
        ['Working area', 'Not stored yet'],
      ],
    },
  },
} as const

export const workerVerificationCopy = {
  vi: {
    kicker: 'Xác minh',
    title: 'Hồ sơ xác minh',
    legalName: 'Tên pháp lý',
    dateOfBirth: 'Ngày sinh',
    yearsExperience: 'Năm kinh nghiệm',
    districts: 'Khu vực làm việc',
    districtsPlaceholder: 'Khu vực làm việc, cách nhau bằng dấu phẩy',
    homeLat: 'Vĩ độ điểm xuất phát',
    homeLng: 'Kinh độ điểm xuất phát',
    serviceRadius: 'Bán kính km',
    serviceAreaTitle: 'Khu vực phục vụ',
    serviceAreaBody: 'Chọn quận làm điểm xuất phát để Kael ưu tiên việc gần khu vực bạn phục vụ.',
    serviceAreaManual: 'Bạn có thể đổi quận hoặc bán kính trước khi gửi hồ sơ.',
    radiusDecrease: 'Giảm bán kính phục vụ',
    radiusIncrease: 'Tăng bán kính phục vụ',
    radiusPreset: 'Chọn bán kính',
    problemSpecializations: 'Chuyên môn, cách nhau bằng dấu phẩy',
    bankName: 'Ngân hàng',
    bankAccount: 'Số tài khoản',
    selectSkill: 'Chọn kỹ năng',
    files: {
      cccdFront: 'CCCD mặt trước',
      cccdBack: 'CCCD mặt sau',
      selfie: 'Ảnh selfie',
      selectedFallback: 'đã chọn tệp',
      choose: 'Chọn',
    },
    submit: 'Gửi hồ sơ xác minh',
    submitting: 'Đang gửi...',
    permissionError: 'Cần quyền thư viện ảnh để chọn giấy tờ xác minh.',
    uploadError: 'Không thể tải hồ sơ xác minh. Kiểm tra kết nối và thử lại.',
    savedTitle: 'Đã gửi hồ sơ',
    savedBody: 'Đội vận hành sẽ duyệt hồ sơ trước khi bật nhận việc.',
    errors: {
      identity: 'Nhập tên pháp lý và ngày sinh theo YYYY-MM-DD.',
      work: 'Nhập kinh nghiệm, dịch vụ và khu vực làm việc.',
      bank: 'Nhập ngân hàng và số tài khoản nhận tiền.',
      files: 'Cần CCCD mặt trước, CCCD mặt sau và ảnh selfie.',
      submit: 'Hệ thống chưa nhận hồ sơ. Kiểm tra lại kết nối và thử lại.',
    },
    status: {
      approved: 'Đã duyệt',
      draft: 'Nháp',
      rejected: 'Cần bổ sung',
      submitted: 'Đã gửi',
      suspended: 'Tạm khóa',
      under_review: 'Đang duyệt',
    },
  },
  en: {
    kicker: 'Verification',
    title: 'Verification profile',
    legalName: 'Legal name',
    dateOfBirth: 'Date of birth',
    yearsExperience: 'Years of experience',
    districts: 'Work areas',
    districtsPlaceholder: 'Work areas, separated by commas',
    homeLat: 'Home latitude',
    homeLng: 'Home longitude',
    serviceRadius: 'Radius km',
    serviceAreaTitle: 'Service area',
    serviceAreaBody: 'Choose the district used as your starting anchor so Kael can prioritize nearby jobs.',
    serviceAreaManual: 'You can change the district or radius before submitting the profile.',
    radiusDecrease: 'Decrease service radius',
    radiusIncrease: 'Increase service radius',
    radiusPreset: 'Choose radius',
    problemSpecializations: 'Specializations, comma-separated',
    bankName: 'Bank',
    bankAccount: 'Account number',
    selectSkill: 'Select skill',
    files: {
      cccdFront: 'ID front',
      cccdBack: 'ID back',
      selfie: 'Selfie',
      selectedFallback: 'file selected',
      choose: 'Select',
    },
    submit: 'Submit verification',
    submitting: 'Submitting...',
    permissionError: 'Photo library permission is required to choose verification documents.',
    uploadError: 'Unable to upload verification files. Check your connection and try again.',
    savedTitle: 'Profile submitted',
    savedBody: 'Operations will review the profile before enabling live jobs.',
    errors: {
      identity: 'Enter legal name and date of birth as YYYY-MM-DD.',
      work: 'Enter experience, services, and work areas.',
      bank: 'Enter bank and payout account number.',
      files: 'ID front, ID back, and selfie are required.',
      submit: 'The system did not receive the profile. Check your connection and try again.',
    },
    status: {
      approved: 'Approved',
      draft: 'Draft',
      rejected: 'Needs update',
      submitted: 'Submitted',
      suspended: 'Suspended',
      under_review: 'Under review',
    },
  },
} as const
export type WorkerVerificationCopy = {
  bankAccount: string
  bankName: string
  dateOfBirth: string
  districts: string
  districtsPlaceholder: string
  errors: Record<'bank' | 'files' | 'identity' | 'submit' | 'work', string>
  files: Record<'cccdBack' | 'cccdFront' | 'choose' | 'selectedFallback' | 'selfie', string>
  homeLat: string
  homeLng: string
  kicker: string
  legalName: string
  permissionError: string
  problemSpecializations: string
  radiusDecrease: string
  radiusIncrease: string
  radiusPreset: string
  savedBody: string
  savedTitle: string
  selectSkill: string
  serviceAreaBody: string
  serviceAreaManual: string
  serviceAreaTitle: string
  serviceRadius: string
  status: Record<WorkerVerificationStatus, string>
  submit: string
  submitting: string
  title: string
  uploadError: string
  yearsExperience: string
}

export const workerActionCopy = {
  vi: {
    hiddenAddress: 'ẩn địa chỉ chi tiết',
    completionNote: 'Ghi chú hoàn tất',
    completionPhoto: 'Ảnh nghiệm thu',
    completionPhotoRequired: 'Cần ít nhất 1 ảnh nghiệm thu',
    completionPhotoCount: (count: number) => `${count} ảnh đã chọn`,
    addCompletionPhoto: 'Thêm ảnh',
    completeLater: 'Để sau',
    scopeDescription: 'Mô tả phần phát sinh',
    scopePhotoOptional: 'Ảnh bằng chứng phát sinh nếu có',
    scopePhotoCount: (count: number) => `${count} ảnh phát sinh đã chọn`,
    addScopePhoto: 'Thêm ảnh phát sinh',
    scopeSubmit: 'Yêu cầu đổi phạm vi',
    scopeWaiting: 'Chờ Kael quyết định thay đổi phạm vi.',
    uploading: 'Đang tải ảnh...',
    cancelReason: 'Lý do cần hủy',
    cancelPlaceholder: 'Lý do hủy và tìm thợ thay thế',
    cancelSubmit: 'Yêu cầu hủy có lý do',
    review: 'Kiểm tra lại',
    send: 'Gửi',
    progress: {
      worker_start_travel: 'Bắt đầu di chuyển',
      worker_mark_arrived: 'Đã đến nơi',
      worker_start_inspection: 'Bắt đầu kiểm tra',
      worker_start_repair: 'Bắt đầu sửa',
      worker_complete_job: 'Báo hoàn tất',
    },
    alerts: {
      completionNoteRequiredTitle: 'Cần ghi chú hoàn tất',
      completionNoteRequiredBody: 'Nhập ghi chú ngắn về việc đã làm trước khi báo hoàn tất.',
      completionPhotoRequiredTitle: 'Cần ảnh nghiệm thu',
      completionPhotoRequiredBody: 'Thêm ít nhất một ảnh sau sửa để giữ chuỗi bằng chứng đầy đủ.',
      completionUploadTitle: 'Chưa tải được ảnh',
      completionPermissionTitle: 'Cần quyền chọn ảnh',
      completionPermissionBody: 'Cho phép truy cập ảnh để thêm ảnh nghiệm thu.',
      completeTitle: 'Xác nhận báo hoàn tất?',
      completeBody: 'Kael sẽ kiểm tra bằng chứng hoàn tất và tự chuyển sang bước phù hợp. Thanh toán vẫn khóa ở giai đoạn này.',
      scopeDescriptionTitle: 'Cần mô tả phạm vi mới',
      scopeDescriptionBody: 'Nhập rõ phần phát sinh để Kael quyết định từ bằng chứng.',
      scopeUploadTitle: 'Chưa tải được ảnh phát sinh',
      scopePermissionTitle: 'Cần quyền chọn ảnh',
      scopePermissionBody: 'Cho phép truy cập ảnh để thêm bằng chứng phát sinh.',
      scopeConfirmTitle: 'Gửi yêu cầu đổi phạm vi?',
      scopeConfirmBody: 'Hệ thống sẽ khóa tiến độ cho tới khi Kael ra quyết định phạm vi.',
      cancelReasonTitle: 'Cần lý do hủy',
      cancelReasonBody: 'Nhập lý do cụ thể. Hệ thống sẽ hủy lượt nhận việc này và bắt đầu tìm thợ thay thế sau khi gửi.',
      cancelConfirmTitle: 'Gửi yêu cầu hủy việc?',
      cancelConfirmBody: 'Sau khi gửi, lượt nhận việc của bạn sẽ được hủy và hệ thống tự động tìm thợ thay thế cho khách.',
      arrivalCheckInTitle: 'Xác nhận đã tới sảnh?',
      arrivalCheckInBody: 'Thêm 1 ảnh sảnh hoặc cửa tòa nhà để check-in. Số căn hộ chính xác chỉ mở sau khi khách bấm "Cho thợ lên".',
      arrivalPickPhoto: 'Thêm ảnh sảnh',
      arrivalSkip: 'Tiếp tục không check-in',
      arrivalSkipConfirmTitle: 'Bỏ qua check-in?',
      arrivalSkipConfirmBody: 'Không check-in thì khách không thể mở số căn hộ trong app — bạn sẽ cần gặp khách ở sảnh.',
      arrivalSkipConfirmCta: 'Vẫn báo đã đến',
      arrivalPermissionTitle: 'Cần quyền chọn ảnh',
      arrivalPermissionBody: 'Cho phép truy cập ảnh để thêm ảnh check-in tại sảnh.',
      arrivalUploadTitle: 'Chưa tải được ảnh check-in',
    },
  },
  en: {
    hiddenAddress: 'detailed address hidden',
    completionNote: 'Completion note',
    completionPhoto: 'Completion photo',
    completionPhotoRequired: 'At least 1 completion photo required',
    completionPhotoCount: (count: number) => `${count} photo${count === 1 ? '' : 's'} selected`,
    addCompletionPhoto: 'Add photo',
    completeLater: 'Later',
    scopeDescription: 'New scope details',
    scopePhotoOptional: 'Scope evidence photos optional',
    scopePhotoCount: (count: number) => `${count} scope photo${count === 1 ? '' : 's'} selected`,
    addScopePhoto: 'Add scope photo',
    scopeSubmit: 'Request scope change',
    scopeWaiting: 'Waiting for Kael to decide on the scope change.',
    uploading: 'Uploading photos...',
    cancelReason: 'Cancellation reason',
    cancelPlaceholder: 'Reason for replacement search',
    cancelSubmit: 'Request cancellation',
    review: 'Review',
    send: 'Send',
    progress: {
      worker_start_travel: 'Start travel',
      worker_mark_arrived: 'Mark arrived',
      worker_start_inspection: 'Start inspection',
      worker_start_repair: 'Start repair',
      worker_complete_job: 'Mark complete',
    },
    alerts: {
      completionNoteRequiredTitle: 'Completion note required',
      completionNoteRequiredBody: 'Add a short note about the completed work before marking the job complete.',
      completionPhotoRequiredTitle: 'Completion photo required',
      completionPhotoRequiredBody: 'Add at least one after-repair photo to keep the evidence trail complete.',
      completionUploadTitle: 'Photo upload failed',
      completionPermissionTitle: 'Photo permission required',
      completionPermissionBody: 'Allow photo access to add completion evidence.',
      completeTitle: 'Mark job complete?',
      completeBody: 'Kael will review the completion evidence and either confirm completion or open a dispute. Payment remains locked at this stage.',
      scopeDescriptionTitle: 'New scope details required',
      scopeDescriptionBody: 'Describe the added work so Kael can decide from the evidence.',
      scopeUploadTitle: 'Scope photo upload failed',
      scopePermissionTitle: 'Photo permission required',
      scopePermissionBody: 'Allow photo access to add scope-change evidence.',
      scopeConfirmTitle: 'Send scope change request?',
      scopeConfirmBody: 'Progress stays locked until Kael decides the scope change.',
      cancelReasonTitle: 'Cancellation reason required',
      cancelReasonBody: 'Enter a specific reason. The system will cancel this worker assignment and begin replacement search after you send.',
      cancelConfirmTitle: 'Send cancellation request?',
      cancelConfirmBody: 'After you send, this worker assignment will be cancelled and the system will automatically search for a replacement.',
      arrivalCheckInTitle: 'Confirm lobby arrival?',
      arrivalCheckInBody: 'Add one lobby or building-entrance photo to check in. The exact unit number unlocks only after the customer taps "Let the worker up".',
      arrivalPickPhoto: 'Add lobby photo',
      arrivalSkip: 'Continue without check-in',
      arrivalSkipConfirmTitle: 'Skip check-in?',
      arrivalSkipConfirmBody: 'Without a check-in the customer cannot release the exact unit in-app — you will need to meet them in the lobby.',
      arrivalSkipConfirmCta: 'Mark arrived anyway',
      arrivalPermissionTitle: 'Photo permission required',
      arrivalPermissionBody: 'Allow photo access to add the lobby check-in photo.',
      arrivalUploadTitle: 'Check-in photo upload failed',
    },
  },
} as const

export const mapPreview = {
  replaceWithProvider: 'google-maps-camera-ready',
}

export type WorkerCopy = (typeof workerCopy)[WorkerLanguageMode]
