// Worker UI StyleSheet, extracted verbatim from worker-surfaces.tsx (C4 staged split).
import { Platform, StyleSheet } from 'react-native'
import { workerDockHeight, workerFrameHorizontalPadding } from './constants'

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  inactiveRouteSurface: { display: 'none' },
  canvas: { alignItems: 'center', flex: 1, overflow: 'hidden' },
  workerScroll: { flex: 1, overflowAnchor: 'none', width: '100%' } as any,
  workerStandaloneScroll: { overflow: 'hidden' } as any,
  backdropWarm: { borderRadius: 30, bottom: 72, height: 148, left: -98, opacity: 0.12, position: 'absolute', transform: [{ rotate: '12deg' }], width: 210 },
  backdropMint: { borderRadius: 36, height: 226, opacity: 0.18, position: 'absolute', right: -126, top: 54, width: 294 },
  backdropCyan: { borderRadius: 30, height: 148, left: -96, opacity: 0.1, position: 'absolute', top: 200, transform: [{ rotate: '-10deg' }], width: 220 },
  sectionMotionField: { bottom: 0, overflow: 'hidden', position: 'absolute', top: 0, zIndex: 0 },
  sectionMotionRibbon: { borderRadius: 34, height: 760, left: 18, position: 'absolute', width: 62 },
  sectionMotionWash: { borderRadius: 34, height: 178, position: 'absolute', right: -92, width: 224 },
  sectionMotionCaustic: { borderRadius: 30, bottom: 84, height: 118, left: -104, position: 'absolute', width: 268 },
  sectionMotionGlint: { bottom: 52, height: 260, left: '50%', position: 'absolute', width: 34 },
  scrollContent: { gap: 12, paddingHorizontal: workerFrameHorizontalPadding, paddingTop: 8, zIndex: 2 },
  standaloneScrollContent: { overflow: 'visible' } as any,
  kicker: { fontSize: 12, fontWeight: '600', letterSpacing: 0 },
  screenSubtitle: { fontSize: 12, fontWeight: '700', letterSpacing: 0, lineHeight: 16 },
  screenTitle: { fontSize: 25, fontWeight: '700', letterSpacing: 0, lineHeight: 27 },
  workerTopRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 47, paddingTop: 0 },
  screenHeaderAction: { alignItems: 'center', borderRadius: 18, borderWidth: 1, height: 46, justifyContent: 'center', width: 46 },
  screenHeaderPill: { borderCurve: 'continuous', borderRadius: 999, borderWidth: 1, flexShrink: 0, fontSize: 12, fontWeight: '700', lineHeight: 14, maxWidth: 126, overflow: 'hidden', paddingHorizontal: 11, paddingVertical: 8 },
  glassTopHighlight: { height: 1, left: 16, opacity: 0.82, position: 'absolute', right: 16, top: 0, zIndex: 0 },
  liquidSharpKeyline: { borderCurve: 'continuous', borderRadius: 24, borderWidth: 1, bottom: 0, left: 0, opacity: 0.92, position: 'absolute', right: 0, top: 0, zIndex: 1 },
  liquidSharpKeylinePanel: { borderRadius: 24 },
  liquidSharpKeylineSheet: { borderRadius: 32 },
  liquidSpecularBand: { height: 88, left: -62, position: 'absolute', right: -62, top: -28, transform: [{ rotate: '-8deg' }], zIndex: 0 },
  liquidSpecularBandPanel: { height: 78, top: -22 },
  liquidRefractionPool: { borderRadius: 999, height: 164, opacity: 0.74, position: 'absolute', right: -76, top: 18, width: 230, zIndex: 0 },
  liquidRefractionPoolPanel: { height: 132, right: -58, top: -8, width: 178 },
  liquidPanelGlassOverlay: { borderCurve: 'continuous', borderRadius: 24, bottom: 0, left: 0, position: 'absolute', right: 0, top: 0, zIndex: 0 },
  liquidPanelGlassOverlaySheet: { borderRadius: 32 },
  workerHomeMaterialDepthPlane: { borderCurve: 'continuous', borderRadius: 24, bottom: 0, left: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0, zIndex: 0 },
  workerHomeMaterialDepthPlaneSheet: { borderRadius: 32 },
  workerHomeMaterialSubstrate: { borderCurve: 'continuous', borderRadius: 24, bottom: 0, left: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0, zIndex: 0 },
  workerHomeMaterialSubstrateReadiness: { borderRadius: 24 },
  workerHomeMaterialTopEdge: { height: 1.5, left: 18, position: 'absolute', right: 18, top: 1, zIndex: 2 },
  workerHomeMaterialTopEdgeReadiness: { left: 20, right: 20, top: 1 },
  workerHomeMaterialBottomEdge: { bottom: 1, height: 1, left: 24, position: 'absolute', right: 24, zIndex: 2 },
  workerHomeMaterialBottomEdgeReadiness: { bottom: 1, left: 22, right: 22 },
  workerHomeMapMaterialContours: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0, zIndex: 0 },
  glassSheen: { height: '170%', left: -72, opacity: 0.42, position: 'absolute', top: -46, transform: [{ rotate: '11deg' }], width: 58, zIndex: 0 },
  glassMotionRibbon: { borderRadius: 999, height: 168, left: 16, position: 'absolute', top: -168, width: 58, zIndex: 0 },
  glassMotionRibbonCompact: { height: 118, left: 8, top: -118, width: 38 },
  glassMotionCore: { borderRadius: 999, height: 118, left: 56, position: 'absolute', top: -118, width: 13, zIndex: 0 },
  glassMotionCoreCompact: { height: 86, left: 36, top: -86, width: 9 },
  mapStage: { borderCurve: 'continuous', borderRadius: 24, minHeight: 196, overflow: 'hidden', padding: 0, position: 'relative' },
  workerMapPreviewPressable: { borderCurve: 'continuous', borderRadius: 24, overflow: 'hidden' },
  workerHomeMapNavigationCta: { alignItems: 'center', borderCurve: 'continuous', borderRadius: 16, justifyContent: 'center', marginBottom: 12, marginHorizontal: 12, marginTop: 10, minHeight: 44, paddingHorizontal: 14, position: 'relative', zIndex: 5 },
  workerMapTopHud: { flexDirection: 'row', gap: 8, left: 12, maxWidth: '78%', position: 'absolute', top: 12, zIndex: 4 },
  searchPill: { alignItems: 'center', borderRadius: 999, flexDirection: 'row', gap: 8, minHeight: 38, paddingHorizontal: 12 },
  searchText: { flex: 1, fontSize: 15, fontWeight: '600' },
  mapViewport: { borderCurve: 'continuous', borderRadius: 24, minHeight: 196, overflow: 'hidden', position: 'relative' },
  workerMapControlStack: { gap: 8, position: 'absolute', right: 12, top: 12, zIndex: 6 },
  workerMapControlStackExpanded: { right: 14, top: 14 },
  workerMapControlButton: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.88)', borderColor: 'rgba(31,103,93,0.16)', borderCurve: 'continuous', borderRadius: 14, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  workerMapControlButtonKeyline: { borderCurve: 'continuous', borderRadius: 13, borderWidth: 1, bottom: 2, left: 2, position: 'absolute', right: 2, top: 2 },
  workerMapControlButtonActive: { backgroundColor: 'rgba(220,251,243,0.95)' },
  workerMapZoomLayer: { ...StyleSheet.absoluteFillObject },
  workerMapModalBackdrop: {
    backgroundColor: 'rgba(5,19,17,0.46)',
    bottom: Platform.OS === 'web' ? 0 : undefined,
    flex: 1,
    justifyContent: 'flex-end',
    left: Platform.OS === 'web' ? 0 : undefined,
    padding: 12,
    position: Platform.OS === 'web' ? 'fixed' as any : undefined,
    right: Platform.OS === 'web' ? 0 : undefined,
    top: Platform.OS === 'web' ? 0 : undefined,
    zIndex: Platform.OS === 'web' ? 1000 : undefined,
  },
  workerMapModalSheet: { borderRadius: 28, gap: 12, maxHeight: '92%', paddingBottom: 16, paddingHorizontal: 16, paddingTop: 14 },
  workerMapExpandedHeader: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between', paddingHorizontal: 2 },
  workerMapCloseButton: { alignItems: 'center', borderRadius: 999, borderWidth: 1, flexShrink: 0, height: 38, justifyContent: 'center', marginRight: 12, width: 38 },
  workerExpandedMapViewport: { borderCurve: 'continuous', borderRadius: 24, minHeight: 520, overflow: 'hidden', position: 'relative' },
  expandedMapVeil: { height: 210, left: '58%', opacity: 0.2, top: 102, width: 210 },
  expandedMapMarkerZone: { right: '14%', top: '28%' },
  expandedMapMarkerWorker: { left: '20%', top: '68%' },
  workerMapRouteSummary: { borderRadius: 18, borderWidth: 1, bottom: 36, gap: 4, left: 36, paddingHorizontal: 11, paddingVertical: 6, position: 'absolute', right: 36, zIndex: 8 },
  workerMapSummaryHeader: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  workerMapSummaryBadge: { borderRadius: 999, borderWidth: 1, flexShrink: 0, paddingHorizontal: 8, paddingVertical: 5 },
  workerMapSummaryActions: { flexDirection: 'row', gap: 10 },
  workerMapSummaryButton: { alignItems: 'center', borderRadius: 15, flex: 1, justifyContent: 'center', minHeight: 42, paddingHorizontal: 14 },
  workerMapSummaryButtonSecondary: { borderWidth: 1 },
  mapRouteSummaryTitle: { fontSize: 14.5, fontWeight: '700', letterSpacing: 0, lineHeight: 16 },
  mapRouteSummaryDetail: { fontSize: 11, fontWeight: '700', lineHeight: 13, marginTop: 1 },
  mapRouteSummaryNote: { fontSize: 10, fontWeight: '600', lineHeight: 12, marginTop: 0 },
  compactPresenceMap: { borderCurve: 'continuous', borderRadius: 28, minHeight: 194, overflow: 'hidden', padding: 10, position: 'relative' },
  compactPresenceMapDense: { borderRadius: 24, minHeight: 152, padding: 8 },
  workerJobsMapCrispShell: { borderCurve: 'continuous', borderRadius: 28, borderWidth: 1, bottom: 0, left: 0, opacity: 0.92, position: 'absolute', right: 0, top: 0, zIndex: 6 },
  workerJobsMapCrispShellDense: { borderRadius: 24 },
  workerJobsMapTopEdge: { borderRadius: 999, height: 1, left: 18, opacity: 0.78, position: 'absolute', right: 18, top: 1, zIndex: 7 },
  compactMapViewport: { borderRadius: 24, minHeight: 174, overflow: 'hidden', position: 'relative' },
  compactMapViewportDense: { borderRadius: 20, minHeight: 136 },
  compactMapControlMini: { alignItems: 'center', borderRadius: 999, height: 34, justifyContent: 'center', position: 'absolute', right: 14, top: 14, width: 34, zIndex: 5 },
  compactMapVeil: { left: '54%', opacity: 0.24, top: 42 },
  compactMapMarker: { alignItems: 'center', borderRadius: 999, height: 38, justifyContent: 'center', overflow: 'visible', position: 'absolute', width: 38, zIndex: 4 },
  compactMapMarkerEmpty: { opacity: 0.92 },
  compactMapMarkerZone: { right: '18%', top: '34%' },
  compactMapMarkerWorker: { left: '31%', top: '48%' },
  mapFogTop: { height: 68, left: 0, opacity: 0.06, position: 'absolute', right: 0, top: 0 },
  mapFogBottom: { bottom: -6, height: 62, left: 0, opacity: 0.08, position: 'absolute', right: 0 },
  mapCyanVeil: { borderRadius: 999, height: 158, left: '52%', marginLeft: -79, opacity: 0.23, position: 'absolute', top: 94, width: 158 },
  mapCyanVeilLiquid: { opacity: 0.13 },
  mapLiquidLens: { height: 214, left: '-10%', opacity: 0.36, position: 'absolute', right: '-18%', top: -30, transform: [{ rotate: '-10deg' }], zIndex: 2 },
  mapLiquidSpecularArc: { borderRadius: 999, borderWidth: 1, height: 164, left: '26%', opacity: 0.42, position: 'absolute', top: 22, transform: [{ rotate: '-8deg' }], width: 250, zIndex: 2 },
  mapLiquidGlassOverlay: { borderCurve: 'continuous', borderRadius: 24, bottom: 0, left: 0, position: 'absolute', right: 0, top: 0, zIndex: 3 },
  mapLiquidGlassOverlayExpanded: { borderRadius: 24 },
  mapLiquidGlassEdge: { borderCurve: 'continuous', borderRadius: 24, borderWidth: 1, bottom: 1, left: 1, position: 'absolute', right: 1, top: 1, zIndex: 3 },
  mapSharpInset: { borderCurve: 'continuous', borderRadius: 24, borderWidth: 1, bottom: 0, left: 0, opacity: 0.94, position: 'absolute', right: 0, top: 0, zIndex: 3 },
  homeMapMarker: { alignItems: 'center', borderRadius: 999, height: 38, justifyContent: 'center', overflow: 'visible', position: 'absolute', width: 38, zIndex: 4 },
  workerMapPulseMarker: { alignItems: 'center', height: 34, justifyContent: 'center', width: 34 },
  workerMapPulseHalo: { borderRadius: 999, height: 28, position: 'absolute', width: 28 },
  workerMapPulseCore: { borderRadius: 999, borderWidth: 3, height: 14, width: 14 },
  homeMapZoneRing: { borderRadius: 999, height: 136, left: '22%', opacity: 0.22, position: 'absolute', top: '34%', width: 136, zIndex: 1 },
  homeMapZoneRingLiquid: { opacity: 0.16 },
  homeMapZoneHalo: { borderRadius: 999, height: 102, opacity: 0.24, position: 'absolute', width: 102 },
  mapChipTop: { left: 6, position: 'absolute', top: 15 },
  mapZonePill: { borderRadius: 22, left: 6, maxWidth: '64%', paddingHorizontal: 12, paddingVertical: 9, position: 'absolute', top: 9 },
  mapChipTitle: { fontSize: 14, fontWeight: '700', letterSpacing: 0 },
  mapCardsRow: { flexDirection: 'row', gap: 12, marginTop: -56, zIndex: 5 },
  mapFeatureCard: { borderRadius: 22, flex: 1, minHeight: 100, overflow: 'hidden', padding: 13, position: 'relative' },
  mapFeatureTitle: { fontSize: 17, fontWeight: '600', letterSpacing: 0 },
  mapFeatureMeta: { fontSize: 11, fontWeight: '600', lineHeight: 14, marginTop: 4 },
  mapFeatureIcon: { alignItems: 'center', borderRadius: 999, bottom: 12, height: 50, justifyContent: 'center', position: 'absolute', right: 12, width: 50 },
  shiftCard: { borderCurve: 'continuous', borderRadius: 24, gap: 10, overflow: 'hidden', padding: 14, position: 'relative' },
  shiftActionRow: { flexDirection: 'row', gap: 10 },
  rowBetween: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', position: 'relative', zIndex: 2 },
  identityRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  jobPanelImageIcon: { flexShrink: 0 },
  titleStack: { flex: 1, gap: 4, position: 'relative', zIndex: 2 },
  heroTitle: { fontSize: 18, fontWeight: '600', letterSpacing: 0 },
  bodyText: { fontSize: 13, fontWeight: '600', lineHeight: 18 },
  toggleTrack: { borderRadius: 999, borderWidth: 1, height: 32, overflow: 'hidden', position: 'relative', width: 58 },
  toggleLiquidFill: { borderRadius: 999, bottom: 3, left: 3, position: 'absolute', top: 3, width: 52, zIndex: 0 },
  toggleTrackKeyline: { borderRadius: 999, borderWidth: 1, bottom: 1, left: 1, position: 'absolute', right: 1, top: 1, zIndex: 1 },
  toggleKnob: { borderRadius: 999, borderWidth: 1, height: 24, left: 4, position: 'absolute', top: 4, width: 24, zIndex: 2 },
  workerImageIconStage: { alignItems: 'center', justifyContent: 'center', overflow: 'visible' },
  workerServiceGrid: { flexDirection: 'row', gap: 10 },
  workerServiceTile: { borderCurve: 'continuous', borderRadius: 22, borderWidth: 1, flex: 1, minHeight: 122, overflow: 'hidden', padding: 11, position: 'relative' },
  workerServiceIcon: { alignItems: 'center', borderRadius: 16, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  operationalTileKeyline: { borderCurve: 'continuous', borderRadius: 21, borderWidth: 1, bottom: 1, left: 1, opacity: 0.72, position: 'absolute', right: 1, top: 1, zIndex: 5 },
  workerServiceImageStage: { alignItems: 'center', alignSelf: 'stretch', borderCurve: 'continuous', borderRadius: 18, borderWidth: 1, height: 58, justifyContent: 'center', marginBottom: 2, marginTop: -2, overflow: 'visible', position: 'relative' },
  workerServiceTitle: { fontSize: 14, fontWeight: '700', letterSpacing: 0, lineHeight: 16, marginTop: 2 },
  workerServiceMeta: { fontSize: 10, fontWeight: '700', letterSpacing: 0, marginTop: 3 },
  workerMiniGrid: { flexDirection: 'row', gap: 10 },
  workerMiniCard: { borderCurve: 'continuous', borderRadius: 22, borderWidth: 1, flex: 1, gap: 4, minHeight: 98, overflow: 'hidden', padding: 11, position: 'relative' },
  workerMiniIcon: { alignItems: 'center', borderRadius: 16, borderWidth: 1, height: 38, justifyContent: 'center', marginBottom: 3, width: 38 },
  workerMiniImageStage: { alignItems: 'center', borderCurve: 'continuous', borderRadius: 17, borderWidth: 1, height: 54, justifyContent: 'center', marginBottom: 4, marginLeft: -1, overflow: 'visible', position: 'relative', width: 58 },
  workerOperationalIconAura: { borderRadius: 23, bottom: -7, left: -7, opacity: 0.72, position: 'absolute', right: -7, top: -7, zIndex: 0 },
  workerOperationalIconContent: { alignItems: 'center', justifyContent: 'center', position: 'relative', zIndex: 1 },
  workerMiniImageWrap: { alignSelf: 'flex-start', marginBottom: 2, marginLeft: -2 },
  workerMiniTitle: { fontSize: 15.5, fontWeight: '600', letterSpacing: 0, lineHeight: 18 },
  workerMiniMeta: { fontSize: 10.5, fontWeight: '700', letterSpacing: 0, lineHeight: 14 },
  metricRow: { flexDirection: 'row', gap: 8 },
  metric: { alignItems: 'center', borderRadius: 15, borderWidth: 1, flex: 1, gap: 1, justifyContent: 'center', minHeight: 40, overflow: 'hidden', padding: 6, position: 'relative' },
  metricValue: { fontSize: 15, fontVariant: ['tabular-nums'], fontWeight: '600', position: 'relative', textAlign: 'center', zIndex: 2 },
  metricLabel: { fontSize: 10, fontWeight: '500', position: 'relative', textAlign: 'center', zIndex: 2 },
  requestSheet: { borderRadius: 32, gap: 8, marginTop: -2, overflow: 'hidden', padding: 14, position: 'relative' },
  requestSheetCompact: { marginTop: 0 },
  readinessBadge: { alignItems: 'center', borderRadius: 18, borderWidth: 1, height: 46, justifyContent: 'center', width: 46 },
  serviceBadge: { alignItems: 'center', borderRadius: 999, flexDirection: 'row', gap: 6, minHeight: 34, paddingHorizontal: 10 },
  serviceBadgeText: { fontSize: 13, fontWeight: '600' },
  countdownRing: { alignItems: 'center', borderRadius: 999, borderWidth: 3, justifyContent: 'center', minHeight: 38, minWidth: 70, paddingHorizontal: 10 },
  countdownText: { fontSize: 13, fontVariant: ['tabular-nums'], fontWeight: '600' },
  requestTitle: { fontSize: 19, fontWeight: '600', letterSpacing: 0, lineHeight: 25 },
  areaRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  areaText: { fontSize: 14, fontWeight: '600' },
  kaelBrief: { borderRadius: 23, gap: 6, padding: 10 },
  kaelMini: { borderRadius: 999, borderWidth: 1, height: 29, width: 29 },
  kaelHead: { borderRadius: 999, borderWidth: 1, height: 48, width: 48 },
  kaelBriefTitle: { fontSize: 14, fontWeight: '600' },
  briefItem: { alignItems: 'flex-start', flexDirection: 'row', gap: 8 },
  briefDot: { borderRadius: 999, height: 5, marginTop: 7, width: 5 },
  briefText: { flex: 1, fontSize: 12, fontWeight: '600', lineHeight: 16 },
  priceRow: { flexDirection: 'row', gap: 8 },
  priceDisclaimer: { fontSize: 11, fontWeight: '600', lineHeight: 15 },
  scopeRequestBox: { gap: 8 },
  actionRow: { flexDirection: 'row', gap: 9, position: 'relative', zIndex: 2 },
  pressButton: { alignItems: 'center', borderCurve: 'continuous', borderRadius: 17, flex: 1, justifyContent: 'center', minHeight: 48, overflow: 'hidden', position: 'relative' },
  emptyActionPill: { alignItems: 'center', borderRadius: 17, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 48 },
  pressButtonPressedPrimary: { filter: Platform.OS === 'web' ? 'brightness(0.98)' : undefined } as any,
  pressButtonSecondary: { borderRadius: 15, minHeight: 44 },
  liquidButtonSheen: { height: 78, left: -34, opacity: 0.72, position: 'absolute', top: -18, transform: [{ rotate: '-12deg' }], width: 118, zIndex: 1 },
  disabledButton: { opacity: 0.52 },
  disabledButtonLiquid: { opacity: 1 },
  pressButtonTextPrimary: { fontSize: 14, fontWeight: '700', position: 'relative', zIndex: 2 },
  pressButtonTextSecondary: { fontSize: 13, fontWeight: '700', position: 'relative', zIndex: 2 },
  workerJobsLiquidSection: { marginTop: 10, overflow: 'visible', position: 'relative' },
  workerJobsLiquidContent: { gap: 12, position: 'relative', zIndex: 2 },
  workerJobsSectionWash: { borderCurve: 'continuous', borderRadius: 30, bottom: -10, left: -8, opacity: 0.86, position: 'absolute', right: -8, top: -10, zIndex: 0 },
  workerJobsSectionReflection: { borderRadius: 999, height: 96, left: -42, opacity: 0.50, position: 'absolute', right: -42, top: -30, transform: [{ rotate: '-7deg' }], zIndex: 0 },
  workerJobsSectionBottomLens: { borderRadius: 999, bottom: -46, height: 118, left: '18%', opacity: 0.54, position: 'absolute', right: '8%', zIndex: 0 },
  workerJobsSectionCrispShell: { borderCurve: 'continuous', borderRadius: 30, borderWidth: 1, bottom: -8, left: -6, opacity: 0.82, position: 'absolute', right: -6, top: -8, zIndex: 1 },
  workerJobsSectionTopEdge: { borderRadius: 999, height: 1, left: 18, opacity: 0.72, position: 'absolute', right: 18, top: -7, zIndex: 1 },
  workerJobsCardDepthPlane: { borderCurve: 'continuous', borderRadius: 24, bottom: 0, left: 0, opacity: 0.76, overflow: 'hidden', position: 'absolute', right: 0, top: 0, zIndex: 0 },
  workerJobsCardRefraction: { borderRadius: 999, height: 132, opacity: 0.62, position: 'absolute', right: -48, top: -28, width: 178, zIndex: 1 },
  workerJobsCardTopEdge: { borderRadius: 999, height: 1, left: 18, opacity: 0.70, position: 'absolute', right: 18, top: 1, zIndex: 4 },
  workerJobsCardCrispShell: { borderCurve: 'continuous', borderRadius: 24, borderWidth: 1, bottom: 0, left: 0, opacity: 0.92, position: 'absolute', right: 0, top: 0, zIndex: 6 },
  workerJobsCardInnerInset: { borderCurve: 'continuous', borderRadius: 20, borderWidth: 1, bottom: 4, left: 4, opacity: 0.58, position: 'absolute', right: 4, top: 4, zIndex: 6 },
  workerJobsCardBottomEdge: { borderRadius: 999, bottom: 1, height: 1, left: 20, opacity: 0.62, position: 'absolute', right: 20, zIndex: 7 },
  operationalBand: { flexDirection: 'row', gap: 12 },
  quickPanel: { borderRadius: 25, flex: 1, gap: 5, minHeight: 132, overflow: 'hidden', padding: 14, position: 'relative' },
  quickValue: { fontSize: 23, fontVariant: ['tabular-nums'], fontWeight: '600' },
  quickTitle: { fontSize: 14, fontWeight: '600' },
  sectionTitle: { fontSize: 18, fontWeight: '600' },
  sectionAction: { fontSize: 13, fontWeight: '600' },
  timelineCard: { borderRadius: 27, gap: 12, overflow: 'hidden', padding: 15, position: 'relative' },
  timelineItem: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  timelineRail: { borderRadius: 999, height: 10, width: 10 },
  timelineText: { fontSize: 14, fontWeight: '600' },
  segmentShell: { borderRadius: 20, flexDirection: 'row', gap: 5, overflow: 'hidden', padding: 5, position: 'relative' },
  segmentPill: { alignItems: 'center', borderRadius: 16, flex: 1, justifyContent: 'center', minHeight: 38, paddingHorizontal: 4, position: 'relative', zIndex: 2 },
  segmentLiquidPill: { borderRadius: 16, bottom: 5, left: 0, overflow: 'hidden', position: 'absolute', top: 5, zIndex: 0 },
  segmentLiquidSheen: { borderRadius: 999, height: 14, left: 14, opacity: 0.48, position: 'absolute', right: 14, top: 4 },
  segmentText: { fontSize: 12, fontWeight: '700' },
  workerJobsSegmentRefraction: { borderRadius: 999, height: 66, left: -28, opacity: 0.56, position: 'absolute', right: -28, top: -24, transform: [{ rotate: '-5deg' }], zIndex: 0 },
  workerJobsSegmentCrispShell: { borderCurve: 'continuous', borderRadius: 20, borderWidth: 1, bottom: 0, left: 0, opacity: 0.86, position: 'absolute', right: 0, top: 0, zIndex: 1 },
  workerJobsSegmentTopEdge: { borderRadius: 999, height: 1, left: 14, opacity: 0.76, position: 'absolute', right: 14, top: 1, zIndex: 1 },
  activeJobCard: { borderRadius: 24, borderWidth: 1, gap: 13, overflow: 'hidden', padding: 16, position: 'relative' },
  jobTop: { gap: 10 },
  jobTopRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  jobDiagnosisBox: { borderRadius: 22, gap: 10, padding: 15 },
  flowCard: { borderRadius: 28, gap: 10, overflow: 'hidden', padding: 16, position: 'relative' },
  needsReviewCard: { borderRadius: 24, borderWidth: 1, gap: 13, overflow: 'hidden', padding: 16, position: 'relative' },
  needsTopRow: { alignItems: 'center', justifyContent: 'flex-start', minHeight: 96 },
  needsTextStack: { flex: 1, minWidth: 0 },
  needsImageIcon: { flexShrink: 0 },
  needsInlineImageIcon: { flexShrink: 0, marginTop: -3 },
  needsReviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  statusPill: { borderRadius: 999, fontSize: 12, fontWeight: '700', overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6 },
  cardTitle: { fontSize: 18, fontWeight: '600', letterSpacing: 0, lineHeight: 24 },
  chatShell: { flex: 1, gap: 10, justifyContent: 'space-between', minHeight: 0, paddingBottom: 10, position: 'relative' },
  chatShellReference: { paddingTop: 2 },
  kaelClientStage: { flex: 1, gap: 12, justifyContent: 'space-between', minHeight: 0, overflowAnchor: 'none', paddingBottom: 0, position: 'relative' } as any,
  kaelClientStageReference: { paddingTop: 8 },
  kaelClientStageEmpty: { opacity: 0.92 },
  kaelBlankCanvas: { flex: 1, minHeight: 240, overflow: 'hidden', position: 'relative' },
  kaelCanvasWashLarge: { borderRadius: 32, height: 168, left: -48, opacity: 0.07, position: 'absolute', top: 46, transform: [{ rotate: '-8deg' }], width: 168 },
  kaelCanvasWashWarm: { borderRadius: 28, bottom: 42, height: 126, opacity: 0.06, position: 'absolute', right: -34, transform: [{ rotate: '12deg' }], width: 126 },
  jobRoomWaiting: { alignItems: 'center', gap: 8, justifyContent: 'center', minHeight: 228, padding: 18, position: 'relative', zIndex: 2 },
  jobRoomKaelHead: { height: 70, width: 70 },
  jobRoomRevealStack: { gap: 12 },
  jobRoomRevealStackReference: { flex: 1, justifyContent: 'center', minHeight: 0 },
  jobRoomStack: { gap: 11 },
  workerChatReferenceCenter: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 310, paddingBottom: 44 },
  workerChatWelcomeStage: { alignItems: 'center', gap: 18, justifyContent: 'center', paddingHorizontal: 8 },
  workerChatWelcomeGlyph: { alignItems: 'center', borderRadius: 999, borderWidth: 1, height: 62, justifyContent: 'center', overflow: 'hidden', position: 'relative', width: 62 },
  workerChatWelcomeGlyphAura: { borderRadius: 999, height: 86, opacity: 0.32, position: 'absolute', width: 86 },
  workerChatWelcomeGlyphImage: { height: 48, position: 'relative', width: 48, zIndex: 2 },
  workerChatWelcomeTitle: { alignSelf: 'stretch', fontSize: 23, fontWeight: '700', letterSpacing: 0, lineHeight: 29, maxWidth: 380, textAlign: 'center', whiteSpace: 'nowrap' } as any,
  jobRoomRevealStep: { gap: 11 },
  jobRoomProcessHidden: { opacity: 0 },
  jobRoomProcessTapTarget: { borderRadius: 28 },
  jobRoomProcessCard: { borderRadius: 28, borderWidth: 1, gap: 16, overflow: 'hidden', paddingBottom: 18, paddingHorizontal: 17, paddingTop: 16 },
  jobRoomProcessHead: { alignItems: 'center', flexDirection: 'row', gap: 11 },
  jobRoomProcessAvatar: { alignItems: 'center', borderRadius: 21, borderWidth: 1, flexShrink: 0, height: 50, justifyContent: 'center', overflow: 'hidden', width: 50 },
  jobRoomProcessAvatarImage: { height: 42, width: 42 },
  jobRoomProcessStatus: { alignItems: 'center', borderRadius: 18, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 9, minHeight: 48, paddingHorizontal: 13 },
  jobRoomProcessAccent: { borderRadius: 999, height: 26, width: 6 },
  jobRoomProcessTitle: { flex: 1, fontSize: 14.5, fontWeight: '700', letterSpacing: 0, lineHeight: 18.5 },
  jobRoomProcessMeta: { fontSize: 11.5, fontWeight: '600', letterSpacing: 0, lineHeight: 15 },
  jobRoomProcessSteps: { flexDirection: 'row', gap: 9, paddingHorizontal: 3 },
  jobRoomProcessStep: { borderRadius: 17, borderWidth: 1, flex: 1, minHeight: 64, paddingHorizontal: 9, paddingVertical: 10 },
  jobRoomProcessStepIndex: { fontSize: 10, fontWeight: '700', letterSpacing: 0, lineHeight: 12, marginBottom: 6 },
  jobRoomProcessStepTitle: { fontSize: 11.5, fontWeight: '700', letterSpacing: 0, lineHeight: 15 },
  jobRoomMessageRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 10 },
  jobRoomMessageAvatar: { alignItems: 'center', borderRadius: 18, borderWidth: 1, flexShrink: 0, height: 40, justifyContent: 'center', marginTop: 2, overflow: 'hidden', width: 40 },
  jobRoomMessageAvatarImage: { height: 34, width: 34 },
  jobRoomMessageBubble: { borderRadius: 22, borderTopLeftRadius: 8, borderWidth: 1, flex: 1, gap: 6, overflow: 'hidden', paddingHorizontal: 14, paddingVertical: 12 },
  jobRoomBubbleKicker: { fontSize: 11.5, fontWeight: '700', letterSpacing: 0, lineHeight: 15 },
  jobRoomBubbleTitle: { fontSize: 17, fontWeight: '700', letterSpacing: 0, lineHeight: 22 },
  jobRoomBubbleBody: { fontSize: 13, fontWeight: '700', letterSpacing: 0, lineHeight: 19 },
  jobRoomHeader: { borderRadius: 24, borderWidth: 1, gap: 10, overflow: 'hidden', padding: 13 },
  jobRoomMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  jobRoomMetaCell: { borderRadius: 18, borderWidth: 1, flexBasis: '47%', flexGrow: 1, gap: 4, minHeight: 66, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 9 },
  jobRoomMetaValue: { fontSize: 13, fontWeight: '600', letterSpacing: 0, lineHeight: 17 },
  jobRoomBrief: { borderRadius: 20, borderWidth: 1, gap: 8, overflow: 'hidden', paddingHorizontal: 13, paddingVertical: 11 },
  jobRoomBriefAligned: { marginLeft: 50 },
  jobRoomBriefTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  jobRoomBriefAccent: { borderRadius: 999, height: 18, width: 4 },
  jobRoomBriefTitle: { flex: 1, fontSize: 12.5, fontWeight: '700', letterSpacing: 0, lineHeight: 16 },
  jobRoomBriefText: { lineHeight: 19 },
  jobRoomGate: { alignItems: 'center', borderRadius: 22, borderWidth: 1, flexDirection: 'row', gap: 10, overflow: 'hidden', paddingHorizontal: 12, paddingVertical: 11 },
  jobRoomTopBar: { alignItems: 'center', borderRadius: 26, borderWidth: 1, flexDirection: 'row', gap: 10, marginBottom: 12, minHeight: 74, paddingHorizontal: 12, paddingVertical: 10 },
  jobRoomTopChrome: { gap: 10, marginBottom: 14, marginHorizontal: 0 },
  jobRoomTopUtilityRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 49, paddingHorizontal: 7 },
  jobRoomRoundButton: { alignItems: 'center', borderRadius: 999, borderWidth: 1, height: 46, justifyContent: 'center', overflow: 'hidden', width: 46 },
  jobRoomBackButton: { alignItems: 'center', borderRadius: 20, borderWidth: 1, height: 48, justifyContent: 'center', width: 48 },
  jobRoomKaelBubble: { alignItems: 'center', borderRadius: 999, borderWidth: 1, height: 46, justifyContent: 'center', overflow: 'hidden', width: 46 },
  jobRoomKaelBubbleImage: { height: 34, width: 34 },
  jobRoomHeaderAvatar: { height: 44, width: 44 },
  jobRoomHeaderSpacer: { flex: 1, minHeight: 42 },
  jobRoomStatusPill: { borderRadius: 999, borderWidth: 1, fontSize: 11, fontWeight: '700', letterSpacing: 0, maxWidth: 94, overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 7, textAlign: 'center' },
  jobRoomTitleStack: { flex: 1, minWidth: 0 },
  chatStack: { gap: 10 },
  chatBubble: { alignSelf: 'flex-start', borderRadius: 22, maxWidth: '88%', padding: 12 },
  chatBubbleMine: { alignSelf: 'flex-end' },
  workerKaelProgressPanel: { alignSelf: 'flex-start', borderRadius: 16, borderWidth: 1, gap: 6, marginTop: 6, minWidth: 188, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 8 },
  workerKaelProgressTrack: { backgroundColor: 'rgba(148,163,184,0.22)', borderRadius: 999, height: 5, overflow: 'hidden', width: '100%' },
  workerKaelProgressFill: { borderRadius: 999, height: 5, minWidth: 5 },
  workerKaelProgressText: { fontSize: 11.5, fontWeight: '700', letterSpacing: 0, lineHeight: 15 },
  chatWho: { fontSize: 11.5, fontWeight: '600' },
  chatText: { fontSize: 13.5, fontWeight: '600', lineHeight: 19, marginTop: 3 },
  chatComposerTouchWrap: { marginHorizontal: 0, marginTop: 10 },
  workerKaelParityPanel: { borderRadius: 18, borderWidth: 1, gap: 10, marginTop: 10, overflow: 'hidden', padding: 10 },
  workerKaelParityTitle: { fontSize: 13, fontWeight: '700', letterSpacing: 0 },
  workerKaelParityBody: { fontSize: 11, fontWeight: '700', lineHeight: 15 },
  workerKaelParityActions: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  workerKaelMiniButton: { alignItems: 'center', borderRadius: 14, borderWidth: 1, minHeight: 34, justifyContent: 'center', minWidth: 92, paddingHorizontal: 10, paddingVertical: 7 },
  workerKaelMiniButtonText: { fontSize: 11, fontWeight: '700', letterSpacing: 0 },
  workerKaelFeedbackForm: { gap: 8 },
  workerKaelFeedbackInput: { borderRadius: 14, borderWidth: 1, fontSize: 12, fontWeight: '700', minHeight: 74, paddingHorizontal: 10, paddingVertical: 9, textAlignVertical: 'top' },
  workerKaelFeedbackError: { fontSize: 11, fontWeight: '700', lineHeight: 15 },
  chatComposer: { alignSelf: 'stretch', borderCurve: 'continuous', borderRadius: 24, borderWidth: 1, gap: 5, minHeight: 79, overflow: 'hidden', paddingBottom: 3, paddingHorizontal: 9, paddingTop: 5, position: 'relative', zIndex: 2 },
  workerChatComposerKeyline: { borderCurve: 'continuous', borderRadius: 22, borderWidth: 1, bottom: 3, left: 3, opacity: 0.78, position: 'absolute', right: 3, top: 3, zIndex: 1 },
  chatComposerControlRow: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 42, position: 'relative', zIndex: 2 },
  chatComposerRightActions: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  chatComposerControlSpacer: { flex: 1, minWidth: 0 },
  composerTool: { alignItems: 'center', borderRadius: 15, borderWidth: 1, height: 40, justifyContent: 'center', width: 40 },
  workerChatModePill: { alignItems: 'center', borderRadius: 999, borderWidth: 1, justifyContent: 'center', minHeight: 38, minWidth: 82, overflow: 'hidden', paddingHorizontal: 14, position: 'relative' },
  workerChatModePillGlassLayer: { borderRadius: 999, bottom: 3, left: 3, position: 'absolute', right: 3, top: 3, zIndex: 0 },
  workerChatModeText: { fontSize: 13.5, fontWeight: '700', letterSpacing: 0, lineHeight: 17, position: 'relative', zIndex: 1 },
  chatInput: { borderRadius: 16, borderWidth: 0, flexShrink: 0, fontSize: 16.5, fontWeight: '700', letterSpacing: 0, lineHeight: 21, maxHeight: 76, minHeight: 28, minWidth: 0, paddingBottom: 4, paddingHorizontal: 10, paddingTop: 1, position: 'relative', textAlignVertical: 'top', zIndex: 2 },
  chatInputInvisibleFocus: { backgroundColor: 'transparent', borderColor: 'transparent', borderWidth: 0, boxShadow: 'none', outlineColor: 'transparent', outlineOffset: 0, outlineStyle: 'none', outlineWidth: 0 } as any,
  sendButton: { alignItems: 'center', borderRadius: 999, borderWidth: 1, flexShrink: 0, height: 42, justifyContent: 'center', minWidth: 42, width: 42 },
  earningsHero: { borderRadius: 32, gap: 12, overflow: 'hidden', padding: 18, position: 'relative' },
  earningsHeroWrap: { gap: 0, position: 'relative' },
  earningsBadge: { alignItems: 'center', borderRadius: 24, height: 58, justifyContent: 'center', transform: [{ rotate: '-5deg' }], width: 58 },
  earningsTrendCard: { borderRadius: 32, gap: 14, overflow: 'hidden', padding: 18, position: 'relative' },
  workerEarningsChromeWash: { borderCurve: 'continuous', bottom: 0, left: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0, zIndex: 0 },
  workerEarningsChromeRefraction: { borderRadius: 999, height: 148, opacity: 0.62, position: 'absolute', right: -48, top: -34, width: 188, zIndex: 1 },
  workerEarningsChromeCrispShell: { borderCurve: 'continuous', borderWidth: 1, bottom: 0, left: 0, opacity: 0.92, position: 'absolute', right: 0, top: 0, zIndex: 4 },
  workerEarningsChromeInnerInset: { borderCurve: 'continuous', borderWidth: 1, bottom: 4, left: 4, opacity: 0.56, position: 'absolute', right: 4, top: 4, zIndex: 4 },
  workerEarningsChromeTopEdge: { borderRadius: 999, height: 1, left: 20, opacity: 0.76, position: 'absolute', right: 20, top: 1, zIndex: 5 },
  workerEarningsChromeBottomEdge: { borderRadius: 999, bottom: 1, height: 1, left: 20, opacity: 0.62, position: 'absolute', right: 20, zIndex: 5 },
  workerProfileChromeWash: { borderCurve: 'continuous', bottom: 0, left: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0, zIndex: 0 },
  workerProfileChromeRefraction: { borderRadius: 999, height: 142, opacity: 0.60, position: 'absolute', right: -46, top: -32, width: 184, zIndex: 1 },
  workerProfileChromeCrispShell: { borderCurve: 'continuous', borderWidth: 1, bottom: 0, left: 0, opacity: 0.92, position: 'absolute', right: 0, top: 0, zIndex: 3 },
  workerProfileChromeInnerInset: { borderCurve: 'continuous', borderWidth: 1, bottom: 4, left: 4, opacity: 0.54, position: 'absolute', right: 4, top: 4, zIndex: 3 },
  workerProfileChromeTopEdge: { borderRadius: 999, height: 1, left: 20, opacity: 0.76, position: 'absolute', right: 20, top: 1, zIndex: 4 },
  workerProfileChromeBottomEdge: { borderRadius: 999, bottom: 1, height: 1, left: 20, opacity: 0.60, position: 'absolute', right: 20, zIndex: 4 },
  earningsTrendGlow: { borderRadius: 44, height: 146, opacity: 0.10, position: 'absolute', right: -38, top: -34, transform: [{ rotate: '-6deg' }], width: 146, zIndex: 1 },
  earningsChartShell: { borderRadius: 22, borderWidth: 1, gap: 11, justifyContent: 'space-between', minHeight: 154, overflow: 'hidden', paddingHorizontal: 14, paddingVertical: 13, position: 'relative', zIndex: 2 },
  earningsChartEmptyState: { alignItems: 'center', flex: 1, gap: 8, justifyContent: 'center', minHeight: 124, overflow: 'hidden', position: 'relative' },
  earningsChartEmptyLabel: { fontSize: 12, fontWeight: '600', letterSpacing: 0.2, marginTop: 6, textAlign: 'center' },
  workerChatStaticEmpty: { borderRadius: 22, borderWidth: 1, gap: 8, marginTop: 8, paddingHorizontal: 18, paddingVertical: 20 },
  workerChatStaticEmptyTitle: { fontSize: 16, fontWeight: '700', letterSpacing: 0.2 },
  workerChatStaticEmptyBody: { fontSize: 13, lineHeight: 19 },
  earningsBarRail: { alignItems: 'flex-end', alignSelf: 'stretch', flexDirection: 'row', justifyContent: 'space-between', minHeight: 122, paddingHorizontal: 15 },
  earningsEmptyBar: { borderBottomLeftRadius: 8, borderBottomRightRadius: 8, borderTopLeftRadius: 12, borderTopRightRadius: 12, width: 28 },
  earningsDayRail: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 15 },
  earningsDayLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 0, minWidth: 24, position: 'relative', textAlign: 'center', zIndex: 2 },
  earningsSummaryGrid: { flexDirection: 'row', gap: 10 },
  earningsSummaryCell: { borderRadius: 22, borderWidth: 1, flex: 1, gap: 4, justifyContent: 'center', minHeight: 86, overflow: 'hidden', paddingHorizontal: 16, paddingVertical: 13, position: 'relative' },
  earningsSummaryLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 0, lineHeight: 14, position: 'relative', textAlign: 'left', zIndex: 2 },
  earningsSummaryValue: { fontSize: 17, fontVariant: ['tabular-nums'], fontWeight: '700', letterSpacing: 0, lineHeight: 22, position: 'relative', zIndex: 2 },
  earningsSummaryHint: { fontSize: 11, fontWeight: '600', letterSpacing: 0, lineHeight: 14, position: 'relative', zIndex: 2 },
  moneyText: { fontSize: 34, fontVariant: ['tabular-nums'], fontWeight: '600', letterSpacing: 0 },
  moneyTextState: { fontSize: 24, lineHeight: 30 },
  listCard: { borderRadius: 29, gap: 4, overflow: 'hidden', padding: 10, position: 'relative' },
  earningsLedgerCard: { borderRadius: 29, gap: 6, overflow: 'hidden', padding: 10, position: 'relative' },
  earningsListRow: { alignItems: 'center', borderRadius: 16, flexDirection: 'row', gap: 10, minHeight: 56, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 7, position: 'relative', zIndex: 2 },
  earningsListIcon: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },
  earningsListImageIcon: { flexShrink: 0 },
  earningsListTitle: { flex: 1, fontSize: 13.5, fontWeight: '700', letterSpacing: 0, lineHeight: 18 },
  earningsListMeta: { flexShrink: 0, fontSize: 11.5, fontWeight: '700', letterSpacing: 0, lineHeight: 15, maxWidth: 116, textAlign: 'right' },
  listRow: { alignItems: 'center', flexDirection: 'row', gap: 11, minHeight: 54, paddingHorizontal: 8 },
  listTitle: { flex: 1, fontSize: 14, fontWeight: '600' },
  listMeta: { fontSize: 12, fontWeight: '600', maxWidth: 148, textAlign: 'right' },
  listMetaInline: { fontSize: 11, fontWeight: '600', lineHeight: 14 },
  profileHead: { borderRadius: 30, gap: 14, overflow: 'hidden', paddingHorizontal: 18, paddingVertical: 17, position: 'relative' },
  profileHeroTop: { alignItems: 'center', flexDirection: 'row', gap: 12, position: 'relative', zIndex: 2 },
  profileHeroAction: { flexDirection: 'row', position: 'relative', zIndex: 2 },
  avatarWrap: { alignItems: 'center', borderRadius: 999, height: 56, justifyContent: 'center', width: 56 },
  profileAvatarHero: {
    alignItems: 'center',
    borderRadius: 20,
    height: 52,
    justifyContent: 'center',
    width: 52,
  } as any,
  profileTitleStack: { flex: 1, gap: 3, minWidth: 0 },
  profileName: { fontSize: 23, fontWeight: '600', letterSpacing: 0, lineHeight: 28 },
  profileSubtitle: { fontSize: 13, fontWeight: '600', letterSpacing: 0, lineHeight: 18 },
  profileBadge: { alignItems: 'center', borderRadius: 999, height: 42, justifyContent: 'center', width: 42 },
  scoreNumber: { fontSize: 28, fontWeight: '600', letterSpacing: 0, lineHeight: 34 },
  skillWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, position: 'relative', zIndex: 2 },
  skillPill: { borderRadius: 999, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: 13 },
  skillText: { fontSize: 13, fontWeight: '600' },
  profileMiniGrid: { flexDirection: 'row', gap: 10 },
  profileMiniCard: { borderRadius: 20, borderWidth: 1, flex: 1, gap: 2, minHeight: 118, overflow: 'hidden', paddingBottom: 14, paddingHorizontal: 14, paddingTop: 14 },
  profileMiniImage: { alignSelf: 'flex-start', marginLeft: -4, position: 'relative', zIndex: 2 },
  profileMiniTitle: { fontSize: 16, fontWeight: '600', letterSpacing: 0, lineHeight: 18, position: 'relative', zIndex: 2 },
  profileMiniMeta: { fontSize: 11, fontWeight: '700', letterSpacing: 0, lineHeight: 15, position: 'relative', zIndex: 2 },
  profileSyncPreview: { borderRadius: 24, borderWidth: 1, gap: 4, overflow: 'hidden', padding: 14, position: 'relative' },
  profileSyncPreviewTop: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between', position: 'relative', zIndex: 2 },
  profileLevelCard: { borderRadius: 29, borderWidth: 1, gap: 12, overflow: 'hidden', padding: 14, position: 'relative' },
  profileLevelCornerAura: { borderBottomLeftRadius: 116, borderCurve: 'continuous', borderTopRightRadius: 29, height: 128, position: 'absolute', right: -2, top: -2, width: '48%', zIndex: 1 },
  profileLevelTop: { alignItems: 'center', flexDirection: 'row', gap: 12, position: 'relative', zIndex: 2 },
  profileLevelOrb: { alignItems: 'center', borderRadius: 20, borderWidth: 1, flexShrink: 0, height: 58, justifyContent: 'center', overflow: 'hidden', width: 58 },
  profileLevelOrbMeta: { fontSize: 11, fontWeight: '700', letterSpacing: 0, lineHeight: 13 },
  profileLevelOrbValue: { fontSize: 22, fontWeight: '700', letterSpacing: 0, lineHeight: 25 },
  profileLevelCopy: { flex: 1, gap: 3, minWidth: 0 },
  profileLevelProgressTrack: { borderRadius: 999, borderWidth: 1, height: 12, overflow: 'hidden', position: 'relative', zIndex: 2 },
  profileLevelProgressFill: { borderRadius: 999, bottom: 2, left: 2, position: 'absolute', top: 2 },
  profileLevelNext: { fontSize: 12, fontWeight: '700', letterSpacing: 0, lineHeight: 16, position: 'relative', zIndex: 2 },
  profileLevelSignalGrid: { flexDirection: 'row', gap: 8, position: 'relative', zIndex: 2 },
  profileLevelSignal: { alignItems: 'center', borderCurve: 'continuous', borderRadius: 18, flex: 1, gap: 5, justifyContent: 'center', minHeight: 66, minWidth: 0, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 10, position: 'relative' },
  profileLevelSignalGlass: { borderRadius: 17, bottom: 1, left: 1, position: 'absolute', right: 1, top: 1, zIndex: 0 },
  profileLevelSignalTopEdge: { borderRadius: 999, height: 1, left: 14, position: 'absolute', right: 14, top: 1, zIndex: 1 },
  profileLevelSignalLabel: { fontSize: 10.5, fontWeight: '700', letterSpacing: 0, lineHeight: 13, position: 'relative', textAlign: 'center', zIndex: 2 },
  profileLevelSignalValue: { fontSize: 16, fontVariant: ['tabular-nums'], fontWeight: '700', letterSpacing: 0, lineHeight: 20, position: 'relative', textAlign: 'center', zIndex: 2 },
  profileLevelLadder: { gap: 8, position: 'relative', zIndex: 2 },
  profileLevelLadderHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  profileLevelLadderTitle: { flex: 1, fontSize: 14.5, fontWeight: '700', letterSpacing: 0, lineHeight: 19 },
  profileLevelLadderMax: { flexShrink: 0, fontSize: 11.5, fontWeight: '700', letterSpacing: 0, lineHeight: 15 },
  profileLevelRail: { height: 104, marginHorizontal: -3 },
  profileLevelRailContent: { alignItems: 'center', paddingBottom: 16, paddingHorizontal: 3, paddingTop: 6 },
  profileLevelRailItem: { alignItems: 'center', flexDirection: 'row' },
  profileLevelRailSpacer: { width: 8 },
  profileLevelScrollIndicatorSlot: { height: 18, justifyContent: 'center', marginBottom: 4, marginTop: -18, paddingHorizontal: 5, position: 'relative', zIndex: 2 },
  profileLevelScrollIndicatorTrack: { borderCurve: 'continuous', borderRadius: 999, borderWidth: 1, height: 10, overflow: 'hidden', position: 'relative' },
  profileLevelScrollIndicatorTopEdge: { borderRadius: 999, height: 1, left: 12, opacity: 0.72, position: 'absolute', right: 12, top: 1, zIndex: 1 },
  profileLevelScrollIndicatorThumb: { borderCurve: 'continuous', borderRadius: 999, borderWidth: 1, height: 6, left: 1, overflow: 'hidden', position: 'absolute', top: 1, zIndex: 2 },
  profileLevelScrollIndicatorSheen: { borderRadius: 999, bottom: 0, left: 0, opacity: 0.58, position: 'absolute', right: 0, top: 0 },
  profileLevelChip: { alignItems: 'center', borderRadius: 18, borderWidth: 1, gap: 1, justifyContent: 'center', minHeight: 70, overflow: 'hidden', paddingHorizontal: 10, position: 'relative', width: 62 },
  profileLevelChipSheen: { borderRadius: 999, height: 34, left: -18, opacity: 0.40, position: 'absolute', top: -8, transform: [{ rotate: '-16deg' }], width: 74, zIndex: 0 },
  profileLevelChipMeta: { fontSize: 9.5, fontWeight: '700', letterSpacing: 0, lineHeight: 11, position: 'relative', zIndex: 2 },
  profileLevelChipValue: { fontSize: 18, fontVariant: ['tabular-nums'], fontWeight: '700', letterSpacing: 0, lineHeight: 22, position: 'relative', zIndex: 2 },
  profileLevelChipState: { fontSize: 9.5, fontWeight: '700', letterSpacing: 0, lineHeight: 11, maxWidth: 52, position: 'relative', textAlign: 'center', zIndex: 2 },
  profileLevelDetail: { alignItems: 'center', borderRadius: 18, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 92, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 10 },
  profileLevelMilestone: { alignItems: 'center', borderRadius: 18, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 76, overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 9 },
  profileLevelMilestoneBadge: { alignItems: 'center', borderRadius: 16, borderWidth: 1, flexShrink: 0, height: 46, justifyContent: 'center', overflow: 'hidden', width: 46 },
  profileLevelMilestoneBadgeMeta: { fontSize: 9.5, fontWeight: '700', letterSpacing: 0, lineHeight: 11 },
  profileLevelMilestoneBadgeValue: { fontSize: 17, fontVariant: ['tabular-nums'], fontWeight: '700', letterSpacing: 0, lineHeight: 20 },
  profileLevelMilestoneCopy: { flex: 1, gap: 3, minWidth: 0 },
  profileLevelMilestoneHead: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  profileLevelMilestoneTitle: { flex: 1, fontSize: 13.5, fontWeight: '700', letterSpacing: 0, lineHeight: 17 },
  profileLevelMilestoneState: { flexShrink: 0, fontSize: 10.5, fontWeight: '700', letterSpacing: 0, lineHeight: 13, maxWidth: 72, textAlign: 'right' },
  profileLevelMilestoneText: { fontSize: 11.5, fontWeight: '600', letterSpacing: 0, lineHeight: 15 },
  profileLevelMilestoneReward: { fontSize: 12, fontWeight: '700', letterSpacing: 0, lineHeight: 16 },
  profileListCard: { borderRadius: 29, gap: 8, paddingHorizontal: 12, paddingVertical: 14, position: 'relative' },
  profileListRow: { alignItems: 'center', borderRadius: 16, flexDirection: 'row', gap: 12, minHeight: 52, overflow: 'hidden', paddingHorizontal: 12, position: 'relative', zIndex: 2 },
  profileListImage: { flexShrink: 0 },
  profileListTitle: { flex: 1, fontSize: 14.5, fontWeight: '600', letterSpacing: 0, lineHeight: 20 },
  profileListMeta: { flexShrink: 0, fontSize: 12, fontWeight: '600', letterSpacing: 0, lineHeight: 16, maxWidth: 146, textAlign: 'right' },
  preferenceCard: { borderRadius: 29, gap: 2, overflow: 'hidden', paddingHorizontal: 13, paddingVertical: 12, position: 'relative' },
  preferenceRow: { alignItems: 'center', borderRadius: 18, flexDirection: 'row', justifyContent: 'space-between', minHeight: 54, overflow: 'hidden', paddingHorizontal: 12, position: 'relative', zIndex: 2 },
  preferenceTitle: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 11 },
  preferenceImage: { flexShrink: 0 },
  preferenceCopy: { flex: 1, gap: 2, minWidth: 0 },
  preferenceMetaAction: { flexShrink: 0, fontSize: 12, fontWeight: '600', maxWidth: 112, textAlign: 'right' },
  verificationCard: { borderRadius: 29, gap: 10, overflow: 'hidden', padding: 14, position: 'relative' },
  verificationGrid: { flexDirection: 'row', gap: 8, position: 'relative', zIndex: 2 },
  verificationInput: { borderRadius: 18, borderWidth: 1, fontSize: 14, fontWeight: '600', minHeight: 46, paddingHorizontal: 12, position: 'relative', zIndex: 2 },
  verificationHalfInput: { flex: 1, minWidth: 0 },
  serviceAreaPicker: { borderRadius: 22, borderWidth: 1, gap: 10, overflow: 'hidden', padding: 12, position: 'relative', zIndex: 2 },
  serviceAreaAnchorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, position: 'relative', zIndex: 2 },
  serviceAreaAnchorButton: { borderRadius: 999, borderWidth: 1, justifyContent: 'center', minHeight: 40, paddingHorizontal: 11, paddingVertical: 7 },
  serviceAreaAnchorText: { fontSize: 12, fontWeight: '700', letterSpacing: 0, lineHeight: 16 },
  serviceAreaRadiusRow: { alignItems: 'center', flexDirection: 'row', gap: 10, position: 'relative', zIndex: 2 },
  serviceAreaRadiusButton: { alignItems: 'center', borderRadius: 999, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  serviceAreaRadiusControlText: { fontSize: 22, fontWeight: '700', letterSpacing: 0, lineHeight: 24 },
  serviceAreaRadiusValue: { flex: 1, fontSize: 18, fontWeight: '700', letterSpacing: 0, lineHeight: 24, textAlign: 'center' },
  serviceAreaRadiusPresets: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, position: 'relative', zIndex: 2 },
  verificationHint: { fontSize: 12, fontWeight: '600', lineHeight: 16, position: 'relative', zIndex: 2 },
  verificationFiles: { flexDirection: 'row', gap: 8, position: 'relative', zIndex: 2 },
  verificationFileButton: { alignItems: 'center', borderRadius: 18, borderWidth: 1, flex: 1, gap: 5, justifyContent: 'center', minHeight: 72, padding: 8 },
  verificationFileText: { fontSize: 11, fontWeight: '600', lineHeight: 14, textAlign: 'center' },
  dockWrap: { alignSelf: 'center', minHeight: workerDockHeight, position: 'absolute', zIndex: 30 },
  workerDockSplitRow: { alignItems: 'center', flexDirection: 'row', gap: 14, justifyContent: 'center', minHeight: 64, position: 'relative', width: '100%', zIndex: 2 },
  workerDock: { alignItems: 'center', borderRadius: 29, borderWidth: 1, flexDirection: 'row', gap: 0, height: workerDockHeight, justifyContent: 'space-around', minHeight: workerDockHeight, overflow: 'hidden', paddingHorizontal: 7, paddingVertical: 3, position: 'relative' },
  workerDockMainCluster: { flexShrink: 1 },
  workerDockAssetImage: { opacity: 0.86 },
  workerDockAssetImageFocused: { opacity: 1 },
  workerDockKaelActionPressable: { alignItems: 'center', flexShrink: 0, height: 64, justifyContent: 'center', width: 64, zIndex: 2 },
  workerDockKaelActionGlass: { alignItems: 'center', borderCurve: 'continuous', borderRadius: 32, borderWidth: 1, height: 64, justifyContent: 'center', overflow: 'hidden', position: 'relative', width: 64 },
  workerDockKaelActionEdge: { borderCurve: 'continuous', borderRadius: 31, borderWidth: 1, bottom: 1, left: 1, position: 'absolute', right: 1, top: 1, zIndex: 1 },
  workerDockKaelActionAura: { borderRadius: 999, height: 58, opacity: 0.68, position: 'absolute', right: -11, top: -8, width: 58, zIndex: 0 },
  workerDockKaelImage: { height: 31, width: 31, zIndex: 2 },
  workerDockKaelImageFocused: { height: 33, width: 33 },
  motionSweep: { borderRadius: 999, height: 76, position: 'absolute', top: -18, width: 96 },
  pressed: { opacity: 0.78 },
  hiddenMarker: { height: 0, opacity: 0, width: 0 },
})
