// Customer UI copy dictionaries (VI/EN), extracted from customer-surfaces.tsx (C4 customer stage 2).
import { LOCAL_WORKFLOW_PRICE_DISCLAIMER } from '@home-services/shared'

export const customerProfileEditorCopy = {
  vi: {
    address: {
      error: 'Nhập địa chỉ cụ thể hơn.',
      helper: 'Kael dùng địa chỉ này để điền nhanh khi tạo yêu cầu.',
      placeholder: 'Nhập địa chỉ căn hộ',
      title: 'Địa chỉ mặc định',
    },
    cancel: 'Hủy',
    nickname: {
      error: 'Nhập ít nhất 2 ký tự.',
      helper: 'Bạn có thể đặt tên thân mật, không cần là tên thật.',
      placeholder: 'Nhập biệt danh',
      title: 'Biệt danh',
    },
    save: 'Lưu',
    saveError: 'Không thể lưu hồ sơ. Vui lòng thử lại.',
    saving: 'Đang lưu',
  },
  en: {
    address: {
      error: 'Enter a more specific address.',
      helper: 'Kael uses this address to prefill future requests.',
      placeholder: 'Enter apartment address',
      title: 'Default address',
    },
    cancel: 'Cancel',
    nickname: {
      error: 'Enter at least 2 characters.',
      helper: 'Use a friendly nickname; it does not need to be your legal name.',
      placeholder: 'Enter nickname',
      title: 'Nickname',
    },
    save: 'Save',
    saveError: 'Could not save profile. Please try again.',
    saving: 'Saving',
  },
} as const

export const customerAccountInfoCopy = {
  vi: {
    birthDate: 'Ngày sinh',
    birthDateInvalid: 'Ngày sinh chưa hợp lệ.',
    birthDatePlaceholder: 'DD/MM/YYYY',
    close: 'Đóng',
    email: 'Email (không bắt buộc)',
    emailInvalid: 'Email chưa hợp lệ.',
    emailNote: 'Bạn sẽ nhận lịch sử yêu cầu và hóa đơn qua email này.',
    fieldRequired: 'Nhập ít nhất một thông tin để cập nhật.',
    fullName: 'Họ tên',
    fullNameInvalid: 'Họ tên cần ít nhất 2 ký tự.',
    fullNamePlaceholder: 'Nhập họ tên',
    gender: 'Giới tính',
    genderOptions: { female: 'Nữ', male: 'Nam', other: 'Khác' },
    identityBody: 'Chưa cần cho yêu cầu hiện tại; Kael vẫn dùng thông tin cơ bản để hỗ trợ.',
    identityTitle: 'Xác thực danh tính',
    metaComplete: 'Đã cập nhật',
    metaEmpty: 'Bổ sung',
    metaPartial: (count: number) => `${count}/3 đã lưu`,
    phone: 'Số điện thoại',
    phoneInvalid: 'Số điện thoại chưa hợp lệ.',
    phonePlaceholder: 'Nhập số điện thoại',
    salutation: 'Xưng hô',
    salutationPlaceholder: 'Chọn danh xưng',
    save: 'Cập nhật',
    saveError: 'Không thể cập nhật thông tin. Vui lòng thử lại.',
    saving: 'Đang cập nhật',
    shortFieldInvalid: 'Thông tin này quá dài.',
    title: 'Cập nhật tài khoản',
  },
  en: {
    birthDate: 'Birth date',
    birthDateInvalid: 'Enter a valid birth date.',
    birthDatePlaceholder: 'DD/MM/YYYY',
    close: 'Close',
    email: 'Email (optional)',
    emailInvalid: 'Enter a valid email.',
    emailNote: 'Request history and invoices will be sent to this email.',
    fieldRequired: 'Enter at least one detail to update.',
    fullName: 'Full name',
    fullNameInvalid: 'Full name needs at least 2 characters.',
    fullNamePlaceholder: 'Enter full name',
    gender: 'Gender',
    genderOptions: { female: 'Female', male: 'Male', other: 'Other' },
    identityBody: 'Not required for current requests; Kael still uses the basic profile details.',
    identityTitle: 'Identity verification',
    metaComplete: 'Updated',
    metaEmpty: 'Add details',
    metaPartial: (count: number) => `${count}/3 saved`,
    phone: 'Phone number',
    phoneInvalid: 'Enter a valid phone number.',
    phonePlaceholder: 'Enter phone number',
    salutation: 'Salutation',
    salutationPlaceholder: 'Choose salutation',
    save: 'Update',
    saveError: 'Could not update account information. Please try again.',
    saving: 'Updating',
    shortFieldInvalid: 'This detail is too long.',
    title: 'Update account',
  },
} as const

export const customerFeedbackCopy = {
  vi: {
    cancel: 'Hủy',
    errorRequired: 'Nhập ít nhất 8 ký tự để Kael hiểu rõ hơn.',
    helper: 'Tốt, xấu, khó chịu hay thiếu sót đều được. Kael sẽ ghi nhận để cải thiện trải nghiệm thật.',
    placeholder: 'Điều gì Kael làm tốt hoặc cần sửa?',
    rowMeta: 'Gửi cho Kael',
    rowMetaSent: 'Đã ghi nhận',
    rowTitle: 'Góp ý',
    saveError: 'Kael chưa lưu được góp ý. Vui lòng thử lại.',
    saving: 'Đang gửi',
    submit: 'Gửi góp ý',
    title: 'Góp ý cho Kael',
  },
  en: {
    cancel: 'Cancel',
    errorRequired: 'Enter at least 8 characters so Kael has enough context.',
    helper: 'Good, bad, frustrating, or missing details are all welcome. Kael records this to improve the real experience.',
    placeholder: 'What did Kael do well or need to fix?',
    rowMeta: 'Send to Kael',
    rowMetaSent: 'Received',
    rowTitle: 'Feedback',
    saveError: 'Kael could not save this feedback. Please try again.',
    saving: 'Sending',
    submit: 'Send feedback',
    title: 'Feedback for Kael',
  },
} as const

export const customerPasswordCopy = {
  vi: {
    cancel: 'Hủy',
    confirmLabel: 'Nhập lại mật khẩu',
    confirmPlaceholder: 'Nhập lại mật khẩu mới',
    currentLabel: 'Mật khẩu hiện tại',
    currentPlaceholder: 'Nhập mật khẩu hiện tại',
    currentRequiredError: 'Nhập mật khẩu hiện tại để tiếp tục.',
    mismatchError: 'Hai mật khẩu chưa khớp.',
    passwordLabel: 'Mật khẩu mới',
    passwordPlaceholder: 'Nhập mật khẩu mới',
    rowMeta: 'Cập nhật',
    rowMetaUpdated: 'Đã cập nhật',
    rowTitle: 'Mật khẩu',
    save: 'Đổi mật khẩu',
    saveError: 'Không thể cập nhật mật khẩu. Vui lòng thử lại.',
    saving: 'Đang cập nhật',
    shortError: 'Mật khẩu cần 8-72 ký tự.',
    title: 'Đổi mật khẩu',
    helper: 'Đặt mật khẩu mới cho tài khoản này. Kael sẽ không lưu hoặc hiển thị mật khẩu của bạn.',
  },
  en: {
    cancel: 'Cancel',
    confirmLabel: 'Confirm password',
    confirmPlaceholder: 'Enter the new password again',
    currentLabel: 'Current password',
    currentPlaceholder: 'Enter current password',
    currentRequiredError: 'Enter your current password to continue.',
    mismatchError: 'Passwords do not match.',
    passwordLabel: 'New password',
    passwordPlaceholder: 'Enter new password',
    rowMeta: 'Update',
    rowMetaUpdated: 'Updated',
    rowTitle: 'Password',
    save: 'Update password',
    saveError: 'Could not update password. Please try again.',
    saving: 'Updating',
    shortError: 'Password needs 8-72 characters.',
    title: 'Update password',
    helper: 'Set a new password for this account. Kael does not store or display your password.',
  },
} as const

export const customerProfileCareCopy = {
  vi: {
    interactionLabel: 'Tương tác Kael',
    interactionReady: 'Sẵn sàng',
    savingsLabel: 'Tiết kiệm',
    savingsPending: 'Chờ kiểm giá',
    serviceLabel: 'Dịch vụ đã dùng',
    servicePending: 'Chưa có',
    title: 'Tín hiệu tin cậy',
  },
  en: {
    interactionLabel: 'Kael touchpoints',
    interactionReady: 'Ready',
    savingsLabel: 'Savings',
    savingsPending: 'Awaiting check',
    serviceLabel: 'Services used',
    servicePending: 'No request yet',
    title: 'Trust Signals',
  },
} as const

export const customerProfileSectionCopy = {
  vi: {
    identity: 'Tài khoản căn hộ',
    profileStatus: 'Hồ sơ',
    settings: 'Thiết lập và hỗ trợ',
  },
  en: {
    identity: 'Apartment Account',
    profileStatus: 'Profile',
    settings: 'Settings and Support',
  },
} as const

export const customerCopy = {
  vi: {
    home: {
      title: 'Home Services',
      subtitle: 'Kael sẵn sàng phục vụ tận tình!',
      searchA11y: 'Mở Kael tạo yêu cầu',
      searchText: 'Bạn cần sửa gì?',
      commandKicker: 'Kael',
      commandSubtitle: 'Mở chat nhanh để Kael gom thông tin',
      commandTitle: 'Ổ cắm bị nóng, nước rò, hay cần dọn nhà?',
      commandBody: 'Kael nhận thông tin, phân tích và tự điều phối khi đủ dữ liệu.',
      commandComposer: 'Mô tả sự cố',
      commandSend: 'Gửi',
      contextLabel: 'Căn hộ',
      contextFallback: 'Chưa có khu vực',
      addressHint: 'Chọn khu vực khi gửi yêu cầu',
      addressActiveMeta: 'Khu vực của yêu cầu hiện tại',
      serviceMetaElectrical: 'Ổ cắm, CB, đèn',
      serviceMetaPlumbing: 'Rò rỉ, nghẹt',
      serviceMetaCleaning: 'Dọn căn hộ',
      serviceSectionMeta: '3 nhóm đang hỗ trợ',
      serviceSectionTitle: 'Dịch vụ',
      intakeCta: 'Mở Kael',
      quickActive: 'Yêu cầu',
      quickHistory: 'Hoạt động',
      quickAddress: 'Căn hộ',
      quickTrust: 'Minh bạch giá',
      quickActiveMeta: 'Theo dõi trạng thái',
      quickHistoryMeta: 'Xem tiến trình',
      quickAddressMeta: 'Kiểm tra khu vực',
      quickTrustMeta: 'Ước tính đã kiểm chứng',
      noActiveMeta: 'Chưa có yêu cầu',
      trustTitle: 'Kael kiểm chứng giá',
      trustBody: 'Giá do Kael tính từ dữ liệu hiện có. Kael cập nhật khi có bằng chứng phạm vi mới.',
      notification: (count: number) => `Kael có ${count} cập nhật chưa đọc`,
      activeA11y: (service: string) => `Mở yêu cầu ${service} đang xử lý`,
    },
    ticket: {
      area: 'Khu vực',
      current: 'Hiện tại',
      described: 'Đã mô tả',
      estimate: 'Ước tính',
      finalPrice: 'Giá cuối',
      issue: 'Vấn đề',
      noRequest: 'Không có yêu cầu',
      status: 'Trạng thái',
      unknown: 'Chưa rõ',
      update: 'Cập nhật',
    },
    kael: {
      activeDealError: 'Đang có yêu cầu đang chạy. Mở Hoạt động để theo dõi hoặc hoàn tất trước khi tạo yêu cầu mới.',
      bookingCta: 'Mở chat Kael',
      hubKicker: 'Trợ lý nhận yêu cầu',
      hubTitle: 'Kael nhận mô tả trước',
      hubGreeting: 'Chào bạn, mình là Kael.',
      hubBody: 'Mô tả sự cố điện, nước hoặc vệ sinh. Kael sẽ tóm tắt thành phiếu, chốt ước tính và tự điều phối khi đủ dữ liệu.',
      quickPrompt: 'Bắt đầu bằng dịch vụ',
      attach: 'Đính kèm',
      sessionTitle: 'Phiên nhận yêu cầu',
      sessionMetaReady: 'Đủ để mở phiếu',
      sessionMetaNeedsMore: 'Cần thêm chi tiết',
      assistantSummary: 'Kael đã giữ mô tả này trong phiên. Bước tiếp theo là mở chat Kael để xem ước tính, ghi chú và tiến trình điều phối.',
      assistantMoreDetail: 'Kael cần thêm chi tiết trước khi tạo phiếu.',
      assistantMoreDetailHint: 'Hãy thêm vị trí trong căn hộ, dấu hiệu nhìn thấy, mức độ ảnh hưởng hoặc ảnh trong chat Kael.',
      unsupportedSummary: 'Kael chưa thể tạo phiếu cho dịch vụ ngoài phạm vi hiện tại.',
      unsupportedHint: 'Hiện tại chỉ hỗ trợ sửa điện, sửa nước và vệ sinh/dọn dẹp nhà.',
      quickServiceA11y: (service: string) => `Bắt đầu chat ${service} với Kael`,
      needDetail: 'Mô tả Kael cần rõ hơn trước khi tạo phiếu.',
      needService: 'Cần chọn dịch vụ',
      kaelSendsWorkers: 'Kael gửi thợ',
      summaryTicket: 'Phiếu tóm tắt',
      lockedService: 'Dịch vụ đang khóa',
      unsupportedService: 'Dịch vụ chưa hỗ trợ',
      service: 'Dịch vụ',
    },
    history: {
      filters: ['Sửa', 'Giá', 'Chat', 'Xong'],
      workerWaiting: 'Đang chờ phản hồi',
      workerNone: 'Chưa có thợ nhận',
      workerActive: 'Thợ đang xử lý',
      reviewed: 'Đã gửi đánh giá',
      confirmed: 'Kael đã xác nhận',
      finalConfirm: 'Kael đang xét hoàn tất',
      noWorker: 'Chưa có thợ được ghép',
      cancelledState: 'Yêu cầu đã hủy',
      cancelledBody: 'Kael hiển thị trạng thái hủy đã ghi nhận và cổng chính sách đang khóa giao dịch này. Luồng cũ không được mở lại; bạn có thể tạo yêu cầu mới khi cần.',
      orchestrationStatus: 'Kael đang điều phối',
      waitingWorkerDone: 'Chờ thợ hoàn tất',
      editRequest: 'Chỉnh yêu cầu',
      newRequest: 'Tạo yêu cầu mới',
      openPriceCheck: 'Mở chat Kael',
      cancelTitle: 'Hủy yêu cầu?',
      cancelSearching: 'Yêu cầu tìm thợ sẽ dừng và địa chỉ chi tiết vẫn bị ẩn khỏi thợ.',
      cancelActive: 'Kael sẽ xử lý yêu cầu hủy theo chính sách, ghi dấu vết kiểm tra và báo cho thợ nếu việc đã được nhận.',
      cancelDraft: 'Phiếu sẽ đóng. Bạn có thể tạo yêu cầu mới khi cần.',
      keep: 'Giữ lại',
      cancelRequest: 'Hủy yêu cầu',
      scopeApproveTitle: 'Đồng ý quyết định đổi phạm vi?',
      scopeRejectTitle: 'Khiếu nại đổi phạm vi?',
      scopeApproveBody: 'Hệ thống sẽ ghi nhận bạn đồng ý với quyết định của Kael để thợ tiếp tục sửa.',
      scopeRejectBody: 'Hệ thống sẽ ghi nhận khiếu nại để Kael hoặc hỗ trợ xem lại trước khi thợ tiếp tục phạm vi mới.',
      approve: 'Đồng ý',
      reject: 'Khiếu nại',
      progress: 'Tiến trình yêu cầu',
      scope: 'Đổi phạm vi',
      waitingDecision: 'Kael đang xét',
      reason: 'Lý do',
      workerNoReason: 'Thợ chưa ghi lý do',
      newPrice: 'Giá mới',
      accessTitle: 'Thợ đã tới sảnh',
      accessCheckedInBody: 'Thợ đã check-in tại sảnh. Bấm "Cho thợ lên" để mở số căn hộ chính xác cho thợ.',
      accessAuthorizeCta: 'Cho thợ lên',
      accessReleasedBody: 'Bạn đã cho thợ lên — thợ đã thấy số căn hộ chính xác.',
      kaelReviewing: 'Kael đang xét',
      evidence: 'Bằng chứng hoàn tất',
      evidenceBefore: 'Ảnh trước',
      evidenceAfter: 'Ảnh sau',
      waitingWorkerPrice: 'Chờ Kael chốt',
      priceDisclaimer: LOCAL_WORKFLOW_PRICE_DISCLAIMER,
      chatEmpty: 'Chưa có trao đổi cho yêu cầu này',
      openOrchestration: 'Mở điều phối',
      orchestrationTitle: 'Kael đang điều phối',
      orchestrationBody: 'Kael tự chuyển yêu cầu sang tìm thợ khi dữ liệu đủ theo chính sách. Bạn có thể theo dõi, hủy hoặc khiếu nại nếu cần.',
      paymentReview: 'Thanh toán & đánh giá',
      payment: 'Thanh toán',
      review: 'Đánh giá',
      locked: 'Khóa',
      open: 'Mở',
      presenceTitle: 'Bản đồ hoàn tất',
      presenceHome: 'Điểm hẹn',
      presenceWorker: 'Thợ cập nhật',
      chooseStar: (rating: number) => `Chọn ${rating} sao`,
      submitReview: 'Gửi đánh giá',
      timeline: [
        ['Mô tả vấn đề', ['draft', 'analyzing']],
        ['Kael điều phối', ['awaiting_customer_confirm']],
        ['Tìm thợ', ['broadcasting']],
        ['Thợ nhận việc', ['worker_matched', 'worker_on_way']],
        ['Kiểm tra/sửa', ['arrived', 'inspecting', 'repairing', 'scope_change_pending']],
        ['Thợ báo hoàn tất', ['completed_by_worker']],
        ['Kael xác nhận xong', ['confirmed_by_customer', 'reviewed']],
      ],
    },
    profile: {
      noEmail: 'Chưa có email hồ sơ',
      admin: 'Quản trị',
      customer: 'Khách',
      unknownRole: 'Chưa xác định',
      realData: 'Đang có yêu cầu',
      home: 'CĂN HỘ',
      noRequest: 'Chưa có yêu cầu',
      draft: 'Phiếu nháp',
      service: 'Dịch vụ',
      data: 'Dữ liệu',
      apartment: 'Căn hộ',
      privacy: 'Riêng tư',
      address: 'Địa chỉ',
      kaelManager: 'Quản Gia Kael',
      serviceScope: 'Điện / nước / vệ sinh',
      history: 'Hoạt động',
      interface: 'Giao diện',
      light: 'Sáng',
      dark: 'Tối',
      signOut: 'Đăng xuất',
      switchAccount: 'Đổi tài khoản',
    },
    nav: { home: 'Nhà', booking: 'Yêu cầu', kael: 'Kael', activity: 'Hoạt động', profile: 'Hồ sơ' },
    navA11y: { home: 'Trang chủ', booking: 'Tạo yêu cầu', kael: 'Kael', activity: 'Hoạt động', profile: 'Hồ sơ' },
  },
  en: {
    home: {
      title: 'Home Services',
      subtitle: 'Kael is ready to orchestrate',
      searchA11y: 'Open Kael service chat',
      searchText: 'What needs fixing?',
      commandKicker: 'Kael',
      commandSubtitle: 'Open quick chat so Kael can collect details',
      commandTitle: 'Outlet, leak, or cleaning?',
      commandBody: 'Kael receives the details, analyzes them, and orchestrates when data is sufficient.',
      commandComposer: 'Describe the problem',
      commandSend: 'Send',
      contextLabel: 'Apartment',
      contextFallback: 'No area yet',
      addressHint: 'Choose an area before sending the request',
      addressActiveMeta: 'Area for the current request',
      serviceMetaElectrical: 'Outlet, breaker, light',
      serviceMetaPlumbing: 'Leak, clog',
      serviceMetaCleaning: 'Apartment cleaning',
      serviceSectionMeta: '3 supported groups',
      serviceSectionTitle: 'Services',
      intakeCta: 'Open Kael',
      quickActive: 'Request',
      quickHistory: 'Activity',
      quickAddress: 'Apartment',
      quickTrust: 'Price clarity',
      quickActiveMeta: 'Track status',
      quickHistoryMeta: 'View progress',
      quickAddressMeta: 'Check area',
      quickTrustMeta: 'Audited estimate',
      noActiveMeta: 'No active request',
      trustTitle: 'Kael keeps price audit',
      trustBody: 'Prices are Kael estimates from current evidence. Kael updates them when new scope evidence is added.',
      notification: (count: number) => `Kael has ${count} unread updates`,
      activeA11y: (service: string) => `Open active ${service} request`,
    },
    ticket: {
      area: 'Area',
      current: 'Current',
      described: 'Described',
      estimate: 'Estimate',
      finalPrice: 'Final price',
      issue: 'Problem',
      noRequest: 'No request',
      status: 'Status',
      unknown: 'Unknown',
      update: 'Update',
    },
    kael: {
      activeDealError: 'An active request is running. Open Activity to follow or finish it before creating a new request.',
      bookingCta: 'Open Kael chat',
      hubKicker: 'Service Intake Assistant',
      hubTitle: 'Kael takes the description first',
      hubGreeting: 'Hi, I am Kael.',
      hubBody: 'Describe an electrical, plumbing, or cleaning issue. Kael will turn it into a ticket, lock the estimate, and orchestrate when enough data exists.',
      quickPrompt: 'Start with a service',
      attach: 'Attach',
      sessionTitle: 'Intake session',
      sessionMetaReady: 'Ready for ticket',
      sessionMetaNeedsMore: 'Needs more detail',
      assistantSummary: 'Kael saved this description for the session. Next, open Kael chat to review the estimate, notes, and orchestration progress.',
      assistantMoreDetail: 'Kael needs a little more detail before creating a ticket.',
      assistantMoreDetailHint: 'Add the room, visible symptom, impact level, or photo context in Kael chat.',
      unsupportedSummary: 'Kael cannot create a ticket for a service outside the current scope.',
      unsupportedHint: 'Home Services currently supports electrical repair, plumbing repair, and home cleaning only.',
      quickServiceA11y: (service: string) => `Start ${service} chat with Kael`,
      needDetail: 'Kael needs a clearer description before creating a ticket.',
      needService: 'Choose a service',
      kaelSendsWorkers: 'Kael sends workers',
      summaryTicket: 'Summary ticket',
      lockedService: 'Service unavailable',
      unsupportedService: 'Service not supported',
      service: 'Service',
    },
    history: {
      filters: ['Repair', 'Price', 'Chat', 'Done'],
      workerWaiting: 'Waiting for response',
      workerNone: 'No worker accepted',
      workerActive: 'Worker in progress',
      reviewed: 'Review sent',
      confirmed: 'Kael confirmed',
      finalConfirm: 'Kael reviewing completion',
      noWorker: 'No worker matched',
      cancelledState: 'Request cancelled',
      cancelledBody: 'Kael shows the recorded cancellation state and the policy gate locking this transaction. This workflow is not reopened; create a new request when needed.',
      orchestrationStatus: 'Kael orchestrating',
      waitingWorkerDone: 'Waiting for worker completion',
      editRequest: 'Edit request',
      newRequest: 'New request',
      openPriceCheck: 'Open Kael chat',
      cancelTitle: 'Cancel request?',
      cancelSearching: 'The worker search will stop and the detailed address stays hidden.',
      cancelActive: 'Kael will process this cancellation by policy, record the audit trail, and notify the worker if the job was accepted.',
      cancelDraft: 'This ticket will close. You can create a new request later.',
      keep: 'Keep',
      cancelRequest: 'Cancel request',
      scopeApproveTitle: 'Accept Kael scope decision?',
      scopeRejectTitle: 'Appeal scope change?',
      scopeApproveBody: 'The system will record that you accept Kael decision so the worker can continue.',
      scopeRejectBody: 'The system will record an appeal so Kael or support can review before changed work continues.',
      approve: 'Accept',
      reject: 'Appeal',
      progress: 'Request progress',
      scope: 'Scope change',
      waitingDecision: 'Kael reviewing',
      reason: 'Reason',
      workerNoReason: 'No worker reason yet',
      newPrice: 'New price',
      accessTitle: 'Worker at the lobby',
      accessCheckedInBody: 'The worker checked in at the lobby. Tap "Let the worker up" to reveal your exact unit.',
      accessAuthorizeCta: 'Let the worker up',
      accessReleasedBody: 'You let the worker up — they can now see your exact unit.',
      kaelReviewing: 'Kael reviewing',
      evidence: 'Completion evidence',
      evidenceBefore: 'Before',
      evidenceAfter: 'After',
      waitingWorkerPrice: 'Waiting for Kael',
      priceDisclaimer: 'This is a Kael estimate from the current evidence. Kael may update it when new scope evidence is added.',
      chatEmpty: 'No messages for this request yet',
      openOrchestration: 'Open orchestration',
      orchestrationTitle: 'Kael is orchestrating',
      orchestrationBody: 'Kael moves the request into worker search once policy has enough data. You can track, cancel, or appeal if needed.',
      paymentReview: 'Payment & review',
      payment: 'Payment',
      review: 'Review',
      locked: 'Locked',
      open: 'Open',
      presenceTitle: 'Completion map',
      presenceHome: 'Service point',
      presenceWorker: 'Worker update',
      chooseStar: (rating: number) => `Choose ${rating} stars`,
      submitReview: 'Submit review',
      timeline: [
        ['Describe problem', ['draft', 'analyzing']],
        ['Kael orchestrates', ['awaiting_customer_confirm']],
        ['Find worker', ['broadcasting']],
        ['Worker accepted', ['worker_matched', 'worker_on_way']],
        ['Inspect/repair', ['arrived', 'inspecting', 'repairing', 'scope_change_pending']],
        ['Worker completed', ['completed_by_worker']],
        ['Kael confirmed', ['confirmed_by_customer', 'reviewed']],
      ],
    },
    profile: {
      noEmail: 'No profile email yet',
      admin: 'Admin',
      customer: 'Customer',
      unknownRole: 'Unknown',
      realData: 'Active request',
      home: 'HOME',
      noRequest: 'No request yet',
      draft: 'Draft',
      service: 'Service',
      data: 'Data',
      apartment: 'Apartment',
      privacy: 'Privacy',
      address: 'Address',
      kaelManager: 'Kael',
      serviceScope: 'Electrical / plumbing / cleaning',
      history: 'Activity',
      interface: 'Theme',
      light: 'Light',
      dark: 'Dark',
      signOut: 'Sign out',
      switchAccount: 'Switch account',
    },
    nav: { home: 'Home', booking: 'Request', kael: 'Kael', activity: 'Activity', profile: 'Profile' },
    navA11y: { home: 'Home', booking: 'Create request', kael: 'Kael', activity: 'Activity', profile: 'Profile' },
  },
} as const
