// Customer UI StyleSheet partition 2, extracted from customer-surfaces.tsx (C4 customer split). Merged in styles.ts.
import { Platform, StyleSheet } from 'react-native'
import { customerDockHeight, customerFrameHorizontalPadding } from './constants'
import { customerWorkerTypography } from './constants'

export const customerStyles2 = StyleSheet.create({
  homeCommandComposer: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 2,
  },
  homeCommandComposerText: {
    flex: 1,
    fontSize: 14,
    ...customerWorkerTypography.body,
    lineHeight: 18,
    minWidth: 0,
  },
  homeCommandPrompt: {
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    minHeight: 80,
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 2,
  },
  homeCommandPromptActions: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  homeCommandPromptInput: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    boxShadow: 'none',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 19,
    minHeight: 38,
    minWidth: 0,
    outlineColor: 'transparent',
    outlineOffset: 0,
    outlineStyle: 'none',
    outlineWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    textAlignVertical: 'top',
  } as any,
  homeCommandAttach: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: 10,
  },
  homeCommandAttachText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
  },
  homeCommandSend: {
    alignItems: 'center',
    borderRadius: 17,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 56,
    paddingHorizontal: 15,
  },
  homeCommandSendText: {
    fontSize: 13,
    ...customerWorkerTypography.label,
  },
  twoCol: {
    flexDirection: 'row',
    gap: 10,
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  serviceMeta: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 14,
    marginTop: 2,
    textAlign: 'center',
  },
  smallChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  smallChipText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
  },
  bookingCheckPanel: {
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    padding: 15,
    position: 'relative',
  },
  bookingStack: {
    gap: 16,
    minHeight: 0,
    position: 'relative',
  },
  bookingTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  bookingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  priceBox: {
    borderRadius: 20,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 6,
    minHeight: 74,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  priceBoxLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 14,
  },
  activityPriceBoxLabel: {
    fontWeight: '700',
  },
  priceBoxValue: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 19,
  },
  activityPriceBoxValue: {
    fontWeight: '500',
  },
  bookingCheckRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(35,96,84,0.08)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 34,
  },
  bookingCheckDot: {
    borderRadius: 999,
    height: 9,
    width: 9,
  },
  bookingCheckText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    minWidth: 0,
  },
  bookingCheckMeta: {
    fontSize: 12,
    fontWeight: '600',
    maxWidth: 96,
    textAlign: 'right',
  },
  bookingDiagnosisPanel: {
    borderRadius: 22,
    borderWidth: 1,
    gap: 8,
    minHeight: 98,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  bookingDiagnosisPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 34,
    paddingHorizontal: 11,
  },
  bookingDiagnosisPillText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
  },
  bookingDiagnosisBody: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
  },
  historyHeroPanel: {
    borderCurve: 'continuous',
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    minHeight: 168,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
  },
  activityHeroPanel: {
    borderRadius: 32,
    gap: 15,
    minHeight: 184,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  activityHeroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 42,
    position: 'relative',
    zIndex: 2,
  },
  activityHeroCopy: {
    flex: 1,
    gap: 4,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 0,
  },
  activityHeroTitle: {
    fontSize: 20,
    lineHeight: 24,
  },
  activityMaterialEdge: {
    borderRadius: 999,
    height: 1,
    left: 18,
    opacity: 0.78,
    position: 'absolute',
    right: 18,
    top: 1,
    zIndex: 1,
  },
  activityStatusLens: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    justifyContent: 'center',
    maxWidth: 126,
    minHeight: 34,
    overflow: 'hidden',
    paddingHorizontal: 12,
    position: 'relative',
    zIndex: 2,
  },
  activityStatusText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 15,
  },
  historyHeroPanelCompact: {
    gap: 10,
    padding: 14,
  },
  historyHeroBody: {
    fontSize: 13,
    ...customerWorkerTypography.body,
    lineHeight: 19,
  },
  historyHeroBodyCompact: {
    fontSize: 12,
    lineHeight: 17,
  },
  historyHeroActions: {
    flexDirection: 'row',
    gap: 10,
  },
  historyCheckPanel: {
    borderRadius: 26,
    borderWidth: 1,
    gap: 14,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
  },
  historyThreadCard: {
    borderRadius: 26,
    borderWidth: 1,
    gap: 14,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
  },
  historyChatFeed: {
    gap: 11,
  },
  historyChatEmptyCue: {
    alignSelf: 'flex-end',
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: '84%',
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  historyChatCueText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 16,
  },
  historyChatComposer: {
    borderRadius: 20,
    minHeight: 54,
    padding: 6,
  },
  chatPreviewCard: {
    borderRadius: 20,
    borderWidth: 1,
    gap: 5,
    overflow: 'hidden',
    padding: 12,
  },
  chatPreviewKaelBubble: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  chatPreviewUserBubble: {
    alignSelf: 'flex-end',
    maxWidth: '88%',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  historyDisclaimerText: {
    fontSize: 12,
    ...customerWorkerTypography.body,
    lineHeight: 17,
  },
  homeShortcutGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  homeTileIconStage: {
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  homeShortcutTile: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 7,
    justifyContent: 'center',
    minHeight: 84,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  homeShortcutCopy: {
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: 3,
    minWidth: 0,
  },
  homeShortcutTitle: {
    fontSize: 16,
    ...customerWorkerTypography.label,
    lineHeight: 17,
    textAlign: 'center',
  },
  homeShortcutMeta: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 15,
    textAlign: 'center',
  },
  homeTrustNote: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 82,
    overflow: 'hidden',
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  homeTrustCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  homeTrustTitle: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 18,
  },
  homeTrustBody: {
    fontSize: 12,
    ...customerWorkerTypography.body,
    lineHeight: 17,
  },
  homeServicesBlock: {
    gap: 10,
    marginTop: 18,
  },
  homeServicesTitle: {
    fontSize: 18,
    ...customerWorkerTypography.sectionTitle,
    lineHeight: 22,
  },
  homeServicesMeta: {
    fontSize: 12,
    ...customerWorkerTypography.label,
    lineHeight: 16,
  },
  serviceCard: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    boxShadow: '0 10px 22px rgba(17,70,61,0.07)',
    flexBasis: '31%',
    flex: 1,
    gap: 7,
    justifyContent: 'center',
    minHeight: 94,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  serviceCardHome: {
    alignItems: 'center',
    borderRadius: 22,
    gap: 9,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  serviceCardCompact: {
    borderRadius: 22,
    gap: 6,
    minHeight: 76,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  serviceTitle: {
    fontSize: 14,
    ...customerWorkerTypography.label,
    lineHeight: 16,
    textAlign: 'center',
  },
  serviceTitleHome: {
    alignSelf: 'stretch',
    fontWeight: '700',
    lineHeight: 15,
    textAlign: 'center',
  },
  sectionTitle: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionHeading: {
    fontSize: 18,
    ...customerWorkerTypography.sectionTitle,
  },
  sectionMeta: {
    fontSize: 12,
    ...customerWorkerTypography.body,
  },
  smallServiceGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  smallService: {
    alignItems: 'center',
    borderRadius: 21,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    minHeight: 78,
    overflow: 'hidden',
    paddingHorizontal: 5,
    paddingVertical: 9,
  },
  smallServiceText: {
    fontSize: 10,
    ...customerWorkerTypography.body,
  },
  paymentRail: {
    borderRadius: 24,
    borderWidth: 1,
    boxShadow: 'none',
    gap: 10,
    minHeight: 128,
    overflow: 'hidden',
    padding: 13,
  },
  paymentWarmHalo: {
    borderRadius: 999,
    height: 88,
    opacity: 0.12,
    position: 'absolute',
    right: -26,
    top: -24,
    width: 88,
  },
  paymentOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  paymentOption: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 62,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 9,
  },
  paymentIconBubble: {
    alignItems: 'center',
    borderRadius: 15,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  paymentCopy: {
    flex: 1,
    gap: 2,
  },
  paymentTitle: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
  },
  paymentMeta: {
    fontSize: 11,
    ...customerWorkerTypography.body,
  },
  kicker: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 31,
  },
  cardHeadline: {
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0,
  },
  bubbleKicker: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
  },
  ticketCard: {
    borderRadius: 26,
    borderWidth: 1,
    gap: 12,
    overflow: 'hidden',
    padding: 14,
  },
  ticketCell: {
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 5,
    minHeight: 68,
    overflow: 'hidden',
    padding: 12,
  },
  reportTicketCell: {
    borderRadius: 18,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 4,
    minHeight: 66,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  ticketLabel: {
    fontSize: 11,
    ...customerWorkerTypography.body,
  },
  activityTicketLabel: {
    fontWeight: '700',
  },
  reportTicketLabel: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
  },
  ticketValue: {
    fontSize: 14,
    fontVariant: ['tabular-nums'],
    fontWeight: '600',
    letterSpacing: 0,
  },
  activityTicketValue: {
    fontWeight: '500',
  },
  reportTicketValue: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
  },
  composer: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    boxShadow: 'none',
    flexDirection: 'row',
    gap: 8,
    minHeight: 58,
    overflow: 'hidden',
    padding: 7,
  },
  composerInput: {
    flex: 1,
    flexShrink: 1,
    fontSize: 15,
    ...customerWorkerTypography.body,
    minWidth: 0,
    minHeight: 40,
    paddingHorizontal: 8,
  },
  sendButton: {
    alignItems: 'center',
    borderRadius: 17,
    flexShrink: 0,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  flowCard: {
    borderRadius: 22,
    borderWidth: 1,
    boxShadow: 'none',
    gap: 12,
    overflow: 'hidden',
    padding: 14,
  },
  flowCardCompact: {
    gap: 4,
    padding: 8,
  },
  historyReportCard: {
    borderCurve: 'continuous',
    borderRadius: 26,
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  historyReportHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    minHeight: 24,
  },
  historyReportTitle: {
    flex: 1,
    fontSize: 18,
    lineHeight: 23,
    minWidth: 0,
  },
  historyReportBadge: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 15,
  },
  historyReportBody: {
    fontSize: 13,
    lineHeight: 18,
  },
  historyReportGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  historyTimelineCard: {
    paddingVertical: 16,
  },
  activityTimelineCard: {
    borderCurve: 'continuous',
    borderRadius: 30,
    gap: 2,
    paddingHorizontal: 18,
    paddingVertical: 17,
    position: 'relative',
  },
  historyDoneTimelineCard: {
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  timelineRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 32,
  },
  activityTimelineRow: {
    gap: 12,
    minHeight: 52,
    position: 'relative',
    zIndex: 2,
  },
})
