// Customer UI StyleSheet partition 1, extracted from customer-surfaces.tsx (C4 customer split). Merged in styles.ts.
import { Platform, StyleSheet } from 'react-native'
import { customerDockHeight, customerFrameHorizontalPadding } from './constants'
import { customerWorkerTypography } from './constants'

export const customerStyles1 = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  v4Scroll: {
    gap: 12,
    paddingHorizontal: customerFrameHorizontalPadding,
  },
  hiddenMarker: {
    height: 0,
    opacity: 0,
    position: 'absolute',
    width: 0,
  },
  pressed: {
    opacity: 0.78,
  },
  kaelErrorText: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    paddingHorizontal: 6,
  },
  glassTopHighlight: {
    height: 1,
    left: 16,
    opacity: 0.82,
    position: 'absolute',
    right: 16,
    top: 0,
    zIndex: 0,
  },
  glassSheen: {
    height: '170%',
    left: -72,
    opacity: 0.42,
    position: 'absolute',
    top: -46,
    transform: [{ rotate: '11deg' }],
    width: 58,
    zIndex: 0,
  },
  glassRing: {
    borderRadius: 999,
    borderWidth: 2,
    height: 88,
    opacity: 0.88,
    position: 'absolute',
    right: -30,
    top: 34,
    width: 88,
  },
  liquidCardLight: {
    borderRadius: 999,
    height: 164,
    opacity: 0.18,
    position: 'absolute',
    right: -54,
    top: -48,
    width: 164,
    zIndex: 0,
  },
  liquidCardRim: {
    borderRadius: 999,
    height: 138,
    opacity: 0.12,
    position: 'absolute',
    right: -44,
    top: -40,
    width: 138,
    zIndex: 0,
  },
  liquidTabLight: {
    borderRadius: 999,
    height: 64,
    opacity: 0.16,
    position: 'absolute',
    right: 18,
    top: 3,
    width: 112,
    zIndex: 0,
  },
  profileLiquidOuterEdge: {
    borderCurve: 'continuous',
    borderWidth: 1,
    bottom: 0,
    left: 0,
    opacity: 0.94,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 3,
  },
  profileLiquidInnerEdge: {
    borderCurve: 'continuous',
    borderWidth: 1,
    bottom: 4,
    left: 4,
    opacity: 0.56,
    position: 'absolute',
    right: 4,
    top: 4,
    zIndex: 3,
  },
  profileLiquidTopGlint: {
    borderRadius: 999,
    height: 1,
    left: 18,
    opacity: 0.92,
    position: 'absolute',
    right: 18,
    top: 1,
    zIndex: 4,
  },
  profileLiquidBottomEdge: {
    borderRadius: 999,
    bottom: 1,
    height: 1,
    left: 20,
    opacity: 0.60,
    position: 'absolute',
    right: 20,
    zIndex: 4,
  },
  profileLiquidSheen: {
    borderRadius: 999,
    opacity: 0.72,
    position: 'absolute',
    transform: [{ rotate: '13deg' }],
    zIndex: 0,
  },
  profileHeroLiquidSheen: {
    bottom: -46,
    left: 30,
    top: -48,
    width: 42,
  },
  profileCareLiquidSheen: {
    bottom: -56,
    left: 52,
    top: -60,
    width: 50,
  },
  profilePanelLiquidSheen: {
    bottom: -44,
    left: 28,
    top: -44,
    width: 34,
  },
  profileHeroLiquidEdge: {
    borderRadius: 30,
  },
  profileCareLiquidEdge: {
    borderRadius: 29,
  },
  profilePanelLiquidEdge: {
    borderRadius: 29,
  },
  profileHeroLiquidLens: {
    borderRadius: 999,
    height: 142,
    opacity: 0.60,
    position: 'absolute',
    right: -46,
    top: -32,
    width: 184,
    zIndex: 0,
  },
  profileCareLiquidLens: {
    borderRadius: 999,
    height: 142,
    opacity: 0.18,
    position: 'absolute',
    right: -46,
    top: -32,
    width: 184,
    zIndex: 0,
  },
  profilePanelLiquidLens: {
    borderRadius: 999,
    height: 118,
    opacity: 0.16,
    position: 'absolute',
    right: -42,
    top: -28,
    width: 162,
    zIndex: 0,
  },
  motionSweep: {
    bottom: -40,
    position: 'absolute',
    top: -40,
    width: 44,
    zIndex: 24,
  },
  dockWrap: {
    minHeight: customerDockHeight,
    position: 'absolute',
    zIndex: 30,
  },
  dockGlassAura: {
    borderRadius: 999,
    bottom: -14,
    height: 70,
    left: 18,
    position: 'absolute',
    right: 18,
    zIndex: -1,
  },
  dockWarmAura: {
    borderRadius: 999,
    bottom: -6,
    height: 46,
    opacity: 0.11,
    position: 'absolute',
    right: -12,
    width: 88,
    zIndex: -1,
  },
  customerDockSplitRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    minHeight: customerDockHeight,
    position: 'relative',
    width: '100%',
    zIndex: 2,
  },
  glassDock: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 28,
    borderWidth: 1,
    boxShadow: '0 7px 16px rgba(13,70,65,0.035), inset 0 1px 0 rgba(255,255,255,0.58)',
    flexDirection: 'row',
    gap: 0,
    height: customerDockHeight,
    justifyContent: 'space-around',
    minHeight: customerDockHeight,
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 3,
    position: 'relative',
  },
  customerDockMainCluster: {
    flexShrink: 1,
  },
  customerDockKaelActionPressable: {
    alignItems: 'center',
    flexShrink: 0,
    height: 56,
    justifyContent: 'center',
    width: 56,
    zIndex: 2,
  },
  customerDockKaelActionGlass: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 28,
    borderWidth: 1,
    height: 56,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 56,
  },
  customerDockKaelActionEdge: {
    borderCurve: 'continuous',
    borderRadius: 27,
    borderWidth: 1,
    bottom: 1,
    left: 1,
    position: 'absolute',
    right: 1,
    top: 1,
    zIndex: 1,
  },
  customerDockKaelActionAura: {
    borderRadius: 999,
    height: 50,
    opacity: 0.50,
    position: 'absolute',
    right: -9,
    top: -7,
    width: 50,
    zIndex: 0,
  },
  dockBottomReflection: {
    borderRadius: 999,
    bottom: 8,
    height: 15,
    left: 36,
    opacity: 0.16,
    position: 'absolute',
    right: 36,
    zIndex: 0,
  },
  dockMotionSheen: {
    bottom: -18,
    position: 'absolute',
    top: -18,
    width: 44,
    zIndex: 0,
  },
  dockItem: {
    alignItems: 'center',
    borderRadius: 21,
    flex: 1,
    height: 50,
    justifyContent: 'center',
    position: 'relative',
    zIndex: 2,
  },
  dockItemActive: {
    transform: [{ translateY: -1 }],
  },
  dockDot: {
    borderRadius: 999,
    bottom: 6,
    height: 4,
    position: 'absolute',
    width: 4,
  },
  dockKaelImage: {
    height: 29,
    width: 29,
  },
  v4Content: {
    minHeight: 760,
    position: 'relative',
  },
  profileSectionMintWash: {
    height: 268,
    opacity: 0.08,
    right: -132,
    top: 10,
    width: 278,
  },
  profileSectionGlassSlab: {
    borderBottomLeftRadius: 132,
    borderCurve: 'continuous',
    borderTopLeftRadius: 36,
    height: 292,
    opacity: 0.055,
    position: 'absolute',
    right: -88,
    top: -2,
    transform: [{ rotate: '-7deg' }],
    width: 182,
    zIndex: 0,
  },
  homeTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingBottom: 10,
    paddingHorizontal: 2,
  },
  titleBlock: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  screenTitle: {
    fontSize: 24,
    ...customerWorkerTypography.screenTitle,
    lineHeight: 29,
  },
  plainContent: {
    gap: 12,
    position: 'relative',
  },
  historyDoneStack: {
    gap: 16,
    paddingTop: 2,
  },
  presenceMapCard: {
    borderRadius: 30,
    borderWidth: 1,
    gap: 14,
    overflow: 'hidden',
    padding: 15,
  },
  presenceMapCardCompact: {
    borderRadius: 26,
    gap: 11,
    padding: 12,
  },
  presenceMapViewport: {
    borderCurve: 'continuous',
    borderRadius: 28,
    borderWidth: 1,
    minHeight: 156,
    overflow: 'hidden',
    position: 'relative',
  },
  presenceMapViewportCompact: {
    borderRadius: 24,
    minHeight: 144,
  },
  presenceMapHud: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    left: 12,
    position: 'absolute',
    right: 12,
    top: 10,
    zIndex: 6,
  },
  presenceMapControl: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    maxWidth: '56%',
    minHeight: 32,
    paddingHorizontal: 10,
  },
  presenceMapControlText: {
    fontSize: 11,
    ...customerWorkerTypography.label,
    lineHeight: 14,
  },
  presenceBadge: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    maxWidth: '58%',
    minHeight: 42,
    paddingHorizontal: 10,
    position: 'absolute',
    zIndex: 4,
  },
  presenceBadgeHome: {
    left: 14,
    top: 58,
  },
  presenceBadgeText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  presenceBadgeWorker: {
    bottom: 36,
    right: 14,
  },
  mapBackdrop: {
    bottom: 0,
    left: 0,
    opacity: 0.76,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  mapGlow: {
    borderRadius: 999,
    height: 132,
    left: '50%',
    opacity: 0.34,
    position: 'absolute',
    top: 34,
    transform: [{ translateX: -59 }],
    width: 132,
  },
  mapRoute: {
    borderRadius: 999,
    height: 10,
    left: 60,
    opacity: 0.5,
    position: 'absolute',
    top: 72,
    transformOrigin: 'left center',
    width: 226,
  },
  mapRouteSoft: {
    borderRadius: 999,
    height: 44,
    left: 52,
    opacity: 0.12,
    position: 'absolute',
    top: 54,
    transform: [{ rotate: '-19deg' }],
    width: 240,
  },
  mapVehicle: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    left: '50%',
    overflow: 'hidden',
    position: 'absolute',
    top: 62,
    width: 42,
    zIndex: 2,
  },
  mapLine: {
    height: 1,
    opacity: 0.34,
    position: 'absolute',
    width: 280,
  },
  mapLineOne: {
    top: 38,
    transform: [{ rotate: '-10deg' }],
  },
  mapLineTwo: {
    right: -40,
    top: 88,
    transform: [{ rotate: '25deg' }],
  },
  mapLineThree: {
    left: -28,
    top: 130,
    transform: [{ rotate: '-32deg' }],
  },
  mapRoom: {
    borderRadius: 18,
    borderWidth: 2,
    opacity: 0.42,
    position: 'absolute',
  },
  mapRoomOne: {
    height: 86,
    left: 42,
    top: 24,
    width: 136,
  },
  mapRoomTwo: {
    height: 84,
    right: 35,
    top: 68,
    width: 132,
  },
  mapRoomThree: {
    height: 76,
    left: 68,
    top: 120,
    width: 186,
  },
  mapPin: {
    borderRadius: 999,
    borderWidth: 3,
    height: 18,
    left: '50%',
    opacity: 0.9,
    position: 'absolute',
    top: 66,
    transform: [{ translateX: -9 }],
    width: 18,
  },
  mapNode: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    opacity: 0.95,
    position: 'absolute',
    width: 44,
  },
  mapNodeElectric: {
    left: 50,
    top: 50,
  },
  mapNodeWater: {
    right: 52,
    top: 100,
  },
  searchPill: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    boxShadow: 'none',
    flexDirection: 'row',
    gap: 10,
    marginTop: 0,
    minHeight: 52,
    overflow: 'hidden',
    paddingHorizontal: 14,
  },
  searchText: {
    flex: 1,
    fontSize: 15,
    ...customerWorkerTypography.body,
  },
  homeMapSpace: {
    height: 112,
  },
  homeSheet: {
    boxShadow: 'none',
    gap: 16,
    marginTop: 12,
    minHeight: 620,
    padding: 0,
  },
  homeHeroStack: {
    gap: 16,
  },
  homeAddressCard: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    minHeight: 62,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  homeAddressCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  homeAddressValue: {
    fontSize: 16,
    ...customerWorkerTypography.label,
    lineHeight: 20,
  },
  homeAddressMeta: {
    fontSize: 12,
    ...customerWorkerTypography.body,
    lineHeight: 15,
  },
  homeCommandHero: {
    borderRadius: 28,
    borderWidth: 1,
    boxShadow: '0 18px 38px rgba(21,89,78,0.08)',
    minHeight: 214,
    overflow: 'hidden',
    padding: 16,
  },
  homeCommandHitArea: {
    flex: 1,
    gap: 12,
    minHeight: 176,
    position: 'relative',
  },
  homeCommandHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
    position: 'relative',
    zIndex: 2,
  },
  homeCommandCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  homeCommandOpen: {
    alignItems: 'center',
    borderRadius: 17,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  homeCommandTitle: {
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 23,
  },
  homeCommandSubtitle: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 16,
  },
  homeCommandBody: {
    fontSize: 14,
    ...customerWorkerTypography.body,
    lineHeight: 20,
    position: 'relative',
    zIndex: 2,
  },
  homeCommandContext: {
    alignItems: 'center',
    borderRadius: 19,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 7,
    position: 'relative',
    zIndex: 2,
  },
  homeCommandContextCopy: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  homeCommandContextLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 14,
  },
  homeCommandContextValue: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 17,
  },
})
