// Customer UI StyleSheet partition 3, extracted from customer-surfaces.tsx (C4 customer split). Merged in styles.ts.
import { Platform, StyleSheet } from 'react-native'
import { customerDockHeight, customerFrameHorizontalPadding } from './constants'
import { customerWorkerTypography } from './constants'

export const customerStyles3 = StyleSheet.create({
  activityTimelineRail: {
    borderRadius: 999,
    bottom: 31,
    left: 23,
    position: 'absolute',
    top: 34,
    width: 2,
    zIndex: 0,
  },
  activityTimelineMarker: {
    alignItems: 'center',
    flexShrink: 0,
    width: 14,
  },
  activityTimelineDot: {
    borderWidth: 2,
    height: 13,
    width: 13,
  },
  activityTimelineCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  timelineRowDone: {
    gap: 11,
    minHeight: 36,
  },
  timelineRowCompact: {
    gap: 8,
    minHeight: 18,
  },
  timelineDot: {
    borderRadius: 999,
    height: 10,
    width: 10,
  },
  timelineDotCompact: {
    height: 8,
    width: 8,
  },
  timelineText: {
    fontSize: 13,
    ...customerWorkerTypography.body,
  },
  timelineTextCompact: {
    fontSize: 12,
    lineHeight: 14,
  },
  workerCard: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  workerActions: {
    gap: 8,
    minWidth: 112,
  },
  workerAvatar: {
    borderRadius: 18,
    borderWidth: 1,
    height: 48,
    width: 48,
  },
  workerMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  workerMetaPill: {
    borderRadius: 999,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  reviewRatingButton: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  evidenceTile: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 76,
    overflow: 'hidden',
  },
  evidenceText: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0,
  },
  profileHead: {
    borderRadius: 28,
    borderWidth: 1,
    gap: 12,
    overflow: 'hidden',
    padding: 15,
  },
  profilePrototypeHero: {
    borderCurve: 'continuous',
    borderRadius: 30,
    borderWidth: 1,
    gap: 14,
    minHeight: 114,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 17,
    position: 'relative',
  },
  profilePrototypeTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 4,
  },
  profilePrototypeTitleRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  profilePrototypeTitleCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  profilePrototypeTitle: {
    fontSize: 24,
    ...customerWorkerTypography.screenTitle,
    lineHeight: 29,
  },
  profileIdentityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minWidth: 0,
  },
  profileActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  profileName: {
    flex: 1,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0,
    minWidth: 0,
  },
  statusCard: {
    borderRadius: 28,
    borderWidth: 1,
    boxShadow: 'none',
    gap: 26,
    minHeight: 154,
    overflow: 'hidden',
    padding: 18,
  },
  statusAccentTile: {
    borderRadius: 28,
    height: 140,
    opacity: 0.2,
    position: 'absolute',
    right: -34,
    top: 20,
    transform: [{ rotate: '-10deg' }],
    width: 140,
  },
  statusTitle: {
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 31,
  },
  metricRow: {
    flexDirection: 'row',
    gap: 14,
  },
  metric: {
    flex: 1,
    gap: 5,
  },
  metricLabel: {
    fontSize: 11,
    ...customerWorkerTypography.body,
  },
  metricValue: {
    fontSize: 16,
    fontVariant: ['tabular-nums'],
    fontWeight: '600',
    letterSpacing: 0,
  },
  quickGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  quickCard: {
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    gap: 12,
    minHeight: 88,
    overflow: 'hidden',
    padding: 13,
  },
  quickTitle: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 18,
  },
  listCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 0,
    overflow: 'hidden',
    padding: 6,
    position: 'relative',
  },
  profileGlassListCard: {
    borderCurve: 'continuous',
    borderRadius: 29,
    gap: 8,
    paddingHorizontal: 13,
    paddingVertical: 14,
  },
  profileListSectionTitle: {
    fontSize: 11,
    ...customerWorkerTypography.label,
    lineHeight: 14,
    paddingHorizontal: 6,
    paddingBottom: 2,
    position: 'relative',
    zIndex: 2,
  },
  profileActions: {
    borderCurve: 'continuous',
    borderRadius: 29,
    overflow: 'hidden',
  },
  profileCareWideWrap: {
    marginHorizontal: -5,
    overflow: 'visible',
  },
  profileCareCard: {
    borderCurve: 'continuous',
    borderRadius: 29,
    borderWidth: 1,
    gap: 11,
    minHeight: 146,
    overflow: 'hidden',
    paddingHorizontal: 15,
    paddingVertical: 15,
    position: 'relative',
  },
  profileCareHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 2,
  },
  profileCareTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 21,
    minWidth: 0,
  },
  profileCareStats: {
    borderRadius: 18,
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 2,
  },
  profileCareStat: {
    alignItems: 'center',
    borderRadius: 15,
    borderWidth: 1,
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minHeight: 74,
    paddingHorizontal: 6,
    paddingVertical: 7,
  },
  profileCareStatIcon: {
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    flexShrink: 0,
    height: 31,
    justifyContent: 'center',
    width: 31,
  },
  profileCareStatCopy: {
    alignItems: 'center',
    gap: 2,
    minWidth: 0,
  },
  profileCareStatLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 13,
    textAlign: 'center',
  },
  profileCareStatValue: {
    fontSize: 12.5,
    ...customerWorkerTypography.label,
    lineHeight: 15,
    maxWidth: 84,
    textAlign: 'center',
  },
  profileEditorScrim: {
    backgroundColor: 'rgba(8,20,17,0.28)',
    flex: 1,
    justifyContent: 'flex-end',
    padding: 16,
  },
  profileEditorSheet: {
    borderRadius: 28,
    borderWidth: 1,
    gap: 12,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
  },
  profileEditorTitle: {
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 22,
    position: 'relative',
    zIndex: 2,
  },
  profileEditorHelper: {
    fontSize: 12.5,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 17,
    position: 'relative',
    zIndex: 2,
  },
  profileEditorInput: {
    borderCurve: 'continuous',
    borderRadius: 18,
    borderWidth: 1,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 20,
    minHeight: 52,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'relative',
    zIndex: 2,
  },
  profileEditorInputMultiline: {
    minHeight: 92,
  },
  feedbackInput: {
    minHeight: 132,
  },
  passwordField: {
    gap: 6,
  },
  passwordFieldLabel: {
    fontSize: 12.5,
    ...customerWorkerTypography.label,
    lineHeight: 16,
  },
  profileEditorError: {
    fontSize: 12.5,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 16,
  },
  profileEditorButtonRow: {
    flexDirection: 'row',
    gap: 10,
    position: 'relative',
    zIndex: 2,
  },
  profileEditorButton: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
  },
  profileEditorPrimaryButton: {
    boxShadow: '0 12px 24px rgba(41,173,151,0.18)',
  },
  profileEditorSecondaryButton: {
    boxShadow: 'none',
  },
  profileEditorPrimaryText: {
    fontSize: 14,
    ...customerWorkerTypography.label,
    lineHeight: 17,
  },
  profileEditorSecondaryText: {
    fontSize: 14,
    ...customerWorkerTypography.label,
    lineHeight: 17,
  },
  accountInfoSheet: {
    borderRadius: 30,
    borderWidth: 1,
    gap: 10,
    maxHeight: '88%',
    overflow: 'hidden',
    paddingBottom: 14,
    paddingHorizontal: 14,
    paddingTop: 10,
    position: 'relative',
  },
  accountInfoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 42,
    position: 'relative',
    zIndex: 2,
  },
  accountInfoBackButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  accountInfoBackText: {
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 30,
  },
  accountInfoTitle: {
    flex: 1,
    fontSize: 16,
    ...customerWorkerTypography.label,
    lineHeight: 20,
    textAlign: 'center',
  },
  accountInfoHeaderSpacer: {
    width: 38,
  },
  accountInfoFields: {
    gap: 8,
    paddingBottom: 4,
    paddingTop: 2,
  },
  accountInfoField: {
    borderCurve: 'continuous',
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    minHeight: 76,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 11,
    position: 'relative',
    zIndex: 2,
  },
  accountInfoFieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 16,
  },
  accountInfoFieldInput: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 19,
    minHeight: 30,
    paddingHorizontal: 0,
    paddingVertical: 2,
  },
  accountInfoSegmentRow: {
    flexDirection: 'row',
    gap: 8,
    minHeight: 38,
  },
  accountInfoSegmentButton: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  accountInfoSegmentText: {
    fontSize: 12,
    ...customerWorkerTypography.label,
    lineHeight: 15,
  },
  accountInfoNote: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 15,
    paddingTop: 10,
  },
  accountInfoVerification: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
    minHeight: 64,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 2,
  },
  accountInfoVerificationCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  accountInfoVerificationTitle: {
    fontSize: 13,
    ...customerWorkerTypography.label,
    lineHeight: 17,
  },
  accountInfoVerificationBody: {
    fontSize: 11.5,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 15,
  },
  accountInfoSaveButton: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 999,
    borderWidth: 1,
    boxShadow: '0 12px 24px rgba(41,173,151,0.18)',
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
    position: 'relative',
    zIndex: 2,
  },
  listRow: {
    alignItems: 'center',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 7,
    position: 'relative',
    zIndex: 2,
  },
  profileListRow: {
    borderCurve: 'continuous',
    borderRadius: 16,
    minHeight: 58,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileRowIconStage: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 14,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    overflow: 'visible',
    width: 32,
  },
  listCopy: {
    flex: 1,
    gap: 3,
  },
  profileListCopy: {
    gap: 3,
    minWidth: 0,
  },
  listTitle: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0,
  },
  profileListTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
  },
  listMeta: {
    fontSize: 13,
    ...customerWorkerTypography.body,
  },
  profileListMeta: {
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 15,
    maxWidth: '100%',
    textAlign: 'left',
  },
  listMetaCompact: {
    fontSize: 11,
    lineHeight: 13,
  },
  disabled: {
    opacity: 0.56,
  },
  chevron: {
    fontSize: 24,
    fontWeight: '400',
    letterSpacing: 0,
  },
  switchTrack: {
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 62,
  },
  switchKnob: {
    borderRadius: 999,
    height: 26,
    width: 26,
  },
  themeToggle: {
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 3,
    width: 60,
  },
  themeKnob: {
    borderRadius: 999,
    height: 24,
    width: 24,
  },
  iconButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 48,
  },
  iconShell: {
    alignItems: 'center',
    borderWidth: 1,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  clientImageIconShell: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    boxShadow: 'none',
    overflow: 'visible',
  },
  clientImageIconStage: {
    alignItems: 'center',
    flexShrink: 0,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
  },
  clientImageIcon: {
    flexShrink: 0,
    position: 'relative',
    zIndex: 2,
  },
  clientImageAssetBacking: {
    borderRadius: 999,
    borderWidth: 1,
    bottom: 2,
    left: 2,
    position: 'absolute',
    right: 2,
    top: 2,
    zIndex: 0,
  },
  clientImageAssetSoftener: {
    borderRadius: 999,
    borderWidth: 1,
    bottom: 0,
    left: 0,
    opacity: 0.72,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 3,
  },
  kaelMascotFrame: {
    alignItems: 'center',
    borderWidth: 1,
    boxShadow: '0 6px 16px rgba(8,120,110,0.06)',
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 16,
  },
  primaryButtonCompact: {
    minHeight: 44,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
  },
  secondaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
  },
})
