// @generated by scripts/split-database-types.mjs — do not edit by hand

/* @slice:begin json */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

/* @slice:end json */

export type DatabasePreamble = {
/* @slice:begin database-preamble */
/* @slice:end database-preamble */
}

export type GraphqlPublicSchema = {
/* @slice:begin graphql */
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
/* @slice:end graphql */
}

export type PublicCompositeTypes = {
/* @slice:begin composite */
      [_ in never]: never
/* @slice:end composite */
}
