// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from './base.database.types'
import type { Database } from './schema.database.types'

export type DatabaseFunctions = {
/* @slice:begin functions */
      accept_broadcast_atomic: {
        Args: { p_job_id: string; p_worker_id: string }
        Returns: {
          already_applied: boolean
          candidate_id: string
          error_code: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
        }[]
      }
      acquire_harness_dependency_permit: {
        Args: {
          p_dependency: string
          p_environment: string
          p_half_open_probes: number
          p_probe_ttl_seconds: number
        }
        Returns: {
          allowed: boolean
          probe_token: string
          retry_after_ms: number
          state: string
        }[]
      }
      activate_job_broadcast_batch_atomic: {
        Args: {
          p_batch_id: string
          p_expires_at: string
          p_job_id: string
          p_sent_at: string
          p_worker_ids: string[]
        }
        Returns: {
          id: string
          worker_id: string
        }[]
      }
      admin_approve_learning_candidate: {
        Args: {
          p_admin_id: string
          p_candidate_id: string
          p_review_note?: string
        }
        Returns: {
          candidate_id: string
          error_code: string
          ok: boolean
          rule_id: string
          rule_version: number
          status: string
        }[]
      }
      admin_approve_learning_candidate_atomic: {
        Args: {
          p_admin_id: string
          p_candidate_id: string
          p_review_note?: string
        }
        Returns: {
          candidate_id: string
          error_code: string
          knowledge_error_code: string
          knowledge_ok: boolean
          knowledge_table: string
          knowledge_version: number
          ok: boolean
          record_key: string
          rule_id: string
          rule_version: number
          status: string
        }[]
      }
      admin_cancel_manager_nomination_atomic: {
        Args: { p_nomination_id: string; p_owner_id: string }
        Returns: {
          error_code: string
          nomination_id: string
          ok: boolean
        }[]
      }
      admin_claim_worker_withdrawal_atomic: {
        Args: { p_actor_id: string; p_request_id: string }
        Returns: {
          error_code: string
          ok: boolean
          processing_at_out: string
          processing_by_out: string
          request_id: string
          status_out: string
        }[]
      }
      admin_decide_dispute_atomic: {
        Args: {
          p_admin_id: string
          p_customer_trust_impact?: string
          p_dispute_id: string
          p_outcome: string
          p_reasoning?: string
          p_refund_amount?: number
          p_worker_action?: string
          p_worker_credit_amount?: number
        }
        Returns: {
          decided_at_ts: string
          dispute_id: string
          dispute_status: string
          error_code: string
          ok: boolean
        }[]
      }
      admin_finance_summary: {
        Args: { p_actor_id: string; p_from: string; p_to: string }
        Returns: Json
      }
      admin_nominate_manager_atomic: {
        Args: { p_owner_id: string; p_target_id: string }
        Returns: {
          baseline_role_out: Database["public"]["Enums"]["user_role"]
          error_code: string
          nominated_at_out: string
          nomination_id: string
          ok: boolean
          user_id: string
        }[]
      }
      admin_operations_snapshot: { Args: { p_actor_id: string }; Returns: Json }
      admin_reject_learning_candidate: {
        Args: { p_admin_id: string; p_candidate_id: string; p_reason: string }
        Returns: {
          candidate_id: string
          error_code: string
          ok: boolean
          status: string
        }[]
      }
      admin_resolve_worker_withdrawal_atomic: {
        Args: {
          p_actor_id: string
          p_decision: string
          p_reason?: string
          p_request_id: string
          p_transfer_reference?: string
        }
        Returns: {
          error_code: string
          ok: boolean
          processed_at_out: string
          request_id: string
          status_out: string
        }[]
      }
      admin_review_and_approve_learning_candidate_atomic: {
        Args: {
          p_admin_id: string
          p_candidate_id: string
          p_review_note?: string
        }
        Returns: {
          candidate_id: string
          error_code: string
          knowledge_error_code: string
          knowledge_ok: boolean
          knowledge_table: string
          knowledge_version: number
          ok: boolean
          record_key: string
          rule_id: string
          rule_version: number
          status: string
        }[]
      }
      admin_review_worker_application_atomic: {
        Args: {
          p_admin_id: string
          p_decision: string
          p_queue_id: string
          p_reason?: string
        }
        Returns: {
          decided_at: string
          decision: string
          error_code: string
          ok: boolean
          queue_id: string
          role_out: Database["public"]["Enums"]["user_role"]
          status_out: string
          verification_status_out: Database["public"]["Enums"]["worker_verification_status"]
          worker_id: string
        }[]
      }
      admin_review_worker_payout_method_atomic: {
        Args: {
          p_actor_id: string
          p_decision: string
          p_payout_method_id: string
          p_reason?: string
        }
        Returns: {
          error_code: string
          ok: boolean
          payout_method_id: string
          reviewed_at_out: string
          status_out: string
        }[]
      }
      admin_set_sub_admin_access_atomic: {
        Args: {
          p_action: string
          p_capabilities?: string[]
          p_owner_id: string
          p_reason?: string
          p_target_id: string
        }
        Returns: {
          capabilities_out: string[]
          error_code: string
          ok: boolean
          role_out: Database["public"]["Enums"]["user_role"]
          status_out: string
          updated_at_out: string
          user_id: string
        }[]
      }
      admin_set_worker_access_atomic: {
        Args: {
          p_action: string
          p_actor_id: string
          p_reason: string
          p_worker_id: string
        }
        Returns: {
          decided_at: string
          error_code: string
          is_suspended_out: boolean
          ok: boolean
          verification_status_out: Database["public"]["Enums"]["worker_verification_status"]
          worker_id: string
        }[]
      }
      append_customer_kael_conversation_exchange: {
        Args: {
          p_client_request_id: string
          p_conversation_id: string
          p_customer_id: string
          p_customer_text: string
          p_kael_text: string
        }
        Returns: number
      }
      append_harness_evaluation_sample: {
        Args: {
          p_authorization_bypass: boolean
          p_case_class: string
          p_case_id: string
          p_confirmation_bypass: boolean
          p_cost_usd: number
          p_critical_safety_failure: boolean
          p_error_code: string
          p_evaluation_id: string
          p_latency_ms: number
          p_provider: string
          p_provider_attempt_id: string
          p_repetition: number
          p_resolved_model: string
          p_safe_metadata?: Json
          p_sample_id: string
          p_success: boolean
          p_tool_call_correct: boolean
        }
        Returns: string
      }
      append_harness_event: {
        Args: {
          p_attempt_number: number
          p_cost_usd: number
          p_environment: string
          p_error_code: string
          p_event_class: string
          p_event_id: string
          p_latency_ms: number
          p_model: string
          p_parent_event_id: string
          p_provider: string
          p_release_id: string
          p_run_id: string
          p_safe_metadata?: Json
          p_stage: string
          p_status: string
          p_tool_call_id: string
          p_tool_id: string
          p_trace_id: string
          p_turn_id: string
        }
        Returns: string
      }
      apply_approved_learning_candidate_to_knowledge: {
        Args: { p_admin_id: string; p_candidate_id: string }
        Returns: {
          error_code: string
          knowledge_table: string
          knowledge_version: number
          ok: boolean
          record_key: string
        }[]
      }
      apply_job_incident_assistant_turn_atomic: {
        Args: {
          p_assistant_claim_id: string
          p_event_content: string
          p_evidence_status: string
          p_expected_revision: number
          p_incident_id: string
          p_job_id: string
          p_message_content: string
          p_next_actor: string
          p_question: string
          p_safe_metadata: Json
          p_source_event_id: string
          p_status: string
          p_summary: string
        }
        Returns: {
          applied: boolean
          error_code: string
          incident: Json
          ok: boolean
          stale: boolean
        }[]
      }
      apply_kael_autonomy_decision: {
        Args: {
          p_expected_from: Database["public"]["Enums"]["job_status"]
          p_gate_audit_id: string
          p_job_id: string
          p_to_status: Database["public"]["Enums"]["job_status"]
        }
        Returns: {
          applied_at: string
          error: string
          from_status: Database["public"]["Enums"]["job_status"]
          job_id: string
          ok: boolean
          to_status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      apply_scope_change_database_effect_atomic: {
        Args: {
          p_client_request_id: string
          p_effect_id: string
          p_job_id: string
          p_scope_change_id: string
          p_worker_id: string
        }
        Returns: {
          completed: boolean
          effect_id: string
          error_code: string
          ok: boolean
        }[]
      }
      apply_scope_change_learning_effect_atomic: {
        Args: {
          p_client_request_id: string
          p_effect_id: string
          p_job_id: string
          p_scope_change_id: string
          p_worker_id: string
        }
        Returns: {
          completed: boolean
          effect_id: string
          error_code: string
          ok: boolean
        }[]
      }
      apply_sepay_vietqr_payment_webhook: {
        Args: {
          p_payment_code: string
          p_reference_code?: string
          p_transaction_id: string
          p_transfer_amount: number
        }
        Returns: {
          job_id: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
          outcome: string
          payment_status: string
        }[]
      }
      archive_stale_kael_memory: {
        Args: { p_archive_before?: string }
        Returns: {
          archived_from: string
          subject_id: string
          subject_type: string
        }[]
      }
      auto_promote_learning_candidate_atomic: {
        Args: { p_candidate_id: string }
        Returns: {
          candidate_id: string
          error_code: string
          ok: boolean
          rule_id: string
          rule_version: number
          status: string
        }[]
      }
      begin_harness_evaluation: {
        Args: {
          p_evaluation_id: string
          p_evaluator_id: string
          p_evaluator_kind: string
          p_evaluator_version: string
          p_evidence_class: string
          p_git_sha: string
          p_policy_bundle_sha256: string
          p_prompt_bundle_sha256: string
          p_release_id: string
          p_safe_metadata?: Json
        }
        Returns: boolean
      }
      begin_harness_run: {
        Args: {
          p_actor_id_hash: string
          p_actor_role: string
          p_capability: string
          p_environment: string
          p_job_id: string
          p_parent_run_id: string
          p_release_id: string
          p_route_kind: string
          p_run_id: string
          p_safe_metadata?: Json
          p_trace_id: string
        }
        Returns: boolean
      }
      begin_job_matching_preference_atomic: {
        Args: {
          p_customer_id: string
          p_final_price: number
          p_job_id: string
          p_worker_brief_core: Json
        }
        Returns: {
          error_code: string
          ok: boolean
        }[]
      }
      cancel_job_after_accept_atomic: {
        Args: {
          p_abuse_signals?: string[]
          p_customer_id: string
          p_job_id: string
          p_reason_category?: string
          p_reason_code: string
          p_reason_note?: string
        }
        Returns: {
          abuse_signals: string[]
          admin_review_required: boolean
          cancellation_id: string
          created_at_ts: string
          error_code: string
          job_id_out: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
          phase0_no_monetary_penalty: boolean
          reason_category: string
          reason_code: string
          sub_case: string
          worker_goodwill: Json
          worker_id_out: string
        }[]
      }
      cancel_job_before_accept_atomic: {
        Args: { p_customer_id: string; p_job_id: string }
        Returns: {
          cancelled_at_ts: string
          error_code: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
        }[]
      }
      check_kael_ai_spend: {
        Args: {
          p_actor_id: string
          p_estimated_usd: number
          p_global_daily_cap: number
          p_user_daily_cap: number
          p_user_monthly_cap: number
        }
        Returns: {
          allowed: boolean
          blocked_scope: string
          global_today_usd: number
          user_month_usd: number
          user_today_usd: number
        }[]
      }
      check_kael_chat_rate: {
        Args: { p_per_hour?: number; p_per_minute?: number; p_user_id: string }
        Returns: {
          allowed: boolean
          hour_count: number
          minute_count: number
          reason: string
        }[]
      }
      check_kael_worker_chat_rate: {
        Args: {
          p_per_hour?: number
          p_per_minute?: number
          p_worker_id: string
        }
        Returns: {
          allowed: boolean
          hour_count: number
          minute_count: number
          reason: string
        }[]
      }
      claim_job_broadcast_retry_atomic: {
        Args: {
          p_claim_token: string
          p_customer_id: string
          p_job_id: string
          p_lease_seconds?: number
        }
        Returns: {
          claimed: boolean
          error_code: string
        }[]
      }
      claim_job_incident_chat_turn_atomic: {
        Args: {
          p_actor_id: string
          p_actor_role: string
          p_assistant_claim_id: string
          p_content: string
          p_job_id: string
          p_message_id: string
        }
        Returns: {
          claimed: boolean
          error_code: string
          idempotent: boolean
          incident: Json
          ok: boolean
          revision: number
          source_event_id: string
        }[]
      }
      claim_job_incident_scope_proposal_atomic: {
        Args: {
          p_claim_id: string
          p_job_id: string
          p_quote_id: string
          p_worker_id: string
        }
        Returns: {
          claimed: boolean
          error_code: string
          idempotent: boolean
          incident: Json
          ok: boolean
        }[]
      }
      claim_job_media_cleanup_batch: {
        Args: { p_claim_token: string; p_limit?: number; p_now?: string }
        Returns: {
          intent_id: string
          object_path: string
        }[]
      }
      claim_kael_ai_batch_results: {
        Args: {
          p_claim_token: string
          p_force_poll: boolean
          p_lease_seconds: number
          p_limit: number
          p_now: string
        }
        Returns: {
          created_at: string
          id: string
          next_poll_at: string
          provider_batch_id: string
          status: string
        }[]
      }
      claim_kael_chat_media_cleanup_batch: {
        Args: { p_claim_token: string; p_limit?: number; p_now?: string }
        Returns: {
          intent_id: string
          object_path: string
        }[]
      }
      claim_kael_learning_queue_atomic: {
        Args: { p_claim_id: string; p_limit?: number; p_now?: string }
        Returns: {
          actor_id: string | null
          actor_role: string | null
          attempts: number
          batch_id: string | null
          candidate_payload: Json
          claim_id: string | null
          claimed_at: string | null
          created_at: string
          error_code: string | null
          event_type: string
          finalized_claim_id: string | null
          id: string
          input_payload: Json
          job_id: string | null
          processed_at: string | null
          provider_batch_id: string | null
          queue_state: string
          run_after: string
          skill_id: string
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "kael_learning_queue"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      claim_manual_bank_payment: {
        Args: {
          p_customer_id: string
          p_job_id: string
          p_sending_bank?: string
          p_transferred_at: string
        }
        Returns: {
          job_id: string
          notification_required: boolean
          payment_status: string
          status: Database["public"]["Enums"]["job_status"]
          transfer_claimed_at: string
        }[]
      }
      claim_saved_worker_fallback_atomic: {
        Args: {
          p_expected_worker_id?: string
          p_job_id: string
          p_reason: string
        }
        Returns: {
          claimed: boolean
          customer_id: string
          error_code: string
          preferred_worker_id: string
        }[]
      }
      claim_scope_change_push_effect_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_effect_id: string
          p_job_id: string
          p_scope_change_id: string
          p_worker_id: string
        }
        Returns: {
          claimed: boolean
          completed: boolean
          customer_id: string
          effect_id: string
          error_code: string
          ok: boolean
        }[]
      }
      claim_scope_change_request_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_evidence_photo_urls: string[]
          p_job_id: string
          p_new_description: string
          p_reason: string
          p_worker_id: string
        }
        Returns: {
          claimed: boolean
          created_at_ts: string
          error_code: string
          ok: boolean
          replayed: boolean
          request_state: string
          response_payload: Json
          scope_change_id: string
          scope_status: Database["public"]["Enums"]["scope_change_status"]
          side_effects_state: Json
        }[]
      }
      claim_worker_kael_chat_turn_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_content_type: string
          p_job_id: string
          p_media_refs: string[]
          p_now?: string
          p_session_id: string
          p_text_content: string
          p_worker_id: string
        }
        Returns: {
          assistant_turn_id: string
          claimed: boolean
          completed: boolean
          error_code: string
          lease_expires_at: string
          ok: boolean
          request_id: string
          worker_turn_id: string
          worker_turn_index: number
        }[]
      }
      claim_worker_kael_general_turn_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_content_type: string
          p_media_refs: string[]
          p_now?: string
          p_session_id: string
          p_text_content: string
          p_worker_id: string
        }
        Returns: {
          assistant_turn_id: string
          claimed: boolean
          completed: boolean
          error_code: string
          lease_expires_at: string
          ok: boolean
          request_id: string
          worker_turn_id: string
          worker_turn_index: number
        }[]
      }
      cleanup_orphan_analyzing_jobs: {
        Args: { p_cutoff?: string }
        Returns: {
          cleaned_count: number
        }[]
      }
      commit_kael_ai_batch_item_result: {
        Args: {
          p_batch_id: string
          p_claim_token: string
          p_error_payload: Json
          p_item_id: string
          p_item_status: string
          p_processed_at: string
          p_queue_error_code: string
          p_queue_id: string
          p_queue_state: string
          p_response_payload: Json
        }
        Returns: undefined
      }
      commit_kael_learning_effect_atomic: {
        Args: {
          p_batch_id: string
          p_effect_payload: Json
          p_error_payload: Json
          p_item_id: string
          p_item_status: string
          p_owner_token: string
          p_processed_at: string
          p_queue_error_code: string
          p_queue_id: string
          p_queue_state: string
          p_response_payload: Json
          p_source_mode: string
        }
        Returns: undefined
      }
      complete_customer_account_deletion: {
        Args: { p_client_request_id: string; p_customer_id: string }
        Returns: {
          checkpoint: string
          request_id: string
          request_status: string
        }[]
      }
      complete_harness_idempotency: {
        Args: { p_reservation_id: string; p_response_hash: string }
        Returns: boolean
      }
      complete_job_media_cleanup: {
        Args: { p_claim_token: string; p_intent_ids: string[]; p_now?: string }
        Returns: number
      }
      complete_kael_ai_batch_results_claim: {
        Args: { p_batch_id: string; p_claim_token: string }
        Returns: undefined
      }
      complete_kael_chat_media_cleanup: {
        Args: { p_claim_token: string; p_intent_ids: string[]; p_now?: string }
        Returns: number
      }
      complete_kael_learning_queue_realtime_atomic: {
        Args: { p_claim_id: string; p_now?: string; p_queue_ids: string[] }
        Returns: {
          completed_queue_id: string
          replayed: boolean
        }[]
      }
      complete_scope_change_push_effect_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_effect_id: string
          p_job_id: string
          p_scope_change_id: string
          p_worker_id: string
        }
        Returns: {
          completed: boolean
        }[]
      }
      complete_worker_kael_chat_turn_atomic: {
        Args: {
          p_ai_model: string
          p_ai_provider: Database["public"]["Enums"]["api_provider"]
          p_claim_id: string
          p_content_type: string
          p_cost_usd: number
          p_job_id: string
          p_latency_ms: number
          p_now?: string
          p_request_id: string
          p_safe_metadata: Json
          p_session_id: string
          p_session_metadata_patch: Json
          p_text_content: string
          p_worker_id: string
          p_worker_turn_id: string
        }
        Returns: {
          applied: boolean
          assistant_turn_id: string
          assistant_turn_index: number
          completed: boolean
          error_code: string
          ok: boolean
          stale: boolean
        }[]
      }
      complete_worker_kael_general_turn_atomic: {
        Args: {
          p_ai_model: string
          p_ai_provider: Database["public"]["Enums"]["api_provider"]
          p_claim_id: string
          p_content_type: string
          p_cost_usd: number
          p_latency_ms: number
          p_now?: string
          p_request_id: string
          p_safe_metadata: Json
          p_session_id: string
          p_session_metadata_patch: Json
          p_text_content: string
          p_worker_id: string
          p_worker_turn_id: string
        }
        Returns: {
          applied: boolean
          assistant_turn_id: string
          assistant_turn_index: number
          completed: boolean
          error_code: string
          ok: boolean
          stale: boolean
        }[]
      }
      confirm_kael_chat_atomic:
        | {
            Args: { p_customer_id: string; p_session_id: string }
            Returns: {
              district_code: string
              error_code: string
              job_id: string
              job_status: Database["public"]["Enums"]["job_status"]
              ok: boolean
              service_type: Database["public"]["Enums"]["service_type"]
            }[]
          }
        | {
            Args: {
              p_customer_id: string
              p_price_reasoning_receipt_id: string
              p_session_id: string
            }
            Returns: {
              district_code: string
              error_code: string
              job_id: string
              job_status: Database["public"]["Enums"]["job_status"]
              ok: boolean
              service_type: Database["public"]["Enums"]["service_type"]
            }[]
          }
      confirm_worker_candidate_atomic: {
        Args: {
          p_candidate_id: string
          p_customer_id: string
          p_job_id: string
        }
        Returns: {
          already_applied: boolean
          candidate_id: string
          error_code: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
          worker_id: string
        }[]
      }
      confirm_worker_cash_payment: {
        Args: { p_job_id: string; p_worker_id: string }
        Returns: {
          cash_commission_collected: number
          cash_commission_due: number
          commission_level: number
          commission_rate_bps: number
          gross_amount: number
          job_id: string
          job_status: Database["public"]["Enums"]["job_status"]
          outcome: string
          payment_received_at: string
          payment_status: string
          payment_updated_at: string
          platform_fee: number
          worker_net: number
        }[]
      }
      consume_job_media_uploads: {
        Args: {
          p_job_id: string
          p_now?: string
          p_object_paths: string[]
          p_owner_id: string
        }
        Returns: {
          consumed_count: number
          ok: boolean
          reason: string
        }[]
      }
      consume_kael_chat_media_uploads: {
        Args: {
          p_customer_id: string
          p_now?: string
          p_object_paths: string[]
        }
        Returns: {
          consumed_count: number
          ok: boolean
          reason: string
        }[]
      }
      create_manual_bank_payment_order: {
        Args: {
          p_customer_id: string
          p_expected_gross_amount: number
          p_job_id: string
          p_payment_code: string
          p_payment_updated_at?: string
          p_qr_image_url: string
          p_transfer_content: string
        }
        Returns: {
          gross_amount: number
          job_id: string
          payment_code: string
          payment_qr_image_url: string
          payment_status: string
          payment_transfer_content: string
          payment_updated_at: string
          status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      create_worker_vietqr_payment_intent: {
        Args: {
          p_customer_id: string
          p_expected_gross_amount: number
          p_job_id: string
          p_payment_code: string
          p_payment_updated_at?: string
          p_qr_image_url: string
          p_transfer_content: string
        }
        Returns: {
          commission_level: number
          commission_rate_bps: number
          gross_amount: number
          job_id: string
          job_status: Database["public"]["Enums"]["job_status"]
          payment_code: string
          payment_updated_at: string
          platform_fee: number
          qr_image_url: string
          transfer_content: string
          worker_net: number
        }[]
      }
      create_worker_withdrawal_request: {
        Args: {
          p_amount_vnd: number
          p_client_request_id: string
          p_worker_id: string
        }
        Returns: {
          amount_vnd_out: number
          available_balance_before_vnd_out: number
          bank_account_masked_out: string
          bank_key_out: string
          bank_name_out: string
          error_code: string
          ok: boolean
          request_id: string
          requested_at_out: string
          status_out: string
          updated_at_out: string
        }[]
      }
      decide_manual_bank_payment_reconciliation: {
        Args: {
          p_actor_id: string
          p_amount_received?: number
          p_bank_reference_hash?: string
          p_bank_reference_suffix?: string
          p_credited_at?: string
          p_decision: string
          p_payment_order_id: string
          p_reason_code?: string
        }
        Returns: {
          error_code: string
          hold_until: string
          job_id: string
          ok: boolean
          outcome: string
          payment_status: string
          status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      decide_scope_change_atomic: {
        Args: {
          p_customer_id: string
          p_decision: string
          p_scope_change_id: string
        }
        Returns: {
          decided_at_ts: string
          error_code: string
          job_id_out: string
          ok: boolean
          scope_status: Database["public"]["Enums"]["scope_change_status"]
        }[]
      }
      distance_km: {
        Args: { lat1: number; lat2: number; lng1: number; lng2: number }
        Returns: number
      }
      enqueue_worker_no_show_reviews: {
        Args: { p_now?: string }
        Returns: {
          fallback_options: Json
          job_id_out: string
          reason_code: string
          worker_id_out: string
        }[]
      }
      expire_harness_reliability_reservations: {
        Args: never
        Returns: {
          idempotency_expired: number
          probes_expired: number
          spend_expired: number
        }[]
      }
      fail_harness_idempotency: {
        Args: { p_error_code: string; p_reservation_id: string }
        Returns: boolean
      }
      fail_job_media_uploads: {
        Args: {
          p_job_id: string
          p_now?: string
          p_object_paths: string[]
          p_owner_id: string
        }
        Returns: {
          ok: boolean
          reason: string
          revoked_paths: string[]
        }[]
      }
      finalize_kael_ai_spend:
        | {
            Args: {
              p_actual_usd: number
              p_purpose: string
              p_reservation_id: number
            }
            Returns: undefined
          }
        | {
            Args: {
              p_actual_usd: number
              p_harness_release_id: string
              p_harness_run_id: string
              p_harness_trace_id: string
              p_provider_attempt_id: string
              p_purpose: string
              p_reservation_id: number
            }
            Returns: undefined
          }
      finish_harness_evaluation: {
        Args: {
          p_artifact_sha256: string
          p_evaluation_id: string
          p_metrics: Json
          p_safe_metadata?: Json
          p_sample_count: number
          p_status: string
          p_variance: Json
        }
        Returns: boolean
      }
      finish_harness_run: {
        Args: {
          p_duration_ms: number
          p_error_code: string
          p_run_id: string
          p_safe_metadata?: Json
          p_status: string
        }
        Returns: boolean
      }
      get_customer_profile_insights_aggregate: {
        Args: { p_customer_id: string }
        Returns: {
          active_service_days: number
          active_streak_days: number
          completed_service_count: number
          disputed_transaction_count: number
          fair_price_service_count: number
          has_primary_address: boolean
          kael_interaction_count: number
          member_since: string
          positive_review_rate_percent: number
          preferred_service_count: number
          price_savings_vnd: number
          protected_transaction_count: number
          protected_value_vnd: number
          reviewed_service_count: number
          total_spend_vnd: number
          total_transaction_count: number
        }[]
      }
      get_direct_worker_payment_availability: {
        Args: { p_customer_id: string; p_job_id: string }
        Returns: {
          direct_payment_available: boolean
        }[]
      }
      get_kael_provider_spend_today: { Args: never; Returns: number }
      get_worker_current_commission_tier: {
        Args: { p_worker_id: string }
        Returns: {
          commission_level: number
          commission_rate_bps: number
        }[]
      }
      get_worker_earnings_summary: {
        Args: {
          p_from?: string
          p_platform_fee_rate?: number
          p_to?: string
          p_worker_id: string
        }
        Returns: {
          available_balance: number
          cash_commission_collected_total: number
          cash_commission_due_total: number
          current_commission_level: number
          current_commission_rate_bps: number
          daily_earnings: Json
          from_date: string
          gross_earnings: number
          net_earnings: number
          on_hold_amount: number
          pending_payment_amount: number
          pending_payment_count: number
          platform_fee_total: number
          recent_transactions: Json
          to_date: string
          total_jobs_paid: number
          worker_id: string
        }[]
      }
      get_worker_payment_safety_balance: {
        Args: { p_worker_id: string }
        Returns: {
          available_balance: number
          collateral_reserved_amount: number
          withdrawal_reserved_amount: number
          withdrawn_total: number
        }[]
      }
      get_worker_performance_insights_aggregate: {
        Args: { p_worker_id: string }
        Returns: {
          accepted_broadcast_count: number
          average_response_minutes: number
          average_review_rating: number
          completed_job_count: number
          is_approved: boolean
          is_available: boolean
          is_suspended: boolean
          on_time_job_count: number
          paid_job_count: number
          profile_exists: boolean
          profile_rating: number
          profile_total_jobs: number
          reconciled_earnings_vnd: number
          resolved_incident_case_count: number
          responded_broadcast_count: number
          review_count: number
          scheduled_arrival_job_count: number
          total_broadcast_count: number
          verification_status: string
          work_response_review_count: number
          work_response_score: number
        }[]
      }
      increment_kael_market_cache_hit: {
        Args: { p_cache_id: string }
        Returns: undefined
      }
      insert_notification_atomic: {
        Args: {
          p_body: string
          p_event_type: string
          p_job_id: string
          p_safe_metadata?: Json
          p_title: string
          p_user_id: string
        }
        Returns: {
          created_at_ts: string
          notification_id: string
        }[]
      }
      is_circuit_open: {
        Args: { p_key: string; p_now?: string; p_scope: string }
        Returns: boolean
      }
      maintain_manual_bank_payment_holds: {
        Args: { p_limit?: number }
        Returns: {
          direct_reconcile_count: number
          direct_reconcile_job_ids: string[]
          released_count: number
        }[]
      }
      mark_harness_idempotency_reconcile_required: {
        Args: { p_error_code: string; p_reservation_id: string }
        Returns: boolean
      }
      match_kael_knowledge: {
        Args: {
          p_limit?: number
          p_min_similarity?: number
          p_query_embedding: string
          p_service_type?: string
        }
        Returns: {
          citation_id: string
          content: string
          knowledge_id: string
          knowledge_table: string
          record_key: string
          safe_metadata: Json
          service_type: string
          similarity: number
          title: string
        }[]
      }
      next_job_display_code: { Args: never; Returns: string }
      normalize_hcmc_district_code: {
        Args: { p_input: string }
        Returns: string
      }
      open_dispute_atomic: {
        Args: {
          p_dispute_type: string
          p_evidence_photo_urls?: string[]
          p_initiated_by: string
          p_initiated_by_id: string
          p_initiator_statement: string
          p_job_id: string
          p_kael_neutral_summary?: string
        }
        Returns: {
          admin_review_required: boolean
          created_at_ts: string
          dispute_id: string
          dispute_status: string
          error_code: string
          evidence_locked_at: string
          evidence_snapshot_id: string
          ok: boolean
          priority: string
        }[]
      }
      prepare_customer_account_deletion: {
        Args: { p_client_request_id: string; p_customer_id: string }
        Returns: {
          avatar_storage_ref: string
          checkpoint: string
          request_id: string
          request_status: string
        }[]
      }
      promote_learning_candidate: {
        Args: {
          p_actor_id?: string
          p_actor_role?: string
          p_affected_district?: string
          p_affected_problem?: string
          p_affected_service?: Database["public"]["Enums"]["service_type"]
          p_audit_reason?: string
          p_candidate_payload?: Json
          p_candidate_type: string
          p_confidence?: number
          p_effects?: string[]
          p_evidence_count?: number
          p_job_id?: string
          p_rule_payload?: Json
          p_skill_id: string
          p_target: string
        }
        Returns: {
          candidate_id: string
          error_code: string
          ok: boolean
          rule_id: string
          rule_version: number
        }[]
      }
      queue_learning_candidate_manual_review: {
        Args: {
          p_candidate_id: string
          p_consent_hash: string
          p_evidence_hash: string
          p_input_hash: string
          p_release_id: string
          p_safe_metadata?: Json
          p_source_hash: string
        }
        Returns: {
          candidate_id: string
          error_code: string
          ok: boolean
          status: string
        }[]
      }
      rate_take: {
        Args: {
          p_config: Json
          p_cost: number
          p_key: string
          p_now?: string
          p_scope: string
        }
        Returns: {
          allowed: boolean
          reason: string
          retry_after_ms: number
        }[]
      }
      read_harness_kill_switch: {
        Args: { p_environment: string; p_switch_id: string }
        Returns: {
          enabled: boolean
          reason_code: string
        }[]
      }
      record_circuit_failure: {
        Args: { p_key: string; p_kind: string; p_now?: string; p_scope: string }
        Returns: {
          is_open: boolean
        }[]
      }
      record_circuit_success: {
        Args: { p_key: string; p_scope: string }
        Returns: undefined
      }
      record_customer_cancellation_memory_atomic: {
        Args: {
          p_cancellation_id: string
          p_customer_id: string
          p_job_id: string
        }
        Returns: {
          applied: boolean
        }[]
      }
      record_harness_dependency_result: {
        Args: {
          p_dependency: string
          p_environment: string
          p_error_code: string
          p_half_open_probes: number
          p_open_ms: number
          p_probe_token?: string
          p_release_id: string
          p_success: boolean
          p_threshold: number
          p_window_ms: number
        }
        Returns: string
      }
      record_harness_privileged_operation: {
        Args: {
          p_actor_id_hash: string
          p_actor_role: string
          p_capability: string
          p_environment: string
          p_error_code: string
          p_operation_event_id: string
          p_operation_id: string
          p_reason: string
          p_release_id: string
          p_resource_id_hash: string
          p_resource_type: string
          p_result: string
          p_run_id: string
          p_safe_metadata?: Json
          p_trace_id: string
        }
        Returns: string
      }
      record_harness_slo_observation: {
        Args: {
          p_actual: number
          p_environment: string
          p_release_id: string
          p_safe_metadata?: Json
          p_slo_id: string
          p_window_ended_at: string
          p_window_started_at: string
        }
        Returns: string
      }
      record_kael_ai_batch_poll: {
        Args: {
          p_batch_id: string
          p_canceled_count: number
          p_claim_token: string
          p_ended_at: string
          p_errored_count: number
          p_expired_count: number
          p_expires_at: string
          p_next_poll_at: string
          p_processing_count: number
          p_results_url: string
          p_status: string
          p_succeeded_count: number
        }
        Returns: undefined
      }
      record_kael_ai_spend:
        | {
            Args: { p_actor_id: string; p_cost_usd: number; p_purpose: string }
            Returns: undefined
          }
        | {
            Args: {
              p_actor_id: string
              p_cost_usd: number
              p_harness_release_id: string
              p_harness_run_id: string
              p_harness_trace_id: string
              p_provider_attempt_id: string
              p_purpose: string
            }
            Returns: undefined
          }
      record_kael_provider_spend: {
        Args: { p_cost_usd: number }
        Returns: number
      }
      record_learning_observation_atomic: {
        Args: {
          p_affected_district: string
          p_affected_problem: string
          p_affected_service: Database["public"]["Enums"]["service_type"]
          p_baseline_max: number
          p_baseline_min: number
          p_candidate_type: string
          p_complexity: Database["public"]["Enums"]["complexity_level"]
          p_final_price: number
          p_job_id: string
          p_rating: number
          p_reference_max: number
          p_reference_min: number
          p_review_tags: string[]
          p_reviewed_at: string
          p_scope_change_requested: boolean
        }
        Returns: {
          candidate_id: string
          confidence: number
          error_code: string
          evidence_count: number
          idempotent: boolean
          is_new: boolean
          ok: boolean
          status: string
        }[]
      }
      record_normal_transaction_memory_atomic: {
        Args: { p_customer_id: string; p_job_id: string }
        Returns: {
          applied: boolean
        }[]
      }
      record_platform_bank_balance_snapshot: {
        Args: {
          p_actor_id: string
          p_balance_vnd: number
          p_observed_at: string
        }
        Returns: {
          balance_vnd: number
          observed_at: string
          snapshot_id: string
        }[]
      }
      record_worker_app_active_minute: {
        Args: { p_worker_id: string }
        Returns: {
          active_minutes: number
          incremented: boolean
          last_active_at: string
          worker_id: string
        }[]
      }
      record_worker_cancellation_memory_atomic: {
        Args: {
          p_cancellation_id: string
          p_job_id: string
          p_sub_case: string
          p_worker_id: string
        }
        Returns: {
          applied: boolean
        }[]
      }
      record_worker_disintermediation_memory_atomic: {
        Args: {
          p_job_id: string
          p_message_id: string
          p_signals: string[]
          p_worker_id: string
        }
        Returns: {
          applied: boolean
          disintermediation_risk_count: number
        }[]
      }
      record_worker_kael_qa_atomic: {
        Args: {
          p_answer: Json
          p_job_id: string
          p_now?: string
          p_question: string
          p_worker_id: string
        }
        Returns: {
          error_code: string
          ok: boolean
          qa_id: string
          remaining_questions: number
        }[]
      }
      register_device_push_token_atomic: {
        Args: {
          p_permission_status: string
          p_platform: string
          p_push_token: string
          p_safe_metadata?: Json
          p_user_id: string
        }
        Returns: {
          enabled_out: boolean
          token_id: string
          updated_at_ts: string
        }[]
      }
      register_harness_release: {
        Args: {
          p_access_matrix_sha256: string
          p_bundle_sha256: string
          p_capability_registry_sha256: string
          p_created_by: string
          p_database_types_sha256: string
          p_edge_function_digests: Json
          p_environment: string
          p_evaluation_suite_sha256: string
          p_evaluation_suite_version: string
          p_git_sha: string
          p_manifest_sha256: string
          p_migration_inventory_sha256: string
          p_policy_bundle_sha256: string
          p_previous_release_id: string
          p_promotion_policy_sha256: string
          p_prompt_bundle_sha256: string
          p_release_artifact: Json
          p_release_id: string
          p_reliability_policy_sha256: string
          p_runtime_configuration_sha256: string
          p_safe_metadata?: Json
        }
        Returns: {
          access_matrix_sha256: string
          bundle_sha256: string
          capability_registry_sha256: string
          created_at: string
          created_by: string
          database_types_sha256: string
          edge_function_digests: Json
          environment: string
          evaluation_suite_sha256: string
          evaluation_suite_version: string
          git_sha: string
          manifest_sha256: string
          migration_inventory_sha256: string
          policy_bundle_sha256: string
          previous_release_id: string | null
          promotion_policy_sha256: string
          prompt_bundle_sha256: string
          release_artifact: Json
          release_id: string
          reliability_policy_sha256: string
          runtime_configuration_sha256: string
          safe_metadata: Json
        }
        SetofOptions: {
          from: "*"
          to: "harness_releases"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      reject_worker_candidate_atomic: {
        Args: {
          p_candidate_id: string
          p_customer_id: string
          p_job_id: string
        }
        Returns: {
          already_applied: boolean
          candidate_id: string
          error_code: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
          worker_id: string
        }[]
      }
      release_job_broadcast_retry_claim_atomic: {
        Args: { p_claim_token: string; p_customer_id: string; p_job_id: string }
        Returns: {
          released: boolean
        }[]
      }
      release_job_incident_assistant_claim_atomic: {
        Args: {
          p_assistant_claim_id: string
          p_job_id: string
          p_source_event_id: string
        }
        Returns: {
          released: boolean
        }[]
      }
      release_job_incident_scope_proposal_atomic: {
        Args: { p_claim_id: string; p_incident_id: string; p_job_id: string }
        Returns: {
          released: boolean
        }[]
      }
      release_kael_ai_batch_results_claims: {
        Args: {
          p_claim_token: string
          p_error_code: string
          p_retry_at: string
        }
        Returns: undefined
      }
      release_scope_change_push_effect_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_effect_id: string
          p_error_code: string
          p_job_id: string
          p_scope_change_id: string
          p_worker_id: string
        }
        Returns: {
          released: boolean
        }[]
      }
      release_scope_change_request_claim_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_error_code: string
          p_job_id: string
          p_worker_id: string
        }
        Returns: {
          released: boolean
        }[]
      }
      release_worker_kael_chat_turn_claim_atomic: {
        Args: {
          p_claim_id: string
          p_discard?: boolean
          p_now?: string
          p_request_id: string
          p_session_id: string
          p_worker_id: string
        }
        Returns: {
          discarded: boolean
          released: boolean
        }[]
      }
      renew_kael_ai_batch_results_claim: {
        Args: {
          p_batch_id: string
          p_claim_token: string
          p_claimed_at: string
        }
        Returns: undefined
      }
      request_customer_cancellation_atomic: {
        Args: {
          p_customer_id: string
          p_job_id: string
          p_reason_code: string
          p_reason_note?: string
        }
        Returns: {
          abuse_signals: string[]
          admin_review_required: boolean
          cancellation_id: string
          created_at_ts: string
          error_code: string
          job_id_out: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
          phase0_no_monetary_penalty: boolean
          reason_category: string
          reason_code: string
          sub_case: string
          worker_goodwill: Json
          worker_id_out: string
        }[]
      }
      request_job_incident_scope_change_atomic: {
        Args: {
          p_claim_id: string
          p_evidence_photo_urls: string[]
          p_incident_id: string
          p_job_id: string
          p_kael_computed_max: number
          p_kael_computed_min: number
          p_kael_review: Json
          p_new_description: string
          p_reason: string
          p_worker_id: string
        }
        Returns: {
          created_at_ts: string
          error_code: string
          ok: boolean
          scope_change_id: string
          scope_status: Database["public"]["Enums"]["scope_change_status"]
        }[]
      }
      request_scope_change_atomic: {
        Args: {
          p_claim_id: string
          p_client_request_id: string
          p_database_effect_id?: string
          p_database_effect_payload?: Json
          p_evidence_photo_urls: string[]
          p_job_id: string
          p_kael_computed_max: number
          p_kael_computed_min: number
          p_kael_review: Json
          p_learning_effect_id?: string
          p_learning_effect_payload?: Json
          p_new_description: string
          p_push_effect_id?: string
          p_reason: string
          p_worker_id: string
        }
        Returns: {
          created_at_ts: string
          error_code: string
          ok: boolean
          replayed: boolean
          response_payload: Json
          scope_change_id: string
          scope_status: Database["public"]["Enums"]["scope_change_status"]
          side_effects_state: Json
        }[]
      }
      request_worker_cancellation_atomic: {
        Args: {
          p_evidence_photo_urls?: string[]
          p_job_id: string
          p_reason: string
          p_worker_id: string
        }
        Returns: {
          abuse_signals: string[]
          admin_review_required: boolean
          cancellation_id: string
          cancellation_status: string
          created_at_ts: string
          district_code: string
          error_code: string
          fallback_options: Json
          job_id_out: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
          reason_category: string
          reason_code: string
          service_type_out: Database["public"]["Enums"]["service_type"]
          worker_id_out: string
        }[]
      }
      reserve_harness_idempotency: {
        Args: {
          p_actor_id_hash: string
          p_environment: string
          p_key_hash: string
          p_operation_id: string
          p_release_id: string
          p_request_hash: string
          p_ttl_seconds: number
        }
        Returns: {
          reservation_id: string
          response_hash: string
          state: string
        }[]
      }
      reserve_job_media_upload: {
        Args: {
          p_file_size_bytes: number
          p_job_id: string
          p_mime_type: string
          p_now?: string
          p_object_path: string
          p_owner_id: string
          p_stage: string
        }
        Returns: {
          allowed: boolean
          expires_at: string
          intent_id: string
          reason: string
        }[]
      }
      reserve_kael_ai_spend:
        | {
            Args: {
              p_actor_id: string
              p_estimated_usd: number
              p_global_daily_cap: number
              p_purpose: string
              p_user_daily_cap: number
              p_user_monthly_cap: number
            }
            Returns: {
              allowed: boolean
              blocked_scope: string
              reservation_id: number
            }[]
          }
        | {
            Args: {
              p_actor_id: string
              p_estimated_usd: number
              p_global_daily_cap: number
              p_harness_release_id: string
              p_harness_run_id: string
              p_harness_trace_id: string
              p_provider_attempt_id: string
              p_purpose: string
              p_user_daily_cap: number
              p_user_monthly_cap: number
            }
            Returns: {
              allowed: boolean
              blocked_scope: string
              reservation_id: number
            }[]
          }
      reserve_kael_chat_media_upload: {
        Args: {
          p_customer_id: string
          p_file_size_bytes: number
          p_mime_type: string
          p_now?: string
          p_object_path: string
          p_purpose: string
        }
        Returns: {
          allowed: boolean
          expires_at: string
          intent_id: string
          reason: string
        }[]
      }
      respond_to_direct_worker_payment: {
        Args: {
          p_actor_id: string
          p_actor_role: string
          p_job_id: string
          p_received: boolean
        }
        Returns: {
          collateral_amount: number
          direct_status: string
          error_code: string
          job_id: string
          notification_required: boolean
          ok: boolean
          response_deadline: string
          status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      revoke_job_media_uploads: {
        Args: {
          p_job_id: string
          p_now?: string
          p_object_paths: string[]
          p_owner_id: string
        }
        Returns: {
          ok: boolean
          reason: string
          revoked_paths: string[]
        }[]
      }
      revoke_kael_chat_media_uploads: {
        Args: {
          p_customer_id: string
          p_now?: string
          p_object_paths: string[]
        }
        Returns: {
          ok: boolean
          reason: string
          revoked_paths: string[]
        }[]
      }
      revoke_learning_rule_with_provenance: {
        Args: {
          p_admin_id: string
          p_reason: string
          p_release_id: string
          p_rule_id: string
          p_rule_version: number
        }
        Returns: {
          cascaded_count: number
          error_code: string
          ok: boolean
          rule_id: string
          rule_version: number
        }[]
      }
      rollback_learning_rule: {
        Args: {
          p_reason?: string
          p_rule_id: string
          p_safe_metadata?: Json
          p_skill_id: string
        }
        Returns: {
          error_code: string
          ok: boolean
          rule_id: string
        }[]
      }
      save_job_incident_scope_price_quote_atomic: {
        Args: {
          p_expected_revision: number
          p_incident_id: string
          p_job_id: string
          p_quote: Json
          p_quote_expires_at: string
          p_quote_id: string
          p_worker_id: string
        }
        Returns: {
          error_code: string
          incident: Json
          ok: boolean
        }[]
      }
      select_direct_worker_payment: {
        Args: {
          p_client_request_id: string
          p_customer_id: string
          p_job_id: string
        }
        Returns: {
          collateral_amount: number
          direct_status: string
          error_code: string
          job_id: string
          ok: boolean
          response_deadline: string
          status: Database["public"]["Enums"]["job_status"]
        }[]
      }
      set_harness_kill_switch: {
        Args: {
          p_actor_id: string
          p_enabled: boolean
          p_environment: string
          p_reason_code: string
          p_release_id: string
          p_safe_metadata?: Json
          p_switch_id: string
        }
        Returns: boolean
      }
      set_job_matching_preference_atomic: {
        Args: {
          p_auto_general: boolean
          p_client_request_id: string
          p_customer_id: string
          p_job_id: string
          p_preferred_worker_id: string
          p_strategy: string
        }
        Returns: {
          auto_general: boolean
          error_code: string
          ok: boolean
          preferred_worker_id: string
          strategy: string
        }[]
      }
      set_worker_availability_atomic: {
        Args: { p_is_available: boolean; p_worker_id: string }
        Returns: {
          error_code: string
          is_available: boolean
          ok: boolean
          updated_at_ts: string
        }[]
      }
      start_harness_idempotency_execution: {
        Args: { p_reservation_id: string }
        Returns: boolean
      }
      submit_counter_statement_atomic: {
        Args: { p_actor_id: string; p_dispute_id: string; p_statement: string }
        Returns: {
          dispute_id: string
          dispute_status: string
          error_code: string
          ok: boolean
          updated_at_ts: string
        }[]
      }
      submit_review_atomic: {
        Args: {
          p_comment: string
          p_customer_id: string
          p_job_id: string
          p_rating: number
          p_tags: string[]
        }
        Returns: {
          error_code: string
          job_status: Database["public"]["Enums"]["job_status"]
          ok: boolean
          review_id: string
          reviewed_at_ts: string
        }[]
      }
      submit_worker_registration_atomic: {
        Args: {
          p_actor_id: string
          p_bank_account: string
          p_bank_name: string
          p_cccd_back_url: string
          p_cccd_front_url: string
          p_date_of_birth: string
          p_districts: string[]
          p_gender: string
          p_home_lat: number
          p_home_lng: number
          p_legal_name: string
          p_problem_specializations: string[]
          p_selfie_url: string
          p_service_radius_km: number
          p_service_types: Database["public"]["Enums"]["service_type"][]
          p_worker_id: string
          p_years_experience: number
        }
        Returns: {
          error_code: string
          idempotent_out: boolean
          ok: boolean
          submitted_at_ts: string
          verification_status_out: Database["public"]["Enums"]["worker_verification_status"]
          worker_id_out: string
        }[]
      }
      transition_harness_promotion: {
        Args: {
          p_actor_id: string
          p_approval_id: string
          p_environment: string
          p_evaluation_report_id: string
          p_expected_state: string
          p_next_state: string
          p_packet_sha256: string
          p_reason_code?: string
          p_release_id: string
          p_rollback_release_id: string
          p_safe_metadata?: Json
        }
        Returns: {
          error_code: string
          ok: boolean
          promotion_id: string
          state: string
        }[]
      }
      unregister_device_push_token_atomic: {
        Args: { p_push_token: string; p_user_id: string }
        Returns: {
          token_id: string
          unregistered_out: boolean
          updated_at_ts: string
        }[]
      }
      update_worker_kael_memory_preference: {
        Args: { p_enabled: boolean; p_key: string; p_worker_id: string }
        Returns: boolean
      }
      upsert_customer_refund_payment_method: {
        Args: {
          p_account_holder_name: string
          p_bank_account: string
          p_bank_key: string
          p_customer_id: string
        }
        Returns: {
          bank_account_masked: string
          bank_key: string
          bank_name: string
          id: string
          is_default: boolean
          status: string
          updated_at: string
          verified_at: string
        }[]
      }
      upsert_job_incident_signal_atomic: {
        Args: {
          p_assistant_claim_id: string
          p_content: string
          p_evidence_photo_urls: Json
          p_job_id: string
          p_opened_by: string
          p_reported_description: string
          p_reported_reason: string
          p_request_id: string
        }
        Returns: {
          claimed: boolean
          error_code: string
          idempotent: boolean
          incident: Json
          ok: boolean
          revision: number
          source_event_id: string
        }[]
      }
      upsert_worker_payout_method: {
        Args: {
          p_account_holder_name: string
          p_bank_account: string
          p_bank_key: string
          p_worker_id: string
        }
        Returns: {
          bank_account_masked: string
          bank_key: string
          bank_name: string
          id: string
          reviewed_at: string
          status: string
          updated_at: string
        }[]
      }
      validate_scope_change_evidence_refs: {
        Args: { p_job_id: string; p_media_refs: string[]; p_worker_id: string }
        Returns: {
          ok: boolean
          reason: string
          validated_refs: string[]
        }[]
      }
/* @slice:end functions */
}
