// Reassembles the generated schema. Written by hand; the parts it references are
// generated by scripts/split-database-types.mjs.

import type { DatabasePreamble, GraphqlPublicSchema, PublicCompositeTypes } from './base.database.types'
import type { DatabaseEnums } from './enums.database.types'
import type { DatabaseFunctions } from './functions.database.types'
import type { AdminTables } from './tables/admin.database.types'
import type { CoreTables } from './tables/core.database.types'
import type { CustomerTables } from './tables/customer.database.types'
import type { HarnessTables } from './tables/harness.database.types'
import type { JobsTables } from './tables/jobs.database.types'
import type { KaelTables } from './tables/kael.database.types'
import type { LearningTables } from './tables/learning.database.types'
import type { MatchingTables } from './tables/matching.database.types'
import type { ServiceTables } from './tables/service.database.types'
import type { WorkerTables } from './tables/worker.database.types'
import type { DatabaseViews } from './views.database.types'

export type Database = DatabasePreamble & {
  graphql_public: GraphqlPublicSchema
  public: {
    Tables: AdminTables &
      CoreTables &
      CustomerTables &
      HarnessTables &
      JobsTables &
      KaelTables &
      LearningTables &
      MatchingTables &
      ServiceTables &
      WorkerTables
    Views: DatabaseViews
    Functions: DatabaseFunctions
    Enums: DatabaseEnums
    CompositeTypes: PublicCompositeTypes
  }
}
