// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from './base.database.types'
import type { Database } from './schema.database.types'

export type DatabaseViews = {
/* @slice:begin views */
      admin_model_health_daily: {
        Row: {
          avg_latency_ms: number | null
          call_count: number | null
          day: string | null
          failure_count: number | null
          failure_kind: string | null
          fallback_count: number | null
          model: string | null
          p95_latency_ms: number | null
          provider: Database["public"]["Enums"]["api_provider"] | null
          purpose: string | null
          success_count: number | null
          total_cost_usd: number | null
          updated_at: string | null
        }
        Relationships: []
      }
      customer_overview: {
        Row: {
          bookings_30d: number | null
          bookings_total: number | null
          building_name: string | null
          created_at: string | null
          customer_id: string | null
          dispute_free_rate: number | null
          district: string | null
          last_recomputed_at: string | null
          total_spent: number | null
          unit_number: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_profiles_id_fkey"
            columns: ["customer_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      harness_run_timeline: {
        Row: {
          actor_role: string | null
          attempt_number: number | null
          capability: string | null
          cost_usd: number | null
          environment: string | null
          error_code: string | null
          event_class: string | null
          event_id: string | null
          event_status: string | null
          finished_at: string | null
          job_id: string | null
          latency_ms: number | null
          model: string | null
          occurred_at: string | null
          parent_event_id: string | null
          provider: string | null
          release_id: string | null
          route_kind: string | null
          run_id: string | null
          run_status: string | null
          safe_metadata: Json | null
          stage: string | null
          started_at: string | null
          tool_call_id: string | null
          tool_id: string | null
          trace_id: string | null
          turn_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "harness_events_parent_event_id_fkey"
            columns: ["parent_event_id"]
            isOneToOne: false
            referencedRelation: "harness_events"
            referencedColumns: ["event_id"]
          },
          {
            foreignKeyName: "harness_events_parent_event_id_fkey"
            columns: ["parent_event_id"]
            isOneToOne: false
            referencedRelation: "harness_run_timeline"
            referencedColumns: ["event_id"]
          },
          {
            foreignKeyName: "harness_runs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_cost_daily_summary: {
        Row: {
          avg_cost_per_call_usd: number | null
          avg_input_tokens: number | null
          avg_latency_ms: number | null
          avg_output_tokens: number | null
          call_count: number | null
          day: string | null
          failure_count: number | null
          failure_rate: number | null
          fallback_count: number | null
          p95_latency_ms: number | null
          provider: Database["public"]["Enums"]["api_provider"] | null
          purpose: string | null
          success_count: number | null
          total_cost_usd: number | null
        }
        Relationships: []
      }
      kael_cost_projection_daily: {
        Row: {
          cost_per_job_usd: number | null
          day: string | null
          observed_calls: number | null
          observed_cost_usd: number | null
          observed_jobs: number | null
          projected_1000_jobs_usd: number | null
          projected_10000_jobs_usd: number | null
        }
        Relationships: []
      }
      kael_estimate_accuracy: {
        Row: {
          complexity: Database["public"]["Enums"]["complexity_level"] | null
          in_band_count: number | null
          in_band_rate: number | null
          job_count: number | null
          median_miss_ratio: number | null
          month: string | null
          over_count: number | null
          p90_miss_ratio: number | null
          service_type: Database["public"]["Enums"]["service_type"] | null
          under_count: number | null
        }
        Relationships: []
      }
      kael_monitoring_ab_price_synthesis: {
        Row: {
          collected_cases: number | null
          comparison_provider:
            | Database["public"]["Enums"]["api_provider"]
            | null
          completed_cases: number | null
          experiment_id: string | null
          experiment_key: string | null
          failed_metric_count: number | null
          fallback_provider: Database["public"]["Enums"]["api_provider"] | null
          fallback_rate: number | null
          metric_thresholds: Json | null
          price_range_deviation_vs_actual: number | null
          price_range_deviation_vs_anthropic: number | null
          primary_provider: Database["public"]["Enums"]["api_provider"] | null
          purpose: string | null
          sample_target: number | null
          schema_validation_rate: number | null
          started_at: string | null
          status: string | null
          threshold_decision: string | null
        }
        Relationships: []
      }
      kael_monitoring_provider_daily: {
        Row: {
          avg_latency_ms: number | null
          call_count: number | null
          day: string | null
          failure_count: number | null
          fallback_count: number | null
          p95_latency_ms: number | null
          provider: Database["public"]["Enums"]["api_provider"] | null
          purpose: string | null
          success_count: number | null
          total_cost_usd: number | null
        }
        Relationships: []
      }
      stage1_current_production_acceptance: {
        Row: {
          acceptance_status: string | null
          cleanup_receipt_sha256: string | null
          cohort_id: string | null
          created_at: string | null
          environment: string | null
          hosted_state_sha256: string | null
          note_sha256: string | null
          production_ui_receipt_sha256: string | null
          production_ui_source_sha256: string | null
          promotion_packet_sha256: string | null
          release_id: string | null
          summary_vi: string | null
        }
        Relationships: [
          {
            foreignKeyName: "stage1_production_acceptance_notes_release_id_fkey"
            columns: ["release_id"]
            isOneToOne: true
            referencedRelation: "harness_releases"
            referencedColumns: ["release_id"]
          },
        ]
      }
      worker_overview: {
        Row: {
          avg_response_time_min: number | null
          cancel_rate: number | null
          completion_rate: number | null
          districts: string[] | null
          income_30d: number | null
          is_approved: boolean | null
          is_available: boolean | null
          jobs_30d: number | null
          last_recomputed_at: string | null
          legal_name: string | null
          on_time_rate: number | null
          rating: number | null
          service_types: Database["public"]["Enums"]["service_type"][] | null
          total_income: number | null
          total_jobs: number | null
          verification_status:
            | Database["public"]["Enums"]["worker_verification_status"]
            | null
          worker_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "worker_profiles_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_service_quality_status: {
        Row: {
          average_rating: number | null
          is_locked: boolean | null
          last_reviewed_at: string | null
          locked_until: string | null
          review_count: number | null
          service_type: Database["public"]["Enums"]["service_type"] | null
          worker_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end views */
}
