import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  kaelOrbBubble: {
    borderRadius: 22,
    borderWidth: 1,
    maxWidth: '84%',
    minWidth: 0,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  kaelOrbBubbleLeft: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderBottomLeftRadius: 8,
    borderColor: 'rgba(216,235,232,0.9)',
  },
  kaelOrbBubbleRight: {
    alignSelf: 'flex-end',
    backgroundColor: color.brand.primary,
    borderBottomRightRadius: 8,
    borderColor: 'rgba(255,255,255,0.72)',
  },
  kaelOrbBubbleText: {
    color: color.text.secondary,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  kaelOrbBubbleTextStrong: {
    color: color.text.strong,
    fontWeight: '700',
  },
  kaelOrbBubbleTextRight: {
    color: color.text.inverse,
  },
  kaelOrbCardAura: {
    bottom: -58,
    height: 190,
    left: -42,
    opacity: 0.86,
    right: -46,
    top: -58,
  },
  kaelOrbCardZipAura: {
    height: 210,
    opacity: 0.58,
    right: -92,
    top: -76,
    width: 280,
  },
  kaelOrbComposerCameraIcon: {
    height: 20,
    width: 20,
  },
  kaelOrbMediaAura: {
    bottom: -44,
    height: 120,
    left: -36,
    opacity: 0.48,
    right: -36,
    top: -42,
  },
  kaelOrbMediaLine: {
    backgroundColor: 'rgba(238,255,251,0.9)',
    borderRadius: radius.pill,
    height: 4,
    width: '74%',
  },
  kaelOrbMediaStrip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 9,
    width: '86%',
  },
  kaelOrbMediaThumb: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    height: 70,
    justifyContent: 'flex-end',
    minWidth: 0,
    overflow: 'hidden',
    paddingBottom: 10,
    position: 'relative',
    ...shadow.soft,
  },
  kaelOrbMediaThumbDark: {
    backgroundColor: '#435D63',
  },
  kaelOrbMediaThumbSoft: {
    backgroundColor: '#D8E9E6',
  },
  kaelOrbOpenButton: {
    alignItems: 'center',
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    minHeight: 28,
    minWidth: 58,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  kaelOrbOpenButtonText: {
    color: color.brand.primaryDark,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
    textAlign: 'center',
  },
  kaelOrbOpportunityAside: {
    alignItems: 'flex-end',
    gap: 7,
    maxWidth: 108,
    minWidth: 76,
    position: 'relative',
    zIndex: 1,
  },
  kaelOrbOpportunityCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 70,
    overflow: 'hidden',
    padding: 13,
    position: 'relative',
    ...shadow.soft,
  },
  kaelOrbOpportunityCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  kaelOrbOpportunityIcon: {
    height: 32,
    width: 32,
  },
  kaelOrbOpportunityIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.84)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 16,
    borderWidth: 1,
    flexShrink: 0,
    height: 46,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 46,
    zIndex: 1,
  },
  kaelOrbOpportunityList: {
    alignSelf: 'flex-start',
    gap: 9,
    marginBottom: 6,
    marginTop: 2,
    width: '92%',
  },
  kaelOrbOpportunityMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  kaelOrbOpportunityPayout: {
    color: color.brand.primaryDark,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
    textAlign: 'right',
  },
  kaelOrbOpportunityTitle: {
    color: color.text.strong,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
  },
  kaelOrbQuickChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  kaelOrbQuickChipDisabled: {
    opacity: 0.52,
  },
  kaelOrbQuickChipSelected: {
    backgroundColor: 'rgba(224,251,244,0.88)',
    borderColor: 'rgba(127,226,215,0.78)',
  },
  kaelOrbQuickChipText: {
    color: color.text.secondary,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  kaelOrbQuickChipTextSelected: {
    color: color.brand.primaryDark,
  },
  kaelOrbQuickChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
})
