import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  actionDivider: {
    alignSelf: 'center',
    backgroundColor: 'rgba(13, 127, 112, 0.11)',
    height: 24,
    width: StyleSheet.hairlineWidth,
  },
  actionMenu: {
    ...shadow.soft,
    alignSelf: 'stretch',
    backgroundColor: 'rgba(252,255,254,0.98)',
    borderColor: 'rgba(171, 220, 213, 0.72)',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 44,
    overflow: 'hidden',
    width: '100%',
  },
  actionRow: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 0,
    paddingHorizontal: 3,
  },
  actionRowPressed: {
    backgroundColor: 'rgba(224, 247, 242, 0.78)',
  },
  actionText: {
    color: color.text.strong,
    ...typography.caption2,
    fontWeight: '600',
  },
  check: {
    color: color.brand.primary,
    ...typography.callout,
    fontWeight: '600',
    marginLeft: 5,
  },
  deleteActionText: {
    color: '#E5484D',
    ...typography.caption2,
    fontWeight: '600',
  },
  deleteConfirm: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 250, 250, 0.98)',
    borderColor: 'rgba(229, 72, 77, 0.22)',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 52,
    overflow: 'hidden',
  },
  deleteConfirmAction: {
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 42,
    paddingHorizontal: 5,
  },
  deleteConfirmCancelText: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  deleteConfirmCopy: {
    color: color.text.strong,
    flex: 1,
    ...typography.caption2,
    fontWeight: '600',
    paddingHorizontal: 7,
  },
  deleteConfirmDivider: {
    alignSelf: 'center',
    backgroundColor: 'rgba(229, 72, 77, 0.14)',
    height: 26,
    width: StyleSheet.hairlineWidth,
  },
  deleteConfirmPressed: {
    backgroundColor: 'rgba(255, 232, 233, 0.82)',
  },
  disabled: {
    opacity: 0.48,
  },
  error: {
    color: '#D94C51',
    ...typography.caption2,
    fontWeight: '600',
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  feedback: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  menuGlass: {
    borderRadius: 18,
    overflow: 'hidden',
  },
  menuInner: {
    gap: 3,
  },
  menuPosition: {
    maxWidth: 208,
    position: 'absolute',
    right: 10,
    top: 74,
    width: '59%',
    zIndex: 42,
  },
  menuPositionExpanded: {
    maxWidth: 440,
    width: '92%',
  },
  menuContent: {
    overflow: 'hidden',
    padding: 5,
  },
  moreButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRadius: 13,
    elevation: 2,
    flexShrink: 0,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 44,
    position: 'relative',
    width: 44,
    zIndex: 2,
  },
  moreButtonOpen: {
    backgroundColor: 'rgba(217, 246, 240, 0.78)',
  },
  newSession: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderColor: 'rgba(255,255,255,0.72)',
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginHorizontal: -4,
    minHeight: 44,
    paddingHorizontal: 13,
    position: 'relative',
  },
  newSessionPressed: {
    opacity: 0.78,
  },
  newSessionLiquid: {
    borderWidth: 0,
  },
  newSessionText: {
    color: color.brand.primary,
    ...typography.footnote,
    fontWeight: '600',
  },
  pinnedIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 3,
  },
  pressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  pressedReduced: {
    opacity: 0.78,
  },
  inlineRenameActions: {
    alignItems: 'center',
    bottom: 0,
    flexDirection: 'row',
    gap: 2,
    position: 'absolute',
    right: 8,
    top: 0,
  },
  inlineRenameCancel: {
    alignItems: 'center',
    borderRadius: radius.pill,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: 3,
  },
  inlineRenameCancelText: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  inlineRenameSave: {
    alignItems: 'center',
    backgroundColor: color.brand.primary,
    borderRadius: radius.pill,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: 4,
  },
  inlineRenameSaveText: {
    color: color.text.inverse,
    ...typography.caption2,
    fontWeight: '600',
  },
  session: {
    alignItems: 'center',
    backgroundColor: color.surface.soft,
    borderColor: color.surface.stroke,
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 44,
    overflow: 'hidden',
    position: 'relative',
  },
  sessionCopy: {
    flex: 1,
    gap: 0,
    minWidth: 0,
  },
  sessionCopyRenaming: {
    paddingRight: 94,
  },
  sessionGroup: {
    gap: 3,
  },
  sessionList: {
    gap: 3,
  },
  sessionListViewport: {
    marginTop: 6,
    maxHeight: 138,
  },
  sessionListViewportExpanded: {
    maxHeight: 240,
  },
  sessionMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    minHeight: 44,
    minWidth: 0,
    paddingLeft: 8,
    paddingRight: 8,
    position: 'relative',
    zIndex: 0,
  },
  sessionMeta: {
    color: color.text.muted,
    ...typography.caption2,
  },
  sessionTitle: {
    color: color.text.strong,
    flexShrink: 1,
    ...typography.caption2,
    fontWeight: '600',
  },
  sessionTitleInput: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    textAlignVertical: 'center',
  },
  sessionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    minWidth: 0,
  },
  statusDot: {
    backgroundColor: 'rgba(143, 174, 169, 0.68)',
    borderRadius: 4,
    height: 6,
    marginRight: 7,
    width: 6,
  },
  statusDotSelected: {
    backgroundColor: color.brand.primary,
  },
})
