import { z } from "zod";
import {
  clientRequestIdSchema,
  serviceTypeSchema,
} from "./common.ts";
export const candidateDecisionReceiptSchema = z.object({
  job_id: z.string().uuid(),
  candidate_id: z.string().uuid(),
  worker_id: z.string().uuid(),
  decision: z.enum(['confirm', 'reject']),
  decided_at: z.string().datetime({ offset: true }),
}).strict()

export const candidateDecisionStatusSchema = z.object({
  job_id: z.string().uuid(),
  candidate_id: z.string().uuid(),
  worker_id: z.string().uuid(),
  candidate_status: z.enum(['proposed', 'customer_confirmed', 'customer_declined', 'expired', 'withdrawn']),
  receipt: candidateDecisionReceiptSchema.nullable(),
}).strict().refine((value) => !value.receipt || (
  value.receipt.job_id === value.job_id && value.receipt.candidate_id === value.candidate_id
  && value.receipt.worker_id === value.worker_id
  && value.candidate_status === (value.receipt.decision === 'confirm' ? 'customer_confirmed' : 'customer_declined')
))

export type EdgeCandidateDecisionReceipt = z.infer<typeof candidateDecisionReceiptSchema>
export type EdgeCandidateDecisionStatus = z.infer<typeof candidateDecisionStatusSchema>

export const apartmentAccessAuthorizationSchema = z.object({
  expected_worker_id: z.string().uuid(),
  expected_check_in_at: z.string().datetime({ offset: true }),
}).strict()

export const apartmentAccessAuthorizationReceiptSchema = z.object({
  job_id: z.string().uuid(),
  worker_id: z.string().uuid(),
  checked_in_at: z.string().datetime({ offset: true }),
  authorized_at: z.string().datetime({ offset: true }),
  release_stage: z.literal('unit_released'),
  already_authorized: z.boolean(),
}).strict()

export type EdgeApartmentAccessAuthorizationInput = z.infer<typeof apartmentAccessAuthorizationSchema>
export type EdgeApartmentAccessAuthorizationReceipt = z.infer<typeof apartmentAccessAuthorizationReceiptSchema>

export const apartmentAccessProfileSchema = z.object({
  entry_method: z.string().max(300).optional(),
  parking_note: z.string().max(300).optional(),
  guard_note: z.string().max(300).optional(),
  building_note: z.string().max(300).optional(),
  customer_handoff_note: z.string().max(300).optional(),
}).default({});

export const jobCreateSchema = z.object({
  service_type: serviceTypeSchema,
  description: z.string().trim().min(10).max(2000),
  problem_chips: z.array(z.string().trim().min(1).max(100)).min(1).max(10),
  photo_urls: z.array(z.string().url()).max(5).default([]),
  address_building: z.string().max(200).optional(),
  address_unit: z.string().max(50).optional(),
  address_floor: z.string().max(10).optional(),
  address_district: z.string().max(100).optional(),
  apartment_access_profile: apartmentAccessProfileSchema.optional(),
  scheduled_at: z.string().datetime().optional(),
  // Optional UUID generated by the mobile
  // client per submit. Re-POST with the same id returns the existing job
  // instead of creating a duplicate. NULL keeps legacy callers compatible.
  client_request_id: clientRequestIdSchema.optional(),
});

export const placesAutocompleteSchema = z.object({
  input: z.string().trim().min(2).max(160),
  session_token: z.string().max(120).optional(),
});

export const placesResolveSchema = z.object({
  label: z.string().trim().min(2).max(240).optional(),
  place_id: z.string().trim().min(3).max(240),
});

export const jobMessageSendSchema = z.object({
  content: z.string().trim().min(1).max(5000),
});

export const jobMatchingPreferenceSchema = z.object({
  mode: z.enum(["general", "saved_worker_first"]),
  worker_id: z.string().uuid().optional(),
  auto_general: z.boolean().default(false),
  client_request_id: clientRequestIdSchema,
}).strict().superRefine((value, ctx) => {
  if (value.mode === "saved_worker_first" && !value.worker_id) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: "worker_id is required for saved_worker_first",
      path: ["worker_id"],
    });
  }
  if (value.mode === "general" && value.worker_id) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: "worker_id is only allowed for saved_worker_first",
      path: ["worker_id"],
    });
  }
});

export type JobCreateInput = z.infer<typeof jobCreateSchema>;
export type ApartmentAccessProfileInput = z.infer<
  typeof apartmentAccessProfileSchema
>;
export type PlacesAutocompleteInput = z.infer<typeof placesAutocompleteSchema>;
export type PlacesResolveInput = z.infer<typeof placesResolveSchema>;
export type JobMessageSendInput = z.infer<typeof jobMessageSendSchema>;
export type EdgeJobMatchingPreferenceInput = z.infer<typeof jobMatchingPreferenceSchema>;
