import React from 'react'
import { AppState, View, Image } from 'react-native'
import type { ActionId, WorkModel, SurfaceProps } from './stage-five.types'
import { TW } from './stage-five-tokens'
import { Icon } from './stage-five-icons'
import { Box, Copy, Header, SurfaceFrame, Tap, IconSlot, ToolTile, Primary, Caution } from './stage-five-ui'
import { elapsedSeconds, formatClock } from './stage-five-model'
import { stageFiveText } from './stage-five-copy'
/** Stage 5 only. This is a monitor; visual timer and progress cannot write job status. */
export class StageFiveWork extends React.PureComponent<SurfaceProps<WorkModel>,{now:number;error:string|null;localBusy:boolean}> {
 state={now:Date.now(),error:null,localBusy:false}
 private timer:ReturnType<typeof setInterval>|null=null
 private subscription:ReturnType<typeof AppState.addEventListener>|null=null
 private mounted=false
 componentDidMount(){this.mounted=true;this.syncTimer();this.subscription=AppState.addEventListener('change',()=>this.syncTimer())}
 componentDidUpdate(p:SurfaceProps<WorkModel>){if(p.nowMs!==this.props.nowMs||p.model.jobId!==this.props.model.jobId)this.syncTimer()}
 componentWillUnmount(){this.mounted=false;if(this.timer)clearInterval(this.timer);this.subscription?.remove()}
 private syncTimer(){if(this.timer)clearInterval(this.timer);this.timer=null;if(!this.mounted)return;this.setState({now:Date.now()});if(this.props.nowMs!==undefined||AppState.currentState==='background')return;this.timer=setInterval(()=>this.setState({now:Date.now()}),250)}
 private run=async(id:ActionId)=>{const a=this.props.actions[id];if(!a?.enabled||this.state.localBusy||this.props.busy)return;this.setState({error:null,localBusy:true});try{await a.onPress()}catch(e){if(this.mounted)this.setState({error:e instanceof Error?e.message:stageFiveText(this.props.language,'Không thể thực hiện. Vui lòng thử lại.','Could not complete this action. Please try again.')})}finally{if(this.mounted)this.setState({localBusy:false})}}
 private tap=(id:ActionId)=>this.props.actions[id]?.enabled?()=>void this.run(id):undefined
 render(){const {model:m,referenceMode,reduceMotion,language='vi'}=this.props;const hasArrived=!!m.arrivedLabel||['arrived','inspecting','repairing','scope_change_pending','completed_by_worker','completed','closed'].includes(m.jobStatus??'');const elapsed=elapsedSeconds(this.props.nowMs??this.state.now,m.startedAtMs,m.pausedAtMs,m.pausedMs);return <SurfaceFrame testID="stage5-work">{s=><>
 <Header s={s} language={language}/>
 <Box tint s={s} height={66} style={{marginTop:6*s,paddingHorizontal:18*s,paddingVertical:14*s,borderRadius:20*s}}><View style={{flexDirection:'row',gap:14*s,alignItems:'center'}}><IconSlot name={hasArrived?'check':'locate'} s={s} size={32}/><View style={{flex:1,gap:2*s}}><Copy s={s} size={14} weight="600" color="#00574D">{stageFiveText(language,hasArrived?'Bạn đã có mặt tại địa điểm':'Chưa ghi nhận có mặt',hasArrived?'You are at the location':'Arrival not recorded')}</Copy><Copy s={s} size={12} color={TW.color.body}>{m.arrivedLabel||(hasArrived?stageFiveText(language,'Chưa có thời gian ghi nhận','Arrival time unavailable'):stageFiveText(language,'Chờ xác nhận từ hệ thống','Waiting for system confirmation'))}</Copy></View><Tap s={s} label={stageFiveText(language,'Chỉnh sửa thông tin có mặt','Edit arrival details')} onPress={this.tap('editArrival')} style={{flexDirection:'row',alignItems:'center',gap:4*s}}><Icon name="edit" size={16*s} color="#007B6E"/><Copy s={s} size={12} color="#007B6E">{stageFiveText(language,'Chỉnh sửa','Edit')}</Copy></Tap></View></Box>
 <Box s={s} height={102} style={{marginTop:10*s,padding:13*s}}><View style={{flexDirection:'row',gap:13*s}}>{m.photo?<Image source={m.photo} resizeMode="cover" style={{width:76*s,height:76*s,borderRadius:15*s}}/>:<View style={{width:76*s,height:76*s,borderRadius:15*s,backgroundColor:'#EAF9F5',alignItems:'center',justifyContent:'center'}}><Icon name="home" size={38*s}/></View>}<View style={{flex:1,gap:4*s}}><Copy s={s} size={16} weight="600" style={{paddingRight:72*s}}>{m.serviceTitle||stageFiveText(language,'Chưa có công việc','No active work')}</Copy><View style={{alignSelf:'flex-start',paddingHorizontal:8*s,paddingVertical:2*s,backgroundColor:'#D5FBEE',borderRadius:12*s}}><Copy s={s} size={11} color="#007964">{m.serviceCategory||'—'}</Copy></View><View style={{flexDirection:'row',gap:5*s,alignItems:'center'}}><Icon name="pin" size={18*s} color={TW.color.body}/><Copy s={s} size={12} color={TW.color.body} style={{flex:1}}>{m.addressLine||stageFiveText(language,'Thông tin địa chỉ được bảo vệ','Address details are protected')}</Copy></View></View></View><Tap s={s} label={stageFiveText(language,'Chi tiết công việc','Job details')} onPress={this.tap('details')} style={{position:'absolute',right:14*s,top:17*s,paddingHorizontal:17*s,minHeight:37*s,borderRadius:20*s,backgroundColor:'#F3F7FB',borderWidth:1,borderColor:TW.color.line}}><Copy s={s} size={12}>{stageFiveText(language,'Chi tiết','Details')}</Copy></Tap></Box>
 <Box s={s} height={90} style={{marginTop:10*s,padding:13*s}}><View style={{flexDirection:'row',gap:13*s,alignItems:'center'}}><IconSlot name="clock" s={s} size={40}/><View style={{flex:1,gap:0}}><Copy s={s} size={12}>{stageFiveText(language,'Thời gian làm việc','Work time')}</Copy><View testID="work-timer"><Copy s={s} size={24} weight="600" style={{fontVariant:['tabular-nums'],letterSpacing:-.3*s,lineHeight:28*s}}>{formatClock(elapsed)}</Copy></View><Copy s={s} size={12} color={TW.color.body}>{stageFiveText(language,'Bắt đầu lúc','Started at')} {m.startedLabel||'—'}</Copy></View></View></Box>
 <View style={{flexDirection:'row',gap:8*s,marginTop:10*s}}><ToolTile s={s} label={stageFiveText(language,'Chụp ảnh','Take photo')} icon="camera" onPress={this.tap('photo')} testID="stage5-photo"/><ToolTile s={s} label={stageFiveText(language,'Ghi chú','Notes')} icon="note" onPress={this.tap('note')} testID="stage5-note"/><View testID="worker-v5-in-progress-scope-action" style={{flex:1}}><ToolTile s={s} label={stageFiveText(language,'Báo phát sinh','Report change')} icon="warning" coral onPress={this.tap('scope')} testID="stage5-scope"/></View></View>
 <Box s={s} height={85} style={{marginTop:10*s}}><Tap s={s} label={stageFiveText(language,'Ghi chú nhanh','Quick note')} onPress={this.tap('note')} style={{padding:17*s,flexDirection:'row',alignItems:'center',gap:8*s,minHeight:84*s}}><IconSlot name="bookmark" s={s} size={44} blue/><View style={{flex:1,gap:4*s}}><Copy s={s} size={14} weight="600">{stageFiveText(language,'Ghi chú nhanh','Quick note')}</Copy><Copy s={s} size={12} color={TW.color.body} lines={2}>{m.note||stageFiveText(language,'Thêm ghi chú về tình trạng thực tế, vật tư sử dụng…','Add a note about the actual condition or materials used…')}</Copy></View><Icon name="chevron" size={20*s} color="#5E7D92"/></Tap></Box>
 {this.state.error?<Copy s={s} color="#A83838" style={{marginTop:10*s}}>{this.state.error}</Copy>:null}
 <View style={{marginTop:20*s}}><Primary s={s} language={language} label={referenceMode?stageFiveText(language,'Hoàn thành công việc','Complete work'):stageFiveText(language,'Chuẩn bị hồ sơ hoàn tất','Prepare completion evidence')} onPress={this.tap('complete')} busy={this.state.localBusy||this.props.busy} disabled={!m.canPrepareCompletion} testID="stage5-primary"/></View>
 <Caution s={s}>{stageFiveText(language,'Vui lòng cập nhật đầy đủ trước khi hoàn thành.','Please update all details before completing the work.')}</Caution>
 </>}</SurfaceFrame>}
}
