import { Platform, StyleSheet } from 'react-native'

export const CUSTOMER_LIQUID_NAV_MAX_WIDTH = 384
export const CUSTOMER_LIQUID_NAV_SIDE_INSET = 18
export const CUSTOMER_LIQUID_NAV_DOCK_HEIGHT = 62
export const CUSTOMER_LIQUID_NAV_ORB_SIZE = 68
export const CUSTOMER_LIQUID_NAV_GAP = 7
export const CUSTOMER_LIQUID_NAV_RAIL_PADDING = 2
export const CUSTOMER_LIQUID_NAV_LENS_RADIUS = 30

export const customerV21DockStyles = StyleSheet.create({
  dockIcon: {
    height: 21,
    opacity: 1,
    position: 'relative',
    width: 21,
    zIndex: 3,
  },
  dockIconActive: {
    opacity: 1,
    transform: [{ translateY: -0.15 }, { scale: 1.018 }],
  },
  dockItem: {
    alignItems: 'center',
    borderRadius: 30,
    flex: 1,
    gap: 1,
    height: 56,
    justifyContent: 'center',
    minWidth: 0,
    position: 'relative',
    zIndex: 3,
  },
  dockItemPressed: {
    transform: [{ scale: 0.976 }],
  },
  dockLabel: {
    fontSize: 9.5,
    fontWeight: '500',
    lineHeight: 10,
    maxWidth: 64,
    position: 'relative',
    textAlign: 'center',
    zIndex: 3,
  },
  dockLabelActive: {
    fontWeight: '600',
    transform: [{ translateY: -1 }],
  },
  dockCaustic: {
    ...StyleSheet.absoluteFill,
    overflow: 'hidden',
    zIndex: 0,
  },
  dockCausticGlow: {
    backgroundColor: 'rgba(28,205,179,0.14)',
    borderRadius: 999,
    bottom: -22,
    filter: Platform.OS === 'web' ? 'blur(9px)' : undefined,
    height: 49,
    position: 'absolute',
  } as any,
  dockCausticSweep: {
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderRadius: 999,
    bottom: -18,
    height: 64,
    left: -10,
    opacity: 0.68,
    position: 'absolute',
    right: -10,
    transform: [{ rotate: '-6deg' }],
  },
  dockCausticSweepBright: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 999,
    height: 24,
    left: '48%',
    opacity: 0.44,
    position: 'absolute',
    right: -22,
    top: 5,
    transform: [{ rotate: '-4deg' }],
  },
  dockInnerRefraction: {
    borderBottomColor: 'rgba(42,205,180,0.08)',
    borderColor: 'rgba(255,255,255,0.45)',
    borderRadius: 32,
    borderWidth: 1,
    bottom: 1,
    left: 1,
    opacity: 0.92,
    position: 'absolute',
    right: 1,
    top: 1,
    zIndex: 2,
  },
  dockLens: {
    backgroundColor: 'rgba(248,255,253,0.82)',
    borderColor: 'rgba(255,255,255,0.90)',
    borderRadius: CUSTOMER_LIQUID_NAV_LENS_RADIUS,
    borderWidth: 1,
    bottom: 3,
    left: 3,
    overflow: 'hidden',
    position: 'absolute',
    shadowColor: '#078071',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    top: 3,
    zIndex: 1,
  },
  dockLensBloom: {
    backgroundColor: 'rgba(220,249,242,0.40)',
    borderRadius: CUSTOMER_LIQUID_NAV_LENS_RADIUS,
    bottom: 5,
    left: 6,
    opacity: 0.88,
    position: 'absolute',
    right: 6,
    top: 5,
  },
  dockLensInnerShadow: {
    borderBottomColor: 'rgba(12,181,159,0.14)',
    borderColor: 'rgba(5,95,87,0.045)',
    borderRadius: 28,
    borderWidth: 1,
    bottom: 4,
    left: 4,
    opacity: 0.58,
    position: 'absolute',
    right: 4,
    top: 4,
  },
  dockLensSheen: {
    backgroundColor: 'rgba(255,255,255,0.65)',
    borderRadius: 16,
    bottom: 1,
    left: 1,
    position: 'absolute',
    top: 1,
    width: 18,
    zIndex: 3,
  },
  dockLensTopLight: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    height: 14,
    left: 9,
    opacity: 0.68,
    position: 'absolute',
    right: 12,
    top: 5,
    transform: [{ rotate: '-8deg' }],
  },
  dockOverlay: {
    alignItems: 'center',
    bottom: 12,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 30,
  },
  dockPlane: {
    alignItems: 'center',
    borderRadius: CUSTOMER_LIQUID_NAV_DOCK_HEIGHT / 2,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 0,
    height: CUSTOMER_LIQUID_NAV_DOCK_HEIGHT,
    minHeight: CUSTOMER_LIQUID_NAV_DOCK_HEIGHT,
    overflow: 'hidden',
    padding: CUSTOMER_LIQUID_NAV_RAIL_PADDING,
    position: 'relative',
  },
  dockRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: CUSTOMER_LIQUID_NAV_GAP,
    justifyContent: 'center',
  },
  dockShimmer: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 999,
    filter: Platform.OS === 'web' ? 'blur(2px)' : undefined,
    height: 53,
    left: '-24%',
    opacity: 0.73,
    position: 'absolute',
    top: -31,
    zIndex: 5,
  } as any,
  kaelAccessory: {
    alignItems: 'center',
    borderRadius: CUSTOMER_LIQUID_NAV_ORB_SIZE / 2,
    flexShrink: 0,
    height: CUSTOMER_LIQUID_NAV_ORB_SIZE,
    justifyContent: 'center',
    overflow: 'visible',
    width: CUSTOMER_LIQUID_NAV_ORB_SIZE,
  },
  kaelAccessoryActive: {
    borderColor: 'rgba(46,50,54,0.30)',
    borderWidth: 1,
    shadowColor: '#04302C',
    shadowOffset: { height: 13, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 27,
  },
})
