import { StyleSheet } from 'react-native'

export const CUSTOMER_V21_SURFACE_SIDE_INSET = 16
export const CUSTOMER_V21_SURFACE_MAX_WIDTH = 560

export function customerV21SurfaceContentWidth(viewportWidth: number) {
  return Math.max(
    0,
    Math.min(
      viewportWidth - CUSTOMER_V21_SURFACE_SIDE_INSET * 2,
      CUSTOMER_V21_SURFACE_MAX_WIDTH,
    ),
  )
}

export const customerV21SharedStyles = StyleSheet.create({
  card: {
    borderRadius: 26,
    borderWidth: 1,
    gap: 14,
    marginTop: 14,
    maxWidth: '100%',
    padding: 16,
    width: '100%',
  },
  cardShadowDark: {
    boxShadow: '0 10px 24px rgba(0,0,0,0.10)',
  },
  cardShadowLight: {
    boxShadow: '0 10px 24px rgba(107,170,157,0.10)',
  },
  safeArea: {
    flex: 1,
    maxWidth: '100%',
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  scrollContent: {
    paddingBottom: 128,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  frame: {
    alignItems: 'stretch',
    alignSelf: 'center',
    maxWidth: '100%',
    minWidth: 0,
    width: '100%',
  },
  bodyText: {
    fontSize: 14,
    lineHeight: 20,
  },
  centerText: {
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
  },
  emptyStateFormulaMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.94,
    zIndex: 0,
  },
  emptyStateFormulaMintAuraCard: {
    overflow: 'hidden',
    position: 'relative',
  },
  emptyStateFormulaMintAuraContent: {
    alignItems: 'center',
    gap: 14,
    position: 'relative',
    zIndex: 1,
  },
  emptyStateContent: {
    alignItems: 'center',
    gap: 12,
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  emptyTitle: {
    fontSize: 19,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'center',
  },
  homeEmptyState: {
    overflow: 'hidden',
    position: 'relative',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 34,
  },
  homeEmptyStateShadowDark: {
    shadowColor: '#000000',
  },
  homeEmptyStateShadowLight: {
    shadowColor: '#05695E',
  },
  inactiveAgenticGate: {
    minHeight: 1,
  },
  assetTile: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 64,
    minWidth: 64,
  },
  bareAssetTile: {
    borderWidth: 0,
  },
  topActionText: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 22,
  },
  topAvatarDot: {
    backgroundColor: '#30D27B',
    borderColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 2,
    bottom: -1,
    height: 16,
    position: 'absolute',
    right: -1,
    width: 16,
  },
  topAvatarImage: {
    height: 44,
    width: 44,
  },
  topAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  topAvatarWrap: {
    alignItems: 'center',
    backgroundColor: '#08AF9C',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 20,
    borderWidth: 2,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 58,
  },
  topControl: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  topCopy: {
    alignItems: 'flex-start',
    minWidth: 0,
  },
  topSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    textAlign: 'left',
  },
  topTitle: {
    fontSize: 27,
    fontWeight: '600',
    includeFontPadding: true,
    letterSpacing: 0,
    lineHeight: 34,
    minHeight: 36,
    textAlign: 'left',
  },
  eyebrowDot: {
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  eyebrowPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  eyebrowMotionWrap: {
    alignSelf: 'flex-start',
  },
  eyebrowPillText: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  eyebrowPillTextPreserve: {
    textTransform: 'none',
  },
  flex: {
    flex: 1,
    minWidth: 0,
  },
  infoNotice: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  infoNoticeBody: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  infoNoticeIcon: {
    minHeight: 58,
    minWidth: 58,
  },
  infoNoticeTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  matchingHandoffChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.71)',
    borderColor: 'rgba(204,235,229,0.82)',
    height: 28,
    minHeight: 28,
    paddingHorizontal: 10,
  },
  matchingHandoffChipSelected: {
    backgroundColor: 'rgba(224,252,245,0.88)',
    borderColor: 'rgba(85,214,195,0.36)',
  },
  matchingHandoffChipSelectedText: {
    color: '#087D72',
  },
  matchingHandoffChipSuccess: {
    backgroundColor: '#EAF8EF',
    borderColor: '#BFE8CE',
  },
  matchingHandoffChipSuccessText: {
    color: '#1F9B5B',
  },
  matchingHandoffChipText: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  progressLine: {
    flex: 1,
    borderRadius: 2,
    height: 2,
  },
  progressNode: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    height: 23,
    justifyContent: 'center',
    width: 23,
  },
  progressNodeActive: {
    shadowColor: '#08AF9C',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 7,
  },
  progressNodeText: {
    fontSize: 9,
    fontWeight: '600',
    lineHeight: 12,
  },
  progressRail: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    marginTop: 2,
    position: 'relative',
    width: '100%',
    zIndex: 1,
  },
  cardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  heroChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  heroCopy: {
    alignItems: 'center',
    flex: 1,
    flexShrink: 1,
    gap: 8,
    justifyContent: 'center',
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  heroKael: {
    flexShrink: 0,
    height: 118,
    position: 'relative',
    width: 86,
    zIndex: 1,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 34,
  },
  homeAuraServiceTile: {
    alignItems: 'stretch',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    flexGrow: 1,
    gap: 0,
    minHeight: 100,
    overflow: 'hidden',
    padding: 0,
    position: 'relative',
  },
  homeAuraServiceTileNarrow: {
    flexBasis: '100%',
    maxWidth: '100%',
  },
  homeAuraServiceTileWide: {
    flexBasis: '48%',
    maxWidth: '49%',
  },
  homeV4ServiceTile: {
    alignItems: 'stretch',
    aspectRatio: 1,
    borderRadius: 24,
    borderWidth: 1,
    boxShadow: '0 8px 18px rgba(93,132,128,0.12)',
    flexBasis: '31.5%',
    flexGrow: 0,
    gap: 0,
    maxWidth: '32%',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
    padding: 0,
    position: 'relative',
  },
  homeV4ServiceContent: {
    alignItems: 'stretch',
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  homeV4ServiceVisual: {
    alignItems: 'center',
    flex: 0.7,
    justifyContent: 'center',
    minHeight: 0,
    overflow: 'hidden',
    padding: 0,
  },
  homeV4ServiceImage: {
    height: '100%',
    width: '100%',
  },
  homeV4ServiceFade: {
    ...StyleSheet.absoluteFill,
    zIndex: 1,
  },
  homeV4ServiceLabel: {
    alignItems: 'center',
    flex: 0.3,
    justifyContent: 'center',
    minHeight: 0,
    paddingHorizontal: 5,
    paddingVertical: 4,
  },
  homeV4ServiceTitle: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: -0.15,
    lineHeight: 16,
    textAlign: 'center',
  },
  homeServiceGrid: {
    flexWrap: 'wrap',
    gap: 9,
    justifyContent: 'space-between',
    marginBottom: 14,
    marginTop: 8,
    position: 'relative',
  },
  homeServiceConnector: {
    height: 1,
    position: 'absolute',
    right: -24,
    top: '50%',
    width: 24,
    zIndex: 1,
  },
  homeServiceConnectorDot: {
    borderRadius: 7,
    borderWidth: 1,
    height: 14,
    marginTop: -7,
    position: 'absolute',
    right: -7,
    top: '50%',
    width: 14,
    zIndex: 2,
  },
  homeServiceCopy: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    paddingLeft: 40,
    paddingRight: 14,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 1,
  },
  homeServiceDetailLabel: {
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  homeServiceDetailRail: {
    alignItems: 'center',
    borderTopWidth: 0,
    columnGap: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 6,
    paddingTop: 0,
    rowGap: 6,
  },
  homeServiceDetailRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
    minWidth: 0,
  },
  homeServiceFormulaMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.94,
    zIndex: 0,
  },
  homeServiceIcon: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    height: 74,
    justifyContent: 'center',
    minHeight: 74,
    minWidth: 74,
    position: 'relative',
    width: 74,
  },
  homeServiceHeading: {
    minHeight: 0,
  },
  homeServiceTitle: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 4,
    textAlign: 'left',
  },
  homeServiceVisualPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRightWidth: 1,
    flexShrink: 0,
    justifyContent: 'center',
    minHeight: 100,
    overflow: 'visible',
    position: 'relative',
    width: 80,
    zIndex: 1,
  },
  protectionBar: {
    borderRadius: 999,
    height: 8,
    marginTop: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  protectionBarFill: {
    borderRadius: 999,
    height: '100%',
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  screenRail: {
    gap: 8,
  },
  screenRailItem: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  screenRailTitle: {
    fontSize: 12,
    fontWeight: '700',
  },
  sectionActionButton: {
    alignItems: 'flex-end',
    maxWidth: 112,
    minWidth: 0,
    paddingHorizontal: 2,
    paddingVertical: 4,
    position: 'absolute',
    right: 0,
    top: -1,
    width: 112,
  },
  sectionActionHeader: {
    marginTop: 24,
    minHeight: 29,
    position: 'relative',
  },
  sectionActionHeaderWithAction: {
    paddingRight: 116,
  },
  sectionActionText: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'right',
  },
  sectionActionTitle: {
    minWidth: 0,
    width: '100%',
  },
  sectionHeader: {
    gap: 4,
    marginTop: 22,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 25,
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'flex-start',
    marginTop: 12,
  },
  serviceIcon: {
    minHeight: 82,
    minWidth: 82,
  },
  serviceNote: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    textAlign: 'center',
  },
  serviceTile: {
    alignItems: 'center',
    borderRadius: 26,
    borderWidth: 1,
    flexBasis: '40%',
    flexGrow: 0,
    gap: 8,
    maxWidth: '40%',
    minHeight: 168,
    minWidth: 0,
    padding: 12,
  },
  serviceTitle: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 19,
    textAlign: 'center',
  },
  sourceIconAuraFrame: {
    alignItems: 'center',
    height: 82,
    justifyContent: 'center',
    position: 'relative',
    width: 82,
  },
  sourceIconTile: {
    borderRadius: 22,
    borderWidth: 1,
    elevation: 1,
    height: 64,
    overflow: 'hidden',
    shadowColor: '#056055',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 26,
    width: 64,
  },
  utilityLabel: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
    textAlign: 'center',
  },
})
