import { color } from '@/design/theme'

export const Colors = {
  primary: color.brand.primary,
  primaryDark: color.brand.primaryDark,
  background: color.background,
  surface: color.surface.base,
  text: color.text.primary,
  textSecondary: color.text.secondary,
  border: color.surface.stroke,
  success: color.accent.success,
  warning: color.accent.warning,
  error: color.accent.destructive,
  tabInactive: '#8AA39E',
  priceCheck: {
    canvas: color.background,
    canvasWarm: '#FFF7EA',
    surface: color.surface.base,
    surfaceMint: color.surface.mint,
    surfaceJade: color.mint.auraSoft,
    surfaceAqua: color.mint.mint50,
    surfaceCopper: '#F7E6D1',
    mintSoft: color.mint.auraStrong,
    mint: color.mint.mint300,
    mintStrong: color.brand.primary,
    forest: color.brand.primaryDark,
    forestDark: color.brand.primaryDeep,
    jade: color.brand.primaryDark,
    aqua: color.accent.aqua,
    clay: '#B36A30',
    claySoft: '#EBC39A',
    ink: color.text.primary,
    slate: color.text.secondary,
    muted: color.text.muted,
    line: color.surface.stroke,
    lineStrong: color.surface.strokeStrong,
    success: color.accent.success,
    danger: color.accent.destructive,
  },
}
