import { StyleSheet } from 'react-native'

export const customerV21AgenticStyles = StyleSheet.create({
  agenticUtilityIcon: {
    minHeight: 56,
    minWidth: 56,
  },
  bodyText: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  flex: {
    flex: 1,
  },
  sectionActionText: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'right',
  },
  agenticChatActionButton: {
    flex: 1,
    minWidth: 0,
  },
  agenticChatActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatBody: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatCard: {
    alignSelf: 'flex-start',
    gap: 12,
    marginBottom: 6,
    marginTop: 2,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 32,
    width: '92%',
  },
  agenticChatFact: {
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minHeight: 66,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 9,
    position: 'relative',
  },
  agenticChatFactCentered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  agenticChatFactGrid: {
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatFactLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    lineHeight: 13,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatFactValue: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 5,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatIcon: {
    minHeight: 58,
    minWidth: 58,
  },
  agenticChatNote: {
    fontSize: 11.5,
    fontWeight: '600',
    lineHeight: 16,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatTitle: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceFileCount: {
    alignItems: 'center',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 38,
    minWidth: 54,
    paddingHorizontal: 10,
  },
  agenticEvidenceGateCard: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    padding: 13,
  },
  agenticEvidenceMetricRow: {
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceReasonBox: {
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceReasonInput: {
    width: '100%',
  },
  agenticEvidenceReasonInputShell: {
    minHeight: 48,
  },
  agenticEvidenceToolButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  agenticEvidenceToolRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceToolText: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 15,
  },
  agenticMoreInfoCard: {
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 1,
  },
  agenticPaymentLedger: {
    borderRadius: 18,
    borderWidth: 1,
    gap: 0,
    marginTop: 2,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticRejectReasonCard: {
    alignSelf: 'flex-start',
    borderRadius: 22,
    borderWidth: 1,
    gap: 5,
    maxWidth: '88%',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'relative',
  },
})
