import { StyleSheet } from 'react-native'

export const customerV21AgenticStyles = StyleSheet.create({
  agenticHeroIcon: {
    minHeight: 92,
    minWidth: 92,
  },
  agenticHeroIconCompact: {
    minHeight: 82,
    minWidth: 82,
  },
  agenticHeroMascot: {
    height: 132,
    width: 108,
  },
  agenticHeroMascotCompact: {
    height: 116,
    width: 94,
  },
  agenticHeroMascotWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 142,
    minWidth: 120,
    position: 'relative',
    zIndex: 1,
  },
  agenticHeroMascotWrapCompact: {
    minHeight: 124,
    minWidth: 104,
  },
  agenticHeroPill: {
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  agenticStageHeroBody: {
    fontSize: 19,
    fontWeight: '600',
    lineHeight: 28,
    position: 'relative',
    zIndex: 1,
  },
  agenticStageHeroBodyCompact: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  agenticStageHeroBodyNarrow: {
    fontSize: 14,
    lineHeight: 20,
  },
  agenticStageHeroCard: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.92)',
    flexDirection: 'row',
    gap: 20,
    minHeight: 224,
    overflow: 'hidden',
    paddingHorizontal: 22,
    paddingVertical: 24,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 20, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 38,
  },
  agenticStageHeroCardCompact: {
    gap: 16,
    minHeight: 182,
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  agenticStageHeroCardNarrow: {
    alignSelf: 'center',
    gap: 16,
    minHeight: 198,
    paddingHorizontal: 18,
    paddingVertical: 20,
    width: '92%',
  },
  agenticStageHeroCopyCompact: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  agenticStageHeroTitle: {
    fontSize: 35,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 42,
    position: 'relative',
    zIndex: 1,
  },
  agenticStageHeroTitleCompact: {
    fontSize: 26,
    lineHeight: 32,
    textAlign: 'center',
  },
  agenticStageHeroTitleNarrow: {
    fontSize: 26,
    lineHeight: 32,
  },
  agenticArtifactTile: {
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minHeight: 72,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'relative',
  },
  agenticArtifactValue: {
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    marginTop: 3,
  },
  agenticMetricLabel: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 7,
    textAlign: 'center',
  },
  agenticMetricTile: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 88,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 12,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  agenticMetricValue: {
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 34,
    textAlign: 'center',
  },
  agenticUtilityCard: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 76,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
  },
  agenticUtilityIcon: {
    minHeight: 56,
    minWidth: 56,
  },
  agenticWorkLogRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 78,
    position: 'relative',
    zIndex: 1,
  },
  agenticWorkLogStatusChip: {
    alignSelf: 'center',
    backgroundColor: 'rgba(224,252,245,0.92)',
    borderColor: 'rgba(85,214,195,0.42)',
    justifyContent: 'center',
    marginLeft: 'auto',
    minWidth: 58,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  bodyText: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  flex: {
    flex: 1,
  },
  sectionActionText: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'right',
  },
  utilityBodyText: {
    fontSize: 14,
    lineHeight: 20,
  },
  utilityCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  agenticHomeBackdropAura: {
    bottom: -96,
    left: -22,
    opacity: 0.82,
    position: 'absolute',
    right: -22,
    top: 28,
    zIndex: 0,
  },
  agenticStageBackdropAura: {
    bottom: -92,
    left: -24,
    opacity: 0.86,
    position: 'absolute',
    right: -24,
    top: -112,
  },
  agenticApprovalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  agenticApprovalCard: {
    borderColor: 'rgba(116,224,209,0.55)',
    gap: 12,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 32,
  },
  agenticApprovalFactLabel: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 18,
  },
  agenticApprovalFacts: {
    flexDirection: 'row',
    gap: 14,
  },
  agenticApprovalFactValue: {
    fontSize: 19,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 24,
    marginTop: 4,
  },
  agenticApprovalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  agenticApprovalIcon: {
    minHeight: 76,
    minWidth: 76,
  },
  agenticApprovalMeta: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
  },
  agenticApprovalReason: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 23,
    marginTop: 4,
    position: 'relative',
    zIndex: 1,
  },
  agenticApprovalStatusChip: {
    alignSelf: 'center',
    justifyContent: 'center',
    minWidth: 74,
  },
  agenticApprovalTitle: {
    fontSize: 21,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 27,
  },
  agenticArtifactGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  agenticAuthorityNote: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 10,
    paddingHorizontal: 22,
    textAlign: 'center',
  },
  agenticCaseActionTitle: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 21,
    marginTop: 14,
    position: 'relative',
    zIndex: 1,
  },
  agenticCaseFooterRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
    position: 'relative',
    zIndex: 1,
  },
  agenticCaseHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
    position: 'relative',
    zIndex: 1,
  },
  agenticCaseIcon: {
    minHeight: 68,
    minWidth: 68,
  },
  agenticCasePriorityCard: {
    borderColor: 'rgba(116,224,209,0.55)',
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 34,
  },
  agenticCaseTitle: {
    fontSize: 24,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 30,
  },
  agenticChatActionButton: {
    flex: 1,
    minWidth: 0,
  },
  agenticChatActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatBody: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatCard: {
    alignSelf: 'flex-start',
    gap: 12,
    marginBottom: 6,
    marginTop: 2,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 32,
    width: '92%',
  },
  agenticChatFact: {
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minHeight: 66,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 9,
    position: 'relative',
  },
  agenticChatFactCentered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  agenticChatFactGrid: {
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatFactLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    lineHeight: 13,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatFactValue: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 5,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatIcon: {
    minHeight: 58,
    minWidth: 58,
  },
  agenticChatNote: {
    fontSize: 11.5,
    fontWeight: '600',
    lineHeight: 16,
    position: 'relative',
    zIndex: 1,
  },
  agenticChatTitle: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    position: 'relative',
    zIndex: 1,
  },
  agenticCommandActionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  agenticCommandAmount: {
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 34,
    textAlign: 'right',
  },
  agenticCommandButton: {
    flex: 1,
  },
  agenticCommandHeroCard: {
    borderColor: 'rgba(255,255,255,0.92)',
    gap: 8,
    minHeight: 172,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 34,
  },
  agenticCommandLabelRail: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    marginTop: 4,
    position: 'relative',
    zIndex: 1,
  },
  agenticCommandMoney: {
    alignItems: 'flex-end',
    flex: 1,
  },
  agenticCommandStepLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    textAlign: 'center',
  },
  agenticCommandStepLabelActive: {
    fontWeight: '600',
  },
  agenticCommandTitle: {
    fontSize: 30,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 36,
    position: 'relative',
    zIndex: 1,
  },
  agenticCommandTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceFileCount: {
    alignItems: 'center',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 38,
    minWidth: 54,
    paddingHorizontal: 10,
  },
  agenticEvidenceGateCard: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    padding: 13,
  },
  agenticEvidenceMetricRow: {
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceReasonBox: {
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceReasonInput: {
    width: '100%',
  },
  agenticEvidenceReasonInputShell: {
    minHeight: 48,
  },
  agenticEvidenceToolButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  agenticEvidenceToolRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticEvidenceToolText: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 15,
  },
  agenticHomeStack: {
    position: 'relative',
  },
  agenticMemoryListCard: {
    borderColor: 'rgba(116,224,209,0.46)',
    gap: 0,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 18,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.09,
    shadowRadius: 28,
  },
  agenticMemoryNote: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 10,
    paddingHorizontal: 18,
    textAlign: 'center',
  },
  agenticMemorySaveButton: {
    marginTop: 14,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
  },
  agenticMetricRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
    position: 'relative',
    zIndex: 1,
  },
  agenticMoreInfoCard: {
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 1,
  },
  agenticPaymentLedger: {
    borderRadius: 18,
    borderWidth: 1,
    gap: 0,
    marginTop: 2,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: 'relative',
    zIndex: 1,
  },
  agenticProcessedCard: {
    borderColor: 'rgba(116,224,209,0.42)',
    gap: 0,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 16,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.09,
    shadowRadius: 28,
  },
  agenticProcessedRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 74,
    position: 'relative',
    zIndex: 1,
  },
  agenticProcessedStatusChip: {
    alignSelf: 'center',
    backgroundColor: 'rgba(224,252,245,0.92)',
    borderColor: 'rgba(85,214,195,0.42)',
    justifyContent: 'center',
    marginLeft: 'auto',
    minWidth: 76,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  agenticRejectReasonCard: {
    alignSelf: 'flex-start',
    borderRadius: 22,
    borderWidth: 1,
    gap: 5,
    maxWidth: '88%',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'relative',
  },
  agenticStageStack: {
    position: 'relative',
  },
  agenticTimelineCard: {
    borderColor: 'rgba(116,224,209,0.46)',
    gap: 0,
    overflow: 'hidden',
    paddingVertical: 18,
    position: 'relative',
  },
  agenticTimelineDot: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 3,
    height: 20,
    width: 20,
  },
  agenticTimelineDotActive: {
    backgroundColor: '#DFFBF4',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
  },
  agenticTimelineLine: {
    flex: 1,
    marginVertical: 2,
    width: 2,
  },
  agenticTimelineRail: {
    alignItems: 'center',
    alignSelf: 'stretch',
    width: 28,
  },
  agenticTimelineRow: {
    flexDirection: 'row',
    gap: 12,
    minHeight: 74,
    paddingHorizontal: 18,
    position: 'relative',
    zIndex: 1,
  },
  agenticUtilityGrid: {
    gap: 9,
    marginTop: 12,
    position: 'relative',
    zIndex: 1,
  },
  agenticWorkLogCard: {
    borderColor: 'rgba(116,224,209,0.46)',
    gap: 0,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
  },
  memoryDivider: {
    height: 1,
    marginVertical: 12,
    width: '100%',
  },
  memoryIcon: {
    minHeight: 58,
    minWidth: 58,
  },
  memoryListCard: {
    gap: 0,
  },
  memoryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 78,
    position: 'relative',
    zIndex: 1,
  },
  memoryStatusChip: {
    alignSelf: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    minWidth: 64,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  memoryToggle: {
    alignItems: 'flex-start',
    borderRadius: 18,
    height: 32,
    justifyContent: 'center',
    paddingHorizontal: 4,
    width: 56,
  },
  memoryToggleKnob: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    height: 24,
    shadowColor: '#0A1C22',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 5,
    width: 24,
  },
  memoryToggleKnobOn: {
    alignSelf: 'flex-end',
  },
  memoryTogglePending: {
    alignItems: 'center',
    opacity: 0.84,
  },
})
