import { StyleSheet } from 'react-native'

export const customerV21ChatStyles = StyleSheet.create({
  chatBubble: {
    borderRadius: 22,
    borderWidth: 1,
    maxWidth: '84%',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chatBubbleCustomer: {
    alignSelf: 'flex-end',
    borderBottomRightRadius: 8,
  },
  chatBubbleKael: {
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 8,
  },
  chatBubbleText: {
    fontSize: 14,
    lineHeight: 20,
  },
  chatMediaCameraIcon: {
    height: 20,
    width: 20,
  },
  chatComposerAura: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  chatModeSwitchAura: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  chatComposer: {
    minHeight: 56,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#059B8A',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 24,
  },
  chatComposerDisclaimer: {
    fontSize: 10.5,
    fontWeight: '600',
    lineHeight: 14,
    marginTop: -4,
    textAlign: 'center',
  },
  chatEvidenceStrip: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 10,
  },
  chatFrame: {
    flex: 1,
    gap: 10,
    paddingBottom: 18,
    paddingHorizontal: 16,
    paddingTop: 10,
    position: 'relative',
  },
  chatMediaBadge: {
    alignItems: 'center',
    borderRadius: 8,
    height: 16,
    justifyContent: 'center',
    minWidth: 16,
    paddingHorizontal: 4,
    position: 'absolute',
    right: -4,
    top: -4,
  },
  chatMediaBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    lineHeight: 11,
  },
  chatMediaButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    position: 'relative',
    width: 38,
    zIndex: 1,
  },
  chatMediaButtonDisabled: {
    opacity: 1,
  },
  chatModeButton: {
    position: 'relative',
    zIndex: 1,
  },
  chatModeButtonActive: {
    shadowColor: '#046358',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  chatModeMenu: {
    alignSelf: 'flex-end',
    flexDirection: 'column',
    gap: 4,
    minHeight: 0,
    paddingBottom: 4,
    paddingHorizontal: 4,
    paddingTop: 7,
    position: 'absolute',
    right: 21,
    top: 68,
    width: 172,
    zIndex: 20,
  },
  chatModeMenuButton: {
    borderRadius: 16,
    flex: 0,
    minHeight: 34,
    paddingHorizontal: 9,
    zIndex: 2,
  },
  chatModeMenuOption: {
    borderWidth: 1,
    width: '100%',
  },
  chatModeMenuSheen: {
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderRadius: 999,
    height: 56,
    left: -76,
    position: 'absolute',
    top: -18,
    width: 42,
    zIndex: 1,
  },
  chatModeMenuText: {
    fontSize: 12,
  },
  chatModeSwitch: {
    borderColor: 'rgba(255,255,255,0.88)',
    minHeight: 46,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#087D72',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  chatTimelineTitle: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    textAlign: 'center',
  },
  chatTopCopyCentered: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    transform: [{ translateY: 4 }],
  },
  chatTranscript: {
    flexGrow: 1,
    gap: 8,
    paddingVertical: 6,
  },
  chatTranscriptMenuOpen: {
    paddingTop: 94,
  },
})
