import { Platform, StyleSheet, type ViewStyle } from 'react-native'

const customerV21WebFocusRing = Platform.OS === 'web'
  ? ({ outlineColor: 'rgba(13,167,151,0.62)' } as unknown as ViewStyle)
  : {}

export const customerV21ChatStyles = StyleSheet.create({
  chatBackIcon: {
    height: 22,
    width: 22,
  },
  chatBubble: {
    borderRadius: 22,
    borderWidth: 1,
    maxWidth: '84%',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chatBubbleCustomer: {
    alignSelf: 'flex-end',
    borderBottomRightRadius: 8,
  },
  chatBubbleKael: {
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 8,
  },
  chatBubbleText: {
    fontSize: 14,
    lineHeight: 20,
  },
  chatMediaCameraIcon: {
    height: 20,
    width: 20,
  },
  chatComposerAura: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  chatModeSwitchAura: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  chatComposer: {
    minHeight: 56,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#059B8A',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 24,
  },
  chatComposerDisclaimer: {
    fontSize: 10.5,
    fontWeight: '600',
    lineHeight: 14,
    marginTop: -4,
    textAlign: 'center',
  },
  chatEmptyHero: {
    alignItems: 'center',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 300,
    paddingBottom: 18,
    paddingHorizontal: 24,
    paddingTop: 22,
  },
  chatEmptyHeroContent: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  chatEmptyHeroCopy: {
    fontSize: 20,
    fontWeight: '400',
    letterSpacing: -0.18,
    lineHeight: 29,
    maxWidth: 320,
    textAlign: 'center',
  },
  chatEmptyHeroModelStage: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  chatEvidenceStrip: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 10,
  },
  chatFrame: {
    flex: 1,
    gap: 10,
    paddingBottom: 18,
    paddingHorizontal: 16,
    paddingTop: 10,
    position: 'relative',
  },
  chatHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 58,
    zIndex: 21,
  },
  chatHeaderActions: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    height: 44,
    overflow: 'hidden',
    shadowColor: '#087D72',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  chatHeaderActionsOpen: {
    borderColor: 'rgba(15,174,155,0.30)',
  },
  chatHeaderBackControl: {
    ...customerV21WebFocusRing,
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    shadowColor: '#087D72',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    width: 48,
  },
  chatHeaderModeLabel: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
  },
  chatHeaderModeTrigger: {
    ...customerV21WebFocusRing,
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 21,
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    width: 112,
  },
  chatHeaderModeTriggerOpen: {
    backgroundColor: 'rgba(224,249,243,0.72)',
  },
  chatHeaderNewConversation: {
    ...customerV21WebFocusRing,
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 21,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  chatHeaderNewConversationDisabled: {
    opacity: 0.52,
  },
  chatHeaderSpacer: {
    flex: 1,
    minWidth: 0,
  },
  chatMediaBadge: {
    alignItems: 'center',
    borderRadius: 8,
    height: 16,
    justifyContent: 'center',
    minWidth: 16,
    paddingHorizontal: 4,
    position: 'absolute',
    right: -4,
    top: -4,
  },
  chatMediaBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    lineHeight: 11,
  },
  chatMediaButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    position: 'relative',
    width: 38,
    zIndex: 1,
  },
  chatMediaButtonDisabled: {
    opacity: 1,
  },
  chatModeButton: {
    position: 'relative',
    zIndex: 1,
  },
  chatModeButtonActive: {
    shadowColor: '#046358',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  chatModeMenu: {
    alignSelf: 'flex-end',
    flexDirection: 'column',
    gap: 3,
    minHeight: 0,
    paddingBottom: 4,
    paddingHorizontal: 4,
    paddingTop: 4,
    position: 'absolute',
    maxWidth: 208,
    right: 16,
    top: 68,
    width: '59%',
    zIndex: 20,
  },
  chatModeMenuButton: {
    borderRadius: 13,
    flex: 0,
    minHeight: 46,
    paddingHorizontal: 10,
    paddingVertical: 5,
    zIndex: 2,
  },
  chatModeMenuCheck: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20,
    marginLeft: 8,
  },
  chatModeMenuCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  chatModeMenuDescription: {
    fontSize: 10.5,
    fontWeight: '500',
    lineHeight: 14,
  },
  chatModeMenuOption: {
    alignItems: 'center',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  chatModeMenuSheen: {
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderRadius: 999,
    height: 56,
    left: -76,
    position: 'absolute',
    top: -18,
    width: 42,
    zIndex: 1,
  },
  chatModeMenuText: {
    fontSize: 12.5,
    fontWeight: '700',
    lineHeight: 16,
    textAlign: 'left',
  },
  chatModeSwitch: {
    borderColor: 'rgba(255,255,255,0.88)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 4,
    minHeight: 46,
    overflow: 'hidden',
    padding: 4,
    position: 'relative',
    shadowColor: '#087D72',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  chatTranscript: {
    flexGrow: 1,
    gap: 8,
    paddingVertical: 6,
  },
  chatTranscriptEmpty: {
    justifyContent: 'center',
  },
  chatTranscriptMenuOpen: {
    paddingTop: 112,
  },
  chatTranscriptScroll: {
    flex: 1,
  },
})
