import { Platform, StyleSheet } from 'react-native'

export const CUSTOMER_LIQUID_NAV_MAX_WIDTH = 390
export const CUSTOMER_LIQUID_NAV_SIDE_INSET = 12
export const CUSTOMER_LIQUID_NAV_DOCK_HEIGHT = 56
export const CUSTOMER_LIQUID_NAV_ORB_SIZE = 68
export const CUSTOMER_LIQUID_NAV_GAP = 8
export const CUSTOMER_LIQUID_NAV_RAIL_PADDING = 4

export const customerV21DockStyles = StyleSheet.create({
  dockIcon: {
    height: 27,
    opacity: 0.82,
    position: 'relative',
    transform: [{ translateY: 1 }, { scale: 0.92 }],
    width: 27,
    zIndex: 3,
  },
  dockIconActive: {
    opacity: 1,
    transform: [{ translateY: -1 }, { scale: 1 }],
  },
  dockItem: {
    alignItems: 'center',
    borderRadius: 22,
    flex: 1,
    gap: 2,
    height: 48,
    justifyContent: 'center',
    minWidth: 0,
    position: 'relative',
    zIndex: 3,
  },
  dockItemPressed: {
    transform: [{ scale: 0.9 }],
  },
  dockLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    lineHeight: 11,
    maxWidth: 64,
    position: 'relative',
    textAlign: 'center',
    zIndex: 3,
  },
  dockLabelActive: {
    fontWeight: '600',
    transform: [{ translateY: -1 }],
  },
  dockCaustic: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
    zIndex: 0,
  },
  dockCausticGlow: {
    backgroundColor: 'rgba(28,205,179,0.14)',
    borderRadius: 999,
    bottom: -22,
    filter: Platform.OS === 'web' ? 'blur(9px)' : undefined,
    height: 49,
    position: 'absolute',
  } as any,
  dockCausticSweep: {
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderRadius: 999,
    bottom: -18,
    height: 64,
    left: -10,
    opacity: 0.68,
    position: 'absolute',
    right: -10,
    transform: [{ rotate: '-6deg' }],
  },
  dockCausticSweepBright: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 999,
    height: 24,
    left: '48%',
    opacity: 0.44,
    position: 'absolute',
    right: -22,
    top: 5,
    transform: [{ rotate: '-4deg' }],
  },
  dockInnerRefraction: {
    borderBottomColor: 'rgba(42,205,180,0.08)',
    borderColor: 'rgba(255,255,255,0.45)',
    borderRadius: 27,
    borderWidth: 1,
    bottom: 1,
    left: 1,
    opacity: 0.92,
    position: 'absolute',
    right: 1,
    top: 1,
    zIndex: 2,
  },
  dockLens: {
    backgroundColor: 'rgba(248,255,253,0.94)',
    borderColor: 'rgba(255,255,255,0.98)',
    borderRadius: 24,
    borderWidth: 1,
    bottom: 4,
    left: 4,
    overflow: 'hidden',
    position: 'absolute',
    shadowColor: '#078071',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    top: 4,
    zIndex: 1,
  },
  dockLensBloom: {
    backgroundColor: 'rgba(220,249,242,0.52)',
    borderRadius: 24,
    bottom: 5,
    left: 6,
    opacity: 0.88,
    position: 'absolute',
    right: 6,
    top: 5,
  },
  dockLensInnerShadow: {
    borderBottomColor: 'rgba(12,181,159,0.14)',
    borderColor: 'rgba(5,95,87,0.045)',
    borderRadius: 22,
    borderWidth: 1,
    bottom: 4,
    left: 4,
    opacity: 0.58,
    position: 'absolute',
    right: 4,
    top: 4,
  },
  dockLensSheen: {
    backgroundColor: 'rgba(255,255,255,0.65)',
    borderRadius: 16,
    bottom: 1,
    left: 1,
    position: 'absolute',
    top: 1,
    width: 18,
    zIndex: 3,
  },
  dockLensTopLight: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    height: 14,
    left: 9,
    opacity: 0.68,
    position: 'absolute',
    right: 12,
    top: 5,
    transform: [{ rotate: '-8deg' }],
  },
  dockOverlay: {
    alignItems: 'center',
    bottom: 12,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 30,
  },
  dockPlane: {
    alignItems: 'center',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 0,
    height: CUSTOMER_LIQUID_NAV_DOCK_HEIGHT,
    minHeight: CUSTOMER_LIQUID_NAV_DOCK_HEIGHT,
    overflow: 'hidden',
    padding: CUSTOMER_LIQUID_NAV_RAIL_PADDING,
    position: 'relative',
  },
  dockRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: CUSTOMER_LIQUID_NAV_GAP,
    justifyContent: 'center',
  },
  dockShimmer: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 999,
    filter: Platform.OS === 'web' ? 'blur(2px)' : undefined,
    height: 53,
    left: '-24%',
    opacity: 0.73,
    position: 'absolute',
    top: -31,
    zIndex: 5,
  } as any,
  kaelAccessory: {
    flexShrink: 0,
    height: CUSTOMER_LIQUID_NAV_ORB_SIZE,
    overflow: 'visible',
    width: CUSTOMER_LIQUID_NAV_ORB_SIZE,
  },
  kaelAccessoryActive: {
    transform: [{ scale: 1.015 }],
  },
  kaelAccessoryAura: {
    backgroundColor: 'rgba(23,220,188,0.30)',
    borderRadius: 50,
    bottom: -16,
    filter: Platform.OS === 'web' ? 'blur(8px)' : undefined,
    left: -16,
    opacity: 0.78,
    position: 'absolute',
    right: -16,
    top: -16,
  } as any,
  kaelAccessoryAuraActive: {
    backgroundColor: 'rgba(15,218,183,0.42)',
    opacity: 0.96,
    transform: [{ scale: 1.08 }],
  },
  kaelAccessoryBackdrop: {
    backgroundColor: 'rgba(184,248,236,0.92)',
    borderRadius: 30,
    borderColor: 'rgba(255,255,255,0.80)',
    borderWidth: 1,
    bottom: 5,
    left: 5,
    opacity: 0.82,
    position: 'absolute',
    right: 5,
    top: 5,
    zIndex: 1,
  },
  kaelAccessoryCaustic: {
    backgroundColor: 'rgba(69,231,205,0.18)',
    borderRadius: 28,
    bottom: -9,
    left: 12,
    opacity: 0.46,
    position: 'absolute',
    right: -7,
    top: 18,
    transform: [{ rotate: '-18deg' }],
    zIndex: 3,
  },
  kaelAccessoryFrontRim: {
    borderBottomColor: 'rgba(49,218,193,0.50)',
    borderColor: 'rgba(255,255,255,0.72)',
    borderLeftColor: 'transparent',
    borderRadius: 34,
    borderTopColor: 'transparent',
    borderWidth: 2,
    bottom: 1,
    left: 1,
    opacity: 0.82,
    position: 'absolute',
    right: 1,
    top: 1,
    transform: [{ rotate: '42deg' }],
    zIndex: 7,
  },
  kaelAccessoryGlass: {
    alignItems: 'center',
    backgroundColor: 'rgba(219,251,243,0.76)',
    borderRadius: 34,
    borderWidth: 1,
    height: CUSTOMER_LIQUID_NAV_ORB_SIZE,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#05675D',
    shadowOffset: { height: 15, width: 0 },
    shadowOpacity: 0.20,
    shadowRadius: 29,
    width: CUSTOMER_LIQUID_NAV_ORB_SIZE,
  },
  kaelAccessoryGlassActive: {
    backgroundColor: 'rgba(219,251,243,0.84)',
    shadowOpacity: 0.28,
    shadowRadius: 35,
  },
  kaelAccessoryGlint: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 10,
    filter: Platform.OS === 'web' ? 'blur(1.2px)' : undefined,
    height: 8,
    left: 13,
    opacity: 0.74,
    position: 'absolute',
    top: 9,
    width: 13,
    zIndex: 8,
  } as any,
  kaelAccessoryGlobeTop: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 999,
    height: 18,
    left: 8,
    opacity: 0.78,
    position: 'absolute',
    right: 10,
    top: 4,
    zIndex: 6,
  },
  kaelAccessoryImage: {
    height: 62,
    left: 4,
    position: 'absolute',
    top: -1,
    transform: [{ translateY: 3 }, { scale: 1.025 }],
    width: 60,
    zIndex: 5,
  },
  kaelAccessoryOrbit: {
    borderBottomColor: 'rgba(14,181,158,0.36)',
    borderColor: 'rgba(73,229,204,0.52)',
    borderLeftColor: 'rgba(255,255,255,0.72)',
    borderRadius: 42,
    borderRightColor: 'rgba(14,181,158,0.42)',
    borderTopColor: 'rgba(255,255,255,0.88)',
    borderWidth: 1,
    height: 50,
    left: -8,
    opacity: 0.74,
    position: 'absolute',
    top: 9,
    transform: [{ rotate: '-18deg' }],
    width: 84,
    zIndex: 1,
  },
  kaelAccessoryOrbitActive: {
    borderBottomColor: 'rgba(14,181,158,0.52)',
    borderColor: 'rgba(73,229,204,0.72)',
    opacity: 0.88,
  },
  kaelAccessoryOrbitBack: {
    opacity: 0.42,
    transform: [{ rotate: '24deg' }, { scale: 0.94 }],
    zIndex: 0,
  },
  kaelAccessoryOrbMotion: {
    height: CUSTOMER_LIQUID_NAV_ORB_SIZE,
    position: 'relative',
    width: CUSTOMER_LIQUID_NAV_ORB_SIZE,
    zIndex: 2,
  },
  kaelAccessoryPearl: {
    backgroundColor: '#F7FFFD',
    borderColor: 'rgba(56,222,196,0.40)',
    borderRadius: 4,
    borderWidth: 2,
    height: 7,
    position: 'absolute',
    right: 1,
    shadowColor: '#1BD9B8',
    shadowOpacity: 0.5,
    shadowRadius: 8,
    top: 15,
    width: 7,
  },
  kaelAccessoryPressed: {
    transform: [{ scale: 0.94 }],
  },
  kaelAccessoryRipple: {
    borderColor: 'rgba(35,221,190,0.74)',
    borderRadius: 34,
    borderWidth: 1.5,
    bottom: 2,
    left: 2,
    position: 'absolute',
    right: 2,
    top: 2,
    zIndex: 0,
  },
  kaelAccessoryStatus: {
    backgroundColor: '#12BB7E',
    borderColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 2,
    bottom: 5,
    height: 12,
    position: 'absolute',
    right: 3,
    shadowColor: '#0B8763',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    width: 12,
    zIndex: 10,
  },
  kaelAccessoryStatusHalo: {
    backgroundColor: 'rgba(18,191,132,0.16)',
    borderRadius: 9,
    bottom: 2,
    height: 18,
    position: 'absolute',
    right: 0,
    width: 18,
    zIndex: 9,
  },
  kaelAccessoryStatusWave: {
    borderColor: 'rgba(25,205,144,0.42)',
    borderRadius: 12,
    borderWidth: 1,
    bottom: 0,
    height: 24,
    opacity: 0.42,
    position: 'absolute',
    right: -3,
    width: 24,
    zIndex: 8,
  },
})
