import { StyleSheet } from 'react-native'

export const customerV21HistoryActiveStyles = StyleSheet.create({
  activityActiveDot: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  activityScreenBody: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    marginTop: 3,
  },
  activityScreenCard: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 74,
    overflow: 'hidden',
    padding: 10,
    position: 'relative',
  },
  activityScreenIcon: {
    minHeight: 52,
    minWidth: 52,
  },
  activityScreenPaymentAuraCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(116,224,209,0.64)',
    shadowColor: '#24B3A1',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 30,
  },
  activityStatusHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    marginTop: 12,
  },
  activityStatusRows: {
    gap: 4,
    marginTop: 12,
  },
  activityStatusValue: {
    fontSize: 23,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 29,
    marginTop: 2,
  },
  caseArtifactGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  caseChatFrame: {
    gap: 9,
  },
  caseChatSummaryBody: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    position: 'relative',
    zIndex: 1,
  },
  caseChatSummaryCard: {
    borderColor: 'rgba(255,255,255,0.91)',
    borderRadius: 24,
    gap: 9,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 11,
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  caseChatSummaryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  caseChatSummaryIcon: {
    minHeight: 60,
    minWidth: 60,
  },
  caseChatSummaryText: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  caseChatSummaryTitle: {
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 21,
  },
  caseDivider: {
    height: 1,
    opacity: 0.74,
    width: '100%',
  },
  caseEvidenceCard: {
    gap: 8,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  caseInfoDivider: {
    height: 1,
    width: '100%',
  },
  caseKaelPaymentAuraCard: {
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderColor: 'rgba(116,224,209,0.62)',
    shadowColor: '#24B3A1',
    shadowOpacity: 0.15,
    shadowRadius: 34,
  },
  caseKaelSourceBody: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  caseKaelSourceCard: {
    backgroundColor: 'rgba(255,255,255,0.91)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 24,
    minHeight: 80,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 32,
  },
  caseKaelSourceContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    position: 'relative',
    zIndex: 1,
  },
  caseKaelSourceIcon: {
    minHeight: 60,
    minWidth: 60,
  },
  caseKaelSourceTitle: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 21,
  },
  caseLoadingCard: {
    alignItems: 'center',
    gap: 10,
  },
  caseLocationActionButton: {
    flex: 1,
    minWidth: 0,
  },
  caseLocationActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  caseOptionBadgeTop: {
    alignItems: 'flex-end',
    marginBottom: 7,
  },
  caseOptionBody: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 3,
  },
  caseOptionChoiceStack: {
    gap: 8,
    marginTop: 8,
  },
  caseOptionHeroCard: {
    backgroundColor: 'rgba(255,255,255,0.91)',
    borderColor: 'rgba(13,174,154,0.55)',
    borderRadius: 24,
    gap: 0,
    minHeight: 186,
    overflow: 'hidden',
    padding: 13,
    position: 'relative',
    shadowColor: '#24B3A1',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 26,
  },
  caseOptionHeroIcon: {
    minHeight: 66,
    minWidth: 66,
  },
  caseOptionHeroMain: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  caseOptionMetric: {
    flex: 1,
    minWidth: 0,
  },
  caseOptionMetricLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    lineHeight: 14,
  },
  caseOptionMetricRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  caseOptionMetricValue: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 2,
  },
  caseOptionMoney: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 2,
  },
  caseOptionTitle: {
    fontSize: 21,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 26,
  },
  caseOverviewCard: {
    gap: 14,
  },
  caseOverviewDetailText: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 21,
    marginTop: 3,
  },
  caseOverviewHeroCard: {
    minHeight: 166,
    overflow: 'hidden',
    paddingVertical: 18,
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 26,
  },
  caseOverviewHeroContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  caseOverviewHeroText: {
    flex: 1,
    minWidth: 0,
  },
  caseOverviewInfoCard: {
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  caseOverviewNextButton: {
    marginTop: 0,
  },
  caseOverviewNextCard: {
    borderRadius: 20,
    marginTop: 0,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 11,
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  caseOverviewNextContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    position: 'relative',
    zIndex: 1,
  },
  caseOverviewNextCopy: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
    marginTop: 2,
  },
  caseOverviewNextIcon: {
    minHeight: 58,
    minWidth: 58,
  },
  caseOverviewNextStack: {
    gap: 10,
    marginTop: 9,
  },
  caseOverviewTitle: {
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 34,
    marginTop: 8,
  },
  casePriceLines: {
    gap: 0,
  },
  casePrimaryInfoCard: {
    gap: 12,
  },
  casePrimaryStageButton: {
    marginTop: 14,
    overflow: 'hidden',
    shadowColor: '#24B3A1',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
  },
  caseProgressCard: {
    gap: 10,
    overflow: 'hidden',
    paddingVertical: 12,
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  caseQuoteButton: {
    flex: 1,
    minWidth: 0,
  },
  caseQuoteButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  caseQuoteLedgerCard: {
    backgroundColor: 'rgba(255,255,255,0.91)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 24,
    gap: 0,
    minHeight: 250,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 32,
  },
  caseQuoteStatGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  caseQuoteWorkerMeta: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 2,
  },
  caseQuoteWorkerName: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 25,
  },
  caseQuoteWorkerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
  },
  caseRecommendationCard: {
    gap: 12,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  caseReferenceHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 142,
  },
  caseSourceLayer: {
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  caseStepListCard: {
    backgroundColor: 'rgba(255,255,255,0.91)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 24,
    gap: 0,
    overflow: 'hidden',
    paddingHorizontal: 13,
    paddingVertical: 13,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 32,
  },
  caseStepListContent: {
    gap: 6,
    position: 'relative',
    zIndex: 1,
  },
  caseTimelineCard: {
    backgroundColor: 'rgba(255,255,255,0.91)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 24,
    gap: 0,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 13,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 32,
  },
  caseTimelineContent: {
    gap: 9,
    paddingLeft: 1,
    position: 'relative',
    zIndex: 1,
  },
  caseTimelineRail: {
    backgroundColor: '#D6EBE6',
    bottom: 16,
    left: 10,
    position: 'absolute',
    top: 9,
    width: 2,
    zIndex: 0,
  },
  caseUnderstandingCard: {
    gap: 10,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  caseUnderstandingStrong: {
    fontWeight: '600',
  },
  caseUnderstandingText: {
    fontSize: 19,
    fontWeight: '600',
    lineHeight: 25,
  },
  caseWorkDataSourceText: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  caseWorkLockedActionButton: {
    flex: 1,
    minWidth: 0,
  },
  caseWorkLockedActions: {
    flexDirection: 'row',
    gap: 10,
    position: 'relative',
    zIndex: 1,
  },
  caseWorkSourceChip: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    minWidth: 78,
    overflow: 'hidden',
    paddingHorizontal: 14,
    position: 'relative',
  },
  caseWorkSourceChipText: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  fulfillmentCaption: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 9,
    textAlign: 'center',
  },
  fulfillmentCenteredText: {
    textAlign: 'center',
  },
  fulfillmentChipRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    justifyContent: 'center',
    marginTop: 10,
    position: 'relative',
    zIndex: 1,
  },
  fulfillmentDivider: {
    height: 1,
    marginVertical: 12,
    position: 'relative',
    width: '100%',
    zIndex: 1,
  },
  fulfillmentHeroCard: {
    overflow: 'hidden',
    paddingHorizontal: 15,
    paddingVertical: 18,
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 34,
  },
  fulfillmentHeroCentered: {
    alignItems: 'center',
  },
  fulfillmentHeroPill: {
    alignSelf: 'center',
  },
  fulfillmentKaelCardWrap: {
    marginTop: 9,
  },
  fulfillmentListCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 25,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 13,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
  },
  fulfillmentProgressHeroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    position: 'relative',
    zIndex: 1,
  },
  fulfillmentProgressIcon: {
    minHeight: 78,
    minWidth: 78,
  },
  fulfillmentScopeLabel: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  fulfillmentScopeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  fulfillmentScopeValue: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 21,
    textAlign: 'right',
  },
  fulfillmentStepList: {
    gap: 6,
    position: 'relative',
    zIndex: 1,
  },
  fulfillmentWorkerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    position: 'relative',
    zIndex: 1,
  },
})
