import { StyleSheet } from 'react-native'

import type { CustomerThemeTokens } from '../customer-theme'

type CustomerV21TimelineState = 'done' | 'active' | 'pending'

export function customerV21TimelineDotSurface(state: CustomerV21TimelineState, tokens: CustomerThemeTokens) {
  return {
    backgroundColor: state === 'pending' ? tokens.raised : tokens.primary,
    borderColor: state === 'pending' ? tokens.border : 'rgba(255,255,255,0.92)',
    shadowColor: state === 'active' ? '#08AF9C' : 'transparent',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: state === 'active' ? 0.18 : 0,
    shadowRadius: state === 'active' ? 12 : 0,
  }
}

export function customerV21CaseScopeStepRowSurface(state: CustomerV21TimelineState) {
  return {
    backgroundColor: 'rgba(247,255,251,0.76)',
    borderColor: state === 'active' ? 'rgba(13,174,154,0.45)' : 'rgba(216,235,232,0.80)',
  }
}

export function customerV21CaseScopeStateDotSurface(state: CustomerV21TimelineState) {
  return {
    backgroundColor: state === 'done' ? '#E6FBF3' : state === 'active' ? '#08AF9C' : '#EDF3F2',
    borderColor: state === 'active' ? '#08AF9C' : 'rgba(216,235,232,0.90)',
  }
}

export const customerV21HistoryStyles = StyleSheet.create({
  caseOverviewInfoIcon: {
    minHeight: 64,
    minWidth: 64,
  },
  caseOverviewInfoLabel: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 19,
  },
  caseOverviewInfoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
    position: 'relative',
    zIndex: 1,
  },
  caseOverviewInfoValue: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 2,
  },
  caseProgressLabel: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
    minWidth: 0,
    width: 64,
  },
  caseProgressLabelCenter: {
    textAlign: 'center',
  },
  caseProgressLabelEnd: {
    textAlign: 'right',
  },
  caseProgressLabelRail: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 5,
    marginTop: -2,
    position: 'relative',
    width: '100%',
    zIndex: 1,
  },
  caseProgressLabelSlot: {
    overflow: 'visible',
    width: 23,
  },
  caseProgressLabelSlotCenter: {
    alignItems: 'center',
  },
  caseProgressLabelSlotEnd: {
    alignItems: 'flex-end',
  },
  caseProgressLabelSlotStart: {
    alignItems: 'flex-start',
  },
  caseProgressLabelSpacer: {
    flex: 1,
    height: 1,
  },
  caseProgressLabelStart: {
    textAlign: 'left',
  },
  chevronText: {
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
  },
  statusPill: {
    borderRadius: 999,
    maxWidth: 118,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  caseMiniStat: {
    backgroundColor: 'rgba(255,255,255,0.91)',
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    minHeight: 76,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 26,
  },
  caseMiniStatLabel: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
  },
  caseMiniStatValue: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 23,
    marginTop: 4,
  },
  metric: {
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 82,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
  },
  metricAura: {
    borderColor: 'rgba(113,225,209,0.42)',
    shadowColor: '#087D72',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  metricContent: {
    position: 'relative',
    zIndex: 1,
  },
  factGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricLabel: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    marginTop: 4,
  },
  metricValue: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 21,
  },
  casePriceLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  casePriceLine: {
    alignItems: 'center',
    borderBottomColor: 'rgba(216,235,232,0.70)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  casePriceTotalLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  casePriceTotalLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingTop: 11,
  },
  casePriceTotalValue: {
    fontSize: 19,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'right',
  },
  casePriceValue: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
    maxWidth: '48%',
    textAlign: 'right',
  },
  caseScopeLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  caseScopeStateDot: {
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  caseScopeStateText: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 12,
  },
  caseScopeStepRow: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 38,
    paddingHorizontal: 9,
    paddingVertical: 7,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  caseScopeValue: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 13,
    maxWidth: 86,
    textAlign: 'right',
  },
  caseTimelineBody: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 2,
  },
  caseTimelineDot: {
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  caseTimelineDotText: {
    fontSize: 9,
    fontWeight: '600',
    lineHeight: 11,
  },
  caseTimelineItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
    minHeight: 53,
    position: 'relative',
    zIndex: 1,
  },
  caseTimelineTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  caseWorkerAvatar: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 48,
  },
  caseWorkerAvatarImage: {
    height: '100%',
    width: '100%',
  },
  caseWorkerAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  labelText: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  caseSourceLayer: {
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  caseArtifact: {
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    minHeight: 86,
    overflow: 'hidden',
    padding: 13,
    position: 'relative',
  },
  caseArtifactLabel: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
    position: 'relative',
    zIndex: 1,
  },
  caseArtifactValue: {
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 24,
    marginTop: 6,
    position: 'relative',
    zIndex: 1,
  },
  caseMapCanvas: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#EDF7E8',
    overflow: 'hidden',
    zIndex: 0,
  },
  caseMapAuraLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  caseMapCard: {
    borderColor: '#D8E9DE',
    borderRadius: 24,
    borderWidth: 1,
    height: 215,
    marginTop: 14,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 32,
    width: '100%',
  },
  caseMapEta: {
    alignItems: 'flex-end',
    minWidth: 54,
  },
  caseMapEtaLabel: {
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 12,
    marginTop: 1,
  },
  caseMapEtaValue: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 18,
  },
  caseMapFloat: {
    alignItems: 'center',
    borderRadius: 17,
    borderWidth: 1,
    bottom: 10,
    flexDirection: 'row',
    gap: 10,
    left: 12,
    minHeight: 58,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 9,
    position: 'absolute',
    right: 12,
    shadowColor: '#085F57',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    zIndex: 4,
  },
  caseMapPin: {
    alignItems: 'center',
    backgroundColor: '#08AF9C',
    borderColor: '#FFFFFF',
    borderRadius: 16,
    borderBottomLeftRadius: 0,
    borderWidth: 0,
    height: 32,
    justifyContent: 'center',
    position: 'absolute',
    shadowColor: '#087D72',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    transform: [{ rotate: '-45deg' }],
    width: 32,
    zIndex: 3,
  },
  caseMapPinInner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    height: 11,
    width: 11,
  },
  caseMapPinEnd: {
    right: 45,
    top: 51,
  },
  caseMapPinStart: {
    left: 46,
    top: 127,
  },
  caseMapWorkerMeta: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 2,
  },
  caseMapWorkerName: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 19,
  },
  caseOverviewLiquidScore: {
    alignItems: 'center',
    flexShrink: 0,
    height: 82,
    justifyContent: 'center',
    position: 'relative',
    width: 82,
  },
  caseOptionChoiceBody: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 17,
  },
  caseOptionChoiceCard: {
    borderRadius: 24,
    gap: 0,
    minHeight: 92,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.09,
    shadowRadius: 24,
  },
  caseOptionChoiceContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  caseOptionChoiceIcon: {
    minHeight: 58,
    minWidth: 58,
  },
  caseOptionChoiceTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  caseOverviewScoreAura: {
    bottom: -22,
    left: -22,
    overflow: 'hidden',
    position: 'absolute',
    right: -22,
    top: -22,
  },
  caseOverviewScoreHighlight: {
    backgroundColor: 'rgba(255,255,255,0.70)',
    borderRadius: 999,
    height: 12,
    left: 12,
    position: 'absolute',
    right: 12,
    top: 6,
  },
  caseOverviewScoreInside: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 2,
  },
  caseOverviewScoreLabel: {
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 11,
    maxWidth: 58,
    textAlign: 'center',
  },
  caseOverviewScoreLens: {
    borderRadius: 999,
    borderWidth: 1,
    bottom: 12,
    left: 12,
    overflow: 'hidden',
    position: 'absolute',
    right: 12,
    shadowColor: '#04665B',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.09,
    shadowRadius: 24,
    top: 12,
    zIndex: 1,
  },
  caseOverviewScoreSvg: {
    position: 'absolute',
    transform: [{ rotate: '-90deg' }],
    zIndex: 1,
  },
  caseOverviewScoreValue: {
    fontSize: 25,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 28,
  },
  matchingKaelStatusIconAura: {
    ...StyleSheet.absoluteFillObject,
  },
  matchingKaelStatusIconWrap: {
    height: 86,
    overflow: 'hidden',
    position: 'relative',
    width: 86,
  },
  matchingKaelStatusImage: {
    height: 70,
    left: 8,
    position: 'absolute',
    top: 8,
    width: 70,
  },
  mediaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  arrivalCodeBox: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 10,
    position: 'relative',
    zIndex: 1,
  },
  arrivalCodeDigit: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    shadowColor: '#085F57',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    width: 42,
  },
  arrivalCodeDigitText: {
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 24,
  },
  arrivalCodeDigitPending: {
    opacity: 0.72,
  },
  arrivalCodePending: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 48,
    minWidth: 132,
    paddingHorizontal: 18,
    position: 'relative',
    zIndex: 1,
  },
  arrivalCodePendingText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  arrivalCodePendingWrap: {
    alignItems: 'center',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  stageMediaEmpty: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 64,
    position: 'relative',
    zIndex: 1,
  },
  stageMediaStrip: {
    flexDirection: 'row',
    gap: 7,
    position: 'relative',
    zIndex: 1,
  },
  stageMediaTag: {
    backgroundColor: 'rgba(7,26,36,0.62)',
    borderRadius: 999,
    bottom: 6,
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '600',
    left: 7,
    lineHeight: 12,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
    position: 'absolute',
  },
  stageMediaThumb: {
    backgroundColor: '#254B52',
    borderColor: 'rgba(255,255,255,0.76)',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    height: 68,
    minWidth: 0,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
  },
  stageMediaThumbGlow: {
    backgroundColor: '#28C9B5',
    borderRadius: 22,
    height: 36,
    left: 22,
    opacity: 0.62,
    position: 'absolute',
    top: 15,
    transform: [{ rotate: '45deg' }],
    width: 36,
  },
  successEmblem: {
    alignItems: 'center',
    backgroundColor: 'rgba(203,248,238,0.88)',
    borderRadius: 34,
    height: 104,
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: 2,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#087D72',
    shadowOffset: { height: 22, width: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 44,
    width: 104,
    zIndex: 1,
  },
  successEmblemCore: {
    alignItems: 'center',
    borderRadius: 23,
    borderWidth: 3,
    height: 63,
    justifyContent: 'center',
    shadowColor: '#087D72',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    width: 63,
    zIndex: 1,
  },
  successEmblemAura: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  successEmblemPending: {
    backgroundColor: 'rgba(238,251,247,0.90)',
    shadowOpacity: 0.18,
  },
  successEmblemText: {
    fontSize: 34,
    fontWeight: '600',
    lineHeight: 39,
  },
  fulfillmentListIcon: {
    minHeight: 54,
    minWidth: 54,
  },
  fulfillmentListRow: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 73,
    paddingVertical: 10,
  },
  fulfillmentRowBody: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 17,
  },
  fulfillmentRowTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  fulfillmentStep: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 66,
    padding: 12,
  },
  fulfillmentStepBody: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  fulfillmentStepState: {
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  fulfillmentStepStateText: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 14,
  },
  fulfillmentStepTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  flex: {
    flex: 1,
  },
})
