import { StyleSheet } from 'react-native'

export const customerV21PaymentStyles = StyleSheet.create({
  flex: {
    flex: 1,
    minWidth: 0,
  },
  paymentPriceLine: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 38,
    position: 'relative',
    zIndex: 1,
  },
  paymentPriceLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    minWidth: 0,
  },
  paymentPriceValue: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
    maxWidth: '52%',
    textAlign: 'right',
  },
  paymentMethodHeroIconFrame: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 24,
    borderWidth: 1,
    height: 86,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 26,
    width: 86,
  },
  paymentMethodHeroBankLogo: {
    height: 52,
    position: 'relative',
    width: 74,
    zIndex: 1,
  },
  paymentMethodHeroWalletImage: {
    height: 56,
    position: 'relative',
    width: 56,
    zIndex: 1,
  },
  paymentBankTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.91)',
    borderColor: 'rgba(216,235,232,0.92)',
    borderRadius: 22,
    borderWidth: 1,
    flexBasis: '30%',
    flexGrow: 1,
    height: 88,
    justifyContent: 'center',
    minWidth: 92,
    overflow: 'hidden',
    paddingHorizontal: 10,
    position: 'relative',
    shadowColor: '#085F57',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 22,
  },
  paymentBankTileSelected: {
    borderColor: '#55D6C3',
    borderWidth: 1.5,
    shadowColor: '#08AF9C',
    shadowOpacity: 0.16,
  },
  paymentBankTileDisabled: {
    opacity: 0.76,
  },
  paymentBankLogo: {
    height: 58,
    position: 'relative',
    width: 104,
    zIndex: 1,
  },
  paymentBankCheck: {
    alignItems: 'center',
    backgroundColor: '#08AF9C',
    borderRadius: 13,
    height: 26,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: 8,
    width: 26,
    zIndex: 2,
  },
  paymentBankCheckText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 16,
  },
  paymentMethodRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    minHeight: 56,
    position: 'relative',
    zIndex: 1,
  },
  paymentMethodRowIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    borderWidth: 1,
    height: 60,
    justifyContent: 'center',
    minWidth: 60,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
  },
  paymentMethodAssetIcon: {
    height: 58,
    position: 'relative',
    width: 58,
    zIndex: 1,
  },
  paymentLedgerStep: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 54,
    position: 'relative',
    zIndex: 1,
  },
  paymentLedgerRail: {
    bottom: -15,
    left: 12,
    position: 'absolute',
    top: 30,
    width: 2,
    zIndex: 0,
  },
  paymentLedgerDot: {
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    width: 26,
    zIndex: 1,
  },
  paymentLedgerDotAura: {
    backgroundColor: 'rgba(180,246,234,0.48)',
    borderRadius: 21,
    height: 42,
    position: 'absolute',
    width: 42,
    zIndex: -1,
  },
  paymentLedgerDotText: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 13,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  bodyText: {
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 19,
  },
  chevronText: {
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 26,
  },
  pressed: {
    transform: [{ scale: 0.985 }],
  },
  paymentBankGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
    position: 'relative',
  },
  paymentBankRecommendedCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(74,215,198,0.58)',
    borderRadius: 26,
    minHeight: 112,
    overflow: 'hidden',
    padding: 13,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 15, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 30,
  },
  paymentBankRecommendedFallbackIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    borderWidth: 1,
    height: 66,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    width: 66,
  },
  paymentBankRecommendedLogo: {
    height: 46,
    width: 90,
  },
  paymentBankRecommendedLogoBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 22,
    borderWidth: 1,
    height: 74,
    justifyContent: 'center',
    minWidth: 112,
    overflow: 'hidden',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.09,
    shadowRadius: 22,
  },
  paymentLedgerCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(154,232,219,0.56)',
    borderRadius: 26,
    gap: 0,
    minHeight: 250,
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 18,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
  },
  paymentMethodAmount: {
    fontSize: 30,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 36,
    marginVertical: 3,
  },
  paymentMethodHeroCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(74,215,198,0.62)',
    borderRadius: 26,
    minHeight: 168,
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 15,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 20, width: 0 },
    shadowOpacity: 0.17,
    shadowRadius: 38,
  },
  paymentMethodHeroContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 128,
    position: 'relative',
    zIndex: 1,
  },
  paymentMethodHeroTextColumn: {
    alignItems: 'flex-start',
    flex: 1,
    justifyContent: 'center',
    minHeight: 124,
    minWidth: 0,
  },
  paymentMethodOtherCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(154,232,219,0.52)',
    borderRadius: 24,
    gap: 0,
    minHeight: 136,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 26,
  },
  paymentMethodRightChip: {
    alignSelf: 'center',
    marginLeft: 'auto',
    minWidth: 82,
  },
  paymentPriceCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(154,232,219,0.58)',
    borderRadius: 24,
    gap: 0,
    minHeight: 230,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 15, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
  },
  paymentProtectedAmount: {
    flexShrink: 1,
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 22,
    maxWidth: 112,
    textAlign: 'right',
  },
  paymentProtectedChip: {
    alignSelf: 'center',
    marginTop: 12,
    position: 'relative',
    zIndex: 1,
  },
  paymentProtectedHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(154,232,219,0.62)',
    borderRadius: 30,
    minHeight: 264,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 20,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 20, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 38,
  },
  paymentProtectedServiceCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(154,232,219,0.52)',
    borderRadius: 26,
    minHeight: 104,
    overflow: 'hidden',
    padding: 14,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
  },
  paymentProtectedTitle: {
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 34,
    marginTop: 14,
    textAlign: 'center',
  },
  paymentReviewCaseCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(154,232,219,0.58)',
    borderRadius: 24,
    gap: 10,
    minHeight: 174,
    overflow: 'hidden',
    padding: 13,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 30,
  },
  paymentReviewLeadingCell: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 64,
    width: 70,
  },
  paymentReviewMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    position: 'relative',
    zIndex: 1,
  },
  paymentReviewMetaText: {
    flex: 1,
    fontWeight: '700',
    minWidth: 0,
  },
  paymentReviewMetaTextRight: {
    flex: 1.15,
    fontWeight: '700',
    minWidth: 0,
    textAlign: 'right',
  },
  paymentReviewRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    position: 'relative',
    zIndex: 1,
  },
  paymentReviewServiceIcon: {
    minHeight: 62,
    minWidth: 62,
  },
  paymentReviewTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  paymentSafetyCard: {
    backgroundColor: 'rgba(255,255,255,0.93)',
    borderColor: 'rgba(154,232,219,0.50)',
    borderRadius: 24,
    gap: 0,
    minHeight: 82,
    overflow: 'hidden',
    padding: 12,
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 26,
  },
  paymentSafetyIcon: {
    minHeight: 56,
    minWidth: 56,
  },
  paymentTotalLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
  },
  paymentTotalLine: {
    alignItems: 'center',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 12,
    position: 'relative',
    zIndex: 1,
  },
  paymentTotalValue: {
    flexShrink: 1,
    fontSize: 21,
    fontWeight: '600',
    lineHeight: 26,
    textAlign: 'right',
  },
  paymentWorkerNetLabel: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
  },
  paymentWorkerNetPill: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#EAF8EF',
    borderColor: '#BFE8CE',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    minHeight: 34,
    paddingHorizontal: 12,
    position: 'relative',
    zIndex: 1,
  },
  paymentWorkerNetValue: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 15,
  },
})
