import { StyleSheet } from 'react-native'

export const customerV21ProfileMetricStyles = StyleSheet.create({
  caseOverviewScoreHighlight: {
    backgroundColor: 'rgba(255,255,255,0.70)',
    borderRadius: 999,
    height: 12,
    left: 12,
    position: 'absolute',
    right: 12,
    top: 6,
  },
  caseOverviewScoreInside: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 2,
  },
  caseOverviewScoreSvg: {
    position: 'absolute',
    transform: [{ rotate: '-90deg' }],
    zIndex: 1,
  },
  profileCompactMintAura: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  profileLiquidScore: {
    alignItems: 'center',
    flexShrink: 0,
    justifyContent: 'center',
    position: 'relative',
  },
  profileLiquidScoreLarge: {
    alignSelf: 'center',
  },
  profileScoreLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    lineHeight: 11,
    maxWidth: 82,
    textAlign: 'center',
  },
  profileScoreLabelLarge: {
    fontSize: 10.5,
    lineHeight: 12,
    maxWidth: 86,
  },
  profileScoreLens: {
    borderRadius: 999,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'absolute',
    shadowColor: '#04665B',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.09,
    shadowRadius: 24,
    zIndex: 1,
  },
  profileScoreMeta: {
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: 82,
  },
  profileScoreMetaLarge: {
    maxWidth: 88,
  },
  profileScoreSubLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    lineHeight: 11,
    maxWidth: 82,
    textAlign: 'center',
  },
  profileScoreSubLabelLarge: {
    fontSize: 10.5,
    lineHeight: 12,
    maxWidth: 88,
  },
  profileScoreValue: {
    fontSize: 30,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 34,
  },
  profileScoreValueLarge: {
    fontSize: 38,
    lineHeight: 42,
  },
  profileStatCard: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexBasis: '30%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 76,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 12,
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 24,
  },
  profileStatContent: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  profileStatLabel: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    marginTop: 4,
    textAlign: 'center',
  },
  profileStatValue: {
    fontSize: 23,
    fontWeight: '600',
    lineHeight: 28,
    textAlign: 'center',
  },
  profileStatValueCompact: {
    fontSize: 17,
    lineHeight: 22,
  },
})
