import { StyleSheet } from 'react-native'

export const customerV21ProfilePaymentStyles = StyleSheet.create({
  heroCard: {
    borderColor: 'rgba(74,218,197,0.48)',
    borderRadius: 28,
    padding: 0,
  },
  heroConnector: {
    height: 1,
    position: 'absolute',
    right: -24,
    top: '50%',
    width: 24,
    zIndex: 2,
  },
  heroConnectorDot: {
    borderRadius: 7,
    borderWidth: 1,
    height: 14,
    marginTop: -7,
    position: 'absolute',
    right: -7,
    top: '50%',
    width: 14,
    zIndex: 3,
  },
  heroContent: {
    alignItems: 'stretch',
    flexDirection: 'row',
    minHeight: 142,
  },
  heroCopy: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    paddingBottom: 14,
    paddingLeft: 43,
    paddingRight: 8,
    paddingTop: 14,
  },
  heroIconImage: {
    height: 82,
    position: 'relative',
    width: 82,
    zIndex: 1,
  },
  heroSignal: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 5,
    minWidth: 0,
  },
  heroSignalRail: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 7,
  },
  heroSignalText: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    minWidth: 0,
  },
  heroStatus: {
    alignSelf: 'center',
    flexShrink: 0,
    marginRight: 16,
    maxWidth: 104,
  },
  heroSummary: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 2,
  },
  heroTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroVisualPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRightWidth: 1,
    flexShrink: 0,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
    width: 116,
    zIndex: 1,
  },
})
