import { StyleSheet } from 'react-native'

export const customerV21ProfileUtilityStyles = StyleSheet.create({
  bodyText: {
    fontSize: 14,
    lineHeight: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 23,
  },
  flex: {
    flex: 1,
  },
  infoNoticeIcon: {
    flexShrink: 0,
  },
  pressed: {
    transform: [{ scale: 0.985 }],
  },
  profileInsightChip: {
    backgroundColor: 'rgba(224,252,245,0.88)',
    borderColor: 'rgba(85,214,195,0.40)',
    minWidth: 68,
    position: 'relative',
    zIndex: 1,
  },
  profileInsightEmptyChip: {
    backgroundColor: 'rgba(236,253,248,0.84)',
    borderColor: 'rgba(85,214,195,0.34)',
    minWidth: 68,
    position: 'relative',
    zIndex: 1,
  },
  profileInsightEmptyChipText: {
    color: '#0B8579',
    fontWeight: '700',
  },
  profileInsightChipFrame: {
    alignSelf: 'center',
    borderRadius: 999,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 14,
  },
  profileInsightTitle: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  profileInsightRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 86,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileMintChipText: {
    color: '#087D72',
    fontWeight: '700',
  },
  profileAuraCard: {
    gap: 0,
    overflow: 'hidden',
    position: 'relative',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 28,
  },
  profileAuraCardShadowDark: {
    shadowColor: '#000000',
  },
  profileAuraCardShadowLight: {
    shadowColor: '#087D72',
  },
  profileAuraContent: {
    position: 'relative',
    zIndex: 1,
  },
  profileAddressAddButton: {
    minHeight: 44,
    minWidth: 86,
  },
  profileAddressAddRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  profileAddressBlock: {
    gap: 10,
  },
  profileAddressBlockHeader: {
    gap: 3,
  },
  profileAddressDefaultButton: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  profileAddressDefaultText: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileAddressDivider: {
    height: 1,
    opacity: 0.86,
  },
  profileAddressHint: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileAddressHub: {
    gap: 14,
  },
  profileAddressHubHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileAddressHubIcon: {
    flexShrink: 0,
    minHeight: 76,
    minWidth: 76,
  },
  profileAddressInput: {
    borderRadius: 18,
    borderWidth: 1,
    fontSize: 14,
    fontWeight: '600',
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  profileAddressMessage: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  profileAddressSaveDefaultButton: {
    borderRadius: 22,
  },
  profileAddressSaveDefaultButtonActive: {
    backgroundColor: '#12B8A4',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
  },
  profileAddressSavedIcon: {
    flexShrink: 0,
    minHeight: 62,
    minWidth: 62,
  },
  profileAddressSavedList: {
    gap: 10,
  },
  profileAddressSavedRow: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileAddressUtilityTitle: {
    fontWeight: '400',
  },
  profileAuraButton: {
    backgroundColor: 'rgba(248,255,253,0.92)',
    borderColor: 'rgba(45,211,193,0.38)',
    overflow: 'hidden',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
  },
  profileAvatarDot: {
    backgroundColor: '#30D27B',
    borderColor: '#FFFFFF',
    borderRadius: 5,
    borderWidth: 2,
    bottom: -1,
    height: 10,
    position: 'absolute',
    right: -1,
    width: 10,
  },
  profileAvatarGradientLayer: {
    borderRadius: 28,
    bottom: 0,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
  },
  profileAvatarLarge: {
    alignItems: 'center',
    backgroundColor: '#08AF9C',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 28,
    borderWidth: 2,
    height: 74,
    justifyContent: 'center',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.23,
    shadowRadius: 22,
    width: 74,
  },
  profileAvatarText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    position: 'relative',
    zIndex: 1,
  },
  profileDetailHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profileDetailTitle: {
    fontSize: 25,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 31,
    marginTop: 9,
  },
  profileHeroLarge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 140,
  },
  profileInsightIcon: {
    minHeight: 68,
    minWidth: 68,
  },
  profileKaelNote: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileListCard: {
    padding: 10,
  },
  profileListContent: {
    gap: 0,
  },
  profileListDivider: {
    height: 1,
    marginHorizontal: 14,
    opacity: 0.78,
  },
  profileMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  profileMintChip: {
    backgroundColor: 'rgba(224,252,245,0.88)',
    borderColor: 'rgba(85,214,195,0.42)',
    position: 'relative',
    zIndex: 1,
  },
  profileMintChipFrame: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  profileMoneyBody: {
    fontSize: 16,
    lineHeight: 23,
    maxWidth: 292,
    textAlign: 'center',
  },
  profileMoneyHero: {
    alignItems: 'center',
    gap: 12,
    minHeight: 318,
    justifyContent: 'center',
  },
  profileMoneyKicker: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'center',
  },
  profileNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileOverviewActionStack: {
    gap: 12,
    marginTop: 18,
  },
  profileOverviewUtilityConnector: {
    height: 1,
    width: 15,
  },
  profileOverviewUtilityConnectorDot: {
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    position: 'absolute',
    right: 0,
    top: 2,
    width: 10,
    zIndex: 2,
  },
  profileOverviewUtilityConnectorTrack: {
    alignItems: 'center',
    flexShrink: 0,
    height: 14,
    justifyContent: 'center',
    position: 'relative',
    width: 18,
  },
  profileOverviewUtilityCopy: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 40,
    minWidth: 0,
    paddingLeft: 10,
    paddingRight: 2,
    position: 'relative',
    zIndex: 1,
  },
  profileOverviewUtilityDetailLabel: {
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    minWidth: 0,
    textAlign: 'center',
  },
  profileOverviewUtilityDetailRail: {
    alignItems: 'center',
    borderTopWidth: 1,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 4,
    justifyContent: 'center',
    marginHorizontal: 10,
    marginTop: 8,
    minWidth: 0,
    paddingTop: 8,
    position: 'relative',
    zIndex: 1,
  },
  profileOverviewUtilityFormulaMintAura: {
    ...StyleSheet.absoluteFill,
    opacity: 0.94,
    zIndex: 0,
  },
  profileOverviewUtilityGrid: {
    flexWrap: 'nowrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  profileOverviewUtilityIcon: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    height: 40,
    minHeight: 40,
    minWidth: 40,
    width: 40,
  },
  profileOverviewUtilityIconFrame: {
    alignItems: 'center',
    height: 38,
    justifyContent: 'center',
    position: 'relative',
    width: 36,
  },
  profileOverviewUtilityTile: {
    alignItems: 'stretch',
    borderCurve: 'continuous',
    borderRadius: 22,
    flexBasis: 0,
    flexDirection: 'column',
    flexGrow: 1,
    flexShrink: 1,
    gap: 0,
    justifyContent: 'center',
    minHeight: 112,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 10,
  },
  profileOverviewUtilityPaymentTile: {
    flexGrow: 1.16,
  },
  profileOverviewUtilityTitle: {
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginLeft: 3,
    minWidth: 0,
    textAlign: 'left',
  },
  profileOverviewUtilityVisualPanel: {
    alignItems: 'center',
    flexShrink: 0,
    height: 40,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
    width: 36,
    zIndex: 1,
  },
  profileOverviewHeroCard: {
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 30,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 22, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 44,
  },
  profilePaymentForm: {
    gap: 12,
  },
  profileProgressFill: {
    backgroundColor: '#08AF9C',
    overflow: 'hidden',
    shadowColor: '#087D72',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
  },
  profileProgressSheen: {
    backgroundColor: 'rgba(255,255,255,0.70)',
    borderRadius: 999,
    bottom: -3,
    position: 'absolute',
    top: -3,
    width: 54,
  },
  profileProtectedJob: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileRankingEmptyChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(236,253,248,0.78)',
    borderColor: 'rgba(85,214,195,0.34)',
    minWidth: 82,
    position: 'relative',
    zIndex: 1,
  },
  profileRankingEmptyChipText: {
    color: '#0B8579',
    fontWeight: '700',
  },
  profileRankingEntryCard: {
    borderColor: 'rgba(74,218,197,0.48)',
    borderRadius: 28,
    gap: 0,
    padding: 0,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 38,
  },
  profileRankingEntryConnector: {
    height: 1,
    position: 'absolute',
    right: -24,
    top: '50%',
    width: 24,
    zIndex: 2,
  },
  profileRankingEntryConnectorDot: {
    borderRadius: 7,
    borderWidth: 1,
    height: 14,
    marginTop: -7,
    position: 'absolute',
    right: -7,
    top: '50%',
    width: 14,
    zIndex: 3,
  },
  profileRankingEntryContent: {
    alignItems: 'stretch',
    flexDirection: 'row',
    minHeight: 136,
  },
  profileRankingEntryCopy: {
    flex: 1,
    gap: 4,
    justifyContent: 'center',
    minWidth: 0,
    paddingBottom: 15,
    paddingLeft: 43,
    paddingRight: 18,
    paddingTop: 15,
  },
  profileRankingEntryIcon: {
    alignItems: 'center',
    height: 82,
    justifyContent: 'center',
    position: 'relative',
    width: 82,
  },
  profileRankingEntryIconImage: {
    height: 72,
    position: 'relative',
    width: 72,
    zIndex: 1,
  },
  profileRankingEntryProgress: {
    marginTop: 3,
  },
  profileRankingEntrySignal: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 5,
    minWidth: 0,
  },
  profileRankingEntrySignalRail: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 2,
  },
  profileRankingEntrySignalText: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    minWidth: 0,
  },
  profileRankingEntryStatusChipFrame: {
    flexShrink: 0,
    maxWidth: 104,
  },
  profileRankingEntrySubtitle: {
    fontSize: 12,
    lineHeight: 17,
  },
  profileRankingEntryTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  profileRankingEntryTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  profileRankingEntryVisualPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRightWidth: 1,
    flexShrink: 0,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
    width: 106,
    zIndex: 1,
  },
  profileRankingHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
    minHeight: 176,
  },
  profileRankingHeroCard: {
    borderColor: 'rgba(113,225,209,0.50)',
    borderRadius: 28,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 20, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 42,
  },
  profileRankingStatusChipFrame: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    marginBottom: 2,
    maxWidth: 190,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  rankNode: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minHeight: 62,
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 9,
    position: 'relative',
  },
  rankNodeActive: {
    shadowColor: '#087D72',
    shadowOffset: { height: 13, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 26,
  },
  rankNodeContent: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  rankNodeLabel: {
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    marginTop: 2,
    textAlign: 'center',
  },
  rankNodeValue: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 22,
  },
  rankNodeRest: {
    shadowColor: '#056459',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  rankRail: {
    flexDirection: 'row',
    gap: 7,
  },
  profileRankProcess: {
    borderRadius: 21,
    borderWidth: 1,
    marginTop: 10,
    minHeight: 58,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
  },
  profileRankProcessContent: {
    gap: 7,
    position: 'relative',
    zIndex: 1,
  },
  profileRankProcessLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileRankProcessValue: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    textAlign: 'right',
  },
  profileSettingsListContent: {
    gap: 8,
  },
  profileSettingsPasswordForm: {
    gap: 10,
    paddingHorizontal: 2,
    paddingTop: 6,
  },
  profileUtilityHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profileUtilityHeroIcon: {
    flexShrink: 0,
    minHeight: 86,
    minWidth: 86,
  },
  profileUtilityStack: {
    gap: 14,
    position: 'relative',
  },
})
