import { StyleSheet } from 'react-native'

export const customerV21ProfileUtilityStyles = StyleSheet.create({
  bodyText: {
    fontSize: 14,
    lineHeight: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 23,
  },
  flex: {
    flex: 1,
  },
  infoNoticeIcon: {
    flexShrink: 0,
  },
  pressed: {
    transform: [{ scale: 0.985 }],
  },
  profileInsightChip: {
    backgroundColor: 'rgba(224,252,245,0.88)',
    borderColor: 'rgba(85,214,195,0.40)',
    minWidth: 68,
    position: 'relative',
    zIndex: 1,
  },
  profileInsightEmptyChip: {
    backgroundColor: 'rgba(236,253,248,0.84)',
    borderColor: 'rgba(85,214,195,0.34)',
    minWidth: 68,
    position: 'relative',
    zIndex: 1,
  },
  profileInsightEmptyChipText: {
    color: '#0B8579',
    fontWeight: '700',
  },
  profileInsightChipFrame: {
    alignSelf: 'center',
    borderRadius: 999,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 14,
  },
  profileInsightTitle: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  profileInsightRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 86,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileMintChipText: {
    color: '#087D72',
    fontWeight: '700',
  },
  profileAuraCard: {
    gap: 0,
    overflow: 'hidden',
    position: 'relative',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 28,
  },
  profileAuraCardShadowDark: {
    shadowColor: '#000000',
  },
  profileAuraCardShadowLight: {
    shadowColor: '#087D72',
  },
  profileAuraContent: {
    position: 'relative',
    zIndex: 1,
  },
  profileSettingsActionIcon: {
    flexShrink: 0,
    minHeight: 68,
    minWidth: 68,
  },
  profileSettingsActionRow: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
  },
  profileRankingEvaluationCard: {
    borderColor: 'rgba(113,225,209,0.46)',
    borderRadius: 25,
    marginTop: 10,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 30,
  },
  profileRankingEvaluationChips: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 9,
  },
  profileRankingEvaluationContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileRankingEvidenceChip: {
    alignItems: 'center',
    borderColor: 'rgba(85,214,195,0.34)',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 7,
    position: 'relative',
  },
  profileRankingEvidenceLabel: {
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  profileRankingEvidenceValue: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 1,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  profileAddressAddButton: {
    minHeight: 44,
    minWidth: 86,
  },
  profileAddressAddRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  profileAddressBlock: {
    gap: 10,
  },
  profileAddressBlockHeader: {
    gap: 3,
  },
  profileAddressDefaultButton: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  profileAddressDefaultText: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileAddressDivider: {
    height: 1,
    opacity: 0.86,
  },
  profileAddressHint: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileAddressHub: {
    gap: 14,
  },
  profileAddressHubHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileAddressHubIcon: {
    flexShrink: 0,
    minHeight: 76,
    minWidth: 76,
  },
  profileAddressInput: {
    borderRadius: 18,
    borderWidth: 1,
    fontSize: 14,
    fontWeight: '600',
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  profileAddressMessage: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  profileAddressSaveDefaultButton: {
    borderRadius: 22,
  },
  profileAddressSaveDefaultButtonActive: {
    backgroundColor: '#12B8A4',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
  },
  profileAddressSavedIcon: {
    flexShrink: 0,
    minHeight: 62,
    minWidth: 62,
  },
  profileAddressSavedList: {
    gap: 10,
  },
  profileAddressSavedRow: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileAddressUtilityTitle: {
    fontWeight: '800',
  },
  profileAgenticCard: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
    minHeight: 92,
  },
  profileAgenticChevron: {
    fontSize: 26,
    fontWeight: '600',
    lineHeight: 28,
  },
  profileAgenticIcon: {
    minHeight: 82,
    minWidth: 82,
  },
  profileAuraButton: {
    backgroundColor: 'rgba(248,255,253,0.92)',
    borderColor: 'rgba(45,211,193,0.38)',
    overflow: 'hidden',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
  },
  profileAvatarDot: {
    backgroundColor: '#30D27B',
    borderColor: '#FFFFFF',
    borderRadius: 5,
    borderWidth: 2,
    bottom: -1,
    height: 10,
    position: 'absolute',
    right: -1,
    width: 10,
  },
  profileAvatarGradientLayer: {
    borderRadius: 28,
    bottom: 0,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
  },
  profileAvatarLarge: {
    alignItems: 'center',
    backgroundColor: '#08AF9C',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 28,
    borderWidth: 2,
    height: 74,
    justifyContent: 'center',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 9, width: 0 },
    shadowOpacity: 0.23,
    shadowRadius: 22,
    width: 74,
  },
  profileAvatarText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    position: 'relative',
    zIndex: 1,
  },
  profileDetailHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profileDetailTitle: {
    fontSize: 25,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 31,
    marginTop: 9,
  },
  profileHeroLarge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 132,
  },
  profileInsightIcon: {
    minHeight: 68,
    minWidth: 68,
  },
  profileKaelNote: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileListCard: {
    padding: 10,
  },
  profileListContent: {
    gap: 0,
  },
  profileListDivider: {
    height: 1,
    marginHorizontal: 14,
    opacity: 0.78,
  },
  profileMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  profileMintChip: {
    backgroundColor: 'rgba(224,252,245,0.88)',
    borderColor: 'rgba(85,214,195,0.42)',
    position: 'relative',
    zIndex: 1,
  },
  profileMintChipFrame: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  profileMoneyBody: {
    fontSize: 16,
    lineHeight: 23,
    maxWidth: 292,
    textAlign: 'center',
  },
  profileMoneyHero: {
    alignItems: 'center',
    gap: 12,
    minHeight: 318,
    justifyContent: 'center',
  },
  profileMoneyKicker: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'center',
  },
  profileNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileOverviewActionStack: {
    gap: 12,
    marginTop: 18,
  },
  profileOverviewAgenticCard: {
    borderColor: 'rgba(74,218,197,0.48)',
    borderRadius: 25,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 34,
  },
  profileOverviewHeroCard: {
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 30,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 22, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 44,
  },
  profilePaymentForm: {
    gap: 12,
  },
  profileProgressFill: {
    backgroundColor: '#08AF9C',
    overflow: 'hidden',
    shadowColor: '#087D72',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
  },
  profileProgressSheen: {
    backgroundColor: 'rgba(255,255,255,0.70)',
    borderRadius: 999,
    bottom: -3,
    position: 'absolute',
    top: -3,
    width: 54,
  },
  profileProtectedJob: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  profileRankingEmptyChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(236,253,248,0.78)',
    borderColor: 'rgba(85,214,195,0.34)',
    minWidth: 82,
    position: 'relative',
    zIndex: 1,
  },
  profileRankingEmptyChipText: {
    color: '#0B8579',
    fontWeight: '700',
  },
  profileRankingEntryCard: {
    borderColor: 'rgba(74,218,197,0.48)',
    borderRadius: 28,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 38,
  },
  profileRankingEntryChevron: {
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  profileRankingEntryContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 128,
  },
  profileRankingEntryIcon: {
    flexShrink: 0,
    minHeight: 82,
    minWidth: 82,
  },
  profileRankingEntryMeta: {
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  profileRankingEntryMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginTop: 6,
  },
  profileRankingEntryTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  profileRankingHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
    minHeight: 176,
  },
  profileRankingHeroCard: {
    borderColor: 'rgba(113,225,209,0.50)',
    borderRadius: 28,
    shadowColor: '#08AF9C',
    shadowOffset: { height: 20, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 42,
  },
  profileRankingStatusChipFrame: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    marginBottom: 2,
    maxWidth: 190,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#08AF9C',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  rankNode: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minHeight: 62,
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 9,
    position: 'relative',
  },
  rankNodeActive: {
    shadowColor: '#087D72',
    shadowOffset: { height: 13, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 26,
  },
  rankNodeContent: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  rankNodeLabel: {
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    marginTop: 2,
    textAlign: 'center',
  },
  rankNodeValue: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 22,
  },
  rankNodeRest: {
    shadowColor: '#056459',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
  },
  rankRail: {
    flexDirection: 'row',
    gap: 7,
  },
  profileRankProcess: {
    borderRadius: 21,
    borderWidth: 1,
    marginTop: 10,
    minHeight: 58,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    shadowColor: '#087D72',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
  },
  profileRankProcessContent: {
    gap: 7,
    position: 'relative',
    zIndex: 1,
  },
  profileRankProcessLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  profileRankProcessValue: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    textAlign: 'right',
  },
  profileSettingsListContent: {
    gap: 8,
  },
  profileSettingsPasswordForm: {
    gap: 10,
    paddingHorizontal: 2,
    paddingTop: 6,
  },
  profileUtilityHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  profileUtilityHeroIcon: {
    flexShrink: 0,
    minHeight: 86,
    minWidth: 86,
  },
  profileUtilityStack: {
    gap: 14,
    position: 'relative',
  },
})
