import { StyleSheet } from 'react-native'

export const customerV21SharedStyles = StyleSheet.create({
  card: {
    borderRadius: 26,
    borderWidth: 1,
    gap: 14,
    marginTop: 14,
    maxWidth: '100%',
    padding: 16,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.10,
    shadowRadius: 24,
    width: '100%',
  },
  cardShadowDark: {
    shadowColor: '#000000',
  },
  cardShadowLight: {
    shadowColor: '#6BAA9D',
  },
  safeArea: {
    flex: 1,
    maxWidth: '100%',
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  scrollContent: {
    paddingBottom: 128,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  frame: {
    alignItems: 'stretch',
    alignSelf: 'center',
    minWidth: 0,
  },
  bodyText: {
    fontSize: 14,
    lineHeight: 20,
  },
  centerText: {
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
  },
  emptyStateContent: {
    alignItems: 'center',
    gap: 12,
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  emptyTitle: {
    fontSize: 19,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'center',
  },
  homeEmptyState: {
    overflow: 'hidden',
    position: 'relative',
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 34,
  },
  homeEmptyStateShadowDark: {
    shadowColor: '#000000',
  },
  homeEmptyStateShadowLight: {
    shadowColor: '#05695E',
  },
  inactiveAgenticGate: {
    minHeight: 1,
  },
  assetTile: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 64,
    minWidth: 64,
  },
  topControlIcon: {
    flexShrink: 0,
  },
  topActionText: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 22,
  },
  topAvatarDot: {
    backgroundColor: '#30D27B',
    borderColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 2,
    bottom: -1,
    height: 16,
    position: 'absolute',
    right: -1,
    width: 16,
  },
  topAvatarImage: {
    height: 44,
    width: 44,
  },
  topAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  topAvatarWrap: {
    alignItems: 'center',
    backgroundColor: '#24B3A1',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 20,
    borderWidth: 2,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 58,
  },
  topControl: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  topCopy: {
    alignItems: 'flex-start',
    minWidth: 0,
  },
  topSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    textAlign: 'left',
  },
  topTitle: {
    fontSize: 27,
    fontWeight: '600',
    includeFontPadding: true,
    letterSpacing: 0,
    lineHeight: 34,
    minHeight: 36,
    textAlign: 'left',
  },
  eyebrowDot: {
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  eyebrowPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  eyebrowMotionWrap: {
    alignSelf: 'flex-start',
  },
  eyebrowPillText: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  eyebrowPillTextPreserve: {
    textTransform: 'none',
  },
  flex: {
    flex: 1,
    minWidth: 0,
  },
  infoNotice: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  infoNoticeBody: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  infoNoticeIcon: {
    minHeight: 58,
    minWidth: 58,
  },
  infoNoticeTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
  },
  matchingHandoffChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.71)',
    borderColor: 'rgba(204,235,229,0.82)',
    height: 28,
    minHeight: 28,
    paddingHorizontal: 10,
  },
  matchingHandoffChipSelected: {
    backgroundColor: 'rgba(224,252,245,0.88)',
    borderColor: 'rgba(85,214,195,0.36)',
  },
  matchingHandoffChipSelectedText: {
    color: '#088779',
  },
  matchingHandoffChipSuccess: {
    backgroundColor: '#EAF8EF',
    borderColor: '#BFE8CE',
  },
  matchingHandoffChipSuccessText: {
    color: '#1F9B5B',
  },
  matchingHandoffChipText: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  progressLine: {
    flex: 1,
    borderRadius: 2,
    height: 2,
  },
  progressNode: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    height: 23,
    justifyContent: 'center',
    width: 23,
  },
  progressNodeActive: {
    shadowColor: '#24B3A1',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 7,
  },
  progressNodeText: {
    fontSize: 9,
    fontWeight: '600',
    lineHeight: 12,
  },
  progressRail: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    marginTop: 2,
    position: 'relative',
    width: '100%',
    zIndex: 1,
  },
  cardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  heroChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  heroCopy: {
    alignItems: 'center',
    flex: 1,
    flexShrink: 1,
    gap: 8,
    justifyContent: 'center',
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  heroKael: {
    flexShrink: 0,
    height: 118,
    position: 'relative',
    width: 86,
    zIndex: 1,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 34,
  },
  homeAuraFrame: {
    marginTop: 2,
    position: 'relative',
  },
  homeAuraServiceTile: {
    borderRadius: 25,
    borderWidth: 1,
    elevation: 2,
    flexBasis: '30%',
    flexGrow: 1,
    gap: 4,
    maxWidth: '32%',
    minHeight: 120,
    overflow: 'hidden',
    paddingBottom: 11,
    paddingHorizontal: 8,
    paddingTop: 11,
    position: 'relative',
    shadowColor: '#088779',
    shadowOffset: { height: 14, width: 0 },
    shadowRadius: 28,
  },
  homeAuraServiceTileShadowDark: {
    shadowColor: '#000000',
    shadowOpacity: 0.16,
  },
  homeAuraServiceTileShadowLight: {
    shadowColor: '#088779',
    shadowOpacity: 0.13,
  },
  homeHero: {
    alignItems: 'center',
    borderRadius: 30,
    flexDirection: 'row',
    gap: 12,
    minHeight: 178,
    overflow: 'hidden',
    position: 'relative',
  },
  homeHeroTitle: {
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'center',
  },
  homeServiceGrid: {
    flexWrap: 'nowrap',
    gap: 9,
    justifyContent: 'space-between',
    marginTop: 8,
    position: 'relative',
  },
  homeServiceNote: {
    fontSize: 9.5,
    lineHeight: 13,
  },
  homeServiceTitle: {
    fontSize: 12,
    lineHeight: 16,
  },
  protectionBar: {
    borderRadius: 999,
    height: 8,
    marginTop: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  protectionBarFill: {
    borderRadius: 999,
    height: '100%',
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  screenRail: {
    gap: 8,
  },
  screenRailItem: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  screenRailTitle: {
    fontSize: 12,
    fontWeight: '700',
  },
  sectionActionButton: {
    alignItems: 'flex-end',
    maxWidth: 112,
    minWidth: 0,
    paddingHorizontal: 2,
    paddingVertical: 4,
    position: 'absolute',
    right: 0,
    top: -1,
    width: 112,
  },
  sectionActionHeader: {
    marginTop: 24,
    minHeight: 29,
    position: 'relative',
  },
  sectionActionHeaderWithAction: {
    paddingRight: 116,
  },
  sectionActionText: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'right',
  },
  sectionActionTitle: {
    minWidth: 0,
    width: '100%',
  },
  sectionHeader: {
    gap: 4,
    marginTop: 22,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 25,
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'flex-start',
    marginTop: 12,
  },
  serviceIcon: {
    minHeight: 82,
    minWidth: 82,
  },
  serviceNote: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    textAlign: 'center',
  },
  serviceTile: {
    alignItems: 'center',
    borderRadius: 26,
    borderWidth: 1,
    flexBasis: '40%',
    flexGrow: 0,
    gap: 8,
    maxWidth: '40%',
    minHeight: 168,
    minWidth: 0,
    padding: 12,
  },
  serviceTitle: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 19,
    textAlign: 'center',
  },
  sourceIconAuraFrame: {
    alignItems: 'center',
    height: 82,
    justifyContent: 'center',
    position: 'relative',
    width: 82,
  },
  sourceIconTile: {
    borderRadius: 22,
    borderWidth: 1,
    elevation: 1,
    height: 64,
    overflow: 'hidden',
    shadowColor: '#056055',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 26,
    width: 64,
  },
  utilityLabel: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 17,
    textAlign: 'center',
  },
})
