export { CustomerHomeSurface } from './surfaces/home'
export { CustomerBookingEntrySurface, CustomerKaelSurface } from './surfaces/booking'
export { CustomerHistorySurface } from './surfaces/history'
export { CustomerProfileSurface } from './surfaces/profile'
export { CustomerV4DockOverlay } from './surfaces/shell'
export type { CustomerDockActive } from './surfaces/shell'
