import { StyleSheet } from 'react-native'

import { entryTheme } from './theme'

export const entryBrandAccessFlowStyles = StyleSheet.create({
  benefitCard: { alignItems: 'center', borderRadius: 23, flex: 1, minHeight: 101, paddingHorizontal: 7, paddingVertical: 10 },
  benefitIcon: { height: 47, marginBottom: 4, width: 47 },
  benefitLabel: { ...entryTheme.typography.caption2, color: entryTheme.color.text.strong, fontWeight: '600', textAlign: 'center' },
  benefitMeta: { ...entryTheme.typography.caption2, color: entryTheme.color.text.muted, marginTop: 2, textAlign: 'center' },
  benefitRow: { flexDirection: 'row', gap: 9, marginBottom: 16, marginTop: 48 },
  centeredScreen: { alignItems: 'center' },
  divider: { alignItems: 'center', flexDirection: 'row', gap: 11, marginHorizontal: 2, marginVertical: 12 },
  dividerLine: { backgroundColor: entryTheme.color.surface.stroke, flex: 1, height: 1 },
  dividerText: { ...entryTheme.typography.caption2, color: entryTheme.color.text.muted },
  error: { ...entryTheme.typography.caption1, color: entryTheme.color.accent.destructive, marginBottom: 10, marginTop: -2 },
  formHead: { paddingBottom: 12, paddingHorizontal: 3, paddingTop: 6 },
  formHeadRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  formPanel: { borderRadius: entryTheme.radius.sheet, paddingBottom: 15, paddingHorizontal: 15, paddingTop: 17 },
  formScroll: { flexGrow: 1, paddingBottom: 18, paddingHorizontal: entryTheme.spacing.screenX },
  formSwitch: { ...entryTheme.typography.caption1, color: entryTheme.color.text.secondary, marginTop: 14, textAlign: 'center' },
  formSwitchLink: { ...entryTheme.typography.caption1, color: entryTheme.color.mint.mint700, fontWeight: '600' },
  formTitle: { ...entryTheme.typography.largeTitle, color: entryTheme.color.text.strong },
  formUtils: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 9, marginHorizontal: 2, marginTop: -2, minHeight: 28 },
  h1: { ...entryTheme.typography.h1, color: entryTheme.color.text.strong },
  keyboard: { flex: 1 },
  lead: { ...entryTheme.typography.body, color: entryTheme.color.text.secondary },
  link: { ...entryTheme.typography.footnote, color: entryTheme.color.mint.mint700, fontWeight: '600' },
  onboardingBottom: { marginTop: 'auto' },
  onboardingHead: { alignItems: 'center', paddingHorizontal: 8, paddingTop: 18 },
  onboardingLead: { marginTop: 7, textAlign: 'center' },
  onboardingTitle: { marginTop: 11, textAlign: 'center' },
  pager: { alignItems: 'center', flexDirection: 'row', gap: 6, height: 25, justifyContent: 'center', marginTop: 8 },
  pagerActive: { backgroundColor: entryTheme.color.mint.mint600, borderRadius: 999, height: 5, width: 18 },
  pagerDot: { backgroundColor: '#BDD8D3', borderRadius: 999, height: 5, width: 5 },
  providerStack: { alignItems: 'stretch', flexDirection: 'row', gap: 10 },
  root: { backgroundColor: entryTheme.color.surface.base, flex: 1 },
  safe: { flex: 1 },
  screen: { flex: 1, paddingBottom: 18, paddingHorizontal: entryTheme.spacing.screenX, paddingTop: 8 },
  splashCenter: { alignItems: 'center', flex: 1, justifyContent: 'center', paddingBottom: 48 },
  termsRow: { marginBottom: 12, marginHorizontal: 2, marginTop: 2 },
  topbar: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: -3, marginBottom: 6, minHeight: 54 },
  topbarSpacer: { width: 54 },
  topbarTitle: { ...entryTheme.typography.subheadline, color: entryTheme.color.text.primary, fontWeight: '600' },
})
