create sequence if not exists public.job_display_code_seq
  as bigint
  increment by 1
  minvalue 1
  start with 1
  cache 1;

create or replace function public.next_job_display_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_seq bigint;
  v_year text := to_char((now() at time zone 'utc'), 'YY');
begin
  v_seq := nextval('public.job_display_code_seq');
  return '#MOH-' || v_year || lpad(v_seq::text, 4, '0');
end;
$$;

revoke all on function public.next_job_display_code() from public, anon;
grant execute on function public.next_job_display_code() to authenticated, service_role;

alter table public.jobs
  add column if not exists display_code text;

alter table public.jobs
  alter column display_code set default public.next_job_display_code();

with ordered_jobs as (
  select
    id,
    row_number() over (order by created_at, id) as rn
  from public.jobs
  where display_code is null
)
update public.jobs as jobs
set display_code =
  '#MOH-' ||
  to_char((jobs.created_at at time zone 'utc'), 'YY') ||
  lpad(ordered_jobs.rn::text, 4, '0')
from ordered_jobs
where jobs.id = ordered_jobs.id;

select setval(
  'public.job_display_code_seq',
  greatest((select count(*) from public.jobs), 1),
  (select count(*) from public.jobs) > 0
);

alter table public.jobs
  alter column display_code set not null;

create unique index if not exists jobs_display_code_key
  on public.jobs (display_code);

comment on column public.jobs.display_code is
  'Stable customer-visible service code generated by Supabase for Kael-led jobs.';
