-- SePay + VietQR payment gate for post-completion customer payments.
-- Payment completion is provider-confirmed only; mobile UI must not mark jobs paid.

alter table public.jobs
  add column if not exists payment_provider text,
  add column if not exists payment_status text not null default 'not_started',
  add column if not exists payment_code text,
  add column if not exists payment_transfer_content text,
  add column if not exists payment_qr_image_url text,
  add column if not exists payment_expires_at timestamptz,
  add column if not exists payment_received_at timestamptz,
  add column if not exists payment_amount_received integer,
  add column if not exists gross_amount integer,
  add column if not exists platform_fee integer,
  add column if not exists worker_net integer,
  add column if not exists sepay_transaction_id text,
  add column if not exists sepay_reference_code text,
  add column if not exists payment_failure_reason text,
  add column if not exists payment_updated_at timestamptz;

alter table public.jobs
  drop constraint if exists jobs_payment_status_check;

alter table public.jobs
  add constraint jobs_payment_status_check
  check (
    payment_status in (
      'not_started',
      'code_requested',
      'vietqr_ready',
      'pending',
      'received',
      'amount_mismatch',
      'expired',
      'failed',
      'reconciled'
    )
  );

create unique index if not exists jobs_payment_code_uidx
  on public.jobs (payment_code)
  where payment_code is not null;

create unique index if not exists jobs_sepay_transaction_uidx
  on public.jobs (sepay_transaction_id)
  where sepay_transaction_id is not null;

create index if not exists jobs_payment_status_idx
  on public.jobs (payment_status);

create index if not exists jobs_payment_expires_at_idx
  on public.jobs (payment_expires_at)
  where payment_expires_at is not null;

comment on column public.jobs.payment_provider is
  'Server-side payment provider selected for the job. Initial production path: sepay_vietqr.';
comment on column public.jobs.payment_status is
  'Explicit payment state. paid job status is only reached after trusted provider confirmation.';
comment on column public.jobs.payment_qr_image_url is
  'VietQR image URL generated by Edge. Treat as sensitive because QR parameters can reveal transfer target.';
comment on column public.jobs.sepay_transaction_id is
  'SePay webhook transaction id used for idempotency.';
