// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type AdminTables = {
/* @slice:begin tables:admin */
      admin_finance_mutation_receipts: {
        Row: {
          actor_id: string
          client_request_id: string
          created_at: string
          id: string
          operation: string
          response: Json
          subject_id: string
        }
        Insert: {
          actor_id: string
          client_request_id: string
          created_at?: string
          id?: string
          operation: string
          response: Json
          subject_id: string
        }
        Update: {
          actor_id?: string
          client_request_id?: string
          created_at?: string
          id?: string
          operation?: string
          response?: Json
          subject_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_finance_mutation_receipts_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_finance_tax_policies: {
        Row: {
          approval_evidence_ref: string | null
          approved_at: string | null
          approved_by: string | null
          created_at: string
          created_by: string
          effective_from: string
          effective_to: string | null
          id: string
          name: string
          policy_key: string
          retired_at: string | null
          retired_by: string | null
          source_reference: string | null
          status: string
          subject_type: string
          updated_at: string
          version: number
        }
        Insert: {
          approval_evidence_ref?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string
          created_by: string
          effective_from: string
          effective_to?: string | null
          id?: string
          name: string
          policy_key: string
          retired_at?: string | null
          retired_by?: string | null
          source_reference?: string | null
          status?: string
          subject_type: string
          updated_at?: string
          version: number
        }
        Update: {
          approval_evidence_ref?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string
          created_by?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          name?: string
          policy_key?: string
          retired_at?: string | null
          retired_by?: string | null
          source_reference?: string | null
          status?: string
          subject_type?: string
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "admin_finance_tax_policies_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_finance_tax_policies_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_finance_tax_policies_retired_by_fkey"
            columns: ["retired_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_finance_tax_rules: {
        Row: {
          calculation_basis: string
          created_at: string
          id: string
          label: string
          policy_id: string
          rate_bps: number
          service_type: Database["public"]["Enums"]["service_type"] | null
          tax_code: string
        }
        Insert: {
          calculation_basis: string
          created_at?: string
          id?: string
          label: string
          policy_id: string
          rate_bps: number
          service_type?: Database["public"]["Enums"]["service_type"] | null
          tax_code: string
        }
        Update: {
          calculation_basis?: string
          created_at?: string
          id?: string
          label?: string
          policy_id?: string
          rate_bps?: number
          service_type?: Database["public"]["Enums"]["service_type"] | null
          tax_code?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_finance_tax_rules_policy_id_fkey"
            columns: ["policy_id"]
            isOneToOne: false
            referencedRelation: "admin_finance_tax_policies"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_financial_adjustments: {
        Row: {
          adjustment_type: string
          cash_outflow_vnd: number
          commission_reversal_vnd: number
          created_at: string
          dispute_id: string | null
          gross_refund_vnd: number
          id: string
          job_id: string
          payment_order_id: string | null
          realization_status: string
          realized_at: string
          reason_code: string
          recorded_by: string
          safe_metadata: Json
          source_key: string
          worker_credit_vnd: number
          worker_id: string | null
        }
        Insert: {
          adjustment_type: string
          cash_outflow_vnd?: number
          commission_reversal_vnd?: number
          created_at?: string
          dispute_id?: string | null
          gross_refund_vnd?: number
          id?: string
          job_id: string
          payment_order_id?: string | null
          realization_status?: string
          realized_at: string
          reason_code: string
          recorded_by: string
          safe_metadata?: Json
          source_key: string
          worker_credit_vnd?: number
          worker_id?: string | null
        }
        Update: {
          adjustment_type?: string
          cash_outflow_vnd?: number
          commission_reversal_vnd?: number
          created_at?: string
          dispute_id?: string | null
          gross_refund_vnd?: number
          id?: string
          job_id?: string
          payment_order_id?: string | null
          realization_status?: string
          realized_at?: string
          reason_code?: string
          recorded_by?: string
          safe_metadata?: Json
          source_key?: string
          worker_credit_vnd?: number
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "admin_financial_adjustments_dispute_id_fkey"
            columns: ["dispute_id"]
            isOneToOne: false
            referencedRelation: "disputes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_financial_adjustments_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_financial_adjustments_payment_order_id_fkey"
            columns: ["payment_order_id"]
            isOneToOne: false
            referencedRelation: "job_payment_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_financial_adjustments_recorded_by_fkey"
            columns: ["recorded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_financial_adjustments_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "admin_financial_adjustments_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_manager_nominations: {
        Row: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          cancelled_at: string | null
          granted_at: string | null
          id: string
          nominated_at: string
          nominated_by: string
          status: string
          target_user_id: string
          updated_at: string
        }
        Insert: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          cancelled_at?: string | null
          granted_at?: string | null
          id?: string
          nominated_at?: string
          nominated_by: string
          status?: string
          target_user_id: string
          updated_at?: string
        }
        Update: {
          baseline_role?: Database["public"]["Enums"]["user_role"]
          cancelled_at?: string | null
          granted_at?: string | null
          id?: string
          nominated_at?: string
          nominated_by?: string
          status?: string
          target_user_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_manager_nominations_nominated_by_fkey"
            columns: ["nominated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_manager_nominations_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_operator_accounts: {
        Row: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          capabilities: string[]
          granted_at: string
          granted_by: string
          last_changed_by: string
          revoked_at: string | null
          status: string
          updated_at: string
          user_id: string
          version: number
        }
        Insert: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          capabilities?: string[]
          granted_at?: string
          granted_by: string
          last_changed_by: string
          revoked_at?: string | null
          status?: string
          updated_at?: string
          user_id: string
          version?: number
        }
        Update: {
          baseline_role?: Database["public"]["Enums"]["user_role"]
          capabilities?: string[]
          granted_at?: string
          granted_by?: string
          last_changed_by?: string
          revoked_at?: string | null
          status?: string
          updated_at?: string
          user_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "admin_operator_accounts_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_operator_accounts_last_changed_by_fkey"
            columns: ["last_changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_operator_accounts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_operator_provisioning: {
        Row: {
          activated_at: string | null
          capabilities: string[]
          created_at: string
          created_by: string
          email: string
          failure_code: string | null
          full_name: string
          id: string
          status: string
          updated_at: string
          user_id: string | null
        }
        Insert: {
          activated_at?: string | null
          capabilities: string[]
          created_at?: string
          created_by: string
          email: string
          failure_code?: string | null
          full_name: string
          id?: string
          status: string
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          activated_at?: string | null
          capabilities?: string[]
          created_at?: string
          created_by?: string
          email?: string
          failure_code?: string | null
          full_name?: string
          id?: string
          status?: string
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "admin_operator_provisioning_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_operator_provisioning_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_support_case_notes: {
        Row: {
          body: string
          created_at: string
          created_by: string
          id: string
          idempotency_key: string
          source_id: string
          source_kind: string
        }
        Insert: {
          body: string
          created_at?: string
          created_by: string
          id?: string
          idempotency_key: string
          source_id: string
          source_kind: string
        }
        Update: {
          body?: string
          created_at?: string
          created_by?: string
          id?: string
          idempotency_key?: string
          source_id?: string
          source_kind?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_support_case_notes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_support_case_preparations: {
        Row: {
          assigned_to: string | null
          checklist: Json
          created_at: string
          last_idempotency_key: string | null
          source_id: string
          source_kind: string
          status: string
          updated_at: string
          updated_by: string
          version: number
        }
        Insert: {
          assigned_to?: string | null
          checklist?: Json
          created_at?: string
          last_idempotency_key?: string | null
          source_id: string
          source_kind: string
          status?: string
          updated_at?: string
          updated_by: string
          version?: number
        }
        Update: {
          assigned_to?: string | null
          checklist?: Json
          created_at?: string
          last_idempotency_key?: string | null
          source_id?: string
          source_kind?: string
          status?: string
          updated_at?: string
          updated_by?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "admin_support_case_preparations_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_support_case_preparations_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_team_mutation_receipts: {
        Row: {
          actor_id: string
          client_request_id: string
          created_at: string
          id: string
          operation: string
          request: Json
          response: Json
          subject_id: string
        }
        Insert: {
          actor_id: string
          client_request_id: string
          created_at?: string
          id?: string
          operation: string
          request: Json
          response: Json
          subject_id: string
        }
        Update: {
          actor_id?: string
          client_request_id?: string
          created_at?: string
          id?: string
          operation?: string
          request?: Json
          response?: Json
          subject_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_team_mutation_receipts_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_team_mutation_receipts_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_worker_application_reviews: {
        Row: {
          decided_at: string
          decided_by: string
          decision: string
          queue_id: string
          reason: string | null
          review_stage: string
          worker_id: string
        }
        Insert: {
          decided_at?: string
          decided_by: string
          decision: string
          queue_id: string
          reason?: string | null
          review_stage?: string
          worker_id: string
        }
        Update: {
          decided_at?: string
          decided_by?: string
          decision?: string
          queue_id?: string
          reason?: string | null
          review_stage?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_worker_application_reviews_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_worker_application_reviews_queue_id_fkey"
            columns: ["queue_id"]
            isOneToOne: true
            referencedRelation: "kael_admin_queue"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_worker_application_reviews_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:admin */
}
