// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Database } from '../schema.database.types'

export type AdminTables = {
/* @slice:begin tables:admin */
      admin_manager_nominations: {
        Row: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          cancelled_at: string | null
          granted_at: string | null
          id: string
          nominated_at: string
          nominated_by: string
          status: string
          target_user_id: string
          updated_at: string
        }
        Insert: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          cancelled_at?: string | null
          granted_at?: string | null
          id?: string
          nominated_at?: string
          nominated_by: string
          status?: string
          target_user_id: string
          updated_at?: string
        }
        Update: {
          baseline_role?: Database["public"]["Enums"]["user_role"]
          cancelled_at?: string | null
          granted_at?: string | null
          id?: string
          nominated_at?: string
          nominated_by?: string
          status?: string
          target_user_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_manager_nominations_nominated_by_fkey"
            columns: ["nominated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_manager_nominations_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_operator_accounts: {
        Row: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          capabilities: string[]
          granted_at: string
          granted_by: string
          last_changed_by: string
          revoked_at: string | null
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          baseline_role: Database["public"]["Enums"]["user_role"]
          capabilities?: string[]
          granted_at?: string
          granted_by: string
          last_changed_by: string
          revoked_at?: string | null
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          baseline_role?: Database["public"]["Enums"]["user_role"]
          capabilities?: string[]
          granted_at?: string
          granted_by?: string
          last_changed_by?: string
          revoked_at?: string | null
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_operator_accounts_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_operator_accounts_last_changed_by_fkey"
            columns: ["last_changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_operator_accounts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_worker_application_reviews: {
        Row: {
          decided_at: string
          decided_by: string
          decision: string
          queue_id: string
          reason: string | null
          worker_id: string
        }
        Insert: {
          decided_at?: string
          decided_by: string
          decision: string
          queue_id: string
          reason?: string | null
          worker_id: string
        }
        Update: {
          decided_at?: string
          decided_by?: string
          decision?: string
          queue_id?: string
          reason?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_worker_application_reviews_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_worker_application_reviews_queue_id_fkey"
            columns: ["queue_id"]
            isOneToOne: true
            referencedRelation: "kael_admin_queue"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_worker_application_reviews_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:admin */
}
