// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type CoreTables = {
/* @slice:begin tables:core */
      ai_provider_routing: {
        Row: {
          cost_ceiling_usd: number
          created_at: string
          daily_provider_cap_usd: number
          fallback_model: string | null
          fallback_provider: Database["public"]["Enums"]["api_provider"] | null
          is_enabled: boolean
          latency_budget_ms: number
          primary_model: string
          primary_provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          safe_metadata: Json
          updated_at: string
          user_visible: boolean
        }
        Insert: {
          cost_ceiling_usd: number
          created_at?: string
          daily_provider_cap_usd?: number
          fallback_model?: string | null
          fallback_provider?: Database["public"]["Enums"]["api_provider"] | null
          is_enabled?: boolean
          latency_budget_ms: number
          primary_model: string
          primary_provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          safe_metadata?: Json
          updated_at?: string
          user_visible?: boolean
        }
        Update: {
          cost_ceiling_usd?: number
          created_at?: string
          daily_provider_cap_usd?: number
          fallback_model?: string | null
          fallback_provider?: Database["public"]["Enums"]["api_provider"] | null
          is_enabled?: boolean
          latency_budget_ms?: number
          primary_model?: string
          primary_provider?: Database["public"]["Enums"]["api_provider"]
          purpose?: string
          safe_metadata?: Json
          updated_at?: string
          user_visible?: boolean
        }
        Relationships: []
      }
      api_logs: {
        Row: {
          cost_usd: number | null
          created_at: string
          error_code: string | null
          fallback_used: boolean
          id: string
          input_tokens: number | null
          job_id: string | null
          latency_ms: number | null
          model: string | null
          output_tokens: number | null
          prompt_version: string | null
          provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          request_id: string | null
          safe_metadata: Json
          success: boolean
          synthetic_cohort_id: string | null
        }
        Insert: {
          cost_usd?: number | null
          created_at?: string
          error_code?: string | null
          fallback_used?: boolean
          id?: string
          input_tokens?: number | null
          job_id?: string | null
          latency_ms?: number | null
          model?: string | null
          output_tokens?: number | null
          prompt_version?: string | null
          provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          request_id?: string | null
          safe_metadata?: Json
          success: boolean
          synthetic_cohort_id?: string | null
        }
        Update: {
          cost_usd?: number | null
          created_at?: string
          error_code?: string | null
          fallback_used?: boolean
          id?: string
          input_tokens?: number | null
          job_id?: string | null
          latency_ms?: number | null
          model?: string | null
          output_tokens?: number | null
          prompt_version?: string | null
          provider?: Database["public"]["Enums"]["api_provider"]
          purpose?: string
          request_id?: string | null
          safe_metadata?: Json
          success?: boolean
          synthetic_cohort_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "api_logs_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "api_logs_synthetic_cohort_id_fkey"
            columns: ["synthetic_cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
        ]
      }
      chat_messages: {
        Row: {
          content: string
          created_at: string
          id: string
          is_read: boolean
          job_id: string
          sender_id: string | null
          sender_role: Database["public"]["Enums"]["message_sender"]
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          is_read?: boolean
          job_id: string
          sender_id?: string | null
          sender_role: Database["public"]["Enums"]["message_sender"]
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          is_read?: boolean
          job_id?: string
          sender_id?: string | null
          sender_role?: Database["public"]["Enums"]["message_sender"]
        }
        Relationships: [
          {
            foreignKeyName: "chat_messages_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      device_push_tokens: {
        Row: {
          created_at: string
          enabled: boolean
          id: string
          last_seen_at: string
          permission_status: string
          platform: string
          push_token: string
          safe_metadata: Json
          token_hash: string
          token_last4: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          enabled?: boolean
          id?: string
          last_seen_at?: string
          permission_status: string
          platform: string
          push_token: string
          safe_metadata?: Json
          token_hash: string
          token_last4: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          enabled?: boolean
          id?: string
          last_seen_at?: string
          permission_status?: string
          platform?: string
          push_token?: string
          safe_metadata?: Json
          token_hash?: string
          token_last4?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "device_push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      disputes: {
        Row: {
          abuse_signals: string[]
          admin_decision: Json | null
          admin_decision_at: string | null
          admin_decision_by: string | null
          admin_review: Json
          counter_party_id: string | null
          counter_party_response_deadline: string
          counter_party_statement: string | null
          created_at: string
          dispute_type: string
          evidence_locked_at: string
          evidence_snapshot_id: string
          id: string
          initiated_by: string
          initiated_by_id: string
          initiator_statement: string
          job_id: string
          kael_neutral_summary: string
          resolved_at: string | null
          status: string
          synthetic_cohort_id: string | null
          updated_at: string
        }
        Insert: {
          abuse_signals?: string[]
          admin_decision?: Json | null
          admin_decision_at?: string | null
          admin_decision_by?: string | null
          admin_review?: Json
          counter_party_id?: string | null
          counter_party_response_deadline: string
          counter_party_statement?: string | null
          created_at?: string
          dispute_type: string
          evidence_locked_at: string
          evidence_snapshot_id: string
          id?: string
          initiated_by: string
          initiated_by_id: string
          initiator_statement: string
          job_id: string
          kael_neutral_summary: string
          resolved_at?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
        }
        Update: {
          abuse_signals?: string[]
          admin_decision?: Json | null
          admin_decision_at?: string | null
          admin_decision_by?: string | null
          admin_review?: Json
          counter_party_id?: string | null
          counter_party_response_deadline?: string
          counter_party_statement?: string | null
          created_at?: string
          dispute_type?: string
          evidence_locked_at?: string
          evidence_snapshot_id?: string
          id?: string
          initiated_by?: string
          initiated_by_id?: string
          initiator_statement?: string
          job_id?: string
          kael_neutral_summary?: string
          resolved_at?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "disputes_admin_decision_by_fkey"
            columns: ["admin_decision_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_counter_party_id_fkey"
            columns: ["counter_party_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_evidence_snapshot_id_fkey"
            columns: ["evidence_snapshot_id"]
            isOneToOne: false
            referencedRelation: "evidence_snapshots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_initiated_by_id_fkey"
            columns: ["initiated_by_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_synthetic_cohort_id_fkey"
            columns: ["synthetic_cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
        ]
      }
      evidence_snapshots: {
        Row: {
          created_at: string
          evidence_locked_at: string
          evidence_snapshot: Json
          id: string
          job_id: string
        }
        Insert: {
          created_at?: string
          evidence_locked_at?: string
          evidence_snapshot?: Json
          id?: string
          job_id: string
        }
        Update: {
          created_at?: string
          evidence_locked_at?: string
          evidence_snapshot?: Json
          id?: string
          job_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_snapshots_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      legal_awareness_patterns: {
        Row: {
          boundary_type: string
          created_at: string
          embedding: string | null
          embedding_model: string | null
          embedding_text: string | null
          embedding_updated_at: string | null
          id: string
          is_enabled: boolean
          pattern_key: string
          response_guidance: string
          safe_metadata: Json
          topic: string
          updated_at: string
        }
        Insert: {
          boundary_type: string
          created_at?: string
          embedding?: string | null
          embedding_model?: string | null
          embedding_text?: string | null
          embedding_updated_at?: string | null
          id?: string
          is_enabled?: boolean
          pattern_key: string
          response_guidance: string
          safe_metadata?: Json
          topic: string
          updated_at?: string
        }
        Update: {
          boundary_type?: string
          created_at?: string
          embedding?: string | null
          embedding_model?: string | null
          embedding_text?: string | null
          embedding_updated_at?: string | null
          id?: string
          is_enabled?: boolean
          pattern_key?: string
          response_guidance?: string
          safe_metadata?: Json
          topic?: string
          updated_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string
          channel: string
          created_at: string
          event_type: string
          id: string
          job_id: string | null
          push_attempt_count: number
          push_expires_at: string | null
          push_last_error_code: string | null
          push_lease_expires_at: string | null
          push_lease_token: string | null
          push_leased_by: string | null
          push_next_attempt_at: string | null
          push_state: string
          push_submitted_at: string | null
          push_submitted_count: number
          read_at: string | null
          safe_metadata: Json
          sent_at: string | null
          status: Database["public"]["Enums"]["notification_status"]
          title: string
          user_id: string
        }
        Insert: {
          body: string
          channel?: string
          created_at?: string
          event_type: string
          id?: string
          job_id?: string | null
          push_attempt_count?: number
          push_expires_at?: string | null
          push_last_error_code?: string | null
          push_lease_expires_at?: string | null
          push_lease_token?: string | null
          push_leased_by?: string | null
          push_next_attempt_at?: string | null
          push_state?: string
          push_submitted_at?: string | null
          push_submitted_count?: number
          read_at?: string | null
          safe_metadata?: Json
          sent_at?: string | null
          status?: Database["public"]["Enums"]["notification_status"]
          title: string
          user_id: string
        }
        Update: {
          body?: string
          channel?: string
          created_at?: string
          event_type?: string
          id?: string
          job_id?: string | null
          push_attempt_count?: number
          push_expires_at?: string | null
          push_last_error_code?: string | null
          push_lease_expires_at?: string | null
          push_lease_token?: string | null
          push_leased_by?: string | null
          push_next_attempt_at?: string | null
          push_state?: string
          push_submitted_at?: string | null
          push_submitted_count?: number
          read_at?: string | null
          safe_metadata?: Json
          sent_at?: string | null
          status?: Database["public"]["Enums"]["notification_status"]
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_bank_balance_snapshots: {
        Row: {
          account_key: string
          balance_vnd: number
          client_request_id: string | null
          created_at: string
          entered_by: string
          id: string
          observed_at: string
        }
        Insert: {
          account_key: string
          balance_vnd: number
          client_request_id?: string | null
          created_at?: string
          entered_by: string
          id?: string
          observed_at: string
        }
        Update: {
          account_key?: string
          balance_vnd?: number
          client_request_id?: string | null
          created_at?: string
          entered_by?: string
          id?: string
          observed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "platform_bank_balance_snapshots_entered_by_fkey"
            columns: ["entered_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      price_baselines: {
        Row: {
          complexity: Database["public"]["Enums"]["complexity_level"]
          created_at: string
          created_by: string | null
          district_code: string
          effective_from: string | null
          id: string
          lifecycle: string
          price_evidence: Json
          price_max: number
          price_min: number
          retired_at: string | null
          service_problem_id: string
          service_type: Database["public"]["Enums"]["service_type"]
          source: string
          supersedes_id: string | null
          updated_at: string
          version: number
        }
        Insert: {
          complexity: Database["public"]["Enums"]["complexity_level"]
          created_at?: string
          created_by?: string | null
          district_code?: string
          effective_from?: string | null
          id?: string
          lifecycle?: string
          price_evidence?: Json
          price_max: number
          price_min: number
          retired_at?: string | null
          service_problem_id: string
          service_type: Database["public"]["Enums"]["service_type"]
          source?: string
          supersedes_id?: string | null
          updated_at?: string
          version?: number
        }
        Update: {
          complexity?: Database["public"]["Enums"]["complexity_level"]
          created_at?: string
          created_by?: string | null
          district_code?: string
          effective_from?: string | null
          id?: string
          lifecycle?: string
          price_evidence?: Json
          price_max?: number
          price_min?: number
          retired_at?: string | null
          service_problem_id?: string
          service_type?: Database["public"]["Enums"]["service_type"]
          source?: string
          supersedes_id?: string | null
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "price_baselines_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "price_baselines_service_problem_id_fkey"
            columns: ["service_problem_id"]
            isOneToOne: false
            referencedRelation: "service_problems"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "price_baselines_supersedes_id_fkey"
            columns: ["supersedes_id"]
            isOneToOne: false
            referencedRelation: "price_baselines"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          account_state: string
          avatar_url: string | null
          created_at: string
          deleted_at: string | null
          deletion_requested_at: string | null
          full_name: string | null
          id: string
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          account_state?: string
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          deletion_requested_at?: string | null
          full_name?: string | null
          id: string
          phone?: string | null
          role: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          account_state?: string
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          deletion_requested_at?: string | null
          full_name?: string | null
          id?: string
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          comment: string | null
          created_at: string
          customer_id: string
          id: string
          job_id: string
          rating: number
          tags: string[]
          worker_id: string
        }
        Insert: {
          comment?: string | null
          created_at?: string
          customer_id: string
          id?: string
          job_id: string
          rating: number
          tags?: string[]
          worker_id: string
        }
        Update: {
          comment?: string | null
          created_at?: string
          customer_id?: string
          id?: string
          job_id?: string
          rating?: number
          tags?: string[]
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      scope_change_request_commands: {
        Row: {
          claim_id: string | null
          claimed_at: string | null
          client_request_id: string
          created_at: string
          evidence_photo_urls: string[]
          job_id: string
          last_error_code: string | null
          new_description: string
          reason: string
          request_state: string
          response_payload: Json | null
          scope_change_id: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          claim_id?: string | null
          claimed_at?: string | null
          client_request_id: string
          created_at?: string
          evidence_photo_urls?: string[]
          job_id: string
          last_error_code?: string | null
          new_description: string
          reason: string
          request_state?: string
          response_payload?: Json | null
          scope_change_id?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          claim_id?: string | null
          claimed_at?: string | null
          client_request_id?: string
          created_at?: string
          evidence_photo_urls?: string[]
          job_id?: string
          last_error_code?: string | null
          new_description?: string
          reason?: string
          request_state?: string
          response_payload?: Json | null
          scope_change_id?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scope_change_request_commands_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scope_change_request_commands_scope_change_id_fkey"
            columns: ["scope_change_id"]
            isOneToOne: true
            referencedRelation: "scope_change_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scope_change_request_commands_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      scope_change_request_effects: {
        Row: {
          attempt_count: number
          claim_id: string | null
          claimed_at: string | null
          client_request_id: string
          completed_at: string | null
          created_at: string
          effect_id: string
          effect_name: string
          effect_state: string
          job_id: string
          last_error_code: string | null
          payload: Json
          scope_change_id: string
          updated_at: string
          worker_id: string
        }
        Insert: {
          attempt_count?: number
          claim_id?: string | null
          claimed_at?: string | null
          client_request_id: string
          completed_at?: string | null
          created_at?: string
          effect_id: string
          effect_name: string
          effect_state?: string
          job_id: string
          last_error_code?: string | null
          payload?: Json
          scope_change_id: string
          updated_at?: string
          worker_id: string
        }
        Update: {
          attempt_count?: number
          claim_id?: string | null
          claimed_at?: string | null
          client_request_id?: string
          completed_at?: string | null
          created_at?: string
          effect_id?: string
          effect_name?: string
          effect_state?: string
          job_id?: string
          last_error_code?: string | null
          payload?: Json
          scope_change_id?: string
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scope_change_request_effects_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scope_change_request_effects_scope_change_id_fkey"
            columns: ["scope_change_id"]
            isOneToOne: false
            referencedRelation: "scope_change_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scope_change_request_effects_worker_id_client_request_id_fkey"
            columns: ["worker_id", "client_request_id"]
            isOneToOne: false
            referencedRelation: "scope_change_request_commands"
            referencedColumns: ["worker_id", "client_request_id"]
          },
        ]
      }
      scope_change_requests: {
        Row: {
          client_request_id: string | null
          created_at: string
          customer_decision_at: string | null
          evidence_photo_urls: string[]
          id: string
          job_id: string
          kael_computed_max: number | null
          kael_computed_min: number | null
          kael_progress: Json | null
          kael_review: Json | null
          original_summary: string | null
          price_max: number | null
          price_min: number | null
          reason: string
          request_timing: string
          requested_description: string
          resume_job_status: Database["public"]["Enums"]["job_status"]
          status: Database["public"]["Enums"]["scope_change_status"]
          updated_at: string
          worker_id: string
        }
        Insert: {
          client_request_id?: string | null
          created_at?: string
          customer_decision_at?: string | null
          evidence_photo_urls?: string[]
          id?: string
          job_id: string
          kael_computed_max?: number | null
          kael_computed_min?: number | null
          kael_progress?: Json | null
          kael_review?: Json | null
          original_summary?: string | null
          price_max?: number | null
          price_min?: number | null
          reason: string
          request_timing?: string
          requested_description: string
          resume_job_status?: Database["public"]["Enums"]["job_status"]
          status?: Database["public"]["Enums"]["scope_change_status"]
          updated_at?: string
          worker_id: string
        }
        Update: {
          client_request_id?: string | null
          created_at?: string
          customer_decision_at?: string | null
          evidence_photo_urls?: string[]
          id?: string
          job_id?: string
          kael_computed_max?: number | null
          kael_computed_min?: number | null
          kael_progress?: Json | null
          kael_review?: Json | null
          original_summary?: string | null
          price_max?: number | null
          price_min?: number | null
          reason?: string
          request_timing?: string
          requested_description?: string
          resume_job_status?: Database["public"]["Enums"]["job_status"]
          status?: Database["public"]["Enums"]["scope_change_status"]
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scope_change_requests_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scope_change_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      source_trust_registry: {
        Row: {
          added_at: string
          added_by: string | null
          auto_tier: number
          criteria_met: Json
          description: string | null
          domain: string
          effective_from: string
          effective_until: string | null
          entity_type: string | null
          established_year: number | null
          first_seen_at: string | null
          id: string
          integrity_flag: boolean
          is_active: boolean
          last_price_seen_at: string | null
          last_reviewed_at: string | null
          last_reviewer_id: string | null
          metadata: Json
          price_unit: string | null
          region: string | null
          review_notes: string | null
          tier: string
          trust_score: number
        }
        Insert: {
          added_at?: string
          added_by?: string | null
          auto_tier?: number
          criteria_met?: Json
          description?: string | null
          domain: string
          effective_from?: string
          effective_until?: string | null
          entity_type?: string | null
          established_year?: number | null
          first_seen_at?: string | null
          id?: string
          integrity_flag?: boolean
          is_active?: boolean
          last_price_seen_at?: string | null
          last_reviewed_at?: string | null
          last_reviewer_id?: string | null
          metadata?: Json
          price_unit?: string | null
          region?: string | null
          review_notes?: string | null
          tier: string
          trust_score: number
        }
        Update: {
          added_at?: string
          added_by?: string | null
          auto_tier?: number
          criteria_met?: Json
          description?: string | null
          domain?: string
          effective_from?: string
          effective_until?: string | null
          entity_type?: string | null
          established_year?: number | null
          first_seen_at?: string | null
          id?: string
          integrity_flag?: boolean
          is_active?: boolean
          last_price_seen_at?: string | null
          last_reviewed_at?: string | null
          last_reviewer_id?: string | null
          metadata?: Json
          price_unit?: string | null
          region?: string | null
          review_notes?: string | null
          tier?: string
          trust_score?: number
        }
        Relationships: [
          {
            foreignKeyName: "source_trust_registry_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "source_trust_registry_last_reviewer_id_fkey"
            columns: ["last_reviewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:core */
}
