// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'

export type CustomerTables = {
/* @slice:begin tables:customer */
      customer_account_deletion_requests: {
        Row: {
          avatar_storage_ref: string | null
          checkpoint: string
          client_request_id: string
          completed_at: string | null
          created_at: string
          customer_id: string
          database_scrubbed_at: string | null
          id: string
          requested_at: string
          status: string
          storage_refs: string[]
          updated_at: string
        }
        Insert: {
          avatar_storage_ref?: string | null
          checkpoint?: string
          client_request_id: string
          completed_at?: string | null
          created_at?: string
          customer_id: string
          database_scrubbed_at?: string | null
          id?: string
          requested_at?: string
          status?: string
          storage_refs?: string[]
          updated_at?: string
        }
        Update: {
          avatar_storage_ref?: string | null
          checkpoint?: string
          client_request_id?: string
          completed_at?: string | null
          created_at?: string
          customer_id?: string
          database_scrubbed_at?: string | null
          id?: string
          requested_at?: string
          status?: string
          storage_refs?: string[]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_account_deletion_requests_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_cancellation_reason_taxonomy: {
        Row: {
          admin_tunable: boolean
          category: string
          code: string
          created_at: string
          is_active: boolean
          label_vi: string
          safe_metadata: Json
          sort_order: number
          updated_at: string
        }
        Insert: {
          admin_tunable?: boolean
          category: string
          code: string
          created_at?: string
          is_active?: boolean
          label_vi: string
          safe_metadata?: Json
          sort_order?: number
          updated_at?: string
        }
        Update: {
          admin_tunable?: boolean
          category?: string
          code?: string
          created_at?: string
          is_active?: boolean
          label_vi?: string
          safe_metadata?: Json
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      customer_cancellation_records: {
        Row: {
          abuse_signals: string[]
          admin_review_required: boolean
          created_at: string
          customer_id: string
          id: string
          job_id: string
          phase0_no_monetary_penalty: boolean
          reason_category: string
          reason_code: string
          reason_note: string | null
          safe_metadata: Json
          status: string
          sub_case: string
          updated_at: string
          worker_goodwill: Json
          worker_id: string | null
        }
        Insert: {
          abuse_signals?: string[]
          admin_review_required?: boolean
          created_at?: string
          customer_id: string
          id?: string
          job_id: string
          phase0_no_monetary_penalty?: boolean
          reason_category: string
          reason_code: string
          reason_note?: string | null
          safe_metadata?: Json
          status?: string
          sub_case: string
          updated_at?: string
          worker_goodwill?: Json
          worker_id?: string | null
        }
        Update: {
          abuse_signals?: string[]
          admin_review_required?: boolean
          created_at?: string
          customer_id?: string
          id?: string
          job_id?: string
          phase0_no_monetary_penalty?: boolean
          reason_category?: string
          reason_code?: string
          reason_note?: string | null
          safe_metadata?: Json
          status?: string
          sub_case?: string
          updated_at?: string
          worker_goodwill?: Json
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_cancellation_records_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_cancellation_records_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_cancellation_records_reason_code_fkey"
            columns: ["reason_code"]
            isOneToOne: false
            referencedRelation: "customer_cancellation_reason_taxonomy"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "customer_cancellation_records_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_favorite_workers: {
        Row: {
          created_at: string
          customer_id: string
          synthetic_cohort_id: string | null
          worker_id: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          synthetic_cohort_id?: string | null
          worker_id: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          synthetic_cohort_id?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_favorite_workers_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_overview"
            referencedColumns: ["customer_id"]
          },
          {
            foreignKeyName: "customer_favorite_workers_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_favorite_workers_synthetic_cohort_id_fkey"
            columns: ["synthetic_cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
          {
            foreignKeyName: "customer_favorite_workers_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "customer_favorite_workers_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_kael_feedback: {
        Row: {
          created_at: string
          customer_id: string
          id: string
          language: string
          message: string
          message_scrubbed: string
          rating: string | null
          reason_scrubbed: string | null
          response_id: string | null
          safe_metadata: Json
          source: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          id?: string
          language?: string
          message: string
          message_scrubbed: string
          rating?: string | null
          reason_scrubbed?: string | null
          response_id?: string | null
          safe_metadata?: Json
          source?: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          id?: string
          language?: string
          message?: string
          message_scrubbed?: string
          rating?: string | null
          reason_scrubbed?: string | null
          response_id?: string | null
          safe_metadata?: Json
          source?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_kael_feedback_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_kael_memory: {
        Row: {
          created_at: string
          customer_id: string
          home_context: Json
          language: string
          last_observed_at: string | null
          memory_version: number
          preference_summary: string
          safe_metadata: Json
          service_preferences: Json
          trust_signals: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          home_context?: Json
          language?: string
          last_observed_at?: string | null
          memory_version?: number
          preference_summary?: string
          safe_metadata?: Json
          service_preferences?: Json
          trust_signals?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          home_context?: Json
          language?: string
          last_observed_at?: string | null
          memory_version?: number
          preference_summary?: string
          safe_metadata?: Json
          service_preferences?: Json
          trust_signals?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_kael_memory_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_membership_point_entries: {
        Row: {
          created_at: string
          customer_id: string
          entry_kind: string
          id: string
          job_id: string
          points: number
          program_version_id: string
          source_ledger_id: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          entry_kind: string
          id?: string
          job_id: string
          points: number
          program_version_id: string
          source_ledger_id: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          entry_kind?: string
          id?: string
          job_id?: string
          points?: number
          program_version_id?: string
          source_ledger_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_membership_point_entries_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_membership_point_entries_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_membership_point_entries_program_version_id_fkey"
            columns: ["program_version_id"]
            isOneToOne: false
            referencedRelation: "ambassador_program_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_membership_point_entries_source_ledger_id_fkey"
            columns: ["source_ledger_id"]
            isOneToOne: false
            referencedRelation: "worker_payment_ledger"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_payment_methods: {
        Row: {
          account_holder_name: string
          bank_account: string
          bank_account_masked: string
          bank_key: string
          bank_name: string
          created_at: string
          customer_id: string
          id: string
          is_default: boolean
          status: string
          synthetic_cohort_id: string | null
          updated_at: string
          verified_at: string | null
        }
        Insert: {
          account_holder_name: string
          bank_account: string
          bank_account_masked: string
          bank_key: string
          bank_name: string
          created_at?: string
          customer_id: string
          id?: string
          is_default?: boolean
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          verified_at?: string | null
        }
        Update: {
          account_holder_name?: string
          bank_account?: string
          bank_account_masked?: string
          bank_key?: string
          bank_name?: string
          created_at?: string
          customer_id?: string
          id?: string
          is_default?: boolean
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          verified_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_payment_methods_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_payment_methods_synthetic_cohort_id_fkey"
            columns: ["synthetic_cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
        ]
      }
      customer_profiles: {
        Row: {
          building_name: string | null
          created_at: string
          default_address: string | null
          district: string | null
          floor: string | null
          id: string
          unit_number: string | null
          updated_at: string
        }
        Insert: {
          building_name?: string | null
          created_at?: string
          default_address?: string | null
          district?: string | null
          floor?: string | null
          id: string
          unit_number?: string | null
          updated_at?: string
        }
        Update: {
          building_name?: string | null
          created_at?: string
          default_address?: string | null
          district?: string | null
          floor?: string | null
          id?: string
          unit_number?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_stats: {
        Row: {
          bookings_30d: number
          bookings_total: number
          customer_id: string
          dispute_free_rate: number | null
          last_recomputed_at: string
          total_spent: number
        }
        Insert: {
          bookings_30d?: number
          bookings_total?: number
          customer_id: string
          dispute_free_rate?: number | null
          last_recomputed_at?: string
          total_spent?: number
        }
        Update: {
          bookings_30d?: number
          bookings_total?: number
          customer_id?: string
          dispute_free_rate?: number | null
          last_recomputed_at?: string
          total_spent?: number
        }
        Relationships: [
          {
            foreignKeyName: "customer_stats_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: true
            referencedRelation: "customer_overview"
            referencedColumns: ["customer_id"]
          },
          {
            foreignKeyName: "customer_stats_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: true
            referencedRelation: "customer_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_worker_links: {
        Row: {
          case_id: string | null
          customer_id: string
          end_reason: string | null
          ended_at: string | null
          ended_by: string | null
          expires_at: string
          formed_at: string
          formed_by_job_id: string | null
          id: string
          program_version_id: string
          source: string
          worker_id: string
        }
        Insert: {
          case_id?: string | null
          customer_id: string
          end_reason?: string | null
          ended_at?: string | null
          ended_by?: string | null
          expires_at: string
          formed_at?: string
          formed_by_job_id?: string | null
          id?: string
          program_version_id: string
          source: string
          worker_id: string
        }
        Update: {
          case_id?: string | null
          customer_id?: string
          end_reason?: string | null
          ended_at?: string | null
          ended_by?: string | null
          expires_at?: string
          formed_at?: string
          formed_by_job_id?: string | null
          id?: string
          program_version_id?: string
          source?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_worker_links_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_worker_links_ended_by_fkey"
            columns: ["ended_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_worker_links_formed_by_job_id_fkey"
            columns: ["formed_by_job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_worker_links_program_version_id_fkey"
            columns: ["program_version_id"]
            isOneToOne: false
            referencedRelation: "ambassador_program_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_worker_links_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "customer_worker_links_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:customer */
}
