// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type JobsTables = {
/* @slice:begin tables:jobs */
      completion_payment_operations: {
        Row: {
          created_at: string
          customer_id: string
          final_price: number
          id: string
          job_id: string
          payment_order_id: string
          request_id: string
          response_snapshot: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          final_price: number
          id?: string
          job_id: string
          payment_order_id: string
          request_id: string
          response_snapshot?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          final_price?: number
          id?: string
          job_id?: string
          payment_order_id?: string
          request_id?: string
          response_snapshot?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "completion_payment_operations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_overview"
            referencedColumns: ["customer_id"]
          },
          {
            foreignKeyName: "completion_payment_operations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "completion_payment_operations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "completion_payment_operations_payment_order_id_fkey"
            columns: ["payment_order_id"]
            isOneToOne: true
            referencedRelation: "job_payment_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      job_broadcast_retry_claims: {
        Row: {
          claim_token: string
          claimed_at: string
          customer_id: string
          expires_at: string
          job_id: string
        }
        Insert: {
          claim_token: string
          claimed_at: string
          customer_id: string
          expires_at: string
          job_id: string
        }
        Update: {
          claim_token?: string
          claimed_at?: string
          customer_id?: string
          expires_at?: string
          job_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_broadcast_retry_claims_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      job_broadcasts: {
        Row: {
          batch_id: string
          broadcast_at: string
          expires_at: string | null
          id: string
          job_id: string
          original_scope_price_quote: Json | null
          responded_at: string | null
          sent_at: string | null
          status: Database["public"]["Enums"]["broadcast_status"]
          synthetic_cohort_id: string | null
          worker_id: string
        }
        Insert: {
          batch_id?: string
          broadcast_at?: string
          expires_at?: string | null
          id?: string
          job_id: string
          original_scope_price_quote?: Json | null
          responded_at?: string | null
          sent_at?: string | null
          status?: Database["public"]["Enums"]["broadcast_status"]
          synthetic_cohort_id?: string | null
          worker_id: string
        }
        Update: {
          batch_id?: string
          broadcast_at?: string
          expires_at?: string | null
          id?: string
          job_id?: string
          original_scope_price_quote?: Json | null
          responded_at?: string | null
          sent_at?: string | null
          status?: Database["public"]["Enums"]["broadcast_status"]
          synthetic_cohort_id?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_broadcasts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_broadcasts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      job_events: {
        Row: {
          actor_id: string | null
          actor_role: Database["public"]["Enums"]["user_role"] | null
          created_at: string
          event_type: string
          from_status: Database["public"]["Enums"]["job_status"] | null
          id: string
          job_id: string
          safe_metadata: Json
          to_status: Database["public"]["Enums"]["job_status"] | null
        }
        Insert: {
          actor_id?: string | null
          actor_role?: Database["public"]["Enums"]["user_role"] | null
          created_at?: string
          event_type: string
          from_status?: Database["public"]["Enums"]["job_status"] | null
          id?: string
          job_id: string
          safe_metadata?: Json
          to_status?: Database["public"]["Enums"]["job_status"] | null
        }
        Update: {
          actor_id?: string | null
          actor_role?: Database["public"]["Enums"]["user_role"] | null
          created_at?: string
          event_type?: string
          from_status?: Database["public"]["Enums"]["job_status"] | null
          id?: string
          job_id?: string
          safe_metadata?: Json
          to_status?: Database["public"]["Enums"]["job_status"] | null
        }
        Relationships: [
          {
            foreignKeyName: "job_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_events_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      job_matching_preferences: {
        Row: {
          auto_general: boolean
          client_request_id: string | null
          created_at: string
          customer_id: string
          fallback_at: string | null
          fallback_reason: string | null
          job_id: string
          matching_operation_id: string | null
          preferred_worker_id: string | null
          selected_at: string | null
          strategy: string
        }
        Insert: {
          auto_general?: boolean
          client_request_id?: string | null
          created_at?: string
          customer_id: string
          fallback_at?: string | null
          fallback_reason?: string | null
          job_id: string
          matching_operation_id?: string | null
          preferred_worker_id?: string | null
          selected_at?: string | null
          strategy?: string
        }
        Update: {
          auto_general?: boolean
          client_request_id?: string | null
          created_at?: string
          customer_id?: string
          fallback_at?: string | null
          fallback_reason?: string | null
          job_id?: string
          matching_operation_id?: string | null
          preferred_worker_id?: string | null
          selected_at?: string | null
          strategy?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_matching_preferences_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_overview"
            referencedColumns: ["customer_id"]
          },
          {
            foreignKeyName: "job_matching_preferences_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_matching_preferences_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_matching_preferences_matching_operation_id_fkey"
            columns: ["matching_operation_id"]
            isOneToOne: false
            referencedRelation: "matching_operations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_matching_preferences_preferred_worker_id_fkey"
            columns: ["preferred_worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "job_matching_preferences_preferred_worker_id_fkey"
            columns: ["preferred_worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      job_media_assets: {
        Row: {
          bucket_id: string
          created_at: string
          file_size_bytes: number | null
          id: string
          job_id: string
          mime_type: string | null
          object_path: string
          owner_id: string
          safe_metadata: Json
          service_type: Database["public"]["Enums"]["service_type"]
          stage: string
        }
        Insert: {
          bucket_id: string
          created_at?: string
          file_size_bytes?: number | null
          id?: string
          job_id: string
          mime_type?: string | null
          object_path: string
          owner_id: string
          safe_metadata?: Json
          service_type: Database["public"]["Enums"]["service_type"]
          stage: string
        }
        Update: {
          bucket_id?: string
          created_at?: string
          file_size_bytes?: number | null
          id?: string
          job_id?: string
          mime_type?: string | null
          object_path?: string
          owner_id?: string
          safe_metadata?: Json
          service_type?: Database["public"]["Enums"]["service_type"]
          stage?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_media_assets_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_media_assets_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      job_media_upload_intents: {
        Row: {
          attached_at: string | null
          bucket_id: string
          cleaned_at: string | null
          cleanup_claim_token: string | null
          cleanup_claimed_at: string | null
          created_at: string
          delete_after: string | null
          expires_at: string
          file_size_bytes: number
          id: string
          job_id: string
          mime_type: string
          object_path: string
          owner_id: string
          stage: string
          status: string
          updated_at: string
        }
        Insert: {
          attached_at?: string | null
          bucket_id?: string
          cleaned_at?: string | null
          cleanup_claim_token?: string | null
          cleanup_claimed_at?: string | null
          created_at?: string
          delete_after?: string | null
          expires_at: string
          file_size_bytes: number
          id?: string
          job_id: string
          mime_type: string
          object_path: string
          owner_id: string
          stage: string
          status?: string
          updated_at?: string
        }
        Update: {
          attached_at?: string | null
          bucket_id?: string
          cleaned_at?: string | null
          cleanup_claim_token?: string | null
          cleanup_claimed_at?: string | null
          created_at?: string
          delete_after?: string | null
          expires_at?: string
          file_size_bytes?: number
          id?: string
          job_id?: string
          mime_type?: string
          object_path?: string
          owner_id?: string
          stage?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_media_upload_intents_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      job_payment_orders: {
        Row: {
          amount_received: number | null
          assigned_at: string | null
          assigned_to: string | null
          bank_reference_hash: string | null
          bank_reference_suffix: string | null
          client_request_id: string | null
          created_at: string
          credited_at: string | null
          customer_confirmed_at: string | null
          customer_id: string
          customer_transfer_claimed_at: string | null
          customer_transferred_at: string | null
          gross_amount: number
          hold_until: string | null
          id: string
          job_id: string
          payment_code: string | null
          payment_method: string
          platform_fee: number
          qr_image_url: string | null
          response_deadline: string | null
          sending_bank_code: string | null
          status: string
          transfer_content: string | null
          updated_at: string
          verified_at: string | null
          verified_by: string | null
          version: number
          worker_confirmed_at: string | null
          worker_id: string
          worker_net: number
        }
        Insert: {
          amount_received?: number | null
          assigned_at?: string | null
          assigned_to?: string | null
          bank_reference_hash?: string | null
          bank_reference_suffix?: string | null
          client_request_id?: string | null
          created_at?: string
          credited_at?: string | null
          customer_confirmed_at?: string | null
          customer_id: string
          customer_transfer_claimed_at?: string | null
          customer_transferred_at?: string | null
          gross_amount: number
          hold_until?: string | null
          id?: string
          job_id: string
          payment_code?: string | null
          payment_method: string
          platform_fee?: number
          qr_image_url?: string | null
          response_deadline?: string | null
          sending_bank_code?: string | null
          status: string
          transfer_content?: string | null
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
          version?: number
          worker_confirmed_at?: string | null
          worker_id: string
          worker_net?: number
        }
        Update: {
          amount_received?: number | null
          assigned_at?: string | null
          assigned_to?: string | null
          bank_reference_hash?: string | null
          bank_reference_suffix?: string | null
          client_request_id?: string | null
          created_at?: string
          credited_at?: string | null
          customer_confirmed_at?: string | null
          customer_id?: string
          customer_transfer_claimed_at?: string | null
          customer_transferred_at?: string | null
          gross_amount?: number
          hold_until?: string | null
          id?: string
          job_id?: string
          payment_code?: string | null
          payment_method?: string
          platform_fee?: number
          qr_image_url?: string | null
          response_deadline?: string | null
          sending_bank_code?: string | null
          status?: string
          transfer_content?: string | null
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
          version?: number
          worker_confirmed_at?: string | null
          worker_id?: string
          worker_net?: number
        }
        Relationships: [
          {
            foreignKeyName: "job_payment_orders_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_payment_orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_payment_orders_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_payment_orders_verified_by_fkey"
            columns: ["verified_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_payment_orders_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "job_payment_orders_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      job_payment_reconciliation_events: {
        Row: {
          actor_id: string | null
          created_at: string
          event_type: string
          id: string
          job_id: string
          payment_order_id: string
          reason_code: string | null
          safe_metadata: Json
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          event_type: string
          id?: string
          job_id: string
          payment_order_id: string
          reason_code?: string | null
          safe_metadata?: Json
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          event_type?: string
          id?: string
          job_id?: string
          payment_order_id?: string
          reason_code?: string | null
          safe_metadata?: Json
        }
        Relationships: [
          {
            foreignKeyName: "job_payment_reconciliation_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_payment_reconciliation_events_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_payment_reconciliation_events_payment_order_id_fkey"
            columns: ["payment_order_id"]
            isOneToOne: false
            referencedRelation: "job_payment_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      job_refund_obligations: {
        Row: {
          amount_vnd: number
          approved_by: string | null
          created_at: string
          id: string
          job_id: string
          payment_order_id: string | null
          source_id: string
          source_type: string
          state: string
          synthetic_cohort_id: string | null
          verified_paid_amount_vnd: number
        }
        Insert: {
          amount_vnd: number
          approved_by?: string | null
          created_at?: string
          id?: string
          job_id: string
          payment_order_id?: string | null
          source_id: string
          source_type: string
          state?: string
          synthetic_cohort_id?: string | null
          verified_paid_amount_vnd: number
        }
        Update: {
          amount_vnd?: number
          approved_by?: string | null
          created_at?: string
          id?: string
          job_id?: string
          payment_order_id?: string | null
          source_id?: string
          source_type?: string
          state?: string
          synthetic_cohort_id?: string | null
          verified_paid_amount_vnd?: number
        }
        Relationships: [
          {
            foreignKeyName: "job_refund_obligations_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_refund_obligations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_refund_obligations_payment_order_id_fkey"
            columns: ["payment_order_id"]
            isOneToOne: false
            referencedRelation: "job_payment_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_refund_obligations_synthetic_cohort_id_fkey"
            columns: ["synthetic_cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
        ]
      }
      job_rfq_price_proposals: {
        Row: {
          commission_level: number
          commission_rate_bps: number
          created_at: string
          currency: string
          customer_id: string
          customer_total: number
          decided_at: string | null
          id: string
          job_id: string
          quote_mode: Database["public"]["Enums"]["service_quote_mode"]
          scope_summary: string
          status: string
          synthetic_cohort_id: string | null
          worker_id: string
        }
        Insert: {
          commission_level: number
          commission_rate_bps: number
          created_at?: string
          currency?: string
          customer_id: string
          customer_total: number
          decided_at?: string | null
          id: string
          job_id: string
          quote_mode: Database["public"]["Enums"]["service_quote_mode"]
          scope_summary: string
          status?: string
          synthetic_cohort_id?: string | null
          worker_id: string
        }
        Update: {
          commission_level?: number
          commission_rate_bps?: number
          created_at?: string
          currency?: string
          customer_id?: string
          customer_total?: number
          decided_at?: string | null
          id?: string
          job_id?: string
          quote_mode?: Database["public"]["Enums"]["service_quote_mode"]
          scope_summary?: string
          status?: string
          synthetic_cohort_id?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_rfq_price_proposals_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_rfq_price_proposals_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_rfq_price_proposals_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      job_worker_candidates: {
        Row: {
          broadcast_id: string | null
          created_at: string
          customer_decided_at: string | null
          customer_decision_kind: string | null
          expires_at: string | null
          id: string
          job_id: string
          original_scope_price_quote: Json | null
          proposed_at: string
          status: string
          synthetic_cohort_id: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          broadcast_id?: string | null
          created_at?: string
          customer_decided_at?: string | null
          customer_decision_kind?: string | null
          expires_at?: string | null
          id?: string
          job_id: string
          original_scope_price_quote?: Json | null
          proposed_at?: string
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          broadcast_id?: string | null
          created_at?: string
          customer_decided_at?: string | null
          customer_decision_kind?: string | null
          expires_at?: string | null
          id?: string
          job_id?: string
          original_scope_price_quote?: Json | null
          proposed_at?: string
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_worker_candidates_broadcast_id_fkey"
            columns: ["broadcast_id"]
            isOneToOne: false
            referencedRelation: "job_broadcasts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_worker_candidates_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "job_worker_candidates_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "job_worker_candidates_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          address_building: string | null
          address_district: string | null
          address_floor: string | null
          address_lat: number | null
          address_lng: number | null
          address_unit: string | null
          apartment_access_profile: Json
          apartment_access_state: Json
          arrived_at: string | null
          broadcast_at: string | null
          cancelled_at: string | null
          client_request_id: string | null
          completed_at: string | null
          completion_notes: string | null
          completion_photo_urls: string[]
          confirmed_at: string | null
          confirmed_search_at: string | null
          created_at: string
          customer_id: string
          description: string
          diagnosis_scope: Json | null
          display_code: string
          estimate_ready_at: string | null
          final_price: number | null
          geo_source: string | null
          gross_amount: number | null
          id: string
          intake_scope_snapshot: Json | null
          kael_advisory: string | null
          kael_complexity:
            | Database["public"]["Enums"]["complexity_level"]
            | null
          kael_estimate_card_v3: Json | null
          kael_price_max: number | null
          kael_price_min: number | null
          kael_problem_identified: string | null
          kael_progress: Json | null
          kael_reference_price_max: number | null
          kael_reference_price_min: number | null
          kael_worker_brief_core: Json | null
          kael_worker_brief_guidance: Json | null
          matched_at: string | null
          paid_at: string | null
          payment_amount_received: number | null
          payment_code: string | null
          payment_expires_at: string | null
          payment_failure_reason: string | null
          payment_provider: string | null
          payment_qr_image_url: string | null
          payment_received_at: string | null
          payment_status: string
          payment_transfer_content: string | null
          payment_updated_at: string | null
          photo_urls: string[]
          platform_fee: number | null
          price_context_1: Json | null
          price_context_2: Json | null
          problem_chips: string[]
          quote_mode: Database["public"]["Enums"]["service_quote_mode"] | null
          reviewed_at: string | null
          scheduled_at: string | null
          scope_change_customer_decision: string | null
          scope_change_description: string | null
          scope_change_price_max: number | null
          scope_change_price_min: number | null
          scope_change_reason: string | null
          sepay_reference_code: string | null
          sepay_transaction_id: string | null
          service_problem_id: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          status: Database["public"]["Enums"]["job_status"]
          synthetic_cohort_id: string | null
          updated_at: string
          work_paused_at: string | null
          work_paused_ms: number
          work_started_at: string | null
          worker_commission_level: number | null
          worker_commission_rate_bps: number | null
          worker_id: string | null
          worker_net: number | null
          worker_work_note: string | null
        }
        Insert: {
          address_building?: string | null
          address_district?: string | null
          address_floor?: string | null
          address_lat?: number | null
          address_lng?: number | null
          address_unit?: string | null
          apartment_access_profile?: Json
          apartment_access_state?: Json
          arrived_at?: string | null
          broadcast_at?: string | null
          cancelled_at?: string | null
          client_request_id?: string | null
          completed_at?: string | null
          completion_notes?: string | null
          completion_photo_urls?: string[]
          confirmed_at?: string | null
          confirmed_search_at?: string | null
          created_at?: string
          customer_id: string
          description: string
          diagnosis_scope?: Json | null
          display_code?: string
          estimate_ready_at?: string | null
          final_price?: number | null
          geo_source?: string | null
          gross_amount?: number | null
          id?: string
          intake_scope_snapshot?: Json | null
          kael_advisory?: string | null
          kael_complexity?:
            | Database["public"]["Enums"]["complexity_level"]
            | null
          kael_estimate_card_v3?: Json | null
          kael_price_max?: number | null
          kael_price_min?: number | null
          kael_problem_identified?: string | null
          kael_progress?: Json | null
          kael_reference_price_max?: number | null
          kael_reference_price_min?: number | null
          kael_worker_brief_core?: Json | null
          kael_worker_brief_guidance?: Json | null
          matched_at?: string | null
          paid_at?: string | null
          payment_amount_received?: number | null
          payment_code?: string | null
          payment_expires_at?: string | null
          payment_failure_reason?: string | null
          payment_provider?: string | null
          payment_qr_image_url?: string | null
          payment_received_at?: string | null
          payment_status?: string
          payment_transfer_content?: string | null
          payment_updated_at?: string | null
          photo_urls?: string[]
          platform_fee?: number | null
          price_context_1?: Json | null
          price_context_2?: Json | null
          problem_chips?: string[]
          quote_mode?: Database["public"]["Enums"]["service_quote_mode"] | null
          reviewed_at?: string | null
          scheduled_at?: string | null
          scope_change_customer_decision?: string | null
          scope_change_description?: string | null
          scope_change_price_max?: number | null
          scope_change_price_min?: number | null
          scope_change_reason?: string | null
          sepay_reference_code?: string | null
          sepay_transaction_id?: string | null
          service_problem_id?: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          status?: Database["public"]["Enums"]["job_status"]
          synthetic_cohort_id?: string | null
          updated_at?: string
          work_paused_at?: string | null
          work_paused_ms?: number
          work_started_at?: string | null
          worker_commission_level?: number | null
          worker_commission_rate_bps?: number | null
          worker_id?: string | null
          worker_net?: number | null
          worker_work_note?: string | null
        }
        Update: {
          address_building?: string | null
          address_district?: string | null
          address_floor?: string | null
          address_lat?: number | null
          address_lng?: number | null
          address_unit?: string | null
          apartment_access_profile?: Json
          apartment_access_state?: Json
          arrived_at?: string | null
          broadcast_at?: string | null
          cancelled_at?: string | null
          client_request_id?: string | null
          completed_at?: string | null
          completion_notes?: string | null
          completion_photo_urls?: string[]
          confirmed_at?: string | null
          confirmed_search_at?: string | null
          created_at?: string
          customer_id?: string
          description?: string
          diagnosis_scope?: Json | null
          display_code?: string
          estimate_ready_at?: string | null
          final_price?: number | null
          geo_source?: string | null
          gross_amount?: number | null
          id?: string
          intake_scope_snapshot?: Json | null
          kael_advisory?: string | null
          kael_complexity?:
            | Database["public"]["Enums"]["complexity_level"]
            | null
          kael_estimate_card_v3?: Json | null
          kael_price_max?: number | null
          kael_price_min?: number | null
          kael_problem_identified?: string | null
          kael_progress?: Json | null
          kael_reference_price_max?: number | null
          kael_reference_price_min?: number | null
          kael_worker_brief_core?: Json | null
          kael_worker_brief_guidance?: Json | null
          matched_at?: string | null
          paid_at?: string | null
          payment_amount_received?: number | null
          payment_code?: string | null
          payment_expires_at?: string | null
          payment_failure_reason?: string | null
          payment_provider?: string | null
          payment_qr_image_url?: string | null
          payment_received_at?: string | null
          payment_status?: string
          payment_transfer_content?: string | null
          payment_updated_at?: string | null
          photo_urls?: string[]
          platform_fee?: number | null
          price_context_1?: Json | null
          price_context_2?: Json | null
          problem_chips?: string[]
          quote_mode?: Database["public"]["Enums"]["service_quote_mode"] | null
          reviewed_at?: string | null
          scheduled_at?: string | null
          scope_change_customer_decision?: string | null
          scope_change_description?: string | null
          scope_change_price_max?: number | null
          scope_change_price_min?: number | null
          scope_change_reason?: string | null
          sepay_reference_code?: string | null
          sepay_transaction_id?: string | null
          service_problem_id?: string | null
          service_type?: Database["public"]["Enums"]["service_type"]
          status?: Database["public"]["Enums"]["job_status"]
          synthetic_cohort_id?: string | null
          updated_at?: string
          work_paused_at?: string | null
          work_paused_ms?: number
          work_started_at?: string | null
          worker_commission_level?: number | null
          worker_commission_rate_bps?: number | null
          worker_id?: string | null
          worker_net?: number | null
          worker_work_note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "jobs_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_service_problem_id_fkey"
            columns: ["service_problem_id"]
            isOneToOne: false
            referencedRelation: "service_problems"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      workflow_recovery_action_audit: {
        Row: {
          action: string
          actor_id: string | null
          affected_reservation_count: number
          case_version: number
          created_at: string
          id: string
          idempotency_key: string
          job_id: string
          observed_job_state: string
          reason: string
          recovery_case_id: string
          safe_metadata: Json
        }
        Insert: {
          action: string
          actor_id?: string | null
          affected_reservation_count?: number
          case_version: number
          created_at?: string
          id?: string
          idempotency_key: string
          job_id: string
          observed_job_state: string
          reason: string
          recovery_case_id: string
          safe_metadata?: Json
        }
        Update: {
          action?: string
          actor_id?: string | null
          affected_reservation_count?: number
          case_version?: number
          created_at?: string
          id?: string
          idempotency_key?: string
          job_id?: string
          observed_job_state?: string
          reason?: string
          recovery_case_id?: string
          safe_metadata?: Json
        }
        Relationships: [
          {
            foreignKeyName: "workflow_recovery_action_audit_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workflow_recovery_action_audit_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workflow_recovery_action_audit_recovery_case_id_fkey"
            columns: ["recovery_case_id"]
            isOneToOne: false
            referencedRelation: "workflow_recovery_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      workflow_recovery_cases: {
        Row: {
          created_at: string
          detected_state: string
          first_detected_at: string
          id: string
          job_id: string
          last_activity_at: string
          last_detected_at: string
          reason_code: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          safe_metadata: Json
          severity: string
          status: string
          updated_at: string
          version: number
        }
        Insert: {
          created_at?: string
          detected_state: string
          first_detected_at: string
          id?: string
          job_id: string
          last_activity_at: string
          last_detected_at: string
          reason_code: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          safe_metadata?: Json
          severity: string
          status?: string
          updated_at?: string
          version?: number
        }
        Update: {
          created_at?: string
          detected_state?: string
          first_detected_at?: string
          id?: string
          job_id?: string
          last_activity_at?: string
          last_detected_at?: string
          reason_code?: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          safe_metadata?: Json
          severity?: string
          status?: string
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "workflow_recovery_cases_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workflow_recovery_cases_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:jobs */
}
