// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type KaelTables = {
/* @slice:begin tables:kael */
      kael_ab_experiments: {
        Row: {
          comparison_provider: Database["public"]["Enums"]["api_provider"]
          created_at: string
          ended_at: string | null
          experiment_key: string
          fallback_provider: Database["public"]["Enums"]["api_provider"] | null
          id: string
          metric_thresholds: Json
          primary_provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          safe_metadata: Json
          sample_target: number
          started_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          comparison_provider: Database["public"]["Enums"]["api_provider"]
          created_at?: string
          ended_at?: string | null
          experiment_key: string
          fallback_provider?: Database["public"]["Enums"]["api_provider"] | null
          id?: string
          metric_thresholds?: Json
          primary_provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          safe_metadata?: Json
          sample_target?: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          comparison_provider?: Database["public"]["Enums"]["api_provider"]
          created_at?: string
          ended_at?: string | null
          experiment_key?: string
          fallback_provider?: Database["public"]["Enums"]["api_provider"] | null
          id?: string
          metric_thresholds?: Json
          primary_provider?: Database["public"]["Enums"]["api_provider"]
          purpose?: string
          safe_metadata?: Json
          sample_target?: number
          started_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      kael_ab_price_synthesis_cases: {
        Row: {
          actual_final_price: number | null
          anthropic_price_max: number | null
          anthropic_price_min: number | null
          anthropic_schema_valid: boolean | null
          case_key: string
          created_at: string
          district_code: string | null
          exclusion_reason: string | null
          experiment_id: string
          fallback_used: boolean
          id: string
          job_id: string | null
          perplexity_price_max: number | null
          perplexity_price_min: number | null
          perplexity_schema_valid: boolean | null
          problem_slug: string | null
          request_id: string | null
          safe_metadata: Json
          service_type: Database["public"]["Enums"]["service_type"] | null
          source: string
          status: string
          updated_at: string
        }
        Insert: {
          actual_final_price?: number | null
          anthropic_price_max?: number | null
          anthropic_price_min?: number | null
          anthropic_schema_valid?: boolean | null
          case_key: string
          created_at?: string
          district_code?: string | null
          exclusion_reason?: string | null
          experiment_id: string
          fallback_used?: boolean
          id?: string
          job_id?: string | null
          perplexity_price_max?: number | null
          perplexity_price_min?: number | null
          perplexity_schema_valid?: boolean | null
          problem_slug?: string | null
          request_id?: string | null
          safe_metadata?: Json
          service_type?: Database["public"]["Enums"]["service_type"] | null
          source: string
          status?: string
          updated_at?: string
        }
        Update: {
          actual_final_price?: number | null
          anthropic_price_max?: number | null
          anthropic_price_min?: number | null
          anthropic_schema_valid?: boolean | null
          case_key?: string
          created_at?: string
          district_code?: string | null
          exclusion_reason?: string | null
          experiment_id?: string
          fallback_used?: boolean
          id?: string
          job_id?: string | null
          perplexity_price_max?: number | null
          perplexity_price_min?: number | null
          perplexity_schema_valid?: boolean | null
          problem_slug?: string | null
          request_id?: string | null
          safe_metadata?: Json
          service_type?: Database["public"]["Enums"]["service_type"] | null
          source?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_ab_price_synthesis_cases_experiment_id_fkey"
            columns: ["experiment_id"]
            isOneToOne: false
            referencedRelation: "kael_ab_experiments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_ab_price_synthesis_cases_experiment_id_fkey"
            columns: ["experiment_id"]
            isOneToOne: false
            referencedRelation: "kael_monitoring_ab_price_synthesis"
            referencedColumns: ["experiment_id"]
          },
          {
            foreignKeyName: "kael_ab_price_synthesis_cases_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_admin_queue: {
        Row: {
          actor_id: string | null
          actor_role: string
          created_at: string
          escalation_level: string
          id: string
          job_id: string | null
          priority: string
          queue_type: string
          reason_code: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          response_summary: string
          safe_metadata: Json
          status: string
          updated_at: string
        }
        Insert: {
          actor_id?: string | null
          actor_role: string
          created_at?: string
          escalation_level: string
          id?: string
          job_id?: string | null
          priority: string
          queue_type: string
          reason_code: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          response_summary: string
          safe_metadata?: Json
          status?: string
          updated_at?: string
        }
        Update: {
          actor_id?: string | null
          actor_role?: string
          created_at?: string
          escalation_level?: string
          id?: string
          job_id?: string | null
          priority?: string
          queue_type?: string
          reason_code?: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          response_summary?: string
          safe_metadata?: Json
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_admin_queue_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_admin_queue_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_admin_queue_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_advisory_audit: {
        Row: {
          actor_id: string | null
          advisory_type: string
          artifact_id: string | null
          created_at: string
          id: string
          job_id: string | null
          purpose: string
          safe_metadata: Json
          template_key: string | null
        }
        Insert: {
          actor_id?: string | null
          advisory_type: string
          artifact_id?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          purpose: string
          safe_metadata?: Json
          template_key?: string | null
        }
        Update: {
          actor_id?: string | null
          advisory_type?: string
          artifact_id?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          purpose?: string
          safe_metadata?: Json
          template_key?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "kael_advisory_audit_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_advisory_audit_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_ai_batch_items: {
        Row: {
          batch_id: string
          created_at: string
          custom_id: string
          error_payload: Json
          id: string
          processed_at: string | null
          queue_id: string | null
          request_payload: Json
          response_payload: Json
          skill_id: string
          status: string
        }
        Insert: {
          batch_id: string
          created_at?: string
          custom_id: string
          error_payload?: Json
          id?: string
          processed_at?: string | null
          queue_id?: string | null
          request_payload?: Json
          response_payload?: Json
          skill_id: string
          status?: string
        }
        Update: {
          batch_id?: string
          created_at?: string
          custom_id?: string
          error_payload?: Json
          id?: string
          processed_at?: string | null
          queue_id?: string | null
          request_payload?: Json
          response_payload?: Json
          skill_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_ai_batch_items_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "kael_ai_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_ai_batch_items_queue_id_fkey"
            columns: ["queue_id"]
            isOneToOne: false
            referencedRelation: "kael_learning_queue"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_ai_batches: {
        Row: {
          canceled_count: number
          created_at: string
          ended_at: string | null
          error_code: string | null
          errored_count: number
          expired_count: number
          expires_at: string | null
          id: string
          next_poll_at: string | null
          processing_count: number
          provider: Database["public"]["Enums"]["api_provider"]
          provider_batch_id: string | null
          purpose: string
          request_count: number
          results_url: string | null
          safe_metadata: Json
          status: string
          submitted_at: string | null
          succeeded_count: number
          updated_at: string
        }
        Insert: {
          canceled_count?: number
          created_at?: string
          ended_at?: string | null
          error_code?: string | null
          errored_count?: number
          expired_count?: number
          expires_at?: string | null
          id?: string
          next_poll_at?: string | null
          processing_count?: number
          provider?: Database["public"]["Enums"]["api_provider"]
          provider_batch_id?: string | null
          purpose?: string
          request_count?: number
          results_url?: string | null
          safe_metadata?: Json
          status?: string
          submitted_at?: string | null
          succeeded_count?: number
          updated_at?: string
        }
        Update: {
          canceled_count?: number
          created_at?: string
          ended_at?: string | null
          error_code?: string | null
          errored_count?: number
          expired_count?: number
          expires_at?: string | null
          id?: string
          next_poll_at?: string | null
          processing_count?: number
          provider?: Database["public"]["Enums"]["api_provider"]
          provider_batch_id?: string | null
          purpose?: string
          request_count?: number
          results_url?: string | null
          safe_metadata?: Json
          status?: string
          submitted_at?: string | null
          succeeded_count?: number
          updated_at?: string
        }
        Relationships: []
      }
      kael_ai_spend_log: {
        Row: {
          actor_id: string | null
          cost_usd: number
          created_at: string
          harness_release_id: string | null
          harness_run_id: string | null
          harness_trace_id: string | null
          id: number
          provider_attempt_id: string | null
          purpose: string
          reservation_expires_at: string | null
          reservation_status: string
        }
        Insert: {
          actor_id?: string | null
          cost_usd: number
          created_at?: string
          harness_release_id?: string | null
          harness_run_id?: string | null
          harness_trace_id?: string | null
          id?: never
          provider_attempt_id?: string | null
          purpose: string
          reservation_expires_at?: string | null
          reservation_status?: string
        }
        Update: {
          actor_id?: string | null
          cost_usd?: number
          created_at?: string
          harness_release_id?: string | null
          harness_run_id?: string | null
          harness_trace_id?: string | null
          id?: never
          provider_attempt_id?: string | null
          purpose?: string
          reservation_expires_at?: string | null
          reservation_status?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_ai_spend_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_analysis_artifacts: {
        Row: {
          artifact_type: string
          confidence: number | null
          created_at: string
          id: string
          job_id: string | null
          provider: Database["public"]["Enums"]["api_provider"] | null
          safe_payload: Json
          service_problem_id: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          summary: string | null
        }
        Insert: {
          artifact_type: string
          confidence?: number | null
          created_at?: string
          id?: string
          job_id?: string | null
          provider?: Database["public"]["Enums"]["api_provider"] | null
          safe_payload?: Json
          service_problem_id?: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          summary?: string | null
        }
        Update: {
          artifact_type?: string
          confidence?: number | null
          created_at?: string
          id?: string
          job_id?: string | null
          provider?: Database["public"]["Enums"]["api_provider"] | null
          safe_payload?: Json
          service_problem_id?: string | null
          service_type?: Database["public"]["Enums"]["service_type"]
          summary?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "kael_analysis_artifacts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_analysis_artifacts_service_problem_id_fkey"
            columns: ["service_problem_id"]
            isOneToOne: false
            referencedRelation: "service_problems"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_autonomy_decision_audit: {
        Row: {
          actor_id: string | null
          actor_role: string
          confidence: number | null
          created_at: string
          decision: Json | null
          decision_source: string
          evidence_refs: string[]
          from_status: Database["public"]["Enums"]["job_status"]
          gate_result: string
          id: string
          job_id: string | null
          reason_code: string
          resulting_event: string | null
          safe_metadata: Json
          to_status: Database["public"]["Enums"]["job_status"]
        }
        Insert: {
          actor_id?: string | null
          actor_role: string
          confidence?: number | null
          created_at?: string
          decision?: Json | null
          decision_source: string
          evidence_refs?: string[]
          from_status: Database["public"]["Enums"]["job_status"]
          gate_result: string
          id?: string
          job_id?: string | null
          reason_code: string
          resulting_event?: string | null
          safe_metadata?: Json
          to_status: Database["public"]["Enums"]["job_status"]
        }
        Update: {
          actor_id?: string | null
          actor_role?: string
          confidence?: number | null
          created_at?: string
          decision?: Json | null
          decision_source?: string
          evidence_refs?: string[]
          from_status?: Database["public"]["Enums"]["job_status"]
          gate_result?: string
          id?: string
          job_id?: string | null
          reason_code?: string
          resulting_event?: string | null
          safe_metadata?: Json
          to_status?: Database["public"]["Enums"]["job_status"]
        }
        Relationships: [
          {
            foreignKeyName: "kael_autonomy_decision_audit_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_autonomy_decision_audit_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_charter_audit: {
        Row: {
          actor_id: string | null
          actor_role: string | null
          charter_version: string
          created_at: string
          file_name: string
          id: string
          operation: string
          safe_metadata: Json
          status: string
        }
        Insert: {
          actor_id?: string | null
          actor_role?: string | null
          charter_version: string
          created_at?: string
          file_name: string
          id?: string
          operation: string
          safe_metadata?: Json
          status: string
        }
        Update: {
          actor_id?: string | null
          actor_role?: string | null
          charter_version?: string
          created_at?: string
          file_name?: string
          id?: string
          operation?: string
          safe_metadata?: Json
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_charter_audit_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_chat_media_upload_intents: {
        Row: {
          bucket_id: string
          cleaned_at: string | null
          cleanup_attempts: number
          cleanup_claim_token: string | null
          cleanup_claimed_at: string | null
          consumed_at: string | null
          created_at: string
          customer_id: string
          delete_after: string
          expires_at: string
          file_size_bytes: number
          id: string
          mime_type: string
          object_path: string
          purpose: string
          status: string
          updated_at: string
        }
        Insert: {
          bucket_id?: string
          cleaned_at?: string | null
          cleanup_attempts?: number
          cleanup_claim_token?: string | null
          cleanup_claimed_at?: string | null
          consumed_at?: string | null
          created_at?: string
          customer_id: string
          delete_after: string
          expires_at: string
          file_size_bytes: number
          id?: string
          mime_type: string
          object_path: string
          purpose: string
          status?: string
          updated_at?: string
        }
        Update: {
          bucket_id?: string
          cleaned_at?: string | null
          cleanup_attempts?: number
          cleanup_claim_token?: string | null
          cleanup_claimed_at?: string | null
          consumed_at?: string | null
          created_at?: string
          customer_id?: string
          delete_after?: string
          expires_at?: string
          file_size_bytes?: number
          id?: string
          mime_type?: string
          object_path?: string
          purpose?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      kael_chat_pre_intake_memory: {
        Row: {
          access_profile: Json
          address_district: string | null
          address_fingerprint: string
          address_label_safe: string | null
          created_at: string
          customer_id: string
          id: string
          last_used_job_id: string | null
          updated_at: string
        }
        Insert: {
          access_profile?: Json
          address_district?: string | null
          address_fingerprint: string
          address_label_safe?: string | null
          created_at?: string
          customer_id: string
          id?: string
          last_used_job_id?: string | null
          updated_at?: string
        }
        Update: {
          access_profile?: Json
          address_district?: string | null
          address_fingerprint?: string
          address_label_safe?: string | null
          created_at?: string
          customer_id?: string
          id?: string
          last_used_job_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_chat_pre_intake_memory_last_used_job_id_fkey"
            columns: ["last_used_job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_chat_rate_limit_log: {
        Row: {
          ts: string
          user_id: string
        }
        Insert: {
          ts?: string
          user_id: string
        }
        Update: {
          ts?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_chat_rate_limit_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_chat_sessions: {
        Row: {
          abandoned_at: string | null
          case_phase: string
          client_request_id: string | null
          created_at: string
          customer_id: string
          diagnosis_scope: Json | null
          estimate_ready_at: string | null
          id: string
          job_id: string | null
          kael_progress: Json | null
          preferred_worker_id: string | null
          safe_metadata: Json
          scheduled_at: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          started_at: string
          status: string
          total_cost_usd: number
          total_turns: number
          updated_at: string
        }
        Insert: {
          abandoned_at?: string | null
          case_phase?: string
          client_request_id?: string | null
          created_at?: string
          customer_id: string
          diagnosis_scope?: Json | null
          estimate_ready_at?: string | null
          id?: string
          job_id?: string | null
          kael_progress?: Json | null
          preferred_worker_id?: string | null
          safe_metadata?: Json
          scheduled_at?: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          started_at?: string
          status?: string
          total_cost_usd?: number
          total_turns?: number
          updated_at?: string
        }
        Update: {
          abandoned_at?: string | null
          case_phase?: string
          client_request_id?: string | null
          created_at?: string
          customer_id?: string
          diagnosis_scope?: Json | null
          estimate_ready_at?: string | null
          id?: string
          job_id?: string | null
          kael_progress?: Json | null
          preferred_worker_id?: string | null
          safe_metadata?: Json
          scheduled_at?: string | null
          service_type?: Database["public"]["Enums"]["service_type"]
          started_at?: string
          status?: string
          total_cost_usd?: number
          total_turns?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_chat_sessions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_chat_sessions_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_chat_sessions_preferred_worker_id_fkey"
            columns: ["preferred_worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "kael_chat_sessions_preferred_worker_id_fkey"
            columns: ["preferred_worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_chat_turns: {
        Row: {
          ai_model: string | null
          ai_provider: Database["public"]["Enums"]["api_provider"] | null
          content_type: string
          cost_usd: number | null
          created_at: string
          id: string
          latency_ms: number | null
          media_refs: string[]
          role: string
          safe_metadata: Json
          session_id: string
          text_content: string | null
          turn_index: number
        }
        Insert: {
          ai_model?: string | null
          ai_provider?: Database["public"]["Enums"]["api_provider"] | null
          content_type: string
          cost_usd?: number | null
          created_at?: string
          id?: string
          latency_ms?: number | null
          media_refs?: string[]
          role: string
          safe_metadata?: Json
          session_id: string
          text_content?: string | null
          turn_index: number
        }
        Update: {
          ai_model?: string | null
          ai_provider?: Database["public"]["Enums"]["api_provider"] | null
          content_type?: string
          cost_usd?: number | null
          created_at?: string
          id?: string
          latency_ms?: number | null
          media_refs?: string[]
          role?: string
          safe_metadata?: Json
          session_id?: string
          text_content?: string | null
          turn_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "kael_chat_turns_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "kael_chat_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_customer_conversation_turns: {
        Row: {
          client_request_id: string | null
          conversation_id: string
          created_at: string
          customer_id: string
          id: string
          role: string
          text_content: string
          turn_index: number
        }
        Insert: {
          client_request_id?: string | null
          conversation_id: string
          created_at?: string
          customer_id: string
          id?: string
          role: string
          text_content: string
          turn_index: number
        }
        Update: {
          client_request_id?: string | null
          conversation_id?: string
          created_at?: string
          customer_id?: string
          id?: string
          role?: string
          text_content?: string
          turn_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "kael_customer_conversation_turns_owner_fk"
            columns: ["conversation_id", "customer_id"]
            isOneToOne: false
            referencedRelation: "kael_customer_conversations"
            referencedColumns: ["id", "customer_id"]
          },
        ]
      }
      kael_customer_conversations: {
        Row: {
          archived_at: string | null
          case_session_id: string | null
          chat_mode: string
          client_request_id: string
          created_at: string
          customer_id: string
          id: string
          pinned_at: string | null
          title: string | null
          total_turns: number
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          case_session_id?: string | null
          chat_mode: string
          client_request_id: string
          created_at?: string
          customer_id: string
          id?: string
          pinned_at?: string | null
          title?: string | null
          total_turns?: number
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          case_session_id?: string | null
          chat_mode?: string
          client_request_id?: string
          created_at?: string
          customer_id?: string
          id?: string
          pinned_at?: string | null
          title?: string | null
          total_turns?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_customer_conversations_case_session_id_fkey"
            columns: ["case_session_id"]
            isOneToOne: true
            referencedRelation: "kael_chat_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_customer_conversations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_guardrail_trip_audit: {
        Row: {
          actor_id: string | null
          actor_role: string
          created_at: string
          guardrail_label: string | null
          id: string
          job_id: string | null
          reason_code: string
          safe_metadata: Json
          source: string
          surface: string
        }
        Insert: {
          actor_id?: string | null
          actor_role: string
          created_at?: string
          guardrail_label?: string | null
          id?: string
          job_id?: string | null
          reason_code: string
          safe_metadata?: Json
          source: string
          surface: string
        }
        Update: {
          actor_id?: string | null
          actor_role?: string
          created_at?: string
          guardrail_label?: string | null
          id?: string
          job_id?: string | null
          reason_code?: string
          safe_metadata?: Json
          source?: string
          surface?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_guardrail_trip_audit_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_guardrail_trip_audit_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_interaction_log: {
        Row: {
          actor_id: string | null
          actor_role: string
          created_at: string
          escalation_level: string
          expected_nuance: string
          id: string
          interaction_type: string
          job_id: string | null
          legitimate_concern_signals: string[]
          nuance: string
          pressure_signals: string[]
          safe_metadata: Json
          sanitized_excerpt: string
          strategy_ids: string[]
        }
        Insert: {
          actor_id?: string | null
          actor_role: string
          created_at?: string
          escalation_level: string
          expected_nuance: string
          id?: string
          interaction_type: string
          job_id?: string | null
          legitimate_concern_signals?: string[]
          nuance: string
          pressure_signals?: string[]
          safe_metadata?: Json
          sanitized_excerpt?: string
          strategy_ids?: string[]
        }
        Update: {
          actor_id?: string | null
          actor_role?: string
          created_at?: string
          escalation_level?: string
          expected_nuance?: string
          id?: string
          interaction_type?: string
          job_id?: string | null
          legitimate_concern_signals?: string[]
          nuance?: string
          pressure_signals?: string[]
          safe_metadata?: Json
          sanitized_excerpt?: string
          strategy_ids?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "kael_interaction_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_interaction_log_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_job_incident_events: {
        Row: {
          actor_id: string | null
          actor_role: string
          assistant_claim_id: string | null
          assistant_claimed_at: string | null
          caused_by_event_id: string | null
          content: string | null
          created_at: string
          id: string
          incident_id: string
          job_id: string
          media_refs: Json
          message_id: string | null
          reported_description_snapshot: string | null
          reported_reason_snapshot: string | null
          request_id: string | null
          safe_metadata: Json
          source_job_status: Database["public"]["Enums"]["job_status"] | null
          source_kind: string
          source_revision: number | null
        }
        Insert: {
          actor_id?: string | null
          actor_role: string
          assistant_claim_id?: string | null
          assistant_claimed_at?: string | null
          caused_by_event_id?: string | null
          content?: string | null
          created_at?: string
          id?: string
          incident_id: string
          job_id: string
          media_refs?: Json
          message_id?: string | null
          reported_description_snapshot?: string | null
          reported_reason_snapshot?: string | null
          request_id?: string | null
          safe_metadata?: Json
          source_job_status?: Database["public"]["Enums"]["job_status"] | null
          source_kind: string
          source_revision?: number | null
        }
        Update: {
          actor_id?: string | null
          actor_role?: string
          assistant_claim_id?: string | null
          assistant_claimed_at?: string | null
          caused_by_event_id?: string | null
          content?: string | null
          created_at?: string
          id?: string
          incident_id?: string
          job_id?: string
          media_refs?: Json
          message_id?: string | null
          reported_description_snapshot?: string | null
          reported_reason_snapshot?: string | null
          request_id?: string | null
          safe_metadata?: Json
          source_job_status?: Database["public"]["Enums"]["job_status"] | null
          source_kind?: string
          source_revision?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "kael_job_incident_events_caused_by_event_id_fkey"
            columns: ["caused_by_event_id"]
            isOneToOne: false
            referencedRelation: "kael_job_incident_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_job_incident_events_incident_id_fkey"
            columns: ["incident_id"]
            isOneToOne: false
            referencedRelation: "kael_job_incidents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_job_incident_events_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_job_incident_events_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "chat_messages"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_job_incidents: {
        Row: {
          created_at: string
          evidence_photo_urls: Json
          evidence_status: string
          id: string
          job_id: string
          last_next_actor: string | null
          last_question: string | null
          last_summary: string | null
          opened_by: string
          reported_description: string
          reported_reason: string
          revision: number
          scope_change_id: string | null
          scope_proposal_claim_id: string | null
          scope_proposal_claimed_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          evidence_photo_urls?: Json
          evidence_status?: string
          id?: string
          job_id: string
          last_next_actor?: string | null
          last_question?: string | null
          last_summary?: string | null
          opened_by: string
          reported_description: string
          reported_reason: string
          revision?: number
          scope_change_id?: string | null
          scope_proposal_claim_id?: string | null
          scope_proposal_claimed_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          evidence_photo_urls?: Json
          evidence_status?: string
          id?: string
          job_id?: string
          last_next_actor?: string | null
          last_question?: string | null
          last_summary?: string | null
          opened_by?: string
          reported_description?: string
          reported_reason?: string
          revision?: number
          scope_change_id?: string | null
          scope_proposal_claim_id?: string | null
          scope_proposal_claimed_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_job_incidents_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_job_incidents_scope_change_id_fkey"
            columns: ["scope_change_id"]
            isOneToOne: false
            referencedRelation: "scope_change_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_knowledge_usage_log: {
        Row: {
          citation_id: string
          created_at: string
          id: string
          job_id: string | null
          knowledge_id: string | null
          knowledge_table: string
          safe_metadata: Json
          session_id: string | null
          similarity: number | null
        }
        Insert: {
          citation_id: string
          created_at?: string
          id?: string
          job_id?: string | null
          knowledge_id?: string | null
          knowledge_table: string
          safe_metadata?: Json
          session_id?: string | null
          similarity?: number | null
        }
        Update: {
          citation_id?: string
          created_at?: string
          id?: string
          job_id?: string | null
          knowledge_id?: string | null
          knowledge_table?: string
          safe_metadata?: Json
          session_id?: string | null
          similarity?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "kael_knowledge_usage_log_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_learning_queue: {
        Row: {
          actor_id: string | null
          actor_role: string | null
          attempts: number
          batch_id: string | null
          candidate_payload: Json
          claim_id: string | null
          claimed_at: string | null
          created_at: string
          error_code: string | null
          event_type: string
          finalized_claim_id: string | null
          id: string
          input_payload: Json
          job_id: string | null
          processed_at: string | null
          provider_batch_id: string | null
          queue_state: string
          run_after: string
          skill_id: string
          updated_at: string
        }
        Insert: {
          actor_id?: string | null
          actor_role?: string | null
          attempts?: number
          batch_id?: string | null
          candidate_payload?: Json
          claim_id?: string | null
          claimed_at?: string | null
          created_at?: string
          error_code?: string | null
          event_type: string
          finalized_claim_id?: string | null
          id?: string
          input_payload?: Json
          job_id?: string | null
          processed_at?: string | null
          provider_batch_id?: string | null
          queue_state?: string
          run_after?: string
          skill_id: string
          updated_at?: string
        }
        Update: {
          actor_id?: string | null
          actor_role?: string | null
          attempts?: number
          batch_id?: string | null
          candidate_payload?: Json
          claim_id?: string | null
          claimed_at?: string | null
          created_at?: string
          error_code?: string | null
          event_type?: string
          finalized_claim_id?: string | null
          id?: string
          input_payload?: Json
          job_id?: string | null
          processed_at?: string | null
          provider_batch_id?: string | null
          queue_state?: string
          run_after?: string
          skill_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_learning_queue_batch_fk"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "kael_ai_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_learning_queue_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_market_artifacts: {
        Row: {
          complexity: Database["public"]["Enums"]["complexity_level"]
          confidence: number | null
          created_at: string
          district_code: string
          failure_reason: string | null
          id: string
          market_range_max: number | null
          market_range_min: number | null
          problem_slug: string
          provider: Database["public"]["Enums"]["api_provider"]
          safe_metadata: Json
          service_problem_id: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          sources_summary: string | null
        }
        Insert: {
          complexity: Database["public"]["Enums"]["complexity_level"]
          confidence?: number | null
          created_at?: string
          district_code?: string
          failure_reason?: string | null
          id?: string
          market_range_max?: number | null
          market_range_min?: number | null
          problem_slug: string
          provider?: Database["public"]["Enums"]["api_provider"]
          safe_metadata?: Json
          service_problem_id?: string | null
          service_type: Database["public"]["Enums"]["service_type"]
          sources_summary?: string | null
        }
        Update: {
          complexity?: Database["public"]["Enums"]["complexity_level"]
          confidence?: number | null
          created_at?: string
          district_code?: string
          failure_reason?: string | null
          id?: string
          market_range_max?: number | null
          market_range_min?: number | null
          problem_slug?: string
          provider?: Database["public"]["Enums"]["api_provider"]
          safe_metadata?: Json
          service_problem_id?: string | null
          service_type?: Database["public"]["Enums"]["service_type"]
          sources_summary?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "kael_market_artifacts_service_problem_id_fkey"
            columns: ["service_problem_id"]
            isOneToOne: false
            referencedRelation: "service_problems"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_market_cache: {
        Row: {
          complexity: Database["public"]["Enums"]["complexity_level"]
          confidence: number
          created_at: string
          district_code: string
          expires_at: string
          hit_count: number
          id: string
          invalidated_at: string | null
          market_range_max: number
          market_range_min: number
          perplexity_raw: Json
          problem_slug: string
          service_type: Database["public"]["Enums"]["service_type"]
          sources_summary: string | null
          updated_at: string
        }
        Insert: {
          complexity: Database["public"]["Enums"]["complexity_level"]
          confidence: number
          created_at?: string
          district_code: string
          expires_at: string
          hit_count?: number
          id?: string
          invalidated_at?: string | null
          market_range_max: number
          market_range_min: number
          perplexity_raw?: Json
          problem_slug: string
          service_type: Database["public"]["Enums"]["service_type"]
          sources_summary?: string | null
          updated_at?: string
        }
        Update: {
          complexity?: Database["public"]["Enums"]["complexity_level"]
          confidence?: number
          created_at?: string
          district_code?: string
          expires_at?: string
          hit_count?: number
          id?: string
          invalidated_at?: string | null
          market_range_max?: number
          market_range_min?: number
          perplexity_raw?: Json
          problem_slug?: string
          service_type?: Database["public"]["Enums"]["service_type"]
          sources_summary?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      kael_memory_archive: {
        Row: {
          archived_from: string
          archived_reason: string
          created_at: string
          id: string
          memory_payload: Json
          subject_id: string | null
          subject_type: string
        }
        Insert: {
          archived_from: string
          archived_reason: string
          created_at?: string
          id?: string
          memory_payload: Json
          subject_id?: string | null
          subject_type: string
        }
        Update: {
          archived_from?: string
          archived_reason?: string
          created_at?: string
          id?: string
          memory_payload?: Json
          subject_id?: string | null
          subject_type?: string
        }
        Relationships: []
      }
      kael_memory_audit: {
        Row: {
          actor_id: string | null
          created_at: string
          id: string
          layer: string
          operation: string
          purpose: string
          safe_metadata: Json
          subject_id: string | null
          subject_type: string
          token_count: number | null
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          id?: string
          layer: string
          operation: string
          purpose: string
          safe_metadata?: Json
          subject_id?: string | null
          subject_type: string
          token_count?: number | null
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          id?: string
          layer?: string
          operation?: string
          purpose?: string
          safe_metadata?: Json
          subject_id?: string | null
          subject_type?: string
          token_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "kael_memory_audit_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_memory_update_receipts: {
        Row: {
          applied_at: string
          event_key: string
          event_type: string
          job_id: string | null
          safe_metadata: Json
          source_event_id: string
          subject_id: string
          subject_type: string
        }
        Insert: {
          applied_at?: string
          event_key: string
          event_type: string
          job_id?: string | null
          safe_metadata?: Json
          source_event_id: string
          subject_id: string
          subject_type: string
        }
        Update: {
          applied_at?: string
          event_key?: string
          event_type?: string
          job_id?: string | null
          safe_metadata?: Json
          source_event_id?: string
          subject_id?: string
          subject_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_memory_update_receipts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_memory_update_receipts_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_optimization_metrics: {
        Row: {
          cost_actual: number | null
          cost_before_estimate: number | null
          cost_delta_estimate: number | null
          created_at: string
          enabled_options: string[]
          id: string
          input_tokens: number | null
          job_id: string | null
          latency_ms: number | null
          metric_source: string
          model: string | null
          option_flags: Json
          output_tokens: number | null
          provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          quality_pass: boolean | null
          quality_signal: string | null
          request_id: string | null
          safe_metadata: Json
        }
        Insert: {
          cost_actual?: number | null
          cost_before_estimate?: number | null
          cost_delta_estimate?: number | null
          created_at?: string
          enabled_options?: string[]
          id?: string
          input_tokens?: number | null
          job_id?: string | null
          latency_ms?: number | null
          metric_source?: string
          model?: string | null
          option_flags?: Json
          output_tokens?: number | null
          provider: Database["public"]["Enums"]["api_provider"]
          purpose: string
          quality_pass?: boolean | null
          quality_signal?: string | null
          request_id?: string | null
          safe_metadata?: Json
        }
        Update: {
          cost_actual?: number | null
          cost_before_estimate?: number | null
          cost_delta_estimate?: number | null
          created_at?: string
          enabled_options?: string[]
          id?: string
          input_tokens?: number | null
          job_id?: string | null
          latency_ms?: number | null
          metric_source?: string
          model?: string | null
          option_flags?: Json
          output_tokens?: number | null
          provider?: Database["public"]["Enums"]["api_provider"]
          purpose?: string
          quality_pass?: boolean | null
          quality_signal?: string | null
          request_id?: string | null
          safe_metadata?: Json
        }
        Relationships: [
          {
            foreignKeyName: "kael_optimization_metrics_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_permission_audit: {
        Row: {
          action: string
          actor_id: string | null
          actor_role: string
          created_at: string
          decision: string
          id: string
          job_id: string | null
          purpose: string
          reason_code: string
          safe_metadata: Json
          topic: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          actor_role: string
          created_at?: string
          decision: string
          id?: string
          job_id?: string | null
          purpose: string
          reason_code: string
          safe_metadata?: Json
          topic?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          actor_role?: string
          created_at?: string
          decision?: string
          id?: string
          job_id?: string | null
          purpose?: string
          reason_code?: string
          safe_metadata?: Json
          topic?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "kael_permission_audit_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_permission_audit_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_provider_circuit: {
        Row: {
          failure_count: number
          key: string
          kind: string
          open_until: string | null
          scope: string
          updated_at: string
          window_started_at: string
        }
        Insert: {
          failure_count?: number
          key: string
          kind: string
          open_until?: string | null
          scope: string
          updated_at?: string
          window_started_at: string
        }
        Update: {
          failure_count?: number
          key?: string
          kind?: string
          open_until?: string | null
          scope?: string
          updated_at?: string
          window_started_at?: string
        }
        Relationships: []
      }
      kael_provider_spend_daily: {
        Row: {
          call_count: number
          spend_date: string
          total_cost_usd: number
          updated_at: string
        }
        Insert: {
          call_count?: number
          spend_date?: string
          total_cost_usd?: number
          updated_at?: string
        }
        Update: {
          call_count?: number
          spend_date?: string
          total_cost_usd?: number
          updated_at?: string
        }
        Relationships: []
      }
      kael_quality_baseline: {
        Row: {
          advisory_accuracy_score: number | null
          api_log_count: number
          avg_review_rating: number | null
          baseline_key: string
          cost_summary: Json
          created_at: string
          id: string
          job_count: number
          provider_breakdown: Json
          purpose_breakdown: Json
          safe_metadata: Json
          sample_ended_at: string | null
          sample_size: number
          sample_started_at: string | null
          schema_validation_rate: number | null
          source: string
          updated_at: string
          vietnamese_tone_score: number | null
        }
        Insert: {
          advisory_accuracy_score?: number | null
          api_log_count?: number
          avg_review_rating?: number | null
          baseline_key: string
          cost_summary?: Json
          created_at?: string
          id?: string
          job_count?: number
          provider_breakdown?: Json
          purpose_breakdown?: Json
          safe_metadata?: Json
          sample_ended_at?: string | null
          sample_size: number
          sample_started_at?: string | null
          schema_validation_rate?: number | null
          source: string
          updated_at?: string
          vietnamese_tone_score?: number | null
        }
        Update: {
          advisory_accuracy_score?: number | null
          api_log_count?: number
          avg_review_rating?: number | null
          baseline_key?: string
          cost_summary?: Json
          created_at?: string
          id?: string
          job_count?: number
          provider_breakdown?: Json
          purpose_breakdown?: Json
          safe_metadata?: Json
          sample_ended_at?: string | null
          sample_size?: number
          sample_started_at?: string | null
          schema_validation_rate?: number | null
          source?: string
          updated_at?: string
          vietnamese_tone_score?: number | null
        }
        Relationships: []
      }
      kael_rate_counter: {
        Row: {
          key: string
          scope: string
          tokens: number
          updated_at: string
          window_started_at: string
        }
        Insert: {
          key: string
          scope: string
          tokens: number
          updated_at?: string
          window_started_at: string
        }
        Update: {
          key?: string
          scope?: string
          tokens?: number
          updated_at?: string
          window_started_at?: string
        }
        Relationships: []
      }
      kael_region_lexicon_candidate: {
        Row: {
          created_at: string
          evidence: Json
          id: string
          marker: string
          proposed_region: string
          proposed_tier: string
          status: string
          support_count: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          evidence?: Json
          id?: string
          marker: string
          proposed_region: string
          proposed_tier: string
          status?: string
          support_count?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          evidence?: Json
          id?: string
          marker?: string
          proposed_region?: string
          proposed_tier?: string
          status?: string
          support_count?: number
          updated_at?: string
        }
        Relationships: []
      }
      kael_rule_application_log: {
        Row: {
          accuracy_delta: number | null
          actor_id: string | null
          actor_role: string | null
          applied_count: number
          applied_target: string
          candidate_id: string | null
          created_at: string
          id: string
          job_id: string | null
          override_count: number
          rule_id: string | null
          safe_metadata: Json
          satisfaction_delta: number | null
          skill_id: string
        }
        Insert: {
          accuracy_delta?: number | null
          actor_id?: string | null
          actor_role?: string | null
          applied_count?: number
          applied_target: string
          candidate_id?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          override_count?: number
          rule_id?: string | null
          safe_metadata?: Json
          satisfaction_delta?: number | null
          skill_id: string
        }
        Update: {
          accuracy_delta?: number | null
          actor_id?: string | null
          actor_role?: string | null
          applied_count?: number
          applied_target?: string
          candidate_id?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          override_count?: number
          rule_id?: string | null
          safe_metadata?: Json
          satisfaction_delta?: number | null
          skill_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_rule_application_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_rule_application_log_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "learning_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_rule_application_log_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_rule_application_log_rule_id_fkey"
            columns: ["rule_id"]
            isOneToOne: false
            referencedRelation: "learning_rules"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_rule_lifecycle_log: {
        Row: {
          actor_id: string | null
          actor_role: string | null
          candidate_id: string | null
          created_at: string
          id: string
          job_id: string | null
          next_state: string
          previous_state: string | null
          rule_id: string | null
          safe_metadata: Json
          skill_id: string
          transition_reason: string
        }
        Insert: {
          actor_id?: string | null
          actor_role?: string | null
          candidate_id?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          next_state: string
          previous_state?: string | null
          rule_id?: string | null
          safe_metadata?: Json
          skill_id: string
          transition_reason: string
        }
        Update: {
          actor_id?: string | null
          actor_role?: string | null
          candidate_id?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          next_state?: string
          previous_state?: string | null
          rule_id?: string | null
          safe_metadata?: Json
          skill_id?: string
          transition_reason?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_rule_lifecycle_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_rule_lifecycle_log_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "learning_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_rule_lifecycle_log_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_rule_lifecycle_log_rule_id_fkey"
            columns: ["rule_id"]
            isOneToOne: false
            referencedRelation: "learning_rules"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_voice_transcript: {
        Row: {
          actor_role: string
          created_at: string
          id: string
          region_hint: string
          safe_metadata: Json
          scrubbed_text: string
          session_id: string | null
          source: string
          user_id: string
        }
        Insert: {
          actor_role?: string
          created_at?: string
          id?: string
          region_hint?: string
          safe_metadata?: Json
          scrubbed_text: string
          session_id?: string | null
          source?: string
          user_id: string
        }
        Update: {
          actor_role?: string
          created_at?: string
          id?: string
          region_hint?: string
          safe_metadata?: Json
          scrubbed_text?: string
          session_id?: string | null
          source?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_voice_transcript_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "kael_chat_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_voice_transcript_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_worker_chat_rate_limit_log: {
        Row: {
          ts: string
          worker_id: string
        }
        Insert: {
          ts?: string
          worker_id: string
        }
        Update: {
          ts?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_worker_chat_rate_limit_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_worker_chat_sessions: {
        Row: {
          archived_at: string | null
          chat_mode: string
          client_request_id: string | null
          closed_at: string | null
          created_at: string
          id: string
          job_id: string | null
          kael_progress: Json | null
          pinned_at: string | null
          safe_metadata: Json
          started_at: string
          status: string
          title: string | null
          total_cost_usd: number
          total_turns: number
          updated_at: string
          worker_id: string
        }
        Insert: {
          archived_at?: string | null
          chat_mode?: string
          client_request_id?: string | null
          closed_at?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          kael_progress?: Json | null
          pinned_at?: string | null
          safe_metadata?: Json
          started_at?: string
          status?: string
          title?: string | null
          total_cost_usd?: number
          total_turns?: number
          updated_at?: string
          worker_id: string
        }
        Update: {
          archived_at?: string | null
          chat_mode?: string
          client_request_id?: string | null
          closed_at?: string | null
          created_at?: string
          id?: string
          job_id?: string | null
          kael_progress?: Json | null
          pinned_at?: string | null
          safe_metadata?: Json
          started_at?: string
          status?: string
          title?: string | null
          total_cost_usd?: number
          total_turns?: number
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_worker_chat_sessions_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_chat_sessions_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_worker_chat_turn_requests: {
        Row: {
          assistant_turn_id: string | null
          attempt_count: number
          claim_id: string | null
          claimed_at: string | null
          client_request_id: string
          completed_at: string | null
          content_type: string
          created_at: string
          id: string
          job_id: string | null
          media_refs: string[]
          session_id: string
          source_job_status: Database["public"]["Enums"]["job_status"] | null
          status: string
          text_content: string
          updated_at: string
          worker_id: string
          worker_turn_id: string
        }
        Insert: {
          assistant_turn_id?: string | null
          attempt_count?: number
          claim_id?: string | null
          claimed_at?: string | null
          client_request_id: string
          completed_at?: string | null
          content_type: string
          created_at?: string
          id?: string
          job_id?: string | null
          media_refs?: string[]
          session_id: string
          source_job_status?: Database["public"]["Enums"]["job_status"] | null
          status: string
          text_content: string
          updated_at?: string
          worker_id: string
          worker_turn_id: string
        }
        Update: {
          assistant_turn_id?: string | null
          attempt_count?: number
          claim_id?: string | null
          claimed_at?: string | null
          client_request_id?: string
          completed_at?: string | null
          content_type?: string
          created_at?: string
          id?: string
          job_id?: string | null
          media_refs?: string[]
          session_id?: string
          source_job_status?: Database["public"]["Enums"]["job_status"] | null
          status?: string
          text_content?: string
          updated_at?: string
          worker_id?: string
          worker_turn_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_worker_chat_turn_requests_assistant_turn_id_fkey"
            columns: ["assistant_turn_id"]
            isOneToOne: false
            referencedRelation: "kael_worker_chat_turns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_chat_turn_requests_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_chat_turn_requests_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "kael_worker_chat_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_chat_turn_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_chat_turn_requests_worker_turn_id_fkey"
            columns: ["worker_turn_id"]
            isOneToOne: true
            referencedRelation: "kael_worker_chat_turns"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_worker_chat_turns: {
        Row: {
          ai_model: string | null
          ai_provider: Database["public"]["Enums"]["api_provider"] | null
          client_request_id: string | null
          content_type: string
          cost_usd: number | null
          created_at: string
          id: string
          job_id: string | null
          latency_ms: number | null
          media_refs: string[]
          role: string
          safe_metadata: Json
          session_id: string
          source_turn_id: string | null
          text_content: string | null
          turn_index: number
        }
        Insert: {
          ai_model?: string | null
          ai_provider?: Database["public"]["Enums"]["api_provider"] | null
          client_request_id?: string | null
          content_type: string
          cost_usd?: number | null
          created_at?: string
          id?: string
          job_id?: string | null
          latency_ms?: number | null
          media_refs?: string[]
          role: string
          safe_metadata?: Json
          session_id: string
          source_turn_id?: string | null
          text_content?: string | null
          turn_index: number
        }
        Update: {
          ai_model?: string | null
          ai_provider?: Database["public"]["Enums"]["api_provider"] | null
          client_request_id?: string | null
          content_type?: string
          cost_usd?: number | null
          created_at?: string
          id?: string
          job_id?: string | null
          latency_ms?: number | null
          media_refs?: string[]
          role?: string
          safe_metadata?: Json
          session_id?: string
          source_turn_id?: string | null
          text_content?: string | null
          turn_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "kael_worker_chat_turns_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_chat_turns_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "kael_worker_chat_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_chat_turns_source_turn_id_fkey"
            columns: ["source_turn_id"]
            isOneToOne: false
            referencedRelation: "kael_worker_chat_turns"
            referencedColumns: ["id"]
          },
        ]
      }
      kael_worker_qa_log: {
        Row: {
          answer: Json
          created_at: string
          id: string
          job_id: string
          question: string
          worker_id: string
        }
        Insert: {
          answer: Json
          created_at?: string
          id?: string
          job_id: string
          question: string
          worker_id: string
        }
        Update: {
          answer?: Json
          created_at?: string
          id?: string
          job_id?: string
          question?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kael_worker_qa_log_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kael_worker_qa_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:kael */
}
