// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type LearningTables = {
/* @slice:begin tables:learning */
      learning_candidate_provenance: {
        Row: {
          candidate_id: string
          consent_hash: string
          consent_status: string
          created_at: string
          dispute_status: string
          evidence_hash: string
          generated_summary_hash: string | null
          input_hash: string
          privacy_status: string
          provenance_status: string
          quality_status: string
          release_id: string
          safe_metadata: Json
          source_hash: string
          source_type: string
          summary_origin: string
          updated_at: string
        }
        Insert: {
          candidate_id: string
          consent_hash: string
          consent_status: string
          created_at?: string
          dispute_status: string
          evidence_hash: string
          generated_summary_hash?: string | null
          input_hash: string
          privacy_status: string
          provenance_status?: string
          quality_status: string
          release_id: string
          safe_metadata?: Json
          source_hash: string
          source_type: string
          summary_origin: string
          updated_at?: string
        }
        Update: {
          candidate_id?: string
          consent_hash?: string
          consent_status?: string
          created_at?: string
          dispute_status?: string
          evidence_hash?: string
          generated_summary_hash?: string | null
          input_hash?: string
          privacy_status?: string
          provenance_status?: string
          quality_status?: string
          release_id?: string
          safe_metadata?: Json
          source_hash?: string
          source_type?: string
          summary_origin?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_candidate_provenance_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: true
            referencedRelation: "learning_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_candidate_reviews: {
        Row: {
          candidate_id: string
          decision: string
          evidence_hash: string | null
          gate_snapshot: Json
          generated_summary_hash: string | null
          reason: string
          release_id: string
          review_id: string
          reviewed_at: string
          reviewer_id: string
          safe_metadata: Json
          source_hash: string | null
          summary_origin: string | null
        }
        Insert: {
          candidate_id: string
          decision: string
          evidence_hash?: string | null
          gate_snapshot?: Json
          generated_summary_hash?: string | null
          reason: string
          release_id: string
          review_id?: string
          reviewed_at?: string
          reviewer_id: string
          safe_metadata?: Json
          source_hash?: string | null
          summary_origin?: string | null
        }
        Update: {
          candidate_id?: string
          decision?: string
          evidence_hash?: string | null
          gate_snapshot?: Json
          generated_summary_hash?: string | null
          reason?: string
          release_id?: string
          review_id?: string
          reviewed_at?: string
          reviewer_id?: string
          safe_metadata?: Json
          source_hash?: string | null
          summary_origin?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "learning_candidate_reviews_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "learning_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "learning_candidate_reviews_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_candidates: {
        Row: {
          affected_district: string | null
          affected_problem: string | null
          affected_service: Database["public"]["Enums"]["service_type"] | null
          audit_reason: string | null
          candidate_type: string
          confidence: number
          created_at: string
          evidence_count: number
          id: string
          promoted_at: string | null
          rolled_back_at: string | null
          status: Database["public"]["Enums"]["learning_candidate_status"]
          suggested_payload: Json
          updated_at: string
        }
        Insert: {
          affected_district?: string | null
          affected_problem?: string | null
          affected_service?: Database["public"]["Enums"]["service_type"] | null
          audit_reason?: string | null
          candidate_type: string
          confidence?: number
          created_at?: string
          evidence_count?: number
          id?: string
          promoted_at?: string | null
          rolled_back_at?: string | null
          status?: Database["public"]["Enums"]["learning_candidate_status"]
          suggested_payload?: Json
          updated_at?: string
        }
        Update: {
          affected_district?: string | null
          affected_problem?: string | null
          affected_service?: Database["public"]["Enums"]["service_type"] | null
          audit_reason?: string | null
          candidate_type?: string
          confidence?: number
          created_at?: string
          evidence_count?: number
          id?: string
          promoted_at?: string | null
          rolled_back_at?: string | null
          status?: Database["public"]["Enums"]["learning_candidate_status"]
          suggested_payload?: Json
          updated_at?: string
        }
        Relationships: []
      }
      learning_observation_receipts: {
        Row: {
          affected_district: string
          affected_problem: string
          affected_service: Database["public"]["Enums"]["service_type"]
          baseline_max: number | null
          baseline_min: number | null
          candidate_id: string
          candidate_type: string
          complexity: Database["public"]["Enums"]["complexity_level"]
          created_at: string
          final_price: number | null
          id: string
          job_id: string
          rating: number | null
          reference_max: number | null
          reference_min: number | null
          review_tags: string[]
          reviewed_at: string
          scope_change_requested: boolean
        }
        Insert: {
          affected_district: string
          affected_problem: string
          affected_service: Database["public"]["Enums"]["service_type"]
          baseline_max?: number | null
          baseline_min?: number | null
          candidate_id: string
          candidate_type: string
          complexity: Database["public"]["Enums"]["complexity_level"]
          created_at?: string
          final_price?: number | null
          id?: string
          job_id: string
          rating?: number | null
          reference_max?: number | null
          reference_min?: number | null
          review_tags?: string[]
          reviewed_at: string
          scope_change_requested: boolean
        }
        Update: {
          affected_district?: string
          affected_problem?: string
          affected_service?: Database["public"]["Enums"]["service_type"]
          baseline_max?: number | null
          baseline_min?: number | null
          candidate_id?: string
          candidate_type?: string
          complexity?: Database["public"]["Enums"]["complexity_level"]
          created_at?: string
          final_price?: number | null
          id?: string
          job_id?: string
          rating?: number | null
          reference_max?: number | null
          reference_min?: number | null
          review_tags?: string[]
          reviewed_at?: string
          scope_change_requested?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "learning_observation_receipts_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "learning_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "learning_observation_receipts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_rule_dependencies: {
        Row: {
          candidate_id: string
          created_at: string
          dependency_id: string
          evidence_hash: string
          release_id: string
          revoked_at: string | null
          rule_id: string
          rule_version: number
          source_hash: string
          status: string
        }
        Insert: {
          candidate_id: string
          created_at?: string
          dependency_id?: string
          evidence_hash: string
          release_id: string
          revoked_at?: string | null
          rule_id: string
          rule_version: number
          source_hash: string
          status?: string
        }
        Update: {
          candidate_id?: string
          created_at?: string
          dependency_id?: string
          evidence_hash?: string
          release_id?: string
          revoked_at?: string | null
          rule_id?: string
          rule_version?: number
          source_hash?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "learning_rule_dependencies_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "learning_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "learning_rule_dependencies_rule_id_fkey"
            columns: ["rule_id"]
            isOneToOne: false
            referencedRelation: "learning_rules"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_rule_revocations: {
        Row: {
          cascaded_dependency_count: number
          reason: string
          release_id: string
          revocation_id: string
          revoked_at: string
          revoked_by: string
          rule_id: string
          rule_version: number
          safe_metadata: Json
        }
        Insert: {
          cascaded_dependency_count?: number
          reason: string
          release_id: string
          revocation_id?: string
          revoked_at?: string
          revoked_by: string
          rule_id: string
          rule_version: number
          safe_metadata?: Json
        }
        Update: {
          cascaded_dependency_count?: number
          reason?: string
          release_id?: string
          revocation_id?: string
          revoked_at?: string
          revoked_by?: string
          rule_id?: string
          rule_version?: number
          safe_metadata?: Json
        }
        Relationships: [
          {
            foreignKeyName: "learning_rule_revocations_revoked_by_fkey"
            columns: ["revoked_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "learning_rule_revocations_rule_id_fkey"
            columns: ["rule_id"]
            isOneToOne: false
            referencedRelation: "learning_rules"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_rule_versions: {
        Row: {
          change_reason: string
          created_at: string
          id: string
          rule_id: string
          rule_payload: Json
          status: Database["public"]["Enums"]["learning_rule_status"]
          version: number
        }
        Insert: {
          change_reason: string
          created_at?: string
          id?: string
          rule_id: string
          rule_payload: Json
          status?: Database["public"]["Enums"]["learning_rule_status"]
          version: number
        }
        Update: {
          change_reason?: string
          created_at?: string
          id?: string
          rule_id?: string
          rule_payload?: Json
          status?: Database["public"]["Enums"]["learning_rule_status"]
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "learning_rule_versions_rule_id_fkey"
            columns: ["rule_id"]
            isOneToOne: false
            referencedRelation: "learning_rules"
            referencedColumns: ["id"]
          },
        ]
      }
      learning_rules: {
        Row: {
          active_version: number
          affected_district: string | null
          affected_problem: string | null
          affected_service: Database["public"]["Enums"]["service_type"] | null
          confidence: number
          created_at: string
          evidence_count: number
          id: string
          rollback_available: boolean
          rule_payload: Json
          rule_type: string
          status: Database["public"]["Enums"]["learning_rule_status"]
          updated_at: string
        }
        Insert: {
          active_version?: number
          affected_district?: string | null
          affected_problem?: string | null
          affected_service?: Database["public"]["Enums"]["service_type"] | null
          confidence?: number
          created_at?: string
          evidence_count?: number
          id?: string
          rollback_available?: boolean
          rule_payload?: Json
          rule_type: string
          status?: Database["public"]["Enums"]["learning_rule_status"]
          updated_at?: string
        }
        Update: {
          active_version?: number
          affected_district?: string | null
          affected_problem?: string | null
          affected_service?: Database["public"]["Enums"]["service_type"] | null
          confidence?: number
          created_at?: string
          evidence_count?: number
          id?: string
          rollback_available?: boolean
          rule_payload?: Json
          rule_type?: string
          status?: Database["public"]["Enums"]["learning_rule_status"]
          updated_at?: string
        }
        Relationships: []
      }
/* @slice:end tables:learning */
}
