// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type MatchingTables = {
/* @slice:begin tables:matching */
      confirmation_operation_receipts: {
        Row: {
          created_at: string
          id: string
          operation_id: string
          request_fingerprint: string
          response_snapshot: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          operation_id: string
          request_fingerprint: string
          response_snapshot?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          operation_id?: string
          request_fingerprint?: string
          response_snapshot?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "confirmation_operation_receipts_operation_id_fkey"
            columns: ["operation_id"]
            isOneToOne: true
            referencedRelation: "confirmation_operations"
            referencedColumns: ["id"]
          },
        ]
      }
      confirmation_operations: {
        Row: {
          accepted_at: string
          confirmation_kind: string
          customer_id: string
          id: string
          idempotency_key: string
          job_id: string | null
          last_error_code: string | null
          quote_mode: Database["public"]["Enums"]["service_quote_mode"]
          release_metadata: Json
          retry_after_ms: number | null
          session_id: string
          state: string
          support_code: string
          synthetic_cohort_id: string | null
          updated_at: string
        }
        Insert: {
          accepted_at?: string
          confirmation_kind: string
          customer_id: string
          id?: string
          idempotency_key: string
          job_id?: string | null
          last_error_code?: string | null
          quote_mode: Database["public"]["Enums"]["service_quote_mode"]
          release_metadata?: Json
          retry_after_ms?: number | null
          session_id: string
          state: string
          support_code: string
          synthetic_cohort_id?: string | null
          updated_at?: string
        }
        Update: {
          accepted_at?: string
          confirmation_kind?: string
          customer_id?: string
          id?: string
          idempotency_key?: string
          job_id?: string | null
          last_error_code?: string | null
          quote_mode?: Database["public"]["Enums"]["service_quote_mode"]
          release_metadata?: Json
          retry_after_ms?: number | null
          session_id?: string
          state?: string
          support_code?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "confirmation_operations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_overview"
            referencedColumns: ["customer_id"]
          },
          {
            foreignKeyName: "confirmation_operations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "confirmation_operations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "confirmation_operations_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "kael_chat_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      matching_operations: {
        Row: {
          confirmation_operation_id: string | null
          created_at: string
          id: string
          job_id: string
          state: string
          synthetic_cohort_id: string | null
          updated_at: string
        }
        Insert: {
          confirmation_operation_id?: string | null
          created_at?: string
          id?: string
          job_id: string
          state?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
        }
        Update: {
          confirmation_operation_id?: string | null
          created_at?: string
          id?: string
          job_id?: string
          state?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "matching_operations_confirmation_operation_id_fkey"
            columns: ["confirmation_operation_id"]
            isOneToOne: false
            referencedRelation: "confirmation_operations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matching_operations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      matching_push_provider_tickets: {
        Row: {
          app_acknowledged_at: string | null
          created_at: string
          device_push_token_id: string
          device_push_token_updated_at: string
          id: string
          last_receipt_check_at: string | null
          matching_delivery_id: string
          next_receipt_check_at: string
          provider_error_code: string | null
          provider_receipt_at: string | null
          provider_status: string
          provider_ticket_id: string
          receipt_attempt_count: number
          token_generation_current_at_receipt: boolean | null
          updated_at: string
        }
        Insert: {
          app_acknowledged_at?: string | null
          created_at?: string
          device_push_token_id: string
          device_push_token_updated_at: string
          id?: string
          last_receipt_check_at?: string | null
          matching_delivery_id: string
          next_receipt_check_at?: string
          provider_error_code?: string | null
          provider_receipt_at?: string | null
          provider_status?: string
          provider_ticket_id: string
          receipt_attempt_count?: number
          token_generation_current_at_receipt?: boolean | null
          updated_at?: string
        }
        Update: {
          app_acknowledged_at?: string | null
          created_at?: string
          device_push_token_id?: string
          device_push_token_updated_at?: string
          id?: string
          last_receipt_check_at?: string | null
          matching_delivery_id?: string
          next_receipt_check_at?: string
          provider_error_code?: string | null
          provider_receipt_at?: string | null
          provider_status?: string
          provider_ticket_id?: string
          receipt_attempt_count?: number
          token_generation_current_at_receipt?: boolean | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "matching_push_provider_tickets_device_push_token_id_fkey"
            columns: ["device_push_token_id"]
            isOneToOne: false
            referencedRelation: "device_push_tokens"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matching_push_provider_tickets_matching_delivery_id_fkey"
            columns: ["matching_delivery_id"]
            isOneToOne: false
            referencedRelation: "matching_recipient_deliveries"
            referencedColumns: ["id"]
          },
        ]
      }
      matching_recipient_deliveries: {
        Row: {
          accepted_at: string | null
          broadcast_id: string
          created_at: string
          delivered_at: string | null
          expires_at: string
          id: string
          job_id: string
          operation_id: string
          seen_at: string | null
          status: string
          synthetic_cohort_id: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          accepted_at?: string | null
          broadcast_id: string
          created_at?: string
          delivered_at?: string | null
          expires_at?: string
          id?: string
          job_id: string
          operation_id: string
          seen_at?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          accepted_at?: string | null
          broadcast_id?: string
          created_at?: string
          delivered_at?: string | null
          expires_at?: string
          id?: string
          job_id?: string
          operation_id?: string
          seen_at?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "matching_recipient_deliveries_broadcast_id_fkey"
            columns: ["broadcast_id"]
            isOneToOne: true
            referencedRelation: "job_broadcasts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matching_recipient_deliveries_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matching_recipient_deliveries_operation_id_fkey"
            columns: ["operation_id"]
            isOneToOne: false
            referencedRelation: "matching_operations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matching_recipient_deliveries_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "matching_recipient_deliveries_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      synthetic_matching_cohort_members: {
        Row: {
          cohort_id: string
          created_at: string
          member_role: Database["public"]["Enums"]["user_role"]
          profile_id: string
        }
        Insert: {
          cohort_id: string
          created_at?: string
          member_role: Database["public"]["Enums"]["user_role"]
          profile_id: string
        }
        Update: {
          cohort_id?: string
          created_at?: string
          member_role?: Database["public"]["Enums"]["user_role"]
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "synthetic_matching_cohort_members_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
          {
            foreignKeyName: "synthetic_matching_cohort_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      synthetic_matching_cohorts: {
        Row: {
          cohort_id: string
          created_at: string
        }
        Insert: {
          cohort_id: string
          created_at?: string
        }
        Update: {
          cohort_id?: string
          created_at?: string
        }
        Relationships: []
      }
      workflow_outbox: {
        Row: {
          attempt_count: number
          created_at: string
          dead_lettered_at: string | null
          event_type: string
          id: string
          last_error_code: string | null
          lease_expires_at: string | null
          lease_token: string | null
          leased_by: string | null
          next_attempt_at: string
          operation_id: string
          safe_payload: Json
          status: string
          updated_at: string
        }
        Insert: {
          attempt_count?: number
          created_at?: string
          dead_lettered_at?: string | null
          event_type: string
          id?: string
          last_error_code?: string | null
          lease_expires_at?: string | null
          lease_token?: string | null
          leased_by?: string | null
          next_attempt_at?: string
          operation_id: string
          safe_payload?: Json
          status?: string
          updated_at?: string
        }
        Update: {
          attempt_count?: number
          created_at?: string
          dead_lettered_at?: string | null
          event_type?: string
          id?: string
          last_error_code?: string | null
          lease_expires_at?: string | null
          lease_token?: string | null
          leased_by?: string | null
          next_attempt_at?: string
          operation_id?: string
          safe_payload?: Json
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workflow_outbox_operation_id_fkey"
            columns: ["operation_id"]
            isOneToOne: false
            referencedRelation: "confirmation_operations"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:matching */
}
