// @generated by scripts/split-database-types.mjs — do not edit by hand

export type ProgramTables = {
/* @slice:begin tables:program */
      ambassador_milestones: {
        Row: {
          id: string
          points_required: number
          rank: number
          reward_vnd: number
          title_en: string
          title_vi: string
          version_id: string
        }
        Insert: {
          id?: string
          points_required: number
          rank: number
          reward_vnd: number
          title_en: string
          title_vi: string
          version_id: string
        }
        Update: {
          id?: string
          points_required?: number
          rank?: number
          reward_vnd?: number
          title_en?: string
          title_vi?: string
          version_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ambassador_milestones_version_id_fkey"
            columns: ["version_id"]
            isOneToOne: false
            referencedRelation: "ambassador_program_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      ambassador_multiplier_tiers: {
        Row: {
          id: string
          min_active_customers: number
          multiplier_bps: number
          version_id: string
        }
        Insert: {
          id?: string
          min_active_customers: number
          multiplier_bps: number
          version_id: string
        }
        Update: {
          id?: string
          min_active_customers?: number
          multiplier_bps?: number
          version_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ambassador_multiplier_tiers_version_id_fkey"
            columns: ["version_id"]
            isOneToOne: false
            referencedRelation: "ambassador_program_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      ambassador_program_versions: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          commission_vnd_per_point: number
          created_at: string
          created_by: string | null
          customer_vnd_per_point: number
          id: string
          invite_claim_days: number
          link_months: number
          network_window_days: number
          rebook_min_jobs: number
          retired_at: string | null
          status: string
          updated_at: string
          version: number
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          commission_vnd_per_point: number
          created_at?: string
          created_by?: string | null
          customer_vnd_per_point: number
          id?: string
          invite_claim_days: number
          link_months: number
          network_window_days: number
          rebook_min_jobs: number
          retired_at?: string | null
          status?: string
          updated_at?: string
          version: number
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          commission_vnd_per_point?: number
          created_at?: string
          created_by?: string | null
          customer_vnd_per_point?: number
          id?: string
          invite_claim_days?: number
          link_months?: number
          network_window_days?: number
          rebook_min_jobs?: number
          retired_at?: string | null
          status?: string
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "ambassador_program_versions_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ambassador_program_versions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      compensation_negotiations: {
        Row: {
          agreed_at: string | null
          case_id: string
          created_at: string
          current_amount_vnd: number
          customer_id: string
          evidence_paths: string[]
          id: string
          offers_count: number
          respond_by: string
          status: string
          updated_at: string
          worker_id: string
        }
        Insert: {
          agreed_at?: string | null
          case_id: string
          created_at?: string
          current_amount_vnd: number
          customer_id: string
          evidence_paths?: string[]
          id?: string
          offers_count?: number
          respond_by: string
          status?: string
          updated_at?: string
          worker_id: string
        }
        Update: {
          agreed_at?: string | null
          case_id?: string
          created_at?: string
          current_amount_vnd?: number
          customer_id?: string
          evidence_paths?: string[]
          id?: string
          offers_count?: number
          respond_by?: string
          status?: string
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "compensation_negotiations_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: true
            referencedRelation: "worker_violation_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compensation_negotiations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compensation_negotiations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "compensation_negotiations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      compensation_offers: {
        Row: {
          action: string
          actor_role: string
          amount_vnd: number | null
          created_at: string
          id: string
          negotiation_id: string
          note: string | null
        }
        Insert: {
          action: string
          actor_role: string
          amount_vnd?: number | null
          created_at?: string
          id?: string
          negotiation_id: string
          note?: string | null
        }
        Update: {
          action?: string
          actor_role?: string
          amount_vnd?: number | null
          created_at?: string
          id?: string
          negotiation_id?: string
          note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "compensation_offers_negotiation_id_fkey"
            columns: ["negotiation_id"]
            isOneToOne: false
            referencedRelation: "compensation_negotiations"
            referencedColumns: ["id"]
          },
        ]
      }
      identity_blocklist: {
        Row: {
          case_id: string | null
          created_at: string
          created_by: string
          id: string
          kind: string
          lift_reason: string | null
          lifted_at: string | null
          lifted_by: string | null
          value_hmac: string
        }
        Insert: {
          case_id?: string | null
          created_at?: string
          created_by: string
          id?: string
          kind: string
          lift_reason?: string | null
          lifted_at?: string | null
          lifted_by?: string | null
          value_hmac: string
        }
        Update: {
          case_id?: string | null
          created_at?: string
          created_by?: string
          id?: string
          kind?: string
          lift_reason?: string | null
          lifted_at?: string | null
          lifted_by?: string | null
          value_hmac?: string
        }
        Relationships: [
          {
            foreignKeyName: "identity_blocklist_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "worker_violation_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "identity_blocklist_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "identity_blocklist_lifted_by_fkey"
            columns: ["lifted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      program_accrual_marks: {
        Row: {
          accrued_worker_id: string | null
          job_id: string
          link_id: string | null
          membership_points: number
          points_milli: number
          processed_at: string
          reversed_at: string | null
          source_ledger_id: string
        }
        Insert: {
          accrued_worker_id?: string | null
          job_id: string
          link_id?: string | null
          membership_points?: number
          points_milli?: number
          processed_at?: string
          reversed_at?: string | null
          source_ledger_id: string
        }
        Update: {
          accrued_worker_id?: string | null
          job_id?: string
          link_id?: string | null
          membership_points?: number
          points_milli?: number
          processed_at?: string
          reversed_at?: string | null
          source_ledger_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "program_accrual_marks_accrued_worker_id_fkey"
            columns: ["accrued_worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "program_accrual_marks_accrued_worker_id_fkey"
            columns: ["accrued_worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "program_accrual_marks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "program_accrual_marks_link_id_fkey"
            columns: ["link_id"]
            isOneToOne: false
            referencedRelation: "customer_worker_links"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "program_accrual_marks_source_ledger_id_fkey"
            columns: ["source_ledger_id"]
            isOneToOne: true
            referencedRelation: "worker_payment_ledger"
            referencedColumns: ["id"]
          },
        ]
      }
      program_push_receipts: {
        Row: {
          claimed_at: string
          notification_id: string
        }
        Insert: {
          claimed_at?: string
          notification_id: string
        }
        Update: {
          claimed_at?: string
          notification_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "program_push_receipts_notification_id_fkey"
            columns: ["notification_id"]
            isOneToOne: true
            referencedRelation: "notifications"
            referencedColumns: ["id"]
          },
        ]
      }
      referral_claim_attempts: {
        Row: {
          code_entered: string
          created_at: string
          customer_id: string
          id: string
          outcome: string
        }
        Insert: {
          code_entered: string
          created_at?: string
          customer_id: string
          id?: string
          outcome: string
        }
        Update: {
          code_entered?: string
          created_at?: string
          customer_id?: string
          id?: string
          outcome?: string
        }
        Relationships: [
          {
            foreignKeyName: "referral_claim_attempts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:program */
}
