// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type ServiceTables = {
/* @slice:begin tables:service */
      service_categories: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          label_vi: string
          service_type: Database["public"]["Enums"]["service_type"]
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          label_vi: string
          service_type: Database["public"]["Enums"]["service_type"]
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          label_vi?: string
          service_type?: Database["public"]["Enums"]["service_type"]
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      service_knowledge_boxes: {
        Row: {
          created_at: string
          embedding: string | null
          embedding_model: string | null
          embedding_text: string | null
          embedding_updated_at: string | null
          id: string
          is_active: boolean
          label_vi: string
          purpose: string
          safe_metadata: Json
          service_type: Database["public"]["Enums"]["service_type"]
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          embedding?: string | null
          embedding_model?: string | null
          embedding_text?: string | null
          embedding_updated_at?: string | null
          id?: string
          is_active?: boolean
          label_vi: string
          purpose: string
          safe_metadata?: Json
          service_type: Database["public"]["Enums"]["service_type"]
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          embedding?: string | null
          embedding_model?: string | null
          embedding_text?: string | null
          embedding_updated_at?: string | null
          id?: string
          is_active?: boolean
          label_vi?: string
          purpose?: string
          safe_metadata?: Json
          service_type?: Database["public"]["Enums"]["service_type"]
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      service_problems: {
        Row: {
          created_at: string
          default_complexity: Database["public"]["Enums"]["complexity_level"]
          id: string
          is_active: boolean
          label_vi: string
          service_category_id: string
          service_type: Database["public"]["Enums"]["service_type"]
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          default_complexity?: Database["public"]["Enums"]["complexity_level"]
          id?: string
          is_active?: boolean
          label_vi: string
          service_category_id: string
          service_type: Database["public"]["Enums"]["service_type"]
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          default_complexity?: Database["public"]["Enums"]["complexity_level"]
          id?: string
          is_active?: boolean
          label_vi?: string
          service_category_id?: string
          service_type?: Database["public"]["Enums"]["service_type"]
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_problems_service_category_id_fkey"
            columns: ["service_category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:service */
}
