// @generated by scripts/split-database-types.mjs — do not edit by hand

import type { Json } from '../base.database.types'
import type { Database } from '../schema.database.types'

export type WorkerTables = {
/* @slice:begin tables:worker */
      worker_account_deletion_requests: {
        Row: {
          checkpoint: string
          client_request_id: string
          completed_at: string | null
          created_at: string
          database_scrubbed_at: string | null
          id: string
          requested_at: string
          status: string
          storage_refs: string[]
          updated_at: string
          worker_id: string
        }
        Insert: {
          checkpoint?: string
          client_request_id: string
          completed_at?: string | null
          created_at?: string
          database_scrubbed_at?: string | null
          id?: string
          requested_at?: string
          status?: string
          storage_refs?: string[]
          updated_at?: string
          worker_id: string
        }
        Update: {
          checkpoint?: string
          client_request_id?: string
          completed_at?: string | null
          created_at?: string
          database_scrubbed_at?: string | null
          id?: string
          requested_at?: string
          status?: string
          storage_refs?: string[]
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_account_deletion_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_ambassador_point_entries: {
        Row: {
          actor_id: string | null
          case_id: string | null
          commission_basis_vnd: number | null
          created_at: string
          customer_id: string | null
          entry_kind: string
          id: string
          idempotency_key: string
          job_id: string | null
          link_id: string | null
          multiplier_bps: number | null
          points_milli: number
          program_version_id: string | null
          reason: string | null
          redemption_id: string | null
          source_ledger_id: string | null
          worker_id: string
        }
        Insert: {
          actor_id?: string | null
          case_id?: string | null
          commission_basis_vnd?: number | null
          created_at?: string
          customer_id?: string | null
          entry_kind: string
          id?: string
          idempotency_key: string
          job_id?: string | null
          link_id?: string | null
          multiplier_bps?: number | null
          points_milli: number
          program_version_id?: string | null
          reason?: string | null
          redemption_id?: string | null
          source_ledger_id?: string | null
          worker_id: string
        }
        Update: {
          actor_id?: string | null
          case_id?: string | null
          commission_basis_vnd?: number | null
          created_at?: string
          customer_id?: string | null
          entry_kind?: string
          id?: string
          idempotency_key?: string
          job_id?: string | null
          link_id?: string | null
          multiplier_bps?: number | null
          points_milli?: number
          program_version_id?: string | null
          reason?: string | null
          redemption_id?: string | null
          source_ledger_id?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_ambassador_point_entries_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_ambassador_point_entries_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_ambassador_point_entries_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_ambassador_point_entries_link_id_fkey"
            columns: ["link_id"]
            isOneToOne: false
            referencedRelation: "customer_worker_links"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_ambassador_point_entries_program_version_id_fkey"
            columns: ["program_version_id"]
            isOneToOne: false
            referencedRelation: "ambassador_program_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_ambassador_point_entries_source_ledger_id_fkey"
            columns: ["source_ledger_id"]
            isOneToOne: false
            referencedRelation: "worker_payment_ledger"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_ambassador_point_entries_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_ambassador_point_entries_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_bonus_clawbacks: {
        Row: {
          amount_vnd: number
          case_id: string | null
          clawback_kind: string
          created_at: string
          decided_by: string
          id: string
          reason: string
          receivable_vnd: number
          redemption_id: string
          reverses_clawback_id: string | null
          worker_id: string
        }
        Insert: {
          amount_vnd: number
          case_id?: string | null
          clawback_kind?: string
          created_at?: string
          decided_by: string
          id?: string
          reason: string
          receivable_vnd?: number
          redemption_id: string
          reverses_clawback_id?: string | null
          worker_id: string
        }
        Update: {
          amount_vnd?: number
          case_id?: string | null
          clawback_kind?: string
          created_at?: string
          decided_by?: string
          id?: string
          reason?: string
          receivable_vnd?: number
          redemption_id?: string
          reverses_clawback_id?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_bonus_clawbacks_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_bonus_clawbacks_redemption_id_fkey"
            columns: ["redemption_id"]
            isOneToOne: false
            referencedRelation: "worker_bonus_redemptions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_bonus_clawbacks_reverses_clawback_id_fkey"
            columns: ["reverses_clawback_id"]
            isOneToOne: true
            referencedRelation: "worker_bonus_clawbacks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_bonus_clawbacks_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_bonus_clawbacks_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_bonus_redemptions: {
        Row: {
          client_request_id: string
          created_at: string
          id: string
          milestone_id: string
          net_vnd: number
          points_milli: number
          program_version_id: string
          reward_vnd: number
          tax_policy_id: string
          tax_withheld_vnd: number
          worker_id: string
        }
        Insert: {
          client_request_id: string
          created_at?: string
          id?: string
          milestone_id: string
          net_vnd: number
          points_milli: number
          program_version_id: string
          reward_vnd: number
          tax_policy_id: string
          tax_withheld_vnd: number
          worker_id: string
        }
        Update: {
          client_request_id?: string
          created_at?: string
          id?: string
          milestone_id?: string
          net_vnd?: number
          points_milli?: number
          program_version_id?: string
          reward_vnd?: number
          tax_policy_id?: string
          tax_withheld_vnd?: number
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_bonus_redemptions_milestone_id_fkey"
            columns: ["milestone_id"]
            isOneToOne: false
            referencedRelation: "ambassador_milestones"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_bonus_redemptions_program_version_id_fkey"
            columns: ["program_version_id"]
            isOneToOne: false
            referencedRelation: "ambassador_program_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_bonus_redemptions_tax_policy_id_fkey"
            columns: ["tax_policy_id"]
            isOneToOne: false
            referencedRelation: "admin_finance_tax_policies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_bonus_redemptions_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_bonus_redemptions_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_cancellation_reason_taxonomy: {
        Row: {
          admin_tunable: boolean
          category: string
          code: string
          created_at: string
          is_active: boolean
          label_vi: string
          safe_metadata: Json
          sort_order: number
          updated_at: string
        }
        Insert: {
          admin_tunable?: boolean
          category: string
          code: string
          created_at?: string
          is_active?: boolean
          label_vi: string
          safe_metadata?: Json
          sort_order?: number
          updated_at?: string
        }
        Update: {
          admin_tunable?: boolean
          category?: string
          code?: string
          created_at?: string
          is_active?: boolean
          label_vi?: string
          safe_metadata?: Json
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      worker_cancellation_requests: {
        Row: {
          abuse_signals: string[]
          admin_decision_at: string | null
          admin_decision_by: string | null
          admin_review_required: boolean
          created_at: string
          evidence_photo_urls: string[]
          fallback_options: Json
          id: string
          job_id: string
          kael_review: Json | null
          reason: string
          reason_category: string | null
          reason_code: string | null
          review_note: string | null
          status: string
          updated_at: string
          worker_id: string
        }
        Insert: {
          abuse_signals?: string[]
          admin_decision_at?: string | null
          admin_decision_by?: string | null
          admin_review_required?: boolean
          created_at?: string
          evidence_photo_urls?: string[]
          fallback_options?: Json
          id?: string
          job_id: string
          kael_review?: Json | null
          reason: string
          reason_category?: string | null
          reason_code?: string | null
          review_note?: string | null
          status?: string
          updated_at?: string
          worker_id: string
        }
        Update: {
          abuse_signals?: string[]
          admin_decision_at?: string | null
          admin_decision_by?: string | null
          admin_review_required?: boolean
          created_at?: string
          evidence_photo_urls?: string[]
          fallback_options?: Json
          id?: string
          job_id?: string
          kael_review?: Json | null
          reason?: string
          reason_category?: string | null
          reason_code?: string | null
          review_note?: string | null
          status?: string
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_cancellation_requests_admin_decision_by_fkey"
            columns: ["admin_decision_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_cancellation_requests_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_cancellation_requests_reason_code_fkey"
            columns: ["reason_code"]
            isOneToOne: false
            referencedRelation: "worker_cancellation_reason_taxonomy"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "worker_cancellation_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_cash_commission_ledger: {
        Row: {
          cash_commission_collected: number
          cash_commission_due: number
          commission_level: number
          commission_rate_bps: number
          confirmed_at: string
          created_at: string
          gross_amount: number
          id: string
          job_id: string
          platform_fee: number
          worker_id: string
          worker_net: number
        }
        Insert: {
          cash_commission_collected: number
          cash_commission_due: number
          commission_level: number
          commission_rate_bps: number
          confirmed_at?: string
          created_at?: string
          gross_amount: number
          id?: string
          job_id: string
          platform_fee: number
          worker_id: string
          worker_net: number
        }
        Update: {
          cash_commission_collected?: number
          cash_commission_due?: number
          commission_level?: number
          commission_rate_bps?: number
          confirmed_at?: string
          created_at?: string
          gross_amount?: number
          id?: string
          job_id?: string
          platform_fee?: number
          worker_id?: string
          worker_net?: number
        }
        Relationships: [
          {
            foreignKeyName: "worker_cash_commission_ledger_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_cash_commission_ledger_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_cash_commission_ledger_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_cash_commission_reconciliations: {
        Row: {
          amount: number
          cash_commission_ledger_id: string
          created_at: string
          id: string
          reconciled_at: string
          worker_id: string
        }
        Insert: {
          amount: number
          cash_commission_ledger_id: string
          created_at?: string
          id?: string
          reconciled_at?: string
          worker_id: string
        }
        Update: {
          amount?: number
          cash_commission_ledger_id?: string
          created_at?: string
          id?: string
          reconciled_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_cash_commission_reconcili_cash_commission_ledger_id_fkey"
            columns: ["cash_commission_ledger_id"]
            isOneToOne: false
            referencedRelation: "worker_cash_commission_ledger"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_cash_commission_reconciliations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_cash_commission_reconciliations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_commission_tiers: {
        Row: {
          commission_rate_bps: number
          created_at: string
          is_active: boolean
          level: number
          min_average_rating: number
          min_completed_jobs: number
          updated_at: string
        }
        Insert: {
          commission_rate_bps: number
          created_at?: string
          is_active?: boolean
          level: number
          min_average_rating: number
          min_completed_jobs: number
          updated_at?: string
        }
        Update: {
          commission_rate_bps?: number
          created_at?: string
          is_active?: boolean
          level?: number
          min_average_rating?: number
          min_completed_jobs?: number
          updated_at?: string
        }
        Relationships: []
      }
      worker_compensation_payouts: {
        Row: {
          amount_vnd: number
          case_id: string
          created_at: string
          customer_id: string
          id: string
          negotiation_id: string
          paid_at: string | null
          paid_by: string | null
          status: string
          transfer_reference: string | null
          worker_id: string
        }
        Insert: {
          amount_vnd: number
          case_id: string
          created_at?: string
          customer_id: string
          id?: string
          negotiation_id: string
          paid_at?: string | null
          paid_by?: string | null
          status?: string
          transfer_reference?: string | null
          worker_id: string
        }
        Update: {
          amount_vnd?: number
          case_id?: string
          created_at?: string
          customer_id?: string
          id?: string
          negotiation_id?: string
          paid_at?: string | null
          paid_by?: string | null
          status?: string
          transfer_reference?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_compensation_payouts_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "worker_violation_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_compensation_payouts_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_compensation_payouts_negotiation_id_fkey"
            columns: ["negotiation_id"]
            isOneToOne: true
            referencedRelation: "compensation_negotiations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_compensation_payouts_paid_by_fkey"
            columns: ["paid_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_compensation_payouts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_compensation_payouts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_direct_payment_collateral_reservations: {
        Row: {
          collateral_amount: number
          created_at: string
          held_at: string
          id: string
          job_id: string
          payment_order_id: string
          resolved_at: string | null
          resolved_by: string | null
          status: string
          updated_at: string
          worker_id: string
        }
        Insert: {
          collateral_amount: number
          created_at?: string
          held_at?: string
          id?: string
          job_id: string
          payment_order_id: string
          resolved_at?: string | null
          resolved_by?: string | null
          status: string
          updated_at?: string
          worker_id: string
        }
        Update: {
          collateral_amount?: number
          created_at?: string
          held_at?: string
          id?: string
          job_id?: string
          payment_order_id?: string
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_direct_payment_collateral_reservat_payment_order_id_fkey"
            columns: ["payment_order_id"]
            isOneToOne: true
            referencedRelation: "job_payment_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_direct_payment_collateral_reservations_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_direct_payment_collateral_reservations_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_direct_payment_collateral_reservations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_direct_payment_collateral_reservations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_discipline_entries: {
        Row: {
          actor_id: string | null
          case_id: string
          created_at: string
          detail: Json
          effective_from: string
          effective_until: string | null
          entry_kind: string
          id: string
          restores_entry_id: string | null
          worker_id: string
        }
        Insert: {
          actor_id?: string | null
          case_id: string
          created_at?: string
          detail?: Json
          effective_from?: string
          effective_until?: string | null
          entry_kind: string
          id?: string
          restores_entry_id?: string | null
          worker_id: string
        }
        Update: {
          actor_id?: string | null
          case_id?: string
          created_at?: string
          detail?: Json
          effective_from?: string
          effective_until?: string | null
          entry_kind?: string
          id?: string
          restores_entry_id?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_discipline_entries_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_discipline_entries_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "worker_violation_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_discipline_entries_restores_entry_id_fkey"
            columns: ["restores_entry_id"]
            isOneToOne: true
            referencedRelation: "worker_discipline_entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_discipline_entries_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_discipline_entries_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_discipline_policy: {
        Row: {
          appeal_window_days: number
          compensation_max_offers: number
          compensation_max_vnd: number
          compensation_min_vnd: number
          compensation_response_days: number
          decision_deadline_hours: number
          id: number
          l1_matching_days: number
          l2_network_freeze_days: number
          l2_points_debit: number
          l3_freeze_days: number
          late_arrival_grace_minutes: number
          no_show_grace_minutes: number
          off_app_evidence_threshold: number
          off_app_window_days: number
          reply_nudge_minutes: number
          strike_window_months: number
          updated_at: string
          withdrawal_hold_days: number
        }
        Insert: {
          appeal_window_days: number
          compensation_max_offers?: number
          compensation_max_vnd?: number
          compensation_min_vnd?: number
          compensation_response_days?: number
          decision_deadline_hours: number
          id?: number
          l1_matching_days: number
          l2_network_freeze_days: number
          l2_points_debit: number
          l3_freeze_days: number
          late_arrival_grace_minutes: number
          no_show_grace_minutes: number
          off_app_evidence_threshold: number
          off_app_window_days: number
          reply_nudge_minutes: number
          strike_window_months: number
          updated_at?: string
          withdrawal_hold_days: number
        }
        Update: {
          appeal_window_days?: number
          compensation_max_offers?: number
          compensation_max_vnd?: number
          compensation_min_vnd?: number
          compensation_response_days?: number
          decision_deadline_hours?: number
          id?: number
          l1_matching_days?: number
          l2_network_freeze_days?: number
          l2_points_debit?: number
          l3_freeze_days?: number
          late_arrival_grace_minutes?: number
          no_show_grace_minutes?: number
          off_app_evidence_threshold?: number
          off_app_window_days?: number
          reply_nudge_minutes?: number
          strike_window_months?: number
          updated_at?: string
          withdrawal_hold_days?: number
        }
        Relationships: []
      }
      worker_identity_numbers: {
        Row: {
          cccd_hmac: string
          cccd_last4: string
          email_hmac: string | null
          entered_at: string
          entered_by: string
          phone_hmac: string | null
          worker_id: string
        }
        Insert: {
          cccd_hmac: string
          cccd_last4: string
          email_hmac?: string | null
          entered_at?: string
          entered_by: string
          phone_hmac?: string | null
          worker_id: string
        }
        Update: {
          cccd_hmac?: string
          cccd_last4?: string
          email_hmac?: string | null
          entered_at?: string
          entered_by?: string
          phone_hmac?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_identity_numbers_entered_by_fkey"
            columns: ["entered_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_identity_numbers_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_identity_numbers_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_kael_feedback: {
        Row: {
          created_at: string
          id: string
          language: string
          rating: string | null
          raw_message: string
          reason_scrubbed: string | null
          response_id: string | null
          safe_metadata: Json
          scrubbed_message: string
          source: string
          status: string
          updated_at: string
          worker_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          language?: string
          rating?: string | null
          raw_message: string
          reason_scrubbed?: string | null
          response_id?: string | null
          safe_metadata?: Json
          scrubbed_message: string
          source?: string
          status?: string
          updated_at?: string
          worker_id: string
        }
        Update: {
          created_at?: string
          id?: string
          language?: string
          rating?: string | null
          raw_message?: string
          reason_scrubbed?: string | null
          response_id?: string | null
          safe_metadata?: Json
          scrubbed_message?: string
          source?: string
          status?: string
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_kael_feedback_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_kael_memory: {
        Row: {
          archived_at: string | null
          created_at: string
          language: string
          last_observed_at: string | null
          memory_version: number
          red_flags: Json
          reliability_signals: Json
          safe_metadata: Json
          service_skill_proficiency: Json
          service_skill_summary: string
          updated_at: string
          worker_id: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          language?: string
          last_observed_at?: string | null
          memory_version?: number
          red_flags?: Json
          reliability_signals?: Json
          safe_metadata?: Json
          service_skill_proficiency?: Json
          service_skill_summary?: string
          updated_at?: string
          worker_id: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          language?: string
          last_observed_at?: string | null
          memory_version?: number
          red_flags?: Json
          reliability_signals?: Json
          safe_metadata?: Json
          service_skill_proficiency?: Json
          service_skill_summary?: string
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_kael_memory_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_kael_training_consent: {
        Row: {
          created_at: string
          language: string
          safe_metadata: Json
          source: string
          training_consent: boolean
          updated_at: string
          worker_id: string
        }
        Insert: {
          created_at?: string
          language?: string
          safe_metadata?: Json
          source?: string
          training_consent?: boolean
          updated_at?: string
          worker_id: string
        }
        Update: {
          created_at?: string
          language?: string
          safe_metadata?: Json
          source?: string
          training_consent?: boolean
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_kael_training_consent_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_matching_proposals: {
        Row: {
          broadcast_id: string
          candidate_id: string
          created_at: string
          id: string
          job_id: string
          price_max: number | null
          price_min: number | null
          scope_summary: string
          status: string
          synthetic_cohort_id: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          broadcast_id: string
          candidate_id: string
          created_at?: string
          id?: string
          job_id: string
          price_max?: number | null
          price_min?: number | null
          scope_summary: string
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          broadcast_id?: string
          candidate_id?: string
          created_at?: string
          id?: string
          job_id?: string
          price_max?: number | null
          price_min?: number | null
          scope_summary?: string
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_matching_proposals_broadcast_id_fkey"
            columns: ["broadcast_id"]
            isOneToOne: true
            referencedRelation: "job_broadcasts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_matching_proposals_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: true
            referencedRelation: "job_worker_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_matching_proposals_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_matching_proposals_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_matching_proposals_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_payment_ledger: {
        Row: {
          available_at: string | null
          commission_level: number
          commission_rate_bps: number
          created_at: string
          gross_amount: number
          id: string
          job_id: string
          payment_provider: string
          payment_state: string
          platform_fee: number
          settlement_state: string
          updated_at: string
          worker_id: string
          worker_net: number
        }
        Insert: {
          available_at?: string | null
          commission_level: number
          commission_rate_bps: number
          created_at?: string
          gross_amount: number
          id?: string
          job_id: string
          payment_provider: string
          payment_state: string
          platform_fee: number
          settlement_state?: string
          updated_at?: string
          worker_id: string
          worker_net: number
        }
        Update: {
          available_at?: string | null
          commission_level?: number
          commission_rate_bps?: number
          created_at?: string
          gross_amount?: number
          id?: string
          job_id?: string
          payment_provider?: string
          payment_state?: string
          platform_fee?: number
          settlement_state?: string
          updated_at?: string
          worker_id?: string
          worker_net?: number
        }
        Relationships: [
          {
            foreignKeyName: "worker_payment_ledger_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: true
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_payment_ledger_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_payment_ledger_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_payout_methods: {
        Row: {
          account_holder_name: string
          bank_account: string
          bank_account_masked: string
          bank_key: string
          bank_name: string
          created_at: string
          id: string
          is_default: boolean
          last_client_request_id: string | null
          review_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          synthetic_cohort_id: string | null
          updated_at: string
          version: number
          worker_id: string
        }
        Insert: {
          account_holder_name: string
          bank_account: string
          bank_account_masked: string
          bank_key: string
          bank_name: string
          created_at?: string
          id?: string
          is_default?: boolean
          last_client_request_id?: string | null
          review_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          version?: number
          worker_id: string
        }
        Update: {
          account_holder_name?: string
          bank_account?: string
          bank_account_masked?: string
          bank_key?: string
          bank_name?: string
          created_at?: string
          id?: string
          is_default?: boolean
          last_client_request_id?: string | null
          review_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          updated_at?: string
          version?: number
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_payout_methods_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_payout_methods_synthetic_cohort_id_fkey"
            columns: ["synthetic_cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
          {
            foreignKeyName: "worker_payout_methods_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_payout_methods_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_profiles: {
        Row: {
          active_service_types:
            | Database["public"]["Enums"]["service_type"][]
            | null
          app_active_minutes: number
          app_last_active_minute: string | null
          bank_account: string | null
          bank_name: string | null
          cccd_back_url: string | null
          cccd_front_url: string | null
          created_at: string
          date_of_birth: string | null
          districts: string[]
          gender: string | null
          home_lat: number | null
          home_lng: number | null
          id: string
          is_approved: boolean
          is_available: boolean
          is_suspended: boolean
          legal_name: string | null
          matching_foreground_active_until: string | null
          matching_push_proven_at: string | null
          problem_specializations: string[]
          rating: number
          selected_service_types: Database["public"]["Enums"]["service_type"][]
          selfie_url: string | null
          service_radius_km: number
          service_types: Database["public"]["Enums"]["service_type"][]
          suspended_until: string | null
          suspension_reason: string | null
          synthetic_cohort_id: string | null
          total_jobs: number
          updated_at: string
          verification_status: Database["public"]["Enums"]["worker_verification_status"]
          years_experience: number
        }
        Insert: {
          active_service_types?:
            | Database["public"]["Enums"]["service_type"][]
            | null
          app_active_minutes?: number
          app_last_active_minute?: string | null
          bank_account?: string | null
          bank_name?: string | null
          cccd_back_url?: string | null
          cccd_front_url?: string | null
          created_at?: string
          date_of_birth?: string | null
          districts?: string[]
          gender?: string | null
          home_lat?: number | null
          home_lng?: number | null
          id: string
          is_approved?: boolean
          is_available?: boolean
          is_suspended?: boolean
          legal_name?: string | null
          matching_foreground_active_until?: string | null
          matching_push_proven_at?: string | null
          problem_specializations?: string[]
          rating?: number
          selected_service_types?: Database["public"]["Enums"]["service_type"][]
          selfie_url?: string | null
          service_radius_km?: number
          service_types?: Database["public"]["Enums"]["service_type"][]
          suspended_until?: string | null
          suspension_reason?: string | null
          synthetic_cohort_id?: string | null
          total_jobs?: number
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["worker_verification_status"]
          years_experience?: number
        }
        Update: {
          active_service_types?:
            | Database["public"]["Enums"]["service_type"][]
            | null
          app_active_minutes?: number
          app_last_active_minute?: string | null
          bank_account?: string | null
          bank_name?: string | null
          cccd_back_url?: string | null
          cccd_front_url?: string | null
          created_at?: string
          date_of_birth?: string | null
          districts?: string[]
          gender?: string | null
          home_lat?: number | null
          home_lng?: number | null
          id?: string
          is_approved?: boolean
          is_available?: boolean
          is_suspended?: boolean
          legal_name?: string | null
          matching_foreground_active_until?: string | null
          matching_push_proven_at?: string | null
          problem_specializations?: string[]
          rating?: number
          selected_service_types?: Database["public"]["Enums"]["service_type"][]
          selfie_url?: string | null
          service_radius_km?: number
          service_types?: Database["public"]["Enums"]["service_type"][]
          suspended_until?: string | null
          suspension_reason?: string | null
          synthetic_cohort_id?: string | null
          total_jobs?: number
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["worker_verification_status"]
          years_experience?: number
        }
        Relationships: [
          {
            foreignKeyName: "worker_profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_referral_codes: {
        Row: {
          code: string
          created_at: string
          revoked_at: string | null
          worker_id: string
        }
        Insert: {
          code: string
          created_at?: string
          revoked_at?: string | null
          worker_id: string
        }
        Update: {
          code?: string
          created_at?: string
          revoked_at?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_referral_codes_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_referral_codes_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_registration_commands: {
        Row: {
          client_request_id: string
          draft_updated_at: string
          error_code: string | null
          operation_id: string
          outcome: string
          recorded_at: string
          submitted_at: string | null
          verification_status:
            | Database["public"]["Enums"]["worker_verification_status"]
            | null
          worker_id: string
        }
        Insert: {
          client_request_id: string
          draft_updated_at: string
          error_code?: string | null
          operation_id?: string
          outcome: string
          recorded_at?: string
          submitted_at?: string | null
          verification_status?:
            | Database["public"]["Enums"]["worker_verification_status"]
            | null
          worker_id: string
        }
        Update: {
          client_request_id?: string
          draft_updated_at?: string
          error_code?: string | null
          operation_id?: string
          outcome?: string
          recorded_at?: string
          submitted_at?: string | null
          verification_status?:
            | Database["public"]["Enums"]["worker_verification_status"]
            | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_registration_commands_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_reply_nudges: {
        Row: {
          customer_message_at: string
          customer_message_id: string
          id: string
          job_id: string
          job_status: string
          nudged_at: string
          worker_id: string
        }
        Insert: {
          customer_message_at: string
          customer_message_id: string
          id?: string
          job_id: string
          job_status: string
          nudged_at?: string
          worker_id: string
        }
        Update: {
          customer_message_at?: string
          customer_message_id?: string
          id?: string
          job_id?: string
          job_status?: string
          nudged_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_reply_nudges_customer_message_id_fkey"
            columns: ["customer_message_id"]
            isOneToOne: true
            referencedRelation: "chat_messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_reply_nudges_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_reply_nudges_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_reply_nudges_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_safety_patterns: {
        Row: {
          created_at: string
          embedding: string | null
          embedding_model: string | null
          embedding_text: string | null
          embedding_updated_at: string | null
          id: string
          is_enabled: boolean
          pattern_key: string
          response_guidance: string
          safe_metadata: Json
          service_type: string
          severity: string
          trigger_topic: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          embedding?: string | null
          embedding_model?: string | null
          embedding_text?: string | null
          embedding_updated_at?: string | null
          id?: string
          is_enabled?: boolean
          pattern_key: string
          response_guidance: string
          safe_metadata?: Json
          service_type: string
          severity?: string
          trigger_topic: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          embedding?: string | null
          embedding_model?: string | null
          embedding_text?: string | null
          embedding_updated_at?: string | null
          id?: string
          is_enabled?: boolean
          pattern_key?: string
          response_guidance?: string
          safe_metadata?: Json
          service_type?: string
          severity?: string
          trigger_topic?: string
          updated_at?: string
        }
        Relationships: []
      }
      worker_scope_change_stats: {
        Row: {
          last_scope_change_at: string | null
          scope_change_rate: number
          scope_change_requests: number
          total_completed_jobs: number
          updated_at: string
          worker_id: string
        }
        Insert: {
          last_scope_change_at?: string | null
          scope_change_rate?: number
          scope_change_requests?: number
          total_completed_jobs?: number
          updated_at?: string
          worker_id: string
        }
        Update: {
          last_scope_change_at?: string | null
          scope_change_rate?: number
          scope_change_requests?: number
          total_completed_jobs?: number
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_scope_change_stats_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_stats: {
        Row: {
          avg_response_time_min: number | null
          cancel_rate: number | null
          completion_rate: number | null
          income_30d: number
          jobs_30d: number
          last_recomputed_at: string
          on_time_rate: number | null
          total_income: number
          worker_id: string
        }
        Insert: {
          avg_response_time_min?: number | null
          cancel_rate?: number | null
          completion_rate?: number | null
          income_30d?: number
          jobs_30d?: number
          last_recomputed_at?: string
          on_time_rate?: number | null
          total_income?: number
          worker_id: string
        }
        Update: {
          avg_response_time_min?: number | null
          cancel_rate?: number | null
          completion_rate?: number | null
          income_30d?: number
          jobs_30d?: number
          last_recomputed_at?: string
          on_time_rate?: number | null
          total_income?: number
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_stats_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_stats_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_suspension_events: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          reason: string | null
          reference_id: string | null
          source: string
          until_at: string | null
          worker_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          reason?: string | null
          reference_id?: string | null
          source: string
          until_at?: string | null
          worker_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          reason?: string | null
          reference_id?: string | null
          source?: string
          until_at?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_suspension_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_suspension_events_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_suspension_events_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_violation_appeals: {
        Row: {
          case_id: string
          decided_at: string | null
          decided_by: string | null
          decision_reason: string | null
          evidence_paths: string[]
          id: string
          reason: string
          status: string
          submitted_at: string
          worker_id: string
        }
        Insert: {
          case_id: string
          decided_at?: string | null
          decided_by?: string | null
          decision_reason?: string | null
          evidence_paths?: string[]
          id?: string
          reason: string
          status?: string
          submitted_at?: string
          worker_id: string
        }
        Update: {
          case_id?: string
          decided_at?: string | null
          decided_by?: string | null
          decision_reason?: string | null
          evidence_paths?: string[]
          id?: string
          reason?: string
          status?: string
          submitted_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_violation_appeals_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: true
            referencedRelation: "worker_violation_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_violation_appeals_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_violation_appeals_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_violation_appeals_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_violation_case_events: {
        Row: {
          actor_id: string | null
          case_id: string
          created_at: string
          detail: Json
          event_kind: string
          id: string
        }
        Insert: {
          actor_id?: string | null
          case_id: string
          created_at?: string
          detail?: Json
          event_kind: string
          id?: string
        }
        Update: {
          actor_id?: string | null
          case_id?: string
          created_at?: string
          detail?: Json
          event_kind?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_violation_case_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_violation_case_events_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "worker_violation_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_violation_cases: {
        Row: {
          appeal_status: string
          created_at: string
          customer_id: string | null
          decided_at: string | null
          decided_by: string | null
          decision_deadline_at: string
          decision_reason: string | null
          dedupe_key: string
          evidence: Json
          id: string
          job_id: string | null
          level: number
          reporter_id: string | null
          source: string
          statement: string | null
          status: string
          suspended_pending_review: boolean
          updated_at: string
          violation_code: string
          worker_id: string
        }
        Insert: {
          appeal_status?: string
          created_at?: string
          customer_id?: string | null
          decided_at?: string | null
          decided_by?: string | null
          decision_deadline_at: string
          decision_reason?: string | null
          dedupe_key: string
          evidence?: Json
          id?: string
          job_id?: string | null
          level: number
          reporter_id?: string | null
          source: string
          statement?: string | null
          status?: string
          suspended_pending_review?: boolean
          updated_at?: string
          violation_code: string
          worker_id: string
        }
        Update: {
          appeal_status?: string
          created_at?: string
          customer_id?: string | null
          decided_at?: string | null
          decided_by?: string | null
          decision_deadline_at?: string
          decision_reason?: string | null
          dedupe_key?: string
          evidence?: Json
          id?: string
          job_id?: string | null
          level?: number
          reporter_id?: string | null
          source?: string
          statement?: string | null
          status?: string
          suspended_pending_review?: boolean
          updated_at?: string
          violation_code?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_violation_cases_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_violation_cases_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_violation_cases_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_violation_cases_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_violation_cases_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_violation_cases_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_withdrawal_requests: {
        Row: {
          account_holder_name: string
          amount_vnd: number
          available_balance_before_vnd: number
          bank_account: string
          bank_account_masked: string
          bank_key: string
          bank_name: string
          client_request_id: string
          created_at: string
          eligible_at: string
          id: string
          last_client_request_id: string | null
          payout_method_id: string
          processed_at: string | null
          processed_by: string | null
          processing_at: string | null
          processing_by: string | null
          requested_at: string
          resolution_reason: string | null
          status: string
          synthetic_cohort_id: string | null
          transfer_reference: string | null
          transfer_reference_hash: string | null
          transfer_reference_suffix: string | null
          updated_at: string
          version: number
          worker_id: string
        }
        Insert: {
          account_holder_name: string
          amount_vnd: number
          available_balance_before_vnd: number
          bank_account: string
          bank_account_masked: string
          bank_key: string
          bank_name: string
          client_request_id: string
          created_at?: string
          eligible_at?: string
          id?: string
          last_client_request_id?: string | null
          payout_method_id: string
          processed_at?: string | null
          processed_by?: string | null
          processing_at?: string | null
          processing_by?: string | null
          requested_at?: string
          resolution_reason?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          transfer_reference?: string | null
          transfer_reference_hash?: string | null
          transfer_reference_suffix?: string | null
          updated_at?: string
          version?: number
          worker_id: string
        }
        Update: {
          account_holder_name?: string
          amount_vnd?: number
          available_balance_before_vnd?: number
          bank_account?: string
          bank_account_masked?: string
          bank_key?: string
          bank_name?: string
          client_request_id?: string
          created_at?: string
          eligible_at?: string
          id?: string
          last_client_request_id?: string | null
          payout_method_id?: string
          processed_at?: string | null
          processed_by?: string | null
          processing_at?: string | null
          processing_by?: string | null
          requested_at?: string
          resolution_reason?: string | null
          status?: string
          synthetic_cohort_id?: string | null
          transfer_reference?: string | null
          transfer_reference_hash?: string | null
          transfer_reference_suffix?: string | null
          updated_at?: string
          version?: number
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_withdrawal_requests_payout_method_id_fkey"
            columns: ["payout_method_id"]
            isOneToOne: false
            referencedRelation: "worker_payout_methods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_withdrawal_requests_processed_by_fkey"
            columns: ["processed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_withdrawal_requests_processing_by_fkey"
            columns: ["processing_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_withdrawal_requests_synthetic_cohort_id_fkey"
            columns: ["synthetic_cohort_id"]
            isOneToOne: false
            referencedRelation: "synthetic_matching_cohorts"
            referencedColumns: ["cohort_id"]
          },
          {
            foreignKeyName: "worker_withdrawal_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_overview"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_withdrawal_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "worker_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
/* @slice:end tables:worker */
}
