import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const ROOT = resolve(__dirname, '../../../../../')
const read = (rel: string) => readFileSync(resolve(ROOT, rel), 'utf-8').replace(/\r\n/g, '\n')

describe('Plan §31 B5 pgvector knowledge RAG', () => {
  it('adds pgvector columns, indexes, and match RPC for Kael knowledge tables', () => {
    const sql = read('supabase/migrations/20260604213000_kael_b5_pgvector_rag.sql')

    expect(sql).toContain('create extension if not exists vector')
    for (const table of ['service_knowledge_boxes', 'worker_safety_patterns', 'legal_awareness_patterns']) {
      expect(sql).toContain(`alter table public.${table}`)
      expect(sql).toContain(`${table}_embedding_hnsw_idx`)
    }
    expect(sql).toContain('create or replace function public.match_kael_knowledge')
    expect(sql).toContain('p_query_embedding extensions.vector(64)')
    expect(sql).toContain('<=> p_query_embedding')
    expect(sql).toContain('citation_id')
    expect(sql).toContain('grant execute on function public.match_kael_knowledge')
  })

  it('adds a safe usage log for knowledge citations without PII or provider secrets', () => {
    const sql = read('supabase/migrations/20260604213000_kael_b5_pgvector_rag.sql')
    const knowledge = read('supabase/functions/mobile-api/_shared/kael/memory/knowledge.ts')

    expect(sql).toContain('create table if not exists public.kael_knowledge_usage_log')
    expect(sql).toContain('knowledge_table')
    expect(sql).toContain('citation_id')
    expect(sql).toContain('safe_metadata jsonb')
    expect(sql).toContain('private.is_admin()')
    expect(knowledge).toContain('kael_knowledge_usage_log')
    expect(knowledge).toContain('retrieveKnowledgeSemantic')
    expect(sql).not.toMatch(/pplx-[a-zA-Z0-9]{20,}/)
  })

  it('backfills approved corpus embeddings with a deterministic local model', () => {
    const script = read('apps/api/scripts/kael-b5-generate-embedding-backfill.mjs')
    const sql = read('supabase/migrations/20260604214000_kael_b5_embedding_backfill.sql')

    expect(script).toContain('kael-local-hash-64-v1')
    expect(sql).toContain('Generated by kael-b5-generate-embedding-backfill')
    expect(sql).toContain("embedding_model = 'kael-local-hash-64-v1'")
    expect(sql).toContain('::extensions.vector(64)')
    expect((sql.match(/update public\.worker_safety_patterns/g) ?? []).length).toBeGreaterThanOrEqual(24)
    expect((sql.match(/update public\.legal_awareness_patterns/g) ?? []).length).toBeGreaterThanOrEqual(8)
    expect((sql.match(/update public\.service_knowledge_boxes/g) ?? []).length).toBeGreaterThanOrEqual(3)
    expect(sql).toContain('"problem_hints"')
    expect(sql).toContain('"embedding_text_version":"b5-2026-06-04"')
    expect(sql).not.toContain('pending_tu_signoff')
  })
})
