import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  ledgerHeroCard: {
    minHeight: 74,
  },
  paymentTotalAmount: {
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 25,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 30,
    marginTop: 3,
  },
  paymentTotalCaption: {
    color: color.text.muted,
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 14,
    textTransform: 'uppercase',
  },
  paymentTotalCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.93)',
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 92,
    overflow: 'hidden',
    paddingHorizontal: 15,
    paddingVertical: 14,
    position: 'relative',
    ...shadow.soft,
  },
  paymentTotalCopy: {
    flex: 1,
    minWidth: 0,
  },
  priceLine: {
    alignItems: 'flex-start',
    borderBottomColor: 'rgba(216,235,232,0.64)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minHeight: 44,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 1,
  },
  priceLineLabel: {
    color: color.text.secondary,
    flex: 1,
    minWidth: 0,
    paddingRight: 2,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  priceLineValue: {
    color: color.text.strong,
    flex: 1.1,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    minWidth: 92,
    textAlign: 'right',
  },
  priceLinesCard: {
    backgroundColor: 'rgba(246,255,252,0.84)',
    borderColor: 'rgba(127,226,215,0.72)',
    borderRadius: 22,
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 6,
    position: 'relative',
    ...shadow.soft,
  },
  priceTotalLabel: {
    color: color.text.strong,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    minWidth: 0,
    paddingRight: 2,
  },
  priceTotalLine: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minHeight: 52,
    paddingTop: 12,
    position: 'relative',
    zIndex: 1,
  },
  priceTotalValue: {
    color: color.brand.primaryDark,
    flex: 1.1,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 23,
    minWidth: 98,
    textAlign: 'right',
  },
})
