import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  earningsHeroAmount: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 27,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 32,
    marginTop: 8,
  },
  earningsHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.79)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 30,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 148,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
    ...shadow.raised,
  },
  earningsHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  earningsHeroContent: {
    flex: 1,
    gap: 12,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  earningsHeroIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  earningsHeroMeta: {
    color: color.text.secondary,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 3,
  },
  earningsHeroMainRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  earningsStatGrid: {
    flexDirection: 'row',
    gap: 8,
    position: 'relative',
    zIndex: 1,
  },
  earningsStatLabel: {
    color: color.text.muted,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
    textAlign: 'center',
  },
  earningsStatTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderColor: 'rgba(255,255,255,0.88)',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 56,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 9,
  },
  earningsStatValue: {
    color: color.text.strong,
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  earningsTransactionAmount: {
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    maxWidth: 108,
    minWidth: 76,
    textAlign: 'right',
  },
  earningsTransactionCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  earningsTransactionIcon: {
    height: 34,
    width: 34,
  },
  earningsTransactionIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 18,
    borderWidth: 1,
    height: 54,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 54,
  },
  earningsTransactionList: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  earningsTransactionMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  earningsTransactionRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    padding: 13,
    position: 'relative',
    zIndex: 1,
  },
  earningsTransactionTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
  },
})
