import { Platform, StyleSheet } from 'react-native'
import { createSurfaceShadow } from '@/components/ui/tokens'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  dashboard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 28,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  dashboardHeading: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 13,
    paddingHorizontal: 18,
    paddingTop: 18,
    position: 'relative',
    zIndex: 1,
  },
  dashboardHeadingCopy: {
    flex: 1,
    minWidth: 0,
  },
  dashboardPeriodTitle: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
  },
  dashboardAmount: {
    color: color.text.strong,
    fontSize: 24,
    fontVariant: ['tabular-nums'],
    fontWeight: '700',
    letterSpacing: -0.45,
    lineHeight: 30,
    marginTop: 2,
  },
  dashboardUnit: {
    color: color.text.muted,
    fontSize: 9,
    lineHeight: 14,
    paddingLeft: 8,
    paddingTop: 2,
  },
  periodRail: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.20)',
    borderColor: 'rgba(255,255,255,0.76)',
    borderRadius: 999,
    borderWidth: 1,
    boxShadow: createSurfaceShadow({ color: '#087D72', offsetY: 8, opacity: 0.08, radius: 18 }),
    flexDirection: 'row',
    height: 54,
    marginHorizontal: 16,
    overflow: 'hidden',
    padding: 4,
    position: 'relative',
    zIndex: 1,
  },
  periodRailOpaque: {
    backgroundColor: color.surface.soft,
    borderColor: color.surface.stroke,
  },
  periodShimmer: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 999,
    filter: Platform.OS === 'web' ? 'blur(2px)' : undefined,
    height: 53,
    left: '-24%',
    position: 'absolute',
    top: -31,
    zIndex: 3,
  } as never,
  periodCaustic: {
    backgroundColor: 'rgba(28,205,179,0.14)',
    borderRadius: 999,
    bottom: -22,
    filter: Platform.OS === 'web' ? 'blur(9px)' : undefined,
    height: 49,
    left: 4,
    position: 'absolute',
    zIndex: 0,
  } as never,
  periodInnerRefraction: {
    borderBottomColor: 'rgba(42,205,180,0.08)',
    borderColor: 'rgba(255,255,255,0.45)',
    borderRadius: 27,
    borderWidth: 1,
    bottom: 1,
    left: 1,
    opacity: 0.92,
    position: 'absolute',
    right: 1,
    top: 1,
    zIndex: 2,
  },
  periodLens: {
    backgroundColor: 'rgba(248,255,253,0.94)',
    borderColor: 'rgba(255,255,255,0.98)',
    borderRadius: 24,
    borderWidth: 1,
    bottom: 4,
    boxShadow: createSurfaceShadow({ color: '#078071', offsetY: 9, opacity: 0.12, radius: 20 }),
    left: 4,
    overflow: 'hidden',
    position: 'absolute',
    top: 4,
    zIndex: 1,
  },
  periodLensBloom: {
    backgroundColor: 'rgba(220,249,242,0.52)',
    borderRadius: 24,
    bottom: 5,
    left: 6,
    opacity: 0.88,
    position: 'absolute',
    right: 6,
    top: 5,
  },
  periodLensTopLight: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 18,
    height: 14,
    left: 9,
    opacity: 0.68,
    position: 'absolute',
    right: 12,
    top: 5,
    transform: [{ rotate: '-8deg' }],
  },
  periodLensSheen: {
    backgroundColor: 'rgba(255,255,255,0.65)',
    borderRadius: 16,
    bottom: 1,
    left: 1,
    position: 'absolute',
    top: 1,
    width: 18,
    zIndex: 3,
  },
  periodLensInnerShadow: {
    borderBottomColor: 'rgba(12,181,159,0.14)',
    borderColor: 'rgba(5,95,87,0.045)',
    borderRadius: 22,
    borderWidth: 1,
    bottom: 4,
    left: 4,
    opacity: 0.58,
    position: 'absolute',
    right: 4,
    top: 4,
  },
  periodButton: {
    alignItems: 'center',
    borderRadius: 999,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 0,
    position: 'relative',
    zIndex: 4,
  },
  periodButtonPressed: {
    transform: [{ scale: 0.94 }],
  },
  periodLabel: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    textAlign: 'center',
  },
  periodLabelActive: {
    color: color.brand.primaryDeep,
    transform: [{ translateY: -1 }],
  },
  chart: {
    height: 194,
    marginHorizontal: 16,
    marginTop: 5,
    overflow: 'hidden',
    position: 'relative',
  },
  chartGrid: {
    bottom: 47,
    justifyContent: 'space-between',
    left: 18,
    position: 'absolute',
    right: 18,
    top: 29,
  },
  chartGridLine: {
    borderTopColor: color.surface.stroke,
    borderTopWidth: 1,
  },
  chartAxis: {
    bottom: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 4,
    position: 'absolute',
    right: 4,
  },
  chartAxisLabel: {
    color: color.text.muted,
    flex: 1,
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 13,
    textAlign: 'center',
  },
  metricGrid: {
    borderTopColor: color.surface.stroke,
    borderTopWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    position: 'relative',
    zIndex: 1,
  },
  metric: {
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    borderRightColor: color.surface.stroke,
    borderRightWidth: 1,
    minHeight: 104,
    paddingBottom: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    width: '50%',
  },
  metricRightColumn: {
    borderRightWidth: 0,
  },
  metricBottomRow: {
    borderBottomWidth: 0,
  },
  metricLabel: {
    color: color.text.secondary,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  metricValue: {
    color: color.text.strong,
    fontSize: 18,
    fontVariant: ['tabular-nums'],
    fontWeight: '700',
    lineHeight: 24,
    marginTop: 4,
  },
  metricValueAccent: {
    color: color.brand.primaryDark,
  },
  metricNote: {
    color: color.text.muted,
    fontSize: 9,
    lineHeight: 13,
    marginTop: 2,
  },
  utilitySectionTitle: {
    color: color.text.strong,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    marginBottom: 9,
    marginHorizontal: 2,
  },
  utilityList: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 22,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    ...shadow.soft,
  },
  utilityRow: {
    alignItems: 'center',
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 72,
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    zIndex: 1,
  },
  utilityRowPressed: {
    opacity: 0.76,
    transform: [{ scale: 0.985 }],
  },
  utilityRowLast: {
    borderBottomWidth: 0,
  },
  utilityIcon: {
    height: 46,
    width: 46,
  },
  utilityCopy: {
    flex: 1,
    marginLeft: 11,
    minWidth: 0,
  },
  utilityTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  utilityDetail: {
    color: color.text.muted,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 1,
  },
  utilityChevron: {
    color: color.brand.primaryDark,
    fontSize: 24,
    fontWeight: '400',
    lineHeight: 28,
    marginLeft: 8,
    textAlign: 'center',
    width: 24,
  },
})
