import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  card: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.soft,
  },
  balanceBlock: {
    backgroundColor: color.surface.mint,
    borderColor: color.surface.stroke,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    position: 'relative',
    zIndex: 1,
  },
  balanceLabel: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  balanceValue: {
    color: color.text.strong,
    fontSize: 25,
    fontWeight: '800',
    lineHeight: 32,
    marginTop: 3,
  },
  balanceNote: {
    color: color.text.secondary,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 5,
  },
  accountBlock: {
    borderBottomColor: color.surface.stroke,
    borderBottomWidth: 1,
    marginTop: 16,
    paddingBottom: 14,
    position: 'relative',
    zIndex: 1,
  },
  sectionLabel: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.45,
    lineHeight: 14,
  },
  accountValue: {
    color: color.text.strong,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 3,
  },
  accountStatus: {
    color: color.text.secondary,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  fieldLabel: {
    color: color.text.secondary,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginBottom: 6,
    marginTop: 16,
    position: 'relative',
    zIndex: 1,
  },
  input: {
    backgroundColor: color.mint.white,
    borderColor: color.surface.stroke,
    borderRadius: 15,
    borderWidth: 1,
    color: color.text.strong,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 13,
    paddingVertical: 11,
    position: 'relative',
    zIndex: 1,
  },
  validationText: {
    color: '#9B4F4F',
    fontSize: 10,
    lineHeight: 15,
    marginTop: 5,
    position: 'relative',
    zIndex: 1,
  },
  actionSpacing: {
    marginTop: 14,
    position: 'relative',
    zIndex: 1,
  },
  message: {
    color: color.brand.primaryDark,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 10,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
  latestRequest: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderColor: color.surface.stroke,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    padding: 13,
    position: 'relative',
    zIndex: 1,
  },
  latestAmount: {
    color: color.text.strong,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    marginTop: 3,
  },
  latestStatus: {
    color: color.brand.primaryDark,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
    marginLeft: 12,
    maxWidth: '46%',
    textAlign: 'right',
  },
  note: {
    color: color.text.muted,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 13,
    position: 'relative',
    textAlign: 'center',
    zIndex: 1,
  },
})
