import { StyleSheet } from 'react-native'

import { color, radius, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    fontFamily: typography.fontFamily,
  },
  iconTileMintAura: {
    opacity: 0.92,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  approvalDecisionCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  approvalDecisionIcon: {
    height: 42,
    width: 42,
  },
  approvalDecisionIconShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(216,235,232,0.9)',
    borderRadius: 22,
    borderWidth: 1,
    height: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
    width: 64,
  },
  approvalDecisionList: {
    backgroundColor: 'rgba(255,255,255,0.77)',
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    ...shadow.soft,
  },
  approvalDecisionMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  approvalDecisionRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(176,222,214,0.38)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 72,
    padding: 12,
    position: 'relative',
  },
  approvalDecisionStatus: {
    backgroundColor: color.mint.mint50,
    borderColor: color.surface.strokeStrong,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: color.brand.primaryDark,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
    maxWidth: 92,
    minWidth: 54,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: 'center',
  },
  approvalDecisionTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  boundaryBody: {
    color: color.text.secondary,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
    position: 'relative',
    zIndex: 1,
  },
  boundaryTitle: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    position: 'relative',
    zIndex: 1,
  },
  chevronText: {
    color: color.brand.primaryDark,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 26,
    paddingHorizontal: 2,
  },
  earningsHeroIcon: {
    height: 42,
    width: 42,
  },
  opportunityMeta: {
    color: color.text.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    marginTop: 2,
  },
  opportunityTitle: {
    color: color.text.strong,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  payoutAccountFieldLabel: {
    color: color.text.strong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  payoutAccountFormCard: {
    backgroundColor: 'rgba(255,255,255,0.80)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    gap: 10,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 14,
    position: 'relative',
    ...shadow.soft,
  },
  payoutAccountInputShell: {
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(127,226,215,0.58)',
    minHeight: 48,
  },
  payoutAccountInputStack: {
    gap: 5,
    position: 'relative',
    zIndex: 1,
  },
  payoutAccountManagementRowActive: {
    backgroundColor: 'rgba(232,255,249,0.72)',
  },
  payoutAccountPrecheckButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(229,255,249,0.86)',
    borderColor: 'rgba(13,179,159,0.38)',
    borderRadius: 18,
    borderWidth: 1,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 12,
    position: 'relative',
    zIndex: 1,
  },
  payoutAccountPrecheckStatus: {
    color: color.brand.primaryDark,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    position: 'relative',
    zIndex: 1,
  },
  payoutAccountPrecheckText: {
    color: color.brand.primaryDark,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
    textAlign: 'center',
  },
  payoutBankCheck: {
    alignItems: 'center',
    backgroundColor: color.brand.primary,
    borderColor: 'rgba(255,255,255,0.9)',
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: 8,
    width: 18,
    zIndex: 2,
  },
  payoutBankCheckText: {
    color: color.text.inverse,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 13,
  },
  payoutBankChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 21,
    borderWidth: 1,
    height: 68,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 11,
    position: 'relative',
    width: '31.8%',
    ...shadow.soft,
  },
  payoutBankChipSelected: {
    backgroundColor: 'rgba(232,255,249,0.88)',
    borderColor: 'rgba(13,179,159,0.55)',
    shadowColor: '#079B8A',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 24,
  },
  payoutBankGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  payoutBankLogo: {
    height: 38,
    maxWidth: '100%',
    width: 86,
  },
  payoutMethodHeroCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderColor: 'rgba(255,255,255,0.94)',
    borderRadius: 25,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 78,
    overflow: 'hidden',
    paddingHorizontal: 13,
    paddingVertical: 10,
    position: 'relative',
    ...shadow.soft,
  },
  payoutMethodHeroCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
    position: 'relative',
    zIndex: 1,
  },
  payoutMethodLogoFrame: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(255,255,255,0.96)',
    borderRadius: 17,
    borderWidth: 1,
    flexShrink: 0,
    height: 50,
    justifyContent: 'center',
    overflow: 'hidden',
    padding: 6,
    position: 'relative',
    width: 68,
    zIndex: 1,
  },
  payoutMethodLogoImage: {
    height: 34,
    width: 58,
  },
  srOnlyText: {
    height: 0,
    opacity: 0,
    position: 'absolute',
    width: 0,
  },
})
