import { StyleSheet } from 'react-native'

import { color, shadow, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: {
    ...typography.body,
  },
  opaqueCard: {
    backgroundColor: color.mint.white,
  },
  accountCard: {
    backgroundColor: color.surface.base,
    borderColor: color.surface.stroke,
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 16,
    position: 'relative',
    ...shadow.soft,
  },
  recordedAccount: {
    backgroundColor: color.surface.mint,
    borderColor: color.surface.stroke,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 11,
    position: 'relative',
    zIndex: 1,
  },
  recordedLabel: {
    color: color.text.muted,
    ...typography.caption2,
    fontWeight: '600',
  },
  recordedValue: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
    marginTop: 3,
  },
  recordedStatus: {
    color: color.brand.primaryDark,
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 4,
  },
  sectionTitle: {
    color: color.text.strong,
    ...typography.subheadline,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 19,
    position: 'relative',
    zIndex: 1,
  },
  bankGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    position: 'relative',
    zIndex: 1,
  },
  bankOption: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: color.surface.stroke,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '31%',
    flexGrow: 1,
    minHeight: 78,
    minWidth: 94,
    paddingHorizontal: 7,
    paddingVertical: 10,
    position: 'relative',
  },
  bankOptionSelected: {
    backgroundColor: color.surface.mint,
    borderColor: color.brand.primary,
    borderWidth: 1.5,
  },
  bankOptionPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  bankLogo: {
    height: 28,
    width: 58,
  },
  bankName: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 6,
    textAlign: 'center',
  },
  bankNameSelected: {
    color: color.brand.primaryDark,
  },
  selectedMark: {
    backgroundColor: color.brand.primary,
    borderRadius: 10,
    color: color.mint.white,
    ...typography.caption2,
    fontWeight: '600',
    height: 18,
    position: 'absolute',
    right: 7,
    textAlign: 'center',
    top: 7,
    width: 18,
  },
  fieldLabel: {
    color: color.text.secondary,
    ...typography.caption2,
    fontWeight: '600',
    marginBottom: 6,
    marginTop: 12,
    position: 'relative',
    zIndex: 1,
  },
  input: {
    backgroundColor: color.mint.white,
    borderColor: color.surface.stroke,
    borderRadius: 15,
    borderWidth: 1,
    color: color.text.strong,
    ...typography.body,
    minHeight: 48,
    paddingHorizontal: 13,
    paddingVertical: 11,
    position: 'relative',
    zIndex: 1,
  },
  inputMismatch: {
    borderColor: '#B96262',
  },
  validationText: {
    color: '#9B4F4F',
    ...typography.caption2,
    marginTop: 5,
    position: 'relative',
    zIndex: 1,
  },
  confirmActionSpacing: {
    marginTop: 14,
    position: 'relative',
    zIndex: 1,
  },
  message: {
    ...typography.caption2,
    fontWeight: '600',
    marginTop: 10,
    textAlign: 'center',
    position: 'relative',
    zIndex: 1,
  },
  messageError: {
    color: '#9B4F4F',
  },
  messageSuccess: {
    color: color.brand.primaryDark,
  },
  privacyNote: {
    color: color.text.muted,
    ...typography.caption2,
    marginTop: 11,
    textAlign: 'center',
    position: 'relative',
    zIndex: 1,
  },
})
