import { StyleSheet } from 'react-native'

import { radius, shadow, spacing, typography } from '@/design/theme'

export const styles = StyleSheet.create({
  workerCustomerFontText: { ...typography.body },
  dashboard: { gap: spacing.lg },
  heroCard: {
    borderRadius: radius.lg,
    borderWidth: 1,
    minHeight: 132,
    overflow: 'hidden',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    position: 'relative',
  },
  heroCopy: { flex: 1, gap: spacing.xs, justifyContent: 'center', maxWidth: '58%', zIndex: 2 },
  eyebrow: { ...typography.caption1, fontWeight: '600', letterSpacing: 0.2, textTransform: 'uppercase' },
  heroValue: { ...typography.title1, fontWeight: '600', letterSpacing: -0.5 },
  heroMeta: { ...typography.footnote, maxWidth: 204 },
  heroWorkart: { bottom: -18, height: 154, position: 'absolute', right: -22, width: 236, zIndex: 0 },
  heroWorkartWash: { bottom: 0, height: '100%', position: 'absolute', right: 68, width: 112, zIndex: 1 },
  periodSection: { gap: spacing.md },
  sectionHeader: { alignItems: 'baseline', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' },
  sectionTitle: { ...typography.title3, fontWeight: '600' },
  sectionMeta: { ...typography.footnote, fontWeight: '600' },
  card: { borderRadius: radius.lg, borderWidth: 1, gap: spacing.md, overflow: 'hidden', padding: spacing.lg, ...shadow.soft },
  cardTitle: { ...typography.headline, fontWeight: '600' },
  periodSelector: { borderRadius: radius.md, borderWidth: 1, overflow: 'hidden', padding: spacing.xs, position: 'relative' },
  periodSelectorRail: { flexDirection: 'row', minHeight: 48, position: 'relative' },
  periodButton: { alignItems: 'center', borderRadius: radius.sm, borderWidth: 0, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: spacing.xs, position: 'relative', zIndex: 2 },
  periodLabel: { ...typography.footnote, fontWeight: '600' },
  periodLabelActive: { fontWeight: '700' },
  chartCard: { borderRadius: radius.lg, borderWidth: 1, gap: spacing.md, minHeight: 194, padding: spacing.lg, ...shadow.soft },
  chartBars: { alignItems: 'flex-end', flexDirection: 'row', gap: spacing.sm, height: 122, justifyContent: 'space-between', paddingTop: spacing.sm },
  chartBarColumn: { alignItems: 'center', flex: 1, gap: spacing.xs },
  chartBarTrack: { borderRadius: radius.pill, height: 92, justifyContent: 'flex-end', overflow: 'hidden', width: 14 },
  chartBar: { borderRadius: radius.pill, minHeight: 8, width: '100%' },
  chartBarLabel: { ...typography.caption2, fontWeight: '600' },
  chartEmpty: { alignItems: 'center', gap: spacing.md, justifyContent: 'center', minHeight: 122 },
  chartEmptyTitle: { ...typography.footnote, textAlign: 'center' },
  emptyRule: { borderRadius: radius.pill, height: 6, width: '72%' },
  metricGrid: { borderBottomWidth: 1, borderTopWidth: 1, flexDirection: 'row' },
  metricCell: { flex: 1, gap: spacing.xs, minWidth: 0, paddingHorizontal: spacing.xs, paddingVertical: spacing.md },
  metricLabel: { ...typography.caption1 },
  metricValue: { ...typography.subheadline, fontWeight: '600', fontVariant: ['tabular-nums'] },
  detailRows: { gap: spacing.sm, paddingTop: spacing.xs },
  moneyRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  moneyLabel: { flex: 1, ...typography.footnote, fontWeight: '500' },
  moneyValue: { ...typography.footnote, fontWeight: '400', maxWidth: '44%' },
  primaryAction: { alignItems: 'center', borderRadius: radius.pill, justifyContent: 'center', minHeight: 52, paddingHorizontal: spacing.lg, ...shadow.soft },
  primaryActionLabel: { ...typography.headline, fontWeight: '600' },
  utilitySectionTitle: { ...typography.title3, fontWeight: '600', marginBottom: spacing.md },
  utilityCard: { borderRadius: radius.lg, borderWidth: 1, overflow: 'hidden', paddingHorizontal: spacing.md, ...shadow.soft },
  utilityRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, minHeight: 70, paddingVertical: spacing.sm },
  iconTile: { alignItems: 'center', borderRadius: radius.sm, borderWidth: 1, flexShrink: 0, height: 40, justifyContent: 'center', width: 40 },
  utilityCopy: { flex: 1, gap: spacing.xs, minWidth: 0 },
  utilityTitle: { ...typography.callout, fontWeight: '600' },
  utilityDetail: { ...typography.footnote },
  utilityChevron: { fontSize: 24, fontWeight: '600', lineHeight: 28, textAlign: 'center', width: 20 },
  divider: { height: 1, marginLeft: 52 },
  pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
  dataNotice: { borderRadius: radius.md, borderWidth: 1, gap: spacing.xs, padding: spacing.md },
  dataNoticeTitle: { ...typography.subheadline, fontWeight: '600' },
  dataNoticeBody: { ...typography.caption1 },
  dataNoticeRetry: { alignItems: 'center', alignSelf: 'flex-start', borderRadius: radius.pill, borderWidth: 1, justifyContent: 'center', minHeight: 40, marginTop: spacing.xs, paddingHorizontal: spacing.md },
  dataNoticeRetryLabel: { ...typography.caption1, fontWeight: '700' },
  dataNoticeRetryDisabled: { opacity: 0.5 },
  dataNoticeLoading: { ...typography.caption1, paddingVertical: spacing.xs },
})
